### PR TITLE
Adds domain and domain_iam_role_name parameters to resource aws_db_instance

### PR DESCRIPTION
**Pull request by nckslvrmn**
I have pulled this code into a new PR as requested by @paddycarver. This was originally written by @mikewalker125.

### CODE REVIEW

**Comment by nckslvrmn** [comment]
Hey @paddycarver. I can certainly take a look at those integration tests and give those a shot. As for @mikewalker125 's correct authorship. i would need his name and email no? I can deduce his name from his username but I'm not sure how I'd get his email to properly change the commit authorship.

**Comment by mikewalker125** [comment]
Sorry, been away from this for a few weeks. I can update the authorship of commit that @nckslvrmn pulled over.

@nckslvrmn, let me know if you'd like help with the integration tests. Thanks for pulling this over!

Mike

**Comment by nckslvrmn** [comment]
i borked the whole thing up, my apologies.

**Comment by nckslvrmn** [comment]
@mikewalker125 if you wanna move the PR over again that would be excellent. The only thing i changed was i made the domain iam role name variable have underscores rather than dashes to follow common patterns.

**Comment by mikewalker125** [comment]
@nckslvrmn Will do it now. If you're interested in doing integration tests, I can grant you access to push to my branch.

**Comment by stomplee** [comment]
Did this ever get implemented?  This PR is from over a year ago and yet I see no mention of it here?  https://www.terraform.io/docs/providers/aws/r/db_instance.html

**Pull request closed without merging**
