### PR TITLE
S3 bucket api gateway integration (Issue #5652)

### LINKED ISSUE #5652: Add example S3 bucket integration for api_gateway_integration
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

See this article on integrating S3 with API Gateway: https://docs.aws.amazon.com/apigateway/latest/developerguide/integrating-api-with-aws-services-s3.html

It would be nice to have an example replicating this in Terraform.

### PR DESCRIPTION
**Pull request by hasheddan**
Fixes #5652 

Example for creating an AWS API Gateway with S3 integration. Follows [this article](https://docs.aws.amazon.com/apigateway/latest/developerguide/integrating-api-with-aws-services-s3.html), but only builds to the point of listing buckets belonging to caller. Article goes on to allow GET, PUT, and DELETE of S3 resources, but this example demonstrates all functionality needed to move forward with the article.

### CODE REVIEW

**Comment by HashedDan** [comment]
@catsby so the diff does not occur if the `selection_pattern = "-"` argument is removed from the 200IntegrationResponse stanza, and the 200 response is still set to the default selection pattern automatically. It appears as though the diff that occurs when explicitly defining the selection_pattern as default is the result of a bug. I would be happy to look into it! Would you prefer that I go ahead and remove the 'selection_pattern' parameter for this example guide, or fix the error first and then add this example with the 'selection_pattern'?

**Comment by HashedDan** [comment]
@catsby just wanted to follow up on this older PR and see if there is still interest. Thanks!

**Comment by ryndaniels** [comment]
@hasheddan thanks for this and sorry for the delay! A couple comments - 
- For the `selection_pattern`, I think it would make sense to remove it from the example for now, and we can address the error as a separate issue
- When I ran this, the initial plan and apply gave me some 404 errors (`Error creating API Gateway Integration Response: NotFoundException: No integration defined for method`) on the integration responses, which I was able to fix by adding `depends_on = ["aws_api_gateway_integration.S3Integration"]` to the response resources. 

If you have the time to still work on this and make those changes we can go ahead and get this merged, otherwise we could pick it up on our end. Thanks!

**Comment by hasheddan** [comment]
@catsby thanks for following up! I will make sure to get these changes completed ASAP!

**Comment by catsby** [comment]
👋 @hasheddan you probably meant to thank @ryndaniels 😆 

Thank you @ryndaniels for picking up on something I dropped the ball on 😦

**Comment by ryndaniels** [comment]
@catsby of course, happy to help out! 😄

**Comment by hasheddan** [comment]
Oh yes! Sorry about that @catsby! Hope you are doing well!

**Comment by ryndaniels** [comment]
This looks great @hasheddan, thanks!

**Pull request merged**
