### PR TITLE
Updated iam_user force delete to include public ssh keys. fixes #4176

### LINKED ISSUE #4176: aws_iam_user with force_destroy should also get rid of SSH keys
### Terraform Version
```
Terraform v0.11.7
```

### Affected Resource(s)

- aws_iam_user

### Terraform Configuration Files

```hcl
resource "aws_iam_user" "u" {
  name = "u"
  force_destroy = true
}
```

### Output

Output of terraform destroy:

```
aws_iam_user.u: Refreshing state... (ID: auditor)
data.aws_caller_identity.current: Refreshing state...
data.aws_ami.stable_coreos: Refreshing state...
data.aws_availability_zones.available: Refreshing state...
data.template_file.cloud_config: Refreshing state...

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  - destroy

Terraform will perform the following actions:

  - aws_iam_user.u


Plan: 0 to add, 0 to change, 1 to destroy.

Do you really want to destroy?
  Terraform will destroy all your managed infrastructure, as shown above.
  There is no undo. Only 'yes' will be accepted to confirm.

  Enter a value: yes

aws_iam_user.u: Destroying... (ID: u)

Error: Error applying plan:

1 error(s) occurred:

* aws_iam_user.u (destroy): 1 error(s) occurred:

* aws_iam_user.auditor: Error deleting IAM User u: DeleteConflict: Cannot delete entity, must remove referenced objects first.
	status code: 409, request id: REDACTED

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

### Expected Behavior

The user should have been destroyed

### Actual Behavior

The user was not destroyed

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`
3. Add SSH pubkey out of band, e.g. `aws upload-ssh-public-key --user-name u --ssh-public-key-body $(cat ~/.ssh/id_rsa.pub)`
4. `terraform destroy`

### Additional Context

Unfortunately, while the `DeleteUser` IAM command claims to produce useful info about the conflicting resources when a delete fails. I have not found this to be true, making this bug all the more frustrating.

### References

None that I know of.

### PR DESCRIPTION
**Pull request by nodefortytwo**
Fixes #4176

Changes proposed in this pull request:

* when force delete is specified delete any public ssh keys attached to user

Output from acceptance testing: 
BEFORE change was applied:
```
-> dazn aws exec -p dazn-demo-one -- make testacc TEST=./aws/ TESTARGS='-run=TestAccAWSUser_ForceDestroy_SSHKey'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws/ -v -parallel 20 -run=TestAccAWSUser_ForceDestroy_SSHKey -timeout 120m
=== RUN   TestAccAWSUser_ForceDestroy_SSHKey
=== PAUSE TestAccAWSUser_ForceDestroy_SSHKey
=== CONT  TestAccAWSUser_ForceDestroy_SSHKey
--- FAIL: TestAccAWSUser_ForceDestroy_SSHKey (17.93s)
    testing.go:599: Error destroying resource! WARNING: Dangling resources
        may exist. The full state and error is shown below.

        Error: Error applying: 1 error occurred:
                * aws_iam_user.test (destroy): 1 error occurred:
                * aws_iam_user.test: Error deleting IAM User tf-acc-test-1916028493612556295: DeleteConflict: Cannot delete entity, must remove referenced objectsfirst.
                status code: 409, request id: c393d746-e00e-11e8-9c3c-8dbf40989de3





        State: aws_iam_user.test:
          ID = tf-acc-test-1916028493612556295
          provider = provider.aws
          arn = arn:aws:iam::621041455573:user/tf-acc-test-1916028493612556295
          force_destroy = true
          name = tf-acc-test-1916028493612556295
          path = /
          unique_id = AIDAJHVSXXJ7EDMBLQLN6
FAIL
FAIL    github.com/nodefortytwo/terraform-provider-aws/aws      17.979s
```
AFTER changes
```
-> dazn aws exec -p dazn-demo-one -- make testacc TEST=./aws/ TESTARGS='-run=TestAccAWSUser_ForceDestroy_SSHKey'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws/ -v -parallel 20 -run=TestAccAWSUser_ForceDestroy_SSHKey -timeout 120m
=== RUN   TestAccAWSUser_ForceDestroy_SSHKey
=== PAUSE TestAccAWSUser_ForceDestroy_SSHKey
=== CONT  TestAccAWSUser_ForceDestroy_SSHKey
--- PASS: TestAccAWSUser_ForceDestroy_SSHKey (19.99s)
PASS
ok      github.com/nodefortytwo/terraform-provider-aws/aws      20.032s
```

ignore the dazn bit, just generates temporary credentials to one of our ephemeral accounts

### CODE REVIEW

**Comment by avolkov-dazn** [comment]
+1

**Comment by robertstettner** [comment]
👍

**Comment by bflad** [comment]
> Output from acceptance testing: I cannot run without applying gofmt to loads of unchanged files?

Upgrading to Go 1.11 should make those disappear. 👍

**Comment by bflad** [comment]
It would be really nice to write up an acceptance test that actually covers this code path. We can set this up similar to how `_disappears` acceptance tests are written. e.g.

```go
func TestAccAWSUser_ForceDestroy_SSHKey(t *testing.T) {
	var user iam.GetUserOutput

	rName := acctest.RandomWithPrefix("tf-acc-test")
	resourceName := "aws_iam_user.test"

	resource.ParallelTest(t, resource.TestCase{
		PreCheck:     func() { testAccPreCheck(t) },
		Providers:    testAccProviders,
		CheckDestroy: testAccCheckAWSUserDestroy,
		Steps: []resource.TestStep{
			{
				Config: testAccAWSUserConfigForceDestory(rName),
				Check: resource.ComposeTestCheckFunc(
					testAccCheckAWSUserExists(resourceName, &user),
					testAccCheckAWSUserUploadsSSHKey(&user),
				),
			},
		},
	})
}

func testAccCheckAWSUserUploadsSSHKey(getUserOutput *iam.GetUserOutput) resource.TestCheckFunc {
	return func(s *terraform.State) error {
		iamconn := testAccProvider.Meta().(*AWSClient).iamconn

		input := &iam.UploadSSHPublicKeyInput{
			UserName:         aws.String(getUserOutput.User.UserName),
			SSHPublicKeyBody: aws.String(/* can be hardcoded or preferably read from a file in aws/test-fixtures */),
		}

		_, err := iamconn.UploadSSHPublicKey(request)
		if err != nil {
			return fmt.Errorf("error uploading IAM User (%s) SSH key: %s", userName, err)
		}

		return nil
	}
}

func testAccAWSUserConfigForceDestroy(rName string) string {
	return fmt.Sprintf(`
resource "aws_iam_user" "test" {
  force_destroy = true
  name = %q
}
`, rName)
}
```

**Comment by nodefortytwo** [comment]
I'll address this over the weekend, thanks for the feedback

**Comment by nodefortytwo** [comment]
Tests added and results added to PR

**Comment by bflad** [comment]
This has been released in [version 1.43.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1430-november-07-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.

**Pull request merged**
