### PR TITLE
Add aws_alb_target_group data source (#764)

### PR DESCRIPTION
**Pull request by aharin**
This PR adds aws_alb_target_group data source as requested in issue #764

### CODE REVIEW

**Comment by aharin** [comment]
```
$ make testacc TEST=./aws TESTARGS='-run=TestAcc.+AWSALBTargetGroup'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -run=TestAcc.+AWSALBTargetGroup -timeout 120m
=== RUN   TestAccDataSourceAWSALBTargetGroup_basic
--- PASS: TestAccDataSourceAWSALBTargetGroup_basic (288.49s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	288.521s
Alexanders-MacBook-Pro:terraform-provider-aws aharin_wrisk$ make testacc TEST=./aws TESTARGS='-run=TestAcc.*AWSALBTargetGroup'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -run=TestAcc.*AWSALBTargetGroup -timeout 120m
=== RUN   TestAccDataSourceAWSALBTargetGroup_basic
--- PASS: TestAccDataSourceAWSALBTargetGroup_basic (257.30s)
=== RUN   TestAccAWSALBTargetGroupAttachment_basic
--- PASS: TestAccAWSALBTargetGroupAttachment_basic (147.34s)
=== RUN   TestAccAWSALBTargetGroupAttachment_withoutPort
--- PASS: TestAccAWSALBTargetGroupAttachment_withoutPort (160.51s)
=== RUN   TestAccAWSALBTargetGroup_basic
--- PASS: TestAccAWSALBTargetGroup_basic (53.86s)
=== RUN   TestAccAWSALBTargetGroup_namePrefix
--- PASS: TestAccAWSALBTargetGroup_namePrefix (54.10s)
=== RUN   TestAccAWSALBTargetGroup_generatedName
--- PASS: TestAccAWSALBTargetGroup_generatedName (53.55s)
=== RUN   TestAccAWSALBTargetGroup_changeNameForceNew
--- PASS: TestAccAWSALBTargetGroup_changeNameForceNew (95.05s)
=== RUN   TestAccAWSALBTargetGroup_changeProtocolForceNew
--- PASS: TestAccAWSALBTargetGroup_changeProtocolForceNew (99.32s)
=== RUN   TestAccAWSALBTargetGroup_changePortForceNew
--- PASS: TestAccAWSALBTargetGroup_changePortForceNew (96.15s)
=== RUN   TestAccAWSALBTargetGroup_changeVpcForceNew
--- PASS: TestAccAWSALBTargetGroup_changeVpcForceNew (85.20s)
=== RUN   TestAccAWSALBTargetGroup_tags
--- PASS: TestAccAWSALBTargetGroup_tags (95.63s)
=== RUN   TestAccAWSALBTargetGroup_updateHealthCheck
--- PASS: TestAccAWSALBTargetGroup_updateHealthCheck (95.97s)
=== RUN   TestAccAWSALBTargetGroup_updateSticknessEnabled
--- PASS: TestAccAWSALBTargetGroup_updateSticknessEnabled (127.47s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	1421.482s
```

**Comment by stack72** [comment]
Hi @aharin 

thanks for the work here - from your code, it seems like we should be setting `arn` OR `name` - is this correct? If so, then we should really check for this in the code

Thoughts?

Paul

**Comment by aharin** [comment]
Hi @stack72 

Indeed if arn is set, then it will be used, otherwise name is used. This is exactly the same behaviour as in dataSourceAwsAlb(). In fact I copied the code from there.  Extra validation could be useful but then it should be done across the board in dataSourceAwsAlb() and other datasources that use the same logic. Perhaps as a separate issue?

**Comment by stack72** [comment]
Hi @aharin 

Ok, that makes sense - this LGTM! Tests pass as expected:

```
% make testacc TEST=./aws TESTARGS='-run=TestAccDataSourceAWSALBTargetGroup'                                                 1 ↵
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -run=TestAccDataSourceAWSALBTargetGroup -timeout 120m
=== RUN   TestAccDataSourceAWSALBTargetGroup_basic
--- PASS: TestAccDataSourceAWSALBTargetGroup_basic (243.92s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	243.946s
```

Thanks for the work here

Paul

**Pull request merged**
