### PR TITLE
Fix typo of `network_configuration`

### PR DESCRIPTION
**Pull request by Mause**

### CODE REVIEW

**Comment by Mause** [comment]
Probably the cause of https://github.com/terraform-providers/terraform-provider-aws/pull/2559/files#r155600246

**Comment by Mause** [comment]
Oh, there is also a typo in the method name

**Comment by Mause** [comment]
Okay, I attempted to extend that test to check that a change is acknowledged and actioned.

Does your travis-ci configuration run acceptance tests?

**Comment by bflad** [comment]
I'll need to get this sorted in #3240

**Comment by radeksimko** [comment]
@bflad Oh, sorry, I didn't notice #3240 yet. I'll review it 🔜 

I'll leave this with you then 😅

**Comment by bflad** [comment]
@radeksimko No worries. 😀  It was a larger than expected refactor on my part yesterday to fix some of the error handling as well as adjust the network_configuration bits too to exercise them better. I'll try to pull these commits into that PR for Monday!

> Does your travis-ci configuration run acceptance tests?

@Mause not at the moment. We currently have an internal CI server that runs acceptance testing for us since it costs 💰 
 (daily on master, ad hoc on branches). I'm not sure if we have plans to open that up past maintainers at the moment.

**Comment by bflad** [comment]
Pulled the commits into #3240 and looking good:
Pulled in #3242 commits:
```
=== RUN   TestAccAWSEcsService_withEcsClusterName
--- PASS: TestAccAWSEcsService_withEcsClusterName (10.88s)
=== RUN   TestAccAWSEcsService_withDeploymentValues
--- PASS: TestAccAWSEcsService_withDeploymentValues (11.12s)
=== RUN   TestAccAWSEcsService_withPlacementConstraints_emptyExpression
--- PASS: TestAccAWSEcsService_withPlacementConstraints_emptyExpression (14.90s)
=== RUN   TestAccAWSEcsService_withPlacementStrategy
--- PASS: TestAccAWSEcsService_withPlacementStrategy (26.64s)
=== RUN   TestAccAWSEcsService_withRenamedCluster
--- PASS: TestAccAWSEcsService_withRenamedCluster (27.79s)
=== RUN   TestAccAWSEcsService_withARN
--- PASS: TestAccAWSEcsService_withARN (38.56s)
=== RUN   TestAccAWSEcsService_withUnnormalizedPlacementStrategy
--- PASS: TestAccAWSEcsService_withUnnormalizedPlacementStrategy (42.26s)
=== RUN   TestAccAWSEcsService_withPlacementConstraints
--- PASS: TestAccAWSEcsService_withPlacementConstraints (42.96s)
=== RUN   TestAccAWSEcsService_withLbChanges
--- PASS: TestAccAWSEcsService_withLbChanges (43.23s)
=== RUN   TestAccAWSEcsService_withFamilyAndRevision
--- PASS: TestAccAWSEcsService_withFamilyAndRevision (49.40s)
=== RUN   TestAccAWSEcsService_withLaunchTypeEC2AndNetworkConfiguration
--- PASS: TestAccAWSEcsService_withLaunchTypeEC2AndNetworkConfiguration (80.44s)
=== RUN   TestAccAWSEcsService_withIamRole
--- PASS: TestAccAWSEcsService_withIamRole (125.37s)
=== RUN   TestAccAWSEcsService_healthCheckGracePeriodSeconds
--- PASS: TestAccAWSEcsService_healthCheckGracePeriodSeconds (201.72s)
=== RUN   TestAccAWSEcsService_withAlb
--- PASS: TestAccAWSEcsService_withAlb (214.05s)
=== RUN   TestAccAWSEcsService_withLaunchTypeFargate
--- PASS: TestAccAWSEcsService_withLaunchTypeFargate (250.18s)
```

**Comment by Mause** [comment]
Changes included as part of #3240

**Comment by bflad** [comment]
@Mause thanks! I figured GitHub would have automatically closed this issue when your commits were merged. 😄

**Pull request closed without merging**
