### PR TITLE
Golang1.11 fmt

### PR DESCRIPTION
**Pull request by mikecook**
Changes proposed in this pull request:

* fix formatting and tests to comply with go 1.11 formatting

### CODE REVIEW

**Comment by mikecook** [comment]
This commit for golang 1.11 breaks backward compatibility for go fmt: 
https://github.com/golang/go/commit/542ea5ad91367d2b40589942cc5757a4d5f43f97

golang version to exit code for make fmtcheck against release v1.33.0:
```
[~/go/src/github.com/terraform-providers/terraform-provider-aws] [v1.33.0|✔] 
18:32 $ for X in 6 7 8 9 10 11-rc ; do echo -n "golang:1.$X: " ; docker run --rm -v ~/go/src/github.com/terraform-providers/terraform-provider-aws:/go/src/github.com/terraform-providers/terraform-provider-aws -w /go/src/github.com/terraform-providers/terraform-provider-aws golang:1.$X make fmtcheck 1>/dev/null ; echo $? ; done
golang:1.6: 0
golang:1.7: 0
golang:1.8: 0
golang:1.9: 0
golang:1.10: 0
golang:1.11-rc: 2
```

golang version to exit code for make fmtcheck against this patch:
```
[~/go/src/github.com/terraform-providers/terraform-provider-aws] [golang1_11_fmt|✔] 
18:30 $ for X in 6 7 8 9 10 11-rc ; do echo -n "golang:1.$X: " ; docker run --rm -v ~/go/src/github.com/terraform-providers/terraform-provider-aws:/go/src/github.com/terraform-providers/terraform-provider-aws -w /go/src/github.com/terraform-providers/terraform-provider-aws golang:1.$X make fmtcheck 1>/dev/null ; echo $? ; done
golang:1.6: 2
golang:1.7: 2
golang:1.8: 2
golang:1.9: 2
golang:1.10: 2
golang:1.11-rc: 0
```

I'm not sure what the best solution is here.

**Comment by bflad** [comment]
Hi @mikecook 👋  Thanks for raising this pull request and for the extra testing you performed across versions! While I believe I was able to workaround the alignment issue by adding newlines, we'll likely just want to roll forward with requiring Go 1.11+ for development and building the provider instead of trying to workaround differences with `go fmt` on previous versions. 

To that end I'm kicking off a _full_ acceptance testing run with Go 1.11.0 with this pull request right now. If we do not find anything unexpected, we will likely pull these changes in along with subsequent TravisCI and README updates. 👍  I'll provide an update tomorrow morning EDT.

**Comment by bflad** [comment]
A full acceptance test run was completed without new issues: `Tests failed: 75, passed: 1970, ignored: 39` -- I have submitted #5721 which includes a commit after these to update the README and TravisCI configuration to require Go 1.11.

**Comment by bflad** [comment]
The two commits here have been merged via #5721 -- not sure why GitHub didn't automatically close this. 😄

**Pull request closed without merging**
