### PR TITLE
Add support for DynamoDBv2 IoT topic rule action

### LINKED ISSUE #4534: Support for IOT Rule Action "dynamoDBv2"
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

There is already a dynamodb IOT topic rule ("aws_iot_topic_rule"), but the dynamodb version 2 rule is not yet suported. It would be nice to have that also.

The version 2.0 rule action is called something like "Split message into multiple columns of a database table (DynamoDB Version 2)" and it's available via AWS Management console.

### New or Affected Resource(s)

* aws_iot_topic_rule, dynamodb object

### Potential Terraform Configuration

```
table_name: my_target_table
iam_role: my_iam_role
```
### References
* https://docs.aws.amazon.com/iot/latest/developerguide/iot-rule-actions.html
See "dynamoDBv2" rule

### PR DESCRIPTION
**Pull request by edwardbrowncross**
Fixes #4534

Changes proposed in this pull request:

* New aws_iot_topic_rule dynamodbv2 object
* Documentation for the above

Output from acceptance testing:
```
$ go test ./... -v -parallel 20 -run=TestAccAWSAvailabilityZones -timeout 120m
=== RUN   TestAccAWSAvailabilityZones_basic
=== PAUSE TestAccAWSAvailabilityZones_basic
=== RUN   TestAccAWSAvailabilityZones_stateFilter
=== PAUSE TestAccAWSAvailabilityZones_stateFilter
=== CONT  TestAccAWSAvailabilityZones_basic
=== CONT  TestAccAWSAvailabilityZones_stateFilter
--- PASS: TestAccAWSAvailabilityZones_basic (23.51s)
--- PASS: TestAccAWSAvailabilityZones_stateFilter (24.80s)
PASS
ok      github.com/edwardbrowncross/terraform-provider-aws/aws  25.387s
```

### CODE REVIEW

**Comment by joshuarose** [comment]
Is there anything the community can do to move this forward? This would be a highly beneficial feature for us!

**Comment by mr337** [comment]
Recently porting from CF to TF and got bit by this. Is there anything else to do to keep this PR moving? Happy to test or help any way I can on my end :)

**Comment by MichaelStott** [comment]
Same here, is there anything we can do to get this merged? It appears that this has been pending for nearly a year.

**Comment by nicofuccella** [comment]
+1

**Comment by sylvainv** [comment]
Could this PR be merged? What's the hold up?

**Comment by lewchuk** [comment]
@bflad @gdavison you two seem like you might be active maintainers of this repo, any chance we can get some eyes on this PR?

**Comment by sylvainv** [comment]
Any update on this issue @bflad

**Pull request merged**
