### PR TITLE
resource/cognito_user_pool: Modify update params

### PR DESCRIPTION
**Pull request by atsushi-ishibashi**
closed: #3389 
```
TF_ACC=1 go test ./aws -v -run=TestAccAWSCognitoUserPool_update -timeout 120m
=== RUN   TestAccAWSCognitoUserPool_update
--- PASS: TestAccAWSCognitoUserPool_update (107.53s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	107.564s
```

### CODE REVIEW

**Comment by atsushi-ishibashi** [comment]
@Ninir @bflad Could you increase the priority of this PR?
We have a trouble that when you modify templates, `auto_verified_attributes` becomes empty.
So I hope the next release includes the fix🙇

**Comment by atsushi-ishibashi** [comment]
@Ninir @radeksimko @bflad Please review this PR:bow:

**Comment by Puneeth-n** [comment]
Is it similar to what I am seeing in #3780

**Comment by atsushi-ishibashi** [comment]
```
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -run=TestAccAWSCognitoUserPool_ -timeout 120m
=== RUN   TestAccAWSCognitoUserPool_importBasic
--- PASS: TestAccAWSCognitoUserPool_importBasic (42.60s)
=== RUN   TestAccAWSCognitoUserPool_basic
--- PASS: TestAccAWSCognitoUserPool_basic (43.12s)
=== RUN   TestAccAWSCognitoUserPool_withAdminCreateUserConfiguration
--- PASS: TestAccAWSCognitoUserPool_withAdminCreateUserConfiguration (68.92s)
=== RUN   TestAccAWSCognitoUserPool_withDeviceConfiguration
--- PASS: TestAccAWSCognitoUserPool_withDeviceConfiguration (66.87s)
=== RUN   TestAccAWSCognitoUserPool_withEmailVerificationMessage
--- PASS: TestAccAWSCognitoUserPool_withEmailVerificationMessage (70.04s)
=== RUN   TestAccAWSCognitoUserPool_withSmsVerificationMessage
--- PASS: TestAccAWSCognitoUserPool_withSmsVerificationMessage (59.70s)
=== RUN   TestAccAWSCognitoUserPool_withEmailConfiguration
--- PASS: TestAccAWSCognitoUserPool_withEmailConfiguration (62.97s)
=== RUN   TestAccAWSCognitoUserPool_withSmsConfiguration
--- PASS: TestAccAWSCognitoUserPool_withSmsConfiguration (62.66s)
=== RUN   TestAccAWSCognitoUserPool_withSmsConfigurationUpdated
--- PASS: TestAccAWSCognitoUserPool_withSmsConfigurationUpdated (86.23s)
=== RUN   TestAccAWSCognitoUserPool_withTags
--- PASS: TestAccAWSCognitoUserPool_withTags (55.70s)
=== RUN   TestAccAWSCognitoUserPool_withAliasAttributes
--- PASS: TestAccAWSCognitoUserPool_withAliasAttributes (58.67s)
=== RUN   TestAccAWSCognitoUserPool_withPasswordPolicy
--- PASS: TestAccAWSCognitoUserPool_withPasswordPolicy (56.31s)
=== RUN   TestAccAWSCognitoUserPool_withLambdaConfig
--- PASS: TestAccAWSCognitoUserPool_withLambdaConfig (82.43s)
=== RUN   TestAccAWSCognitoUserPool_withSchemaAttributes
--- PASS: TestAccAWSCognitoUserPool_withSchemaAttributes (57.57s)
=== RUN   TestAccAWSCognitoUserPool_withVerificationMessageTemplate
--- FAIL: TestAccAWSCognitoUserPool_withVerificationMessageTemplate (77.39s)
	testing.go:494: Step 2, no error received, but expected a match to:
		
		cannot be set to nil
		
		
=== RUN   TestAccAWSCognitoUserPool_update
--- PASS: TestAccAWSCognitoUserPool_update (109.77s)
FAIL
FAIL	github.com/terraform-providers/terraform-provider-aws/aws	1060.993s
make: *** [testacc] Error 1
```
What is the purpose of below test case? @Ninir 
```
{
	Config:      testAccAWSCognitoUserPoolConfig_basic(name),
	ExpectError: regexp.MustCompile(`cannot be set to nil`),
},
```

**Comment by atsushi-ishibashi** [comment]
@Ninir @bflad What is the status of this PR?

**Comment by loivis** [comment]
Hit the same issue in prod 😭. Call for attention @Ninir @bflad

**Comment by Puneeth-n** [comment]
@loivis I also had the same issue. `auto_verified_attributes = email` was somehow overwritten in all our cognito pools and it was pretty random. We use aws lambda for generating custom_message. Somehow strangely adding IAM permissions to our lambda function solved it for us.

```
        {
            "Sid": "CognitoUserPoolAccess",
            "Action": "cognito-idp:*",
            "Effect": "Allow",
            "Resource": "*"
        }
```

**Comment by bflad** [comment]
This has been released in [version 1.32.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1320-august-16-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.

**Pull request merged**
