### PR TITLE
resource/api_gateway_domain_name: Add support for security_policy

### PR DESCRIPTION
**Pull request by stack72**
Fixes: #9100

### CODE REVIEW

**Comment by damianh** [comment]
Nice, was just looking for this. LGTM?

**Comment by AmillerSC** [comment]
@stack72 any ETA on when this PR can be merged? We are seeking this functionality as well. 

Thanks

**Comment by stack72** [comment]
@AmillerSC I’m just a community member - the merge is down to the Terraform team so we need to wait for them I’m afraid

**Comment by AmillerSC** [comment]
@stack72 Understood - appreciate your contribution. I found it odd this wasn't already possible because the documentation says "This resource just establishes ownership of and **the TLS settings** for a particular domain name."

**Comment by damianh** [comment]
Yeah that statement in the docs confused me too

**Pull request merged**
