### PR TITLE
Allow aws_route_table_association import

### LINKED ISSUE #561: Allow import of aws_route_table_association
_This issue was originally opened by @GuiSim as hashicorp/terraform#12280. It was migrated here as part of the [provider split](https://www.hashicorp.com/blog/upcoming-provider-changes-in-terraform-0-10/). The original body of the issue is below._

<hr>

### Terraform Version
v0.8.7

### Affected Resource(s)
- aws_route_table_association

Currently if you run `terraform import` on a `aws_route_table_association` you'll get an error:
```
* import module.X.aws_route_table_association.Y (id: rtbassoc-1234f171): resource aws_route_table_association doesn't support import
``` 

Allowing route table associations to be imported would be really useful. Right now, I can do it by manually editing the state file but it is an error prone process.

You can get the `id` of a route table association through 
```
aws ec2 describe-route-tables --route-table-ids rtb-123436a4
``` 

They follow the format `rtbassoc-XXXXX`.

Thanks!

### PR DESCRIPTION
**Pull request by julienduchesne**
Fixes #561

Changes proposed in this pull request:

* Modify the ID of the route table association resource to contain both the route table ID and the subnet id
* This allows the importation of route table associations using this concatenated ID.
* Export the association ID in a new attribute `association_id`

Output from acceptance testing:

```
TESTARGS='-run=TestAccAWSRouteTableAssociation_basic'  make testacc
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./... -v -run=TestAccAWSRouteTableAssociation_basic -timeout 120m
?       github.com/terraform-providers/terraform-provider-aws   [no test files]
=== RUN   TestAccAWSRouteTableAssociation_basic
--- PASS: TestAccAWSRouteTableAssociation_basic (96.03s)
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws       96.046s
```

### CODE REVIEW

**Comment by pydo** [comment]
Are there any plans to get this merged? Without this functionality I don't see any way of fully importing an existing VPC (except many editing my state file directly?).

**Comment by nijave** [comment]
Is there a reason this isn't being merged?

**Comment by sebmargineanu-ob** [comment]
Would be nice to get this merged as I am currently facing the issue with importing RTAs

**Comment by nijave** [comment]
> 
> 
> Would be nice to get this merged as I am currently facing the issue with importing RTAs

As a work around, you can use something like terraforming (written in Ruby) to export AWS config as security groups then import these into TF state. Next, export TF state and parse for the actual values (state is json) and update your HCL/config. You could also dump with boto3 or any other SDK and generate the config then reconcile. The key is reconciling with tfstate after import.

**Comment by julienduchesne** [comment]
Seems like this was closed in another PR

**Pull request closed without merging**
