### PR TITLE
f/aws_sagemaker_notebook_instance: Volume size

### LINKED ISSUE #15521: EBS Size for Resource: aws_sagemaker_notebook_instance
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

EBS Size:

implementing EBS size configuration when we want to provision notebook instance

Resource: aws_sagemaker_notebook_instance

### Potential Terraform Configuration

```resource "aws_sagemaker_notebook_instance" "ni" {
  name          = "my-notebook-instance"
  role_arn      = aws_iam_role.role.arn
  instance_type = "ml.t2.medium"
  ebs_size         = "<size>"

  tags = {
    Name = "foo"
  }
}
```

* #0000

### PR DESCRIPTION
**Pull request by nikhil-goenka**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates OR Closes #15521

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note

```

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccAWSSagemakerNotebookInstance_volumesize'
--- PASS: TestAccAWSSagemakerNotebookInstance_volumesize (908.14s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	910.463s
$ make testacc TESTARGS='-run=TestAccAWSSagemakerNotebookInstance_basic'
--- PASS: TestAccAWSSagemakerNotebookInstance_basic (470.15s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	472.978s
...
```

### CODE REVIEW

**Comment by DrFaust92** [comment]
Hey @nikhil-goenka, can you add acceptance test for this change?

**Comment by nikhil-goenka** [comment]
> Hey @nikhil-goenka, can you add acceptance test for this change?

added

**Comment by DrFaust92** [comment]
Hey @nikhil-goenka, let create a separate test for explicit volume argument + update. and check for volume default value in the basic test.

**Comment by nikhil-goenka** [comment]
> Hey @nikhil-goenka, lets create a separate test for explicit volume argument + update. and check for volume default value in the basic test.

done

**Comment by breathingdust** [comment]
LGTM 🚀  Thanks @nikhil-goenka 

Verified Acceptance Tests in Commercial (us-west-2)

```console
make testacc TEST=./aws TESTARGS='-run=TestAccAWSSagemakerNotebookInstance_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSSagemakerNotebookInstance_ -timeout 120m
=== RUN   TestAccAWSSagemakerNotebookInstance_basic
=== PAUSE TestAccAWSSagemakerNotebookInstance_basic
=== RUN   TestAccAWSSagemakerNotebookInstance_update
=== PAUSE TestAccAWSSagemakerNotebookInstance_update
=== RUN   TestAccAWSSagemakerNotebookInstance_volumesize
=== PAUSE TestAccAWSSagemakerNotebookInstance_volumesize
=== RUN   TestAccAWSSagemakerNotebookInstance_LifecycleConfigName
=== PAUSE TestAccAWSSagemakerNotebookInstance_LifecycleConfigName
=== RUN   TestAccAWSSagemakerNotebookInstance_tags
=== PAUSE TestAccAWSSagemakerNotebookInstance_tags
=== RUN   TestAccAWSSagemakerNotebookInstance_disappears
=== PAUSE TestAccAWSSagemakerNotebookInstance_disappears
=== RUN   TestAccAWSSagemakerNotebookInstance_root_access
=== PAUSE TestAccAWSSagemakerNotebookInstance_root_access
=== RUN   TestAccAWSSagemakerNotebookInstance_direct_internet_access
=== PAUSE TestAccAWSSagemakerNotebookInstance_direct_internet_access
=== CONT  TestAccAWSSagemakerNotebookInstance_basic
=== CONT  TestAccAWSSagemakerNotebookInstance_disappears
=== CONT  TestAccAWSSagemakerNotebookInstance_root_access
=== CONT  TestAccAWSSagemakerNotebookInstance_direct_internet_access
=== CONT  TestAccAWSSagemakerNotebookInstance_LifecycleConfigName
=== CONT  TestAccAWSSagemakerNotebookInstance_tags
=== CONT  TestAccAWSSagemakerNotebookInstance_update
=== CONT  TestAccAWSSagemakerNotebookInstance_volumesize
=== CONT  TestAccAWSSagemakerNotebookInstance_disappears
    resource_aws_sagemaker_notebook_instance_test.go:254: [INFO] Got non-empty plan, as expected
--- PASS: TestAccAWSSagemakerNotebookInstance_disappears (304.44s)
--- PASS: TestAccAWSSagemakerNotebookInstance_basic (313.16s)
--- PASS: TestAccAWSSagemakerNotebookInstance_LifecycleConfigName (366.77s)
--- PASS: TestAccAWSSagemakerNotebookInstance_tags (376.76s)
--- PASS: TestAccAWSSagemakerNotebookInstance_direct_internet_access (635.02s)
--- PASS: TestAccAWSSagemakerNotebookInstance_root_access (655.80s)
--- PASS: TestAccAWSSagemakerNotebookInstance_update (658.29s)
--- PASS: TestAccAWSSagemakerNotebookInstance_volumesize (697.01s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	698.483s
```

Verified Acceptance Tests in GovCloud (us-gov-west-1)

```console
make testacc TEST=./aws TESTARGS='-run=TestAccAWSSagemakerNotebookInstance_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSSagemakerNotebookInstance_ -timeout 120m
=== RUN   TestAccAWSSagemakerNotebookInstance_basic
=== PAUSE TestAccAWSSagemakerNotebookInstance_basic
=== RUN   TestAccAWSSagemakerNotebookInstance_update
=== PAUSE TestAccAWSSagemakerNotebookInstance_update
=== RUN   TestAccAWSSagemakerNotebookInstance_volumesize
=== PAUSE TestAccAWSSagemakerNotebookInstance_volumesize
=== RUN   TestAccAWSSagemakerNotebookInstance_LifecycleConfigName
=== PAUSE TestAccAWSSagemakerNotebookInstance_LifecycleConfigName
=== RUN   TestAccAWSSagemakerNotebookInstance_tags
=== PAUSE TestAccAWSSagemakerNotebookInstance_tags
=== RUN   TestAccAWSSagemakerNotebookInstance_disappears
=== PAUSE TestAccAWSSagemakerNotebookInstance_disappears
=== RUN   TestAccAWSSagemakerNotebookInstance_root_access
=== PAUSE TestAccAWSSagemakerNotebookInstance_root_access
=== RUN   TestAccAWSSagemakerNotebookInstance_direct_internet_access
=== PAUSE TestAccAWSSagemakerNotebookInstance_direct_internet_access
=== CONT  TestAccAWSSagemakerNotebookInstance_basic
=== CONT  TestAccAWSSagemakerNotebookInstance_disappears
=== CONT  TestAccAWSSagemakerNotebookInstance_direct_internet_access
=== CONT  TestAccAWSSagemakerNotebookInstance_update
=== CONT  TestAccAWSSagemakerNotebookInstance_LifecycleConfigName
=== CONT  TestAccAWSSagemakerNotebookInstance_tags
=== CONT  TestAccAWSSagemakerNotebookInstance_volumesize
=== CONT  TestAccAWSSagemakerNotebookInstance_root_access
=== CONT  TestAccAWSSagemakerNotebookInstance_disappears
    resource_aws_sagemaker_notebook_instance_test.go:254: [INFO] Got non-empty plan, as expected
--- PASS: TestAccAWSSagemakerNotebookInstance_disappears (339.18s)
--- PASS: TestAccAWSSagemakerNotebookInstance_LifecycleConfigName (340.36s)
--- PASS: TestAccAWSSagemakerNotebookInstance_tags (347.52s)
--- PASS: TestAccAWSSagemakerNotebookInstance_basic (350.14s)
--- PASS: TestAccAWSSagemakerNotebookInstance_volumesize (544.99s)
--- PASS: TestAccAWSSagemakerNotebookInstance_root_access (594.18s)
--- PASS: TestAccAWSSagemakerNotebookInstance_update (647.71s)
--- PASS: TestAccAWSSagemakerNotebookInstance_direct_internet_access (665.55s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	666.884s
```

**Pull request merged**
