### PR TITLE
Fix Cognito RoleMapping validation for Token types

### PR DESCRIPTION
**Pull request by tomelliff**
If the mapping_rule isn't set then this should be the equivalent of it not having any mapping rules defined.
Looks like the negation was missed on this.

Fixes https://github.com/terraform-providers/terraform-provider-aws/issues/2232

### CODE REVIEW

**Comment by tomelliff** [comment]
Just seen another pull request for this after checking for the issue but it was missing tests: https://github.com/terraform-providers/terraform-provider-aws/pull/2246.

Happy to rebase this on the previous PR so that @makapuu's work can be accepted too.

Also, I wanted to add a wider acceptance test for `aws_cognito_identity_pool_roles_attachment` so that we created a token based role mapping there (there's an acceptance test for the error https://github.com/terraform-providers/terraform-provider-aws/blob/79ed212c594fd8e848d0274cd0efc70bbf4cede8/aws/resource_aws_cognito_identity_pool_roles_attachment_test.go#L126-L140) but token based role mappings can only be done with Cognito identity providers and that requires an app client so we'd need https://github.com/terraform-providers/terraform-provider-aws/pull/2874 to be merged first.

**Comment by bflad** [comment]
@tomelliff thanks for your work here. Given https://github.com/terraform-providers/terraform-provider-aws/pull/2246#issuecomment-355774533 and #1803 being merged could you rebase against #2246 and help finish this up? We'd greatly appreciate it. 😄  🚀  :shipit:

**Comment by tomelliff** [comment]
@bflad I've rebased against that commit so it's now included along with my further changes plus the test.

Let me know if you need anything else.

**Comment by tomelliff** [comment]
@bflad Did you need anything else from me on this? Would be great if we can get this fix in for the next release because then I think I can tear out my Cloudformation workarounds for what was the missing Terraform Cognito resources plus this bug.

**Comment by bflad** [comment]
@tomelliff thanks for the gentle ping - I missed coming back to this for you. Sorry about that. 😢  Taking a look now.

**Comment by bflad** [comment]
This has been released in [terraform-provider-aws version 1.9.0](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#190-february-09-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.

**Pull request merged**
