### PR TITLE
resource/dynamodb_table: drop custom ValidateFunc for stream_view_type

### PR DESCRIPTION
**Pull request by loivis**
And use const from aws sdk.

### CODE REVIEW

**Comment by bflad** [comment]
Can you please fix the `make test` failure?
```
aws/resource_aws_dynamodb_table_test.go:706:16: undefined: validateStreamViewType
```

**Comment by loivis** [comment]
:sweat_smile: Sorry I was in a rush and forgot to check.

**Comment by bflad** [comment]
This is currently causing two acceptance test failures:
```
=== RUN   TestAccAWSDynamoDbTable_streamSpecification
--- FAIL: TestAccAWSDynamoDbTable_streamSpecification (27.23s)
    testing.go:513: Step 1 error: config is invalid: aws_dynamodb_table.basic-dynamodb-table: expected stream_view_type to be one of [NEW_IMAGE OLD_IMAGE NEW_AND_OLD_IMAGES KEYS_ONLY], got 
FAIL
=== RUN   TestAccAWSDynamoDbTable_streamSpecificationValidation
--- FAIL: TestAccAWSDynamoDbTable_streamSpecificationValidation (2.36s)
    testing.go:506: Step 0, expected error:
        
        config is invalid: aws_dynamodb_table.basic-dynamodb-table: expected stream_view_type to be one of [NEW_IMAGE OLD_IMAGE NEW_AND_OLD_IMAGES KEYS_ONLY], got 
        
        To match:
        
        stream_view_type is required when stream_enabled = true$
```

I think you need to allow `""` to match current behavior.

**Comment by loivis** [comment]
😓 I thought I've tested. Added empty string now.

```
=== RUN   TestAccAWSDynamoDbTable_streamSpecification
--- PASS: TestAccAWSDynamoDbTable_streamSpecification (66.57s)
=== RUN   TestAccAWSDynamoDbTable_streamSpecificationValidation
--- PASS: TestAccAWSDynamoDbTable_streamSpecificationValidation (3.19s)
```

**Pull request merged**
