### PR TITLE
add documentaion about lambda permissions with Alexa

### PR DESCRIPTION
**Pull request by flyinprogrammer**
This documents this github issue in Terraform: https://github.com/hashicorp/terraform/issues/9893#issuecomment-316472422

Happy to make this whatever we want, just trying to help!

### CODE REVIEW

**Comment by apparentlymart** [comment]
Thanks for writing this up, @flyinprogrammer.

As discussed in hashicorp/terraform#9893, I don't think we want to set the precedent that the docs for this resource are going to include examples for every service that can integrate with Lambda. Instead, I'd like to find a general bit of AWS documentation on how to set permissions for _any_ service and then explain how to translate the permission elements to Terraform. Unfortunately I can't find any such documentation in the Lambda docs... [the "Use Cases" section](http://docs.aws.amazon.com/lambda/latest/dg/use-cases.html) seems to be the closest thing, and indeed we could explain how to translate the arguments from their `aws lambda add-permission` invocation examples, but that wouldn't help with Alexa specifically since the docs for that aren't linked from here.

I tried to find some docs on a `add-permission` invocation for Alexa specifically, but the best I could find was [a forum post about it](https://forums.developer.amazon.com/questions/3639/does-anyone-know-the-arn-of-the-alexa-event-source.html). Unfortunately these "edges" between AWS services tend to always have pretty rough, incomplete documentation. :confounded:

**Comment by radeksimko** [comment]
Agreed with @apparentlymart 

That said I understand it's not always easy to "translate" official AWS examples into Terraform configs.

I assume the middle ground here could be `examples` directory in the repo?
https://github.com/terraform-providers/terraform-provider-aws/tree/master/examples

**Comment by Ninir** [comment]
I agree with @radeksimko 

Also, what do you folks think about having multiple examples exposed as tabs, when "nb of examples" > 1 ? This would make the doc clearer, and have a lot of useful examples.
I have to admit that the examples directory is not the first thing you think of :/

**Comment by radeksimko** [comment]
> Also, what do you folks think about having multiple examples exposed as tabs

That's not a bad idea, but requires a bit more significant website changes which are IMO out of scope of this otherwise simple PR. There are plans for versioned docs which are likely to address examples too, but I can't share any timeline or specifics of those plans.

**Comment by apparentlymart** [comment]
I like the idea of representing this as an example in the examples dir for now, and we can decide separately how (and whether) to incorporate the examples into the website at some later time, as @Ninir suggested.

(I agreed that it'd be cool to have the examples in the website, but we need to get some more fundamental stuff fixed with the website first, as @radeksimko mentioned.)

**Comment by Ninir** [comment]
@flyinprogrammer Could you rework this PR to include this example in the `examples/` directory?

Thanks!

**Comment by flyinprogrammer** [comment]
sure code - be right back :smiley:

**Comment by flyinprogrammer** [comment]
Idk how you feel about the `2.18 KB` `lambda_function.zip`. But this is the easiest way to run the example. :man_shrugging: 

And of course I'm more than happy to make changes; do not hesitate to be critical!

**Comment by radeksimko** [comment]
It's ok to attach 2KB ZIP file to the example.
Let me know if you need any further help.

**Comment by flyinprogrammer** [comment]
@radeksimko i think this is "done" just waiting for feedback from ya'll

**Pull request merged**
