### PR TITLE
updates testing for aws_efs_file_system

### PR DESCRIPTION
**Pull request by thatderek**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" comments, they generate extra noise for pull request followers and do not help prioritize the request

Relates #10688

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
NONE
```

Output from acceptance testing:

```
root@add5211fb606:/go/src/github.com/terraform-providers/terraform-provider-aws# AWS_PROFILE=default make testacc TEST=./aws TESTARGS='-run=TestAccAWSEFSFileSystem_basic'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSEFSFileSystem_basic -timeout 120m
=== RUN   TestAccAWSEFSFileSystem_basic
=== PAUSE TestAccAWSEFSFileSystem_basic
=== CONT  TestAccAWSEFSFileSystem_basic
--- PASS: TestAccAWSEFSFileSystem_basic (83.48s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	83.519s
root@add5211fb606:/go/src/github.com/terraform-providers/terraform-provider-aws# 
```
༼ つ ◕_◕ ༽つ GIVE HALFLIFE 3

### CODE REVIEW

**Comment by ewbankkit** [comment]
@thatderek Thanks for this.
Could you please test with the max number of allowed tags (50 I think)? The original code used a loop and the response's `Marker` field to potentially call `DescribeTags` multiple times and concatenate the results.
It was looking at this resource that prompted https://github.com/terraform-providers/terraform-provider-aws/pull/10834.

**Comment by thatderek** [comment]
Will do @ewbankkit . Assuming the test breaks (which, ya looking at it, it very well might) should the fix be implemented in `keyvaluetags`? If there, should I make it a part of this PR, something separate, or wait on (potentially an already WIP) someone else to do? 

It might be a week or two until I can get to the larger fix if it needs to be done; the downtime that allowed me to work on the couple of recent PRs to this repo has sadly run out. 
 (⊃◜⌓◝⊂)

**Comment by thatderek** [comment]
Oh actually @ewbankkit it looks like tags=50 works just fine. Would you mind checking the updated test in the `dd78` commit to ensure that covers the case you were talking about? If so, I think this is ready for further review. 

```root@388ef170a828:/go/src/github.com/terraform-providers/terraform-provider-aws# AWS_PROFILE=default make testacc TEST=./aws TESTARGS='-run=TestAccAWSEFSFileSystem_basic'  
==> Checking that code complies with gofmt requirements...
^TTF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSEFSFileSystem_basic -timeout 120m
1k=== RUN   TestAccAWSEFSFileSystem_basic
=== PAUSE TestAccAWSEFSFileSystem_basic
=== CONT  TestAccAWSEFSFileSystem_basic
--- PASS: TestAccAWSEFSFileSystem_basic (128.78s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	128.815s
root@388ef170a828:/go/src/github.com/terraform-providers/terraform-provider-aws# ```

**Comment by ewbankkit** [comment]
@thatderek Yes, that was the test case I meant.
Verified acceptance tests:

```console
$ make testacc TEST=./aws TESTARGS='-run=TestAccAWSEFSFileSystem_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSEFSFileSystem_ -timeout 120m
go: downloading github.com/aws/aws-sdk-go v1.25.45
go: extracting github.com/aws/aws-sdk-go v1.25.45
go: finding github.com/aws/aws-sdk-go v1.25.45
=== RUN   TestAccAWSEFSFileSystem_basic
=== PAUSE TestAccAWSEFSFileSystem_basic
=== RUN   TestAccAWSEFSFileSystem_pagedTags
=== PAUSE TestAccAWSEFSFileSystem_pagedTags
=== RUN   TestAccAWSEFSFileSystem_kmsKey
=== PAUSE TestAccAWSEFSFileSystem_kmsKey
=== RUN   TestAccAWSEFSFileSystem_kmsConfigurationWithoutEncryption
=== PAUSE TestAccAWSEFSFileSystem_kmsConfigurationWithoutEncryption
=== RUN   TestAccAWSEFSFileSystem_ProvisionedThroughputInMibps
=== PAUSE TestAccAWSEFSFileSystem_ProvisionedThroughputInMibps
=== RUN   TestAccAWSEFSFileSystem_ThroughputMode
=== PAUSE TestAccAWSEFSFileSystem_ThroughputMode
=== RUN   TestAccAWSEFSFileSystem_lifecyclePolicy
=== PAUSE TestAccAWSEFSFileSystem_lifecyclePolicy
=== RUN   TestAccAWSEFSFileSystem_lifecyclePolicy_update
=== PAUSE TestAccAWSEFSFileSystem_lifecyclePolicy_update
=== RUN   TestAccAWSEFSFileSystem_lifecyclePolicy_removal
=== PAUSE TestAccAWSEFSFileSystem_lifecyclePolicy_removal
=== CONT  TestAccAWSEFSFileSystem_basic
=== CONT  TestAccAWSEFSFileSystem_ThroughputMode
=== CONT  TestAccAWSEFSFileSystem_ProvisionedThroughputInMibps
=== CONT  TestAccAWSEFSFileSystem_kmsConfigurationWithoutEncryption
=== CONT  TestAccAWSEFSFileSystem_kmsKey
=== CONT  TestAccAWSEFSFileSystem_pagedTags
=== CONT  TestAccAWSEFSFileSystem_lifecyclePolicy_removal
=== CONT  TestAccAWSEFSFileSystem_lifecyclePolicy_update
=== CONT  TestAccAWSEFSFileSystem_lifecyclePolicy
--- PASS: TestAccAWSEFSFileSystem_kmsConfigurationWithoutEncryption (38.98s)
--- PASS: TestAccAWSEFSFileSystem_pagedTags (40.75s)
--- PASS: TestAccAWSEFSFileSystem_ThroughputMode (64.93s)
--- PASS: TestAccAWSEFSFileSystem_ProvisionedThroughputInMibps (70.40s)
--- PASS: TestAccAWSEFSFileSystem_lifecyclePolicy (76.10s)
--- PASS: TestAccAWSEFSFileSystem_lifecyclePolicy_removal (94.92s)
--- PASS: TestAccAWSEFSFileSystem_kmsKey (112.76s)
--- PASS: TestAccAWSEFSFileSystem_basic (117.73s)
--- PASS: TestAccAWSEFSFileSystem_lifecyclePolicy_update (144.54s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	144.597s
```

**Pull request merged**
