### PR TITLE
d/aws_nat_gateway: Add missing address attributes to the schema

### PR DESCRIPTION
**Pull request by darend**
## what

Include Address attributes in NAT Gateway data source

## why

Address attributes were not listed in the schema which prevented them from being referenced

## Sample TF Project

```
provider "aws" {
  region  = "${var.region}"
  version = ">=1.2.0"
}

data "aws_nat_gateway" "default" {
    id = "${var.nat_id}"
}

output "subnet_id" {
    value = "${data.aws_nat_gateway.default.subnet_id}"
}

output "private_ip" {
    value = "${data.aws_nat_gateway.default.private_ip}"
}
```

Running terraform with DEBUG logging I see this warning:

```
2017/11/07 13:04:19 [WARN] Output interpolation "private_ip" failed: Resource 'data.aws_nat_gateway.default' does not have attribute 'private_ip' for variable 'data.aws_nat_gateway.default.private_ip'
```

See https://github.com/terraform-providers/terraform-provider-aws/pull/1294#discussion_r149505469

### CODE REVIEW

**Comment by tomelliff** [comment]
This just bit me and was trying to work out why the `aws_nat_gateway` data source wasn't exporting the `public_ip` as the docs suggested until I saw the schema.

I've not built this from your branch but it might be worth expanding the acceptance test to make sure that these attributes actually are exported.

**Comment by darend** [comment]
> I've not built this from your branch but it might be worth expanding the acceptance test to make sure that these attributes actually are exported.

👍 Ill look for an example

**Comment by radeksimko** [comment]
@darend Thanks for the PR, as @tomelliff mentioned having acceptance test would be incredibly helpful.

See this example:

https://github.com/terraform-providers/terraform-provider-aws/blob/b8d4e1570fc43a2acee6b6e47f63c9db6b067fa2/aws/data_source_aws_db_instance_test.go#L11-L29

It's ok to just add `TestCheckResourceAttrSet` to any existing acceptance test.

**Comment by darend** [comment]
@radeksimko test updated and passed:

```
> make testacc TESTARGS='-run=TestAccDataSourceAwsNatGateway'           ✓

==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v -run=TestAccDataSourceAwsNatGateway -timeout 120m
?   	github.com/terraform-providers/terraform-provider-aws	[no test files]
=== RUN   TestAccDataSourceAwsNatGateway
--- PASS: TestAccDataSourceAwsNatGateway (219.30s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	219.335s
```

**Pull request merged**
