### PR TITLE
Fix permanent diff on aws_opsworks ssh_key and password

### PR DESCRIPTION
**Pull request by xsalazar**
### Summary

Previously, there was an issue when using [`custom_cookbooks_source`](https://www.terraform.io/docs/providers/aws/r/opsworks_stack.html#custom_cookbooks_source) in the [`aws_opsworks_stack`](https://www.terraform.io/docs/providers/aws/r/opsworks_stack.html) resource, Terraform would continuously reapply changes to both [`ssh_key`](https://www.terraform.io/docs/providers/aws/r/opsworks_stack.html#ssh_key) and [`password`](https://www.terraform.io/docs/providers/aws/r/opsworks_stack.html#password) despite no changes actually happening.

This is because, on read, the `resourceAwsOpsworksSetStackCustomCookbooksSource` method would create an intermediate map before attempting to update the resource data. However, map entries for both `Password` and `SshKey` were [removed](https://github.com/hashicorp/terraform/pull/6203/files#diff-24535403dfb766885f3c893bf704a47e), since the [AWS API](https://docs.aws.amazon.com/cli/latest/reference/opsworks/describe-stacks.html) will return `*****FILTERED*****` for sensitive data.

Since these entries were removed, they would be read as empty strings, and when Terraform compared these read values to the values in code, there would always be a difference between the code and empty string. Thus, every `terraform apply` would claim a difference and rewrite those values.

To solve this issue, the old value from the resource data is copied into the intermediate map and Terraform will no longer think it detects changes to these properties where there are none.

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" comments, they generate extra noise for pull request followers and do not help prioritize the request

### Related Issues
#165
#176
#421
#4411
https://github.com/hashicorp/terraform/pull/6203
https://github.com/hashicorp/terraform/issues/6648
https://github.com/hashicorp/terraform/issues/3635
https://github.com/hashicorp/terraform/issues/6192
https://github.com/hashicorp/terraform/issues/6826
https://github.com/hashicorp/terraform/issues/10675
https://github.com/hashicorp/terraform/issues/4790
https://github.com/hashicorp/terraform/issues/17959

### Release Notes
Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
- Fixes issue where `terraform apply` continuously suggests applying changes to `ssh_key` or `password` in `custom_cookbooks_source` property for `aws_opsworks_stack`
- Fixes issue where `terraform apply` continuously suggests applying changes to `ssh_key` or `password` in `app_source` property for `aws_opsworks_application`
```

### Test
Output from acceptance testing:
```
$ make testacc TESTARGS='-run=TestAccAWSOpsworksStack_CustomCookbooks_SetPrivateProperties' TEST=./aws
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -parallel 20 -run=TestAccAWSOpsworksStack_CustomCookbooks_SetPrivateProperties -timeout 120m
=== RUN   TestAccAWSOpsworksStack_CustomCookbooks_SetPrivateProperties
=== PAUSE TestAccAWSOpsworksStack_CustomCookbooks_SetPrivateProperties
=== CONT  TestAccAWSOpsworksStack_CustomCookbooks_SetPrivateProperties
--- PASS: TestAccAWSOpsworksStack_CustomCookbooks_SetPrivateProperties (58.38s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	58.655s
```

### CODE REVIEW

**Comment by xsalazar** [comment]
Paging @apparentlymart since he started this work in #176. Would you be able to review this?

**Comment by wagner** [comment]
@xsalazar is this the same issue affecting `aws_opsworks_application.app_source.ssh_key`?

**Comment by xsalazar** [comment]
@wagner Yeah, it looks like there's an issue in there as well. It's the [same mapping pattern](https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/resource_aws_opsworks_application.go#L434-L461), but the existing code for getting the `password` is wrong, and the missing `ssh_key` suffers from the same issue that this PR solves.

**Comment by xsalazar** [comment]
Would @apparentlymart or @bflad be able to check out this PR? It would close quite a few tickets and is pretty straightforward.

**Comment by aeschright** [comment]
Looks good! We just need a documentation update, similar to https://www.terraform.io/docs/providers/aws/r/emr_cluster.html#kerberos_attributes-1

**Comment by xsalazar** [comment]
@aeschright done!

**Pull request merged**
