### PR TITLE
Bug fix for issue 3268

### PR DESCRIPTION
**Pull request by wattdave**
https://github.com/terraform-providers/terraform-provider-aws/issues/3268

This seems to arise via explicit use of the 'state' variable.

### CODE REVIEW

**Comment by wattdave** [comment]
@bflad Here you go; it includes a test that illustrates the explicit overwrite of the service role that causes grief when trying to change an existing compute environment.

**Comment by wattdave** [comment]
@bflad This seems gtg now - are these tests what you want?

**Comment by bflad** [comment]
The acceptance test is failing currently, but I'll fix it on merge.

```
=== RUN   TestAccAWSBatchComputeEnvironment_updateState
--- FAIL: TestAccAWSBatchComputeEnvironment_updateState (96.32s)
    testing.go:513: Step 1 error: Check failed: Check 3/3 error: aws_batch_compute_environment.ec2: Attribute 'service_role' expected "tf_acc_test_batch_svc_role_7867757812779672119", got "arn:aws:iam::*******:role/tf_acc_test_batch_svc_role_7867757812779672119"
FAIL
```

**Comment by bflad** [comment]
Merged into master and will release with v1.11.0 of the AWS provider. Thanks so much!

**Comment by bflad** [comment]
This has been released in [version 1.11.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1110-march-09-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.

**Pull request merged**
