### PR TITLE
Replace ARN string creation of the form 'fmt.Sprintf("arn:...")' with functions in 'arn.go'

### PR DESCRIPTION
**Pull request by ewbankkit**
Fixes https://github.com/terraform-providers/terraform-provider-aws/issues/1783.
Progress is recorded in the task list in that issue.
```
go test -timeout 30s github.com/terraform-providers/terraform-provider-aws/aws -run '^TestArn_'
ok  	github.com/terraform-providers/terraform-provider-aws/aws	0.006s
```

### CODE REVIEW

**Comment by ewbankkit** [comment]
Unit tests:
```
$ go test -timeout 30s github.com/terraform-providers/terraform-provider-aws/aws -run ^TestArn_
ok  	github.com/terraform-providers/terraform-provider-aws/aws	0.006s
```

**Comment by ewbankkit** [comment]
Added `buildRdsArnString` and `buildRedshiftArnString` which are called from the various RDS and Redshift resource respectively as wrappers that can return errors as I didn't want to refactor the calling code excessively.

**Comment by ewbankkit** [comment]
Removing _WIP_.

**Comment by ewbankkit** [comment]
See also https://github.com/terraform-providers/terraform-provider-aws/issues/2123.

**Comment by Ninir** [comment]
Hi @ewbankkit 

Could you fix conflicts here so that we can review & merge accordingly?

Thanks!

**Comment by ewbankkit** [comment]
Replaced by https://github.com/terraform-providers/terraform-provider-aws/pull/2683.

**Pull request closed without merging**
