### PR TITLE
resource/autoscaling_policy: fix conditional logic based on policy type

### LINKED ISSUE #3689: Auto scaling target tracking policies confused by cooldown
### Terraform Version
v0.11.3

### Affected Resource(s)
- aws_autoscaling_policy

### Terraform Configuration Files
```hcl
resource "aws_autoscaling_policy" "staging_memory" {
  name = "memory-reservation"

  autoscaling_group_name = "staging"
  policy_type            = "TargetTrackingScaling"

  target_tracking_configuration {
    customized_metric_specification {
      metric_dimension {
        name  = "ClusterName"
        value = "staging"
      }

      metric_name = "MemoryReservation"
      namespace   = "AWS/ECS"
      statistic   = "Maximum"
    }

    target_value = "75"
  }
}
```

### Expected Behavior
Terraform should be able to modify properties of the autoscaling policy.

### Actual Behavior
Terraform complains that target tracking policies cannot have a cooldown.
https://gist.github.com/tilgovi/75b45757ba6cd86c962c8adc60cce000

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Define a target tracking policy for an autoscaling group
2. `terraform apply`
3. Modify any property of the policy
4. `terraform apply`

### Important Factoids
It seems as though maybe the AWS API reports a default value that Terraform is then complaining about being non-nil.

### LINKED ISSUE #3715: Step scaling policies cannot be modified
### Terraform Version
Core - v0.11.3
AWS Provider - v1.10

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_autoscaling_policy

### Terraform Configuration Files
```hcl
resource "aws_autoscaling_policy" "ecs_general_purpose_scale_out" {
  name = "memory-reservation-high"

  autoscaling_group_name    = "${module.ecs_general_purpose.group}"
  estimated_instance_warmup = 60

  adjustment_type = "PercentChangeInCapacity"
  policy_type     = "StepScaling"

  metric_aggregation_type = "Maximum"

  step_adjustment {
    scaling_adjustment          = 100
    metric_interval_lower_bound = 0
  }
}
```

### Expected Behavior
Modifying a field, such as the scaling adjustment, should modify the resource.

### Actual Behavior
Terraform fails with a validation error.

```
Error: Error applying plan:

1 error(s) occurred:

* aws_autoscaling_policy.ecs_general_purpose_scale_out: 1 error(s) occurred:

* aws_autoscaling_policy.ecs_general_purpose_scale_out: StepScaling policy types cannot use scaling_adjustment!
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`
2. Modify a field
3. `terraform apply`

### Important Factoids
There is error is nonsensical and contradicts the documentation and the behavior on create. Step scaling policies do have a scaling adjustment.

### PR DESCRIPTION
**Pull request by loivis**
fix #3715  
fix #3689 

Issue with current approach is that even user doesn't set the argument, it will be set to `zero` in terraform state from aws api response as placeholder. Later on during update, `zero` value is used thus trigger the error. One way to fix is to add conditional logic in read function as well. I'm not feeling comfortable with this because multiple conditions are introduced to handle the same situation.

Instead, I'm changing the logic in the same place to set arguments only for valid policy types. With checking policy type before setting input parameter, it's also easily compare each parameter with api specification.

I didn't figure out how to distinguish `zero` value between user input and terraform state value in current logic but that's not the focus here.

### CODE REVIEW

**Comment by loivis** [comment]
```
⎇  make fmt; and echo > aws/debug.log ; and make testacc TEST=./aws TESTARGS='-run=TestAccAWSAutoscalingPolicy_'
gofmt -w $(find . -name '*.go' |grep -v vendor)
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -run=TestAccAWSAutoscalingPolicy_ -timeout 120m
=== RUN   TestAccAWSAutoscalingPolicy_basic
--- PASS: TestAccAWSAutoscalingPolicy_basic (139.01s)
=== RUN   TestAccAWSAutoscalingPolicy_disappears
--- PASS: TestAccAWSAutoscalingPolicy_disappears (104.02s)
=== RUN   TestAccAWSAutoscalingPolicy_upgrade
--- PASS: TestAccAWSAutoscalingPolicy_upgrade (132.35s)
=== RUN   TestAccAWSAutoscalingPolicy_SimpleScalingStepAdjustment
--- PASS: TestAccAWSAutoscalingPolicy_SimpleScalingStepAdjustment (99.10s)
=== RUN   TestAccAWSAutoscalingPolicy_TargetTrack_Predefined
--- PASS: TestAccAWSAutoscalingPolicy_TargetTrack_Predefined (103.59s)
=== RUN   TestAccAWSAutoscalingPolicy_TargetTrack_Custom
--- PASS: TestAccAWSAutoscalingPolicy_TargetTrack_Custom (97.17s)
=== RUN   TestAccAWSAutoscalingPolicy_zerovalue
--- PASS: TestAccAWSAutoscalingPolicy_zerovalue (99.81s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	775.102s
```

**Comment by tilgovi** [comment]
I expect this will fix #3789 also

**Comment by tyjonesAncestry** [comment]
Can we get this merged? This is actively breaking us in Prod as well.

**Comment by tilgovi** [comment]
We're only a few days out from the initial report and there is a complete PR. Thank you, @loivis!

**Comment by mathematician** [comment]
When could this be merged? I am unsure if the documentation for autoscaling_policy works in its current state at all.

**Comment by bflad** [comment]
This has been released in [version 1.13.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1130-march-28-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.

**Pull request merged**
