### PR TITLE
[WIP] r/aws_globalaccelerator_endpoint_group: Add aws_globalaccelerator_endpoint_group resource

### PR DESCRIPTION
**Pull request by gazoakley**
Partly addresses #6739

Changes proposed in this pull request:

* **New Resource:** `aws_globalaccelerator_endpoint_group`

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccAWSAvailabilityZones'

...
```

### CODE REVIEW

**Comment by bflad** [comment]
This is ready for rebase with master. 👍

**Comment by sahotay** [comment]
When this will be available to use?

**Comment by chrissnell** [comment]
Can one of us from the community help with the rebase?

**Comment by john-delivuk** [comment]
@bflad I've rebased with master, if you want to update the PR, or I can open a fresh one
https://github.com/john-delivuk/terraform-provider-aws/tree/f-globalaccelerator-endpoint-group

**Comment by bflad** [comment]
@john-delivuk new PR works 👍

**Comment by john-delivuk** [comment]
PR #8328 Is open.

**Comment by bflad** [comment]
This pull request is now superseded by #8328 which includes the original commits. 👍

**Pull request closed without merging**
