### PR TITLE
Adding missing wafregional resources

### PR DESCRIPTION
**Pull request by BSick7**
This PR amends the following PRs with updates to finalize:
* https://github.com/terraform-providers/terraform-provider-aws/pull/1045
* https://github.com/terraform-providers/terraform-provider-aws/pull/1046
* https://github.com/terraform-providers/terraform-provider-aws/pull/1047

I have left @DennyLoko commits intact with minor revisions amended.

### CODE REVIEW

**Comment by radeksimko** [comment]
Hi @BSick7 
I appreciate the effort but I think I'd prefer to review 1 PR per resource. Do you mind splitting it up?

Thanks.

**Comment by BSick7** [comment]
Doh!
Will do @radeksimko!

**Comment by lamont** [comment]
Is there anything I can do to help or review this request? I sure would enjoy regional_waf resources.

**Comment by pvanbuijtene** [comment]
> I appreciate the effort but I think I'd prefer to review 1 PR per resource. Do you mind splitting it up?
@radeksimko trying to help a bit with the PRs, I've split it up and rebased it.

- aws_wafregional_web_acl #3754 
- aws_wafregional_web_acl_association #3755 
- aws_wafregional_rule #3756

Will also help with the review feedback.

**Comment by radeksimko** [comment]
Closing in favour of #3754 and #3755 

#3756 was just merged and will be part of the next release.

**Pull request closed without merging**
