### PR TITLE
update vendor

### LINKED ISSUE #2348: Variable changes from TF 0.11 have affected functionality - not in changelog
### Terraform Version
0.10.6

### Affected Resource(s)
anything inside of a module, possibly any resource using `default = ""`

### Terraform Configuration Files
variables.tf:

```hcl
 42 variable "private_ip" {
 43   default = ""
 44 }
```

main.tf

```
 81 resource "aws_instance" "main" {
...snip...
 94   private_ip             = "${var.private_ip}"
...snip...
```

### Expected Behavior
Running apply multiple times would not change the resource

### Actual Behavior
Running apply wants to remove/create the resource on every apply due to it thinking that private ip has changed and wants to recreate it

### Steps to Reproduce

```
$ rm -rf .terraform; terraform init >/dev/null; cat *.tf | grep -E 'provider..aws' -A 1; terraform plan -var staging_nat_enable=true -var dev_nat_enable=false | tail -n 8
provider "aws" {
  version = "1.2"

------------------------------------------------------------------------

No changes. Infrastructure is up-to-date.

This means that Terraform did not detect any differences between your
configuration and real physical resources that exist. As a result, no
actions need to be performed.

$ find . -name '*.tf' -exec sed -i 's/version = "1.2"/version = "1.3"/g' {} \;                                                                                                                                     

$ rm -rf .terraform; terraform init >/dev/null; cat *.tf | grep -E 'provider..aws' -A 1; terraform plan -var staging_nat_enable=true -var dev_nat_enable=false | tail -n 8
provider "aws" {
  version = "1.3"
Plan: 3 to add, 3 to change, 3 to destroy.

------------------------------------------------------------------------

Note: You didn't specify an "-out" parameter to save this plan, so Terraform
can't guarantee that exactly these actions will be performed if
"terraform apply" is subsequently run.
```

### Important Factoids
In aws 1.2 this was fine, in aws 1.3 its not

### References
#2345

### PR DESCRIPTION
**Pull request by jbardin**
Update terraform to 0.11.2-a262a0e04, to fix the case where an empty string needs to be considered unset for a computed field. Fixes #2348

Clean unused packages from vendor folder.

Update GNUMakefile to build tests faster.

### CODE REVIEW

**Comment by jbardin** [comment]
I agree too. This was intended to get a release out ASAP, but the timeline fell through.

I can merge this as is if we want to fix the linked issue, or wait for a core release (which should be soon-ish).

**Comment by catsby** [comment]
If "soonish" is next week, then I think waiting would be 👍

**Comment by apparentlymart** [comment]
v0.11.2 is now out, so we could update this PR to reference that release by its tag.

**Comment by jbardin** [comment]
Rebased on master, updated terraform packages to the v0.11.2 tag, and removed a few more unused vendor packages.

**Pull request merged**
