### PR TITLE
Automatically apply service labels to new issues

### PR DESCRIPTION
**Pull request by aeschright**
First pass at generating all the HashiBot issue regexps for applying service labels to issues.

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" comments, they generate extra noise for pull request followers and do not help prioritize the request

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
N/A
```

Output from acceptance testing:

```
N/A
```

### CODE REVIEW

**Comment by bflad** [comment]
Could/should these be consolidated per service to reduce the configuration and bot overhead? e.g.

```hcl
behavior "regexp_issue_labeler" "service_acm" {
  regexp = "(\\* |data \"|resource \")aws_acm_"
  labels = ["service/acm"]
}
```

**Comment by appilon** [comment]
@bflad @aeschright That could be a small optimization but I'm not sure how much change would need to be done to the tool that generated these configs. This is a stopgap until we develop a behavior that can take in a mapping similar to the PR path labeler.

**Comment by aeschright** [comment]
No problem, I took @appilon's advice and wrote a Ruby script :)

**Comment by bflad** [comment]
Superseded by updated hashibot behavior and #9551 😄

**Pull request closed without merging**
