### PR TITLE
CodeBuild Webhook FilterGroups

### LINKED ISSUE #7503: Support for AWS CodeBuild Webhook Filter
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

_This issue was originally opened by @OfirYaron as hashicorp/terraform#20289. It was migrated here as a result of the [provider split](https://www.hashicorp.com/blog/upcoming-provider-changes-in-terraform-0-10/). The original body of the issue is below._

<hr>

AWS introduced a new feature for their CI/CD pipeline - CodeBuild:

long waited **Github Webhook Filter** - to allow further filtering of the webhook by some of it's payload content
it give the ability to decide what condition are met before triggering the build process.

feature specifications:
https://docs.aws.amazon.com/codebuild/latest/userguide/sample-github-pull-request.html#sample-github-pull-request-filter-webhook-events

### PR DESCRIPTION
**Pull request by tomkuehl**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" comments, they generate extra noise for pull request followers and do not help prioritize the request

Fixes #7503 

Changes proposed in this pull request:

* Add filter_group argument to resource aws_codebuild_webhook

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccAWSCodeBuildWebhook_FilterGroup'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./... -v -parallel 20 -run=TestAccAWSCodeBuildWebhook_FilterGroup -timeout 120m
?       github.com/terraform-providers/terraform-provider-aws   [no test files]
=== RUN   TestAccAWSCodeBuildWebhook_FilterGroup
=== PAUSE TestAccAWSCodeBuildWebhook_FilterGroup
=== CONT  TestAccAWSCodeBuildWebhook_FilterGroup
--- PASS: TestAccAWSCodeBuildWebhook_FilterGroup (42.81s)
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws       42.871s
```

ToDo:
- [x] Fix update of existing hook
- [x] Update test
- [x] Update docs

### CODE REVIEW

**Comment by tomkuehl** [comment]
Shall i add a notice that the branch_filter argument is deprecated?

**Comment by pedrofaria** [comment]
> Shall i add a notice that the branch_filter argument is deprecated?

IMHO, no.

This option still available on Go SDK.

**Comment by tomkuehl** [comment]
I added a note about using filter_group over branch_filter like in the AWS docs: https://docs.aws.amazon.com/de_de/codebuild/latest/APIReference/API_Webhook.html

It's working so far. Only thing left are the tests. First I have to read the docs and then I will implement them 😅

**Comment by tomkuehl** [comment]
I added the test as far as i came. It throws this exception: `OAuthProviderException: Repository not found or permission denied.` Where can i edit the repo it uses? Don't find it.. Can someone with a little bit more experience help me out?

**Comment by bflad** [comment]
Hi @tomkuehl 👋 The BitBucket and GitHub repositories the CodeBuild resources use for testing can be controlled via the `AWS_CODEBUILD_BITBUCKET_SOURCE_LOCATION` and `AWS_CODEBUILD_GITHUB_SOURCE_LOCATION` environments variables:

https://github.com/terraform-providers/terraform-provider-aws/blob/f329cc925d4b679a1de120a2a28bce48a14a8e2a/aws/resource_aws_codebuild_project_test.go#L16-L38

**Comment by tomkuehl** [comment]
Thank you @bflad !! Now the test works. I only have one question left: Why? :D I thought these numbers (e.g. 3033132000: https://github.com/terraform-providers/terraform-provider-aws/pull/8110/files#diff-8984e55d6f33639a7b185d987d2233eeR174) where auto-generated?

And what exactly is this step for? https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/resource_aws_codebuild_webhook_test.go#L149-L154 Do we need it in the filter_group test as well? Because it doesn't work.. ^^

**Comment by bflad** [comment]
Those `TypeSet` hashes (e.g. `3033132000`) can either be tested like that, which can be brittle depending on the configuration, or by inspecting the `&webhook` returned by `testAccCheckAWSCodeBuildWebhookExists`, e.g.

```go
// After testAccCheckAWSCodeBuildWebhookExists() call in Check
testAccCheckAWSCodeBuildWebhookFilters(&webhook, [][]*codebuild.WebhookFilter{
  // fill in details
}),

// new top level function
func testAccCheckAWSCodeBuildWebhookFilters(webhook *codebuild.Webhook, expectedFilters [][]*codebuild.WebhookFilter) resource.TestCheckFunc {
	return func(s *terraform.State) error {
		if webhook == nil {
			return fmt.Errorf("webhook missing")
		}

		if !reflect.DeepEqual(webhook.FilterGroups, expectedFilters) {
			return fmt.Errorf("expected webhook filter configuration (%v), got: %v", expectedFilters, webhook.FilterGroups)
		}

		return nil
	}
}
```

> And what exactly is this step for? https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/resource_aws_codebuild_webhook_test.go#L149-L154 Do we need it in the filter_group test as well? Because it doesn't work.. ^^

Yes, that should be included. It verifies that someone can run `terraform import` successfully on the infrastructure and not show any differences in Terraform immediately after. If it is failing, it likely means the resource `Read()` function is not properly calling `d.Set()` for the attribute. If you provide the error output from the testing, we can provide more targeted guidance.

**Comment by tomkuehl** [comment]
Thanks!

This is the error from the test:
```
ImportStateVerify attributes not equivalent. Difference is shown below. Top is actual, bottom is expected.

(map[string]string) {}

(map[string]string) (len=7) {
(string) (len=14) "filter_group.#": (string) (len=1) "2",
(string) (len=46) "filter_group.178477371.exclude_matched_pattern": (string) (len=5) "false",
(string) (len=30) "filter_group.178477371.pattern": (string) (len=17) "refs/heads/master",
(string) (len=27) "filter_group.178477371.type": (string) (len=8) "HEAD_REF",
(string) (len=47) "filter_group.2768903781.exclude_matched_pattern": (string) (len=5) "false",
(string) (len=31) "filter_group.2768903781.pattern": (string) (len=20) "PULL_REQUEST_CREATED",
(string) (len=28) "filter_group.2768903781.type": (string) (len=5) "EVENT"
}
```

And the error from `d.Set("filter_group", project.Webhook.FilterGroups)` says: `filter_group.0: '' expected a map, got 'slice'`

**Comment by danisabad** [comment]
Hello, @tomkuehl! Thank you for this PR.
I've just tested it for 0.12, works well. 

I can see that there is a functionality to create multiple event filter groups for a webhook. Do you have plans to implement that as well?

**Comment by tomkuehl** [comment]
Hey @danisabad, thanks for testing it!

What exactly do you mean? You can already provide multiple event types as a comma-separated string. e.g.:
```
filter_group {
    type = "EVENT"
    pattern = "PUSH,PULL_REQUEST_CREATED"
}
```

**Comment by danisabad** [comment]
Let me illustrate example:

cb_filter_groups

**Comment by sgal** [comment]
@tomkuehl This looks awesome! How far from completion you think this PR is? I would love to have this feature available cause now I have to stick with cloudformation templates which are quite cumbersome to reuse in this case.

**Comment by tomkuehl** [comment]
Hi @sgal! Currently the test is failing & last time i worked on it, i didn't find out why... I also want to implement the use case @danisabad showed. (Didn't know it was possible in the first place). When these 2 things are done it should be ready to merge. Currently i don't have much time to work on this, so any help is welcome :)

**Comment by tomkuehl** [comment]
Awesome @raivenlilianto, thank you!!!

So if i'm right, the last thing missing is the functionality to add multiple event filter groups? Start working on this now

**Comment by talton-heb** [comment]
> > Shall i add a notice that the branch_filter argument is deprecated?
> 
> IMHO, no.
> 
> This option still available on Go SDK.

If you try and set both branchFilter and filterGroups at the same time, AWS gives a warning along the lines of `"You cannot use branchFilter and filterGroups at the same time. Specify the branch filter using filterGroups"`

Since filterGroups are a strict superset of the branchFilter functionality, I would suggest deprecating the `branch_filter` terraform config option.

**Comment by tomkuehl** [comment]
Multiple filter_groups are working now... But i broke the tests ☹️ Could someone please take a look at this? When the tests work again this PR is ready to merge IMO

**Comment by sgal** [comment]
@tomkuehl According to CI it is all green now - is there anything that's missing?

**Comment by tomkuehl** [comment]
The CI was red because the test was incompatible with multiple filter groups. This one is fixed now, but if i run `make testacc TESTARGS='-run=TestAccAWSCodeBuildWebhook_FilterGroup'` it results in an error:
```TF_ACC=1 go test ./... -v -parallel 20 -run=TestAccAWSCodeBuildWebhook_FilterGroup -timeout 120m
?       github.com/terraform-providers/terraform-provider-aws   [no test files]
=== RUN   TestAccAWSCodeBuildWebhook_FilterGroup
=== PAUSE TestAccAWSCodeBuildWebhook_FilterGroup
=== CONT  TestAccAWSCodeBuildWebhook_FilterGroup
--- FAIL: TestAccAWSCodeBuildWebhook_FilterGroup (41.39s)
    testing.go:538: Step 1 error: ImportStateVerify attributes not equivalent. Difference is shown below. Top is actual, bottom is expected.
        
        (map[string]string) {
        }
        
        
        (map[string]string) (len=12) {
         (string) (len=14) "filter_group.#": (string) (len=1) "2",
         (string) (len=32) "filter_group.1895770492.filter.#": (string) (len=1) "2",
         (string) (len=56) "filter_group.1895770492.filter.0.exclude_matched_pattern": (string) (len=5) "false",
         (string) (len=40) "filter_group.1895770492.filter.0.pattern": (string) (len=4) "PUSH",
         (string) (len=37) "filter_group.1895770492.filter.0.type": (string) (len=5) "EVENT",
         (string) (len=56) "filter_group.1895770492.filter.1.exclude_matched_pattern": (string) (len=4) "true",
         (string) (len=40) "filter_group.1895770492.filter.1.pattern": (string) (len=17) "refs/heads/master",
         (string) (len=37) "filter_group.1895770492.filter.1.type": (string) (len=8) "HEAD_REF",
         (string) (len=31) "filter_group.936864534.filter.#": (string) (len=1) "1",
         (string) (len=55) "filter_group.936864534.filter.0.exclude_matched_pattern": (string) (len=5) "false",
         (string) (len=39) "filter_group.936864534.filter.0.pattern": (string) (len=20) "PULL_REQUEST_UPDATED",
         (string) (len=36) "filter_group.936864534.filter.0.type": (string) (len=5) "EVENT"
        }
        
FAIL
FAIL    github.com/terraform-providers/terraform-provider-aws/aws       41.446s
make: *** [testacc] Error 1
```

I didn't find out why it happens yet..

**Comment by tomkuehl** [comment]
Here we go, fixed the tests! IMO this PR is now ready to merge :)

**Comment by tomkuehl** [comment]
Can we get this reviewed? :) cc @bflad

**Comment by KursLabIgor** [comment]
Guys, please merge it. I really surprised that I cant manage it from terraform.

**Comment by ivz-abhinav** [comment]
Thanks for the efforts @tomkuehl 

I hope this is merged soon, we need it for one of the projects.

**Comment by bflad** [comment]
This has been released in [version 2.14.0 of the Terraform AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#2140-june-06-2019). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.

**Pull request merged**
