### PR TITLE
New Service: WorkMail

### PR DESCRIPTION
**Pull request by borisroman**
Added the WorkMail service according to https://github.com/terraform-providers/terraform-provider-aws/blob/master/.github/CONTRIBUTING.md#pull-requests

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates #6430 

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
- WorkMail service added
```

### CODE REVIEW

**Comment by ewbankkit** [comment]
Once https://github.com/terraform-providers/terraform-provider-aws/pull/11893 is merged then we can also add tagging support for WorkMail as it was added in [AWS SDK v1.28.10](https://github.com/aws/aws-sdk-go/releases/tag/v1.28.10).

**Comment by bflad** [comment]
Hi @borisroman 👋 Thank you for submitting this. Can you please also ensure the hashibot configuration is updated? https://github.com/terraform-providers/terraform-provider-aws/blob/master/.github/CONTRIBUTING.md#new-service

  - In `.hashibot.hcl`: Add the new service to automated issue and pull request labeling. e.g. with the `quicksight` service

```hcl
behavior "regexp_issue_labeler_v2" "service_labels" {
  # ... other configuration ...

  label_map = {
    # ... other services ...
    "service/workmail" = [
      "aws_workmail_",
    ],
    # ... other services ...
  }
}

behavior "pull_request_path_labeler" "service_labels"
  # ... other configuration ...

  label_map = {
    # ... other services ...
    "service/workmail" = [
      "**/*_workmail_*",
      "**/workmail_*",
    ],
    # ... other services ...
  }
}
```

Then this should be good to go. Thanks.

**Comment by borisroman** [comment]
Hi @bflad 

I should've mentioned; it's already in the codebase: https://github.com/terraform-providers/terraform-provider-aws/blob/master/.hashibot.hcl#L518

Hope that resolves your comment

**Comment by bflad** [comment]
@borisroman awesome! Sorry I didn't already know that.

**Comment by borisroman** [comment]
Thanks @bflad !

**Pull request merged**
