### PR TITLE
aws_ecs_cluster: add importer

### PR DESCRIPTION
**Pull request by darkowlzz**
Related to #1762

### CODE REVIEW

**Comment by TylerBrock** [comment]
Would love to see this get merged if possible @radeksimko.

**Comment by kwent** [comment]
I also need this feature

**Comment by loivis** [comment]
@bflad With your suggestion, are we forcing to use arn to import the resource? I think it's easier to import using cluster name only.

**Comment by bflad** [comment]
This has been released in [terraform-provider-aws version 1.7.0](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#170-january-12-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.

**Pull request closed without merging**
