### PR TITLE
Add `private_ips` attribute to `aws_lb` resource

### PR DESCRIPTION
**Pull request by h0nIg**
fixed merge errors of https://github.com/terraform-providers/terraform-provider-aws/pull/2901

### CODE REVIEW

**Comment by h0nIg** [comment]
@gdavison @bflad can you please take a look? this is extremly cumbersome, since this PR will bring so much value and nobody is taking a look at it.

**Comment by h0nIg** [comment]
can you please take a look? @bflad @radeksimko @Ninir @ryndaniels @stack72 @nywilken @gdavison @grubernaut @jen20 @catsby @aeschright @paddycarver @appilon @tombuildsstuff @apparentlymart @jbardin @abinashmeher999 @hendrik363

**Comment by ewbankkit** [comment]
@h0nIg Thanks for this.

Validated acceptance test:

```console
$ AWS_DEFAULT_REGION=us-east-2 make testacc TEST=./aws/ TESTARGS='-run=TestAccAWSLB_ALB_basic'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws/ -v -count 1 -parallel 20 -run=TestAccAWSLB_ALB_basic -timeout 120m
=== RUN   TestAccAWSLB_ALB_basic
=== PAUSE TestAccAWSLB_ALB_basic
=== CONT  TestAccAWSLB_ALB_basic
--- PASS: TestAccAWSLB_ALB_basic (188.85s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	188.894s
```

Will this interact correctly with the ability to specify a private IP address per-subnet: https://github.com/terraform-providers/terraform-provider-aws/pull/12331?

**Comment by h0nIg** [comment]
i just checked the other PR, with it you will get the ability to specify an IP address. This PR just scans for the network interfaces associated to the loadbalancer, which will get used to determine the attached ip address to that network interface. Therefore it does not care about if the IP address was specified manually or allocated automatically.

@ewbankkit therefore good to get merged

**Comment by maryelizbeth** [comment]
Hi Y’all,

Per the conversation on #2901, we’ll work with the author of #11404 to address any changes that may be needed to merge the PR and will merge it once the work is complete.

As a result, we will close this PR in order to focus conversation on #11404.

If you feel that #11404 does not adequately address your workflow, please open a new GitHub Issue describing the gap. If you have concerns regarding the design of the upstream API, please reach out to AWS.

We apologize for letting this linger without response and will work to merge #11404 in an upcoming release.

**Pull request closed without merging**
