### PR TITLE
r/emr_cluster: Avoid spurious diff of log_uri

### LINKED ISSUE #1356: aws_emr_cluster.log_uri forces new resource
Once log_uri is set for an aws_emr_cluster resource, it will force a new resource every time:

Executing `terraform plan` will return something like this:

```
-/+ aws_emr_cluster.offline-reporting (new resource required)
     ....
     log_uri:   "s3n://my-emr-logs/offline-reporting/" => "s3://my-emr-logs/offline-reporting/" (forces new resource)
     ....
```

### PR DESCRIPTION
**Pull request by radeksimko**
Fixes #1356

### Test results

```
=== RUN   TestAccAWSEMRCluster_visibleToAllUsers
--- FAIL: TestAccAWSEMRCluster_visibleToAllUsers (435.08s)
	testing.go:435: Step 0 error: After applying this step, the plan was not empty:
		
		DIFF:
		
		UPDATE: aws_route_table.r
		  route.#:                                    "0" => "1"
		  route.3310190312.cidr_block:                "" => "0.0.0.0/0"
		  route.3310190312.egress_only_gateway_id:    "" => ""
		  route.3310190312.gateway_id:                "" => "igw-bf138ed8"
		  route.3310190312.instance_id:               "" => ""
		  route.3310190312.ipv6_cidr_block:           "" => ""
		  route.3310190312.nat_gateway_id:            "" => ""
		  route.3310190312.network_interface_id:      "" => ""
		  route.3310190312.vpc_peering_connection_id: "" => ""
		...
=== RUN   TestAccAWSEMRCluster_bootstrap_ordering
--- PASS: TestAccAWSEMRCluster_bootstrap_ordering (444.84s)
=== RUN   TestAccAWSEMRCluster_tags
--- PASS: TestAccAWSEMRCluster_tags (445.07s)
=== RUN   TestAccAWSEMRCluster_security_config
--- PASS: TestAccAWSEMRCluster_security_config (461.40s)
=== RUN   TestAccAWSEMRCluster_terminationProtected
--- PASS: TestAccAWSEMRCluster_terminationProtected (464.73s)
=== RUN   TestAccAWSEMRCluster_basic
--- PASS: TestAccAWSEMRCluster_basic (471.66s)
=== RUN   TestAccAWSEMRCluster_s3Logging
--- PASS: TestAccAWSEMRCluster_s3Logging (884.87s)
```

That one failure is intermittent and unrelated to this PR.

### CODE REVIEW

**Comment by agalazis** [comment]
which version is this fix included in?

**Comment by radeksimko** [comment]
@agalazis correct, the easiest way to find out when was a given PR released is to use `Ctrl/Cmd+F` in the Changelog with the PR number.

**Comment by diddle-doo** [comment]
I am still having an issue, in-spite of upgrading the provider version
terraform --version 
Terraform v0.11.7
+ provider.aws v1.25.0

      log_uri:                                            "s3n://logs-xxxxxx-us-east-1/logs/" => "s3://logs-xxxxxx-us-east-1/logs" (forces new resource)

can you please help?

**Comment by bflad** [comment]
@diddle-doo you need to add a trailing `/` in your configuration.

`"s3n://logs-xxxxxx-us-east-1/logs/" => "s3://logs-xxxxxx-us-east-1/logs"` is saying:

* The API is returning: `s3n://logs-xxxxxx-us-east-1/logs/`
* Your configuration appears to have: `s3://logs-xxxxxx-us-east-1/logs`
* The code change here allows Terraform to accept both `s3n://logs-xxxxxx-us-east-1/logs/` and `s3://logs-xxxxxx-us-east-1/logs/` (note trailing `/` is still required)

**Comment by diddle-doo** [comment]
Thank you :)

**Pull request merged**
