### PR TITLE
resource/aws_kinesis_stream: Add support for encryption

### PR DESCRIPTION
**Pull request by stack72**
Fixes: #1109

Got an issue with StopEncryption - working on this atm

### CODE REVIEW

**Comment by ungureanuvladvictor** [comment]
Any update on this?

**Comment by aggallim** [comment]
+1, any updates?

**Comment by Ninir** [comment]
Hey @stack72 

Are you still having issues with the StopEncryption thing?
Do you think you would have time to finish that if not?

Thanks!

**Comment by stack72** [comment]
@Ninir if you want, we can jump on a call at some point and i can show you the issues I am having with this :)

**Comment by Ninir** [comment]
Hi Paul!

Sure, if I can be of any help... 😄 🤷‍♂️ !

**Comment by ungureanuvladvictor** [comment]
Bump on this one!

**Comment by Ninir** [comment]
@stack72 Do you want to hangout / Skype / other? :)

**Comment by stack72** [comment]
Hi @Ninir

This is now ready for review - I worked through it with @tombuildsstuff on
Saturday

Paul

**Comment by Ninir** [comment]
Thanks for that @stack72 !

(Could you indicate me a way to contact you for a quick chat? Gitter / other? thanks!)

**Comment by stack72** [comment]
@Ninir i can log into gitter - also, the acceptance tests for this were run via teamcity

**Comment by gdearment** [comment]
Any updates on when this might go through?

**Pull request merged**
