### PR TITLE
resource/wafv2_web_acl: update method params in acctest check

### PR DESCRIPTION
**Pull request by anGie44**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
resource/wafv2_web_acl: remove extra param in acctest check method updated in #13674
```

Output from acceptance testing:

```
--- PASS: TestAccAwsWafv2WebACL_Disappears (82.96s)
--- PASS: TestAccAwsWafv2WebACL_Minimal (118.95s)
--- PASS: TestAccAwsWafv2WebACL_ChangeNameForceNew (209.82s)
--- PASS: TestAccAwsWafv2WebACL_RateBasedStatement (233.68s)
--- PASS: TestAccAwsWafv2WebACL_ManagedRuleGroupStatement (234.70s)
--- PASS: TestAccAwsWafv2WebACL_Basic (239.86s)
--- PASS: TestAccAwsWafv2WebACL_Tags (259.57s)
--- PASS: TestAccAwsWafv2WebACL_RuleGroupReferenceStatement (296.79s)
```

### CODE REVIEW

**Comment by pvanbuijtene** [comment]
How did this pass the CI tests... I also ran the tests locally without any issue 🤔

**Comment by anGie44** [comment]
are you referring to the acceptance tests? it may have been the timing, this PR I merged in changed the method signature https://github.com/terraform-providers/terraform-provider-aws/pull/13674

**Comment by pvanbuijtene** [comment]
aah ok, was wondering how I caused this... we don't want failing builds :)

**Comment by anGie44** [comment]
@pvanbuijtene` master` is all set for rebasing your PRs that might of been affected by this

**Pull request merged**
