### PR TITLE
Issue #4064 Add application/x-x509-ca-cert as allowable MIME type for aws_s3_bucket_object

### PR DESCRIPTION
**Pull request by saravanan30erd**

### CODE REVIEW

**Comment by saravanan30erd** [comment]
@bflad added acceptance test,

$ make testacc TEST=./aws TESTARGS='-run=TestAccDataSourceAWSS3BucketObject_readableBodyXX509CACert'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -run=TestAccDataSourceAWSS3BucketObject_readableBodyXX509CACert -timeout 120m
=== RUN   TestAccDataSourceAWSS3BucketObject_readableBodyXX509CACert
--- PASS: TestAccDataSourceAWSS3BucketObject_readableBodyXX509CACert (158.97s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	159.008s

**Comment by saravanan30erd** [comment]
@bflad is there anything I can do to push this?

**Comment by bflad** [comment]
@saravanan30erd you might want to take a look at the link in the comment for the `isContentTypeAllowed()` function there: https://github.com/hashicorp/terraform/pull/3858#issuecomment-156856738

We cannot guarantee that this MIME type is UTF-8 safe and it could corrupt the Terraform state given the right binary content. This would need to be Base64 encoded in another attribute for safety.

**Comment by bflad** [comment]
Closing due to lack of response and because the change as implemented could introduce Terraform state corruption due to the content type. We might accept a different solution that instead works with Base64 encoding content of binary content before it enters the Terraform state.

**Pull request closed without merging**
