### PR TITLE
Elastic Beanstalk support for PlatformArn

### PR DESCRIPTION
**Pull request by jbienkowski311**
If you are using AWS's ready to use [solutions stacks](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/concepts.platforms.html), then you are fine. But if for some reason you would like to use [AWS Custom Platform](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/custom-platforms.html), then Terraform will not support it.
This PR adds support for CloudFormation's parameter `PlatformArn`, therefore adding support for Custom Platforms to Terraform.

Changes proposed in this pull request:

* Add support for `platform_arn` parameter to Elastic Beanstalk Environment resource. More about PlatformArn can be found in [AWS Docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-beanstalk-environment.html#cfn-beanstalk-environment-platformarn)

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccAWSBeanstalkEnv_platformArn'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./... -v -run=TestAccAWSBeanstalkEnv_platformArn -timeout 120m
?   	github.com/terraform-providers/terraform-provider-aws	[no test files]
=== RUN   TestAccAWSBeanstalkEnv_platformArn
--- PASS: TestAccAWSBeanstalkEnv_platformArn (494.89s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	494.914s
```

### CODE REVIEW

**Comment by jbienkowski311** [comment]
Hi @bflad :wave: Thanks for the review. I think I have fixed all the pointed issues. The test still passes, so nothing got broken :wink:  

```
$ make testacc TESTARGS='-run=TestAccAWSBeanstalkEnv_platformArn'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./... -v -run=TestAccAWSBeanstalkEnv_platformArn -timeout 120m
?   	github.com/terraform-providers/terraform-provider-aws	[no test files]
=== RUN   TestAccAWSBeanstalkEnv_platformArn
--- PASS: TestAccAWSBeanstalkEnv_platformArn (486.35s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	486.373s
```

**Comment by bflad** [comment]
Yay! Thats great news, although it looks like AWS will automatically fill in `PlatformArn` when defining the environment in other ways, e.g.

```
--- FAIL: TestAccAWSBeanstalkEnv_basic_settings_update (409.34s)
    testing.go:527: Step 0 error: After applying this step, the plan was not empty:
        
        DIFF:
        
        UPDATE: aws_elastic_beanstalk_environment.tfenvtest
          platform_arn: "arn:aws:elasticbeanstalk:us-west-2::platform/Python 2.6 running on 64bit Amazon Linux/0.1.0" => ""
```

My recommendation would be to add `Computed: true` to the `platform_arn` in this case, which is safe since the attribute conflicts with the other attributes. 👍

**Comment by jbienkowski311** [comment]
Hi @bflad, I have rerun the whole `TestAccAWSBeanstalkEnv_` test suite. One test seems to be broken, not sure if I should fix it or not - let me know. Also the output is in batches, because I have hit the timeout of 2hours...

```
$ make testacc TEST=./aws TESTARGS='-run=TestAccAWSBeanstalkEnv_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -run=TestAccAWSBeanstalkEnv_ -timeout 120m
=== RUN   TestAccAWSBeanstalkEnv_basic
--- PASS: TestAccAWSBeanstalkEnv_basic (509.68s)
=== RUN   TestAccAWSBeanstalkEnv_tier
--- PASS: TestAccAWSBeanstalkEnv_tier (639.01s)
=== RUN   TestAccAWSBeanstalkEnv_outputs
--- PASS: TestAccAWSBeanstalkEnv_outputs (476.72s)
=== RUN   TestAccAWSBeanstalkEnv_cname_prefix
--- PASS: TestAccAWSBeanstalkEnv_cname_prefix (546.04s)
=== RUN   TestAccAWSBeanstalkEnv_config
--- PASS: TestAccAWSBeanstalkEnv_config (634.75s)
=== RUN   TestAccAWSBeanstalkEnv_resource
--- PASS: TestAccAWSBeanstalkEnv_resource (688.12s)
=== RUN   TestAccAWSBeanstalkEnv_tags
--- PASS: TestAccAWSBeanstalkEnv_tags (931.26s)
=== RUN   TestAccAWSBeanstalkEnv_vpc
--- PASS: TestAccAWSBeanstalkEnv_vpc (585.39s)
=== RUN   TestAccAWSBeanstalkEnv_template_change
--- FAIL: TestAccAWSBeanstalkEnv_template_change (425.34s)
    testing.go:527: Step 0 error: Error applying: 1 error occurred:
        	* aws_elastic_beanstalk_configuration_template.template: 1 error occurred:
        	* aws_elastic_beanstalk_configuration_template.template: Error creating Elastic Beanstalk configuration template: InvalidParameterValue: No Solution Stack named '64bit Amazon Linux 2016.03 v2.1.3 running Go 1.5' found.
        	status code: 400, request id: 3b60019f-fbdb-40ea-9379-86c7c26cca91      
=== RUN   TestAccAWSBeanstalkEnv_basic_settings_update
--- PASS: TestAccAWSBeanstalkEnv_basic_settings_update (794.85s)
=== RUN   TestAccAWSBeanstalkEnv_version_label
--- PASS: TestAccAWSBeanstalkEnv_version_label (699.70s)
=== RUN   TestAccAWSBeanstalkEnv_settingWithJsonValue
panic: test timed out after 2h0m0s

$ make testacc TEST=./aws TESTARGS='-run=TestAccAWSBeanstalkEnv_platformArn'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -run=TestAccAWSBeanstalkEnv_platformArn -timeout 120m
=== RUN   TestAccAWSBeanstalkEnv_platformArn
--- PASS: TestAccAWSBeanstalkEnv_platformArn (471.23s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	471.255s

$ make testacc TEST=./aws TESTARGS='-run=TestAccAWSBeanstalkEnv_settingWithJsonValue'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -run=TestAccAWSBeanstalkEnv_settingWithJsonValue -timeout 120m
=== RUN   TestAccAWSBeanstalkEnv_settingWithJsonValue
--- PASS: TestAccAWSBeanstalkEnv_settingWithJsonValue (506.60s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	506.622s
```

**Comment by bflad** [comment]
Regarding hitting the acceptance testing timeout, once Terraform 0.11.9 is tagged and released, I will pull in the dependency and implement https://github.com/terraform-providers/terraform-provider-aws/issues/5874

In the meantime, you can _temporarily_ (we don't want to mess up the above process) add `t.Parallel()` to each of the acceptance testing functions as necessary and then remove that before committing. It will default `-parallel` to the number of CPUs but we normally run our CI server with 20 parallelism just fine. 😄

**Comment by bflad** [comment]
Interestingly enough that test passes in our CI environment with `AWS_DEFAULT_REGION` set to `us-west-2` -- feel free to take a look if you wish, but shouldn't be an issue for merging this PR. I'm working on running the tests now.

**Comment by jbienkowski311** [comment]
I used `AWS_DEFAULT_REGION` set to `us-east-1` and it was failing, so maybe that's why.

**Comment by bflad** [comment]
This has been released in [version 1.40.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1400-october-10-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.

**Pull request merged**
