### PR TITLE
adding aws_vpc_peering_connections

### LINKED ISSUE #6350: add aws_vpc_peering_connections to list all available peering connections
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

* Add aws_vpc_peering_connections
list all peering connections using filters, returning ids, cidr_blocks
and peer_cidr_blocks
useful when trying to build route tables between vpcs with multiple
peering connections managed in different state files

### New or Affected Resource(s)

* aws_vpc_peering_connections

### Potential Terraform Configuration

```hcl
# Declare the data source
data "aws_vpc_peering_connections" "pcs" {
  filter {
    name = "requester-vpc-info.vpc-id"
    values = ["${aws_vpc.foo.id}"]
  }
}

# Create a route table
resource "aws_route_table" "rt" {
  vpc_id = "${aws_vpc.foo.id}"
}

# Create a route
resource "aws_route" "r" {
  count                     = "${length(data.aws_vpc_peering_connections.pcs.ids)}"
  route_table_id            = "${aws_route_table.rt.id}"
  destination_cidr_block    = "${element(data.aws_vpc_peering_connections.pcs.peer_cidr_blocks, count.index)}"
  vpc_peering_connection_id = "${element(data.aws_vpc_peering_connections.pcs.ids, count.index)}"
}
```

### PR DESCRIPTION
**Pull request by moshea**
Fixes #6350

Changes proposed in this pull request:

* Add aws_vpc_peering_connections
list all peering connections using filters, returning ids, cidr_blocks
and peer_cidr_blocks
useful when trying to build route tables between vpcs with multiple
peering connections managed in different state files

Output from acceptance testing:

```
$ TEST="github.com/terraform-providers/terraform-provider-aws/aws -run TestAccDataSou
rceAwsVpcPeeringConnections_basic" make testacc
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test github.com/terraform-providers/terraform-provider-aws/aws -run TestAccDataSourceAwsVpcPeeringConnections_basic -v  -timeout 120m
=== RUN   TestAccDataSourceAwsVpcPeeringConnections_basic
--- PASS: TestAccDataSourceAwsVpcPeeringConnections_basic (77.57s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	77.614s
...
```

### CODE REVIEW

**Comment by ewbankkit** [comment]
It may be unnecessary to return `cidr_blocks` and `peer_cidr_blocks` from the new `aws_vpc_peering_connections` data source but instead to follow the pattern of the [`aws_route_tables`](https://www.terraform.io/docs/providers/aws/d/route_tables.html)/[`aws_route_table`](https://www.terraform.io/docs/providers/aws/d/route_table.html) and [`aws_subnet_ids`](https://www.terraform.io/docs/providers/aws/d/subnet_ids.html)/[`aws_subnet`](https://www.terraform.io/docs/providers/aws/d/subnet.html) data sources and just return `ids` from the new data source and use the [`aws_vpc_peering_connection`](https://www.terraform.io/docs/providers/aws/d/vpc_peering_connection.html) data source to obtain the various CIDR blocks (and other attributes).
Something like:

```hcl
data "aws_vpc_peering_connection_ids" "pcs" {
  filter {
    name = "requester-vpc-info.vpc-id"
    values = ["${aws_vpc.foo.id}"]
  }
}

data "aws_vpc_peering_connection" "pc" {
  count = "${length(data.aws_vpc_peering_connection_ids.example.ids)}"
  id = "${data.aws_vpc_peering_connection_ids.pcs.ids[count.index]}"
}
```

We're not consistent with our naming, so the new data source could be named `aws_vpc_peering_connections` or `aws_vpc_peering_connection_ids`.

**Comment by moshea** [comment]
@ewbankkit, your point makes sense, and is a better convention, as it keeps the code more DRY, to rely on the single data source to get all the information, while the list only returns IDs
renamed it to `aws_vpc_peering_connection_ids`
Code and documentation updated, and tests are still passing!

```
/go/src/github.com/terraform-providers/terraform-provider-aws # TEST="github.com/terraform-providers/terraform-provider-aws/aws -run TestAccDataSou
rceAwsVpcPeeringConnectionIds_basic" make testacc
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test github.com/terraform-providers/terraform-provider-aws/aws -run TestAccDataSourceAwsVpcPeeringConnectionIds_basic -v  -timeout 120m
=== RUN   TestAccDataSourceAwsVpcPeeringConnectionIds_basic
--- PASS: TestAccDataSourceAwsVpcPeeringConnectionIds_basic (59.32s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	59.344s
```

**Comment by bflad** [comment]
Sorry for any confusion with the "plural" data source naming. We prefer `aws_SERVICE_THINGs` going forward to allow for future enhancements that may include other attributes. e.g. `aws_subnet_ids` will likely return ARNs as well, so it would make more sense as `aws_subnets` from a naming perspective. I'd imagine the same applies here.

We'll eventually alias and likely deprecate the existing `_ids` data sources at some point in the future.

**Comment by moshea** [comment]
No problem @bflad, renamed the function back to vpc_peering_connections to keep with naming conventions. Ran tests and they are still passing

```
/go/src/github.com/terraform-providers/terraform-provider-aws # TEST="github.com/terraform-providers/terraform-provider-aws/aws -run TestAccDataSourceAwsVpcPeeringConnections_basic" make testacc
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test github.com/terraform-providers/terraform-provider-aws/aws -run TestAccDataSourceAwsVpcPeeringConnections_basic -v  -timeout 120m
=== RUN   TestAccDataSourceAwsVpcPeeringConnections_basic
--- PASS: TestAccDataSourceAwsVpcPeeringConnections_basic (104.57s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	104.599s
```

**Comment by cxfcxf** [comment]
was implanting the same thing, found it after i finished. same idea

suggest put a EC2AttributeFilterList which takes status as a filter

```go
	req.Filters = buildEC2AttributeFilterList(
		map[string]string{
			"status-code": d.Get("status").(string),
		},
	)
```

**Comment by ewbankkit** [comment]
Closing this one as it has been replaced by #9491.

**Pull request closed without merging**
