### PR TITLE
Support volume type io2

### LINKED ISSUE #14817: resource/aws_ebs_volume: support io2 volume type
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS have [introduced](https://aws.amazon.com/blogs/aws/new-ebs-volume-type-io2-more-iops-gib-higher-durability/) the `io2` volume type. On create, the `aws_ebs_volume` resource [currently rejects](https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/resource_aws_ebs_volume.go#L128) the `iops` attribute for volumes that are not `io1`.

Requires Go SDK 1.34.10.

### New or Affected Resource(s)

* aws_ebs_volume

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* https://aws.amazon.com/blogs/aws/new-ebs-volume-type-io2-more-iops-gib-higher-durability/
* https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/resource_aws_ebs_volume.go#L128

### PR DESCRIPTION
**Pull request by nikhil-goenka**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates OR Closes #14817

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note

```

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccAWSInstance_EbsRootDevice_ModifyIOPS'
--- PASS: TestAccAWSInstance_EbsRootDevice_ModifyIOPS_Io2 (240.86s)
--- PASS: TestAccAWSInstance_EbsRootDevice_ModifyIOPS_Io1 (241.39s)
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws       241.812s
...
```

### CODE REVIEW

**Comment by bflad** [comment]
Hi @nikhil-goenka 👋  Thank you so much for updating these as well -- while we are updating these enumeration validations, could you switch these to using the newly available and automatically updating `ec2.VolumeType_Values()` so we no longer need to manually manage them? See also #14601. Cheers! e.g.

```go
ValidationFunc: validation.StringInSlice(ec2.VolumeType_Values(), false),
```

**Comment by nikhil-goenka** [comment]
> Hi @nikhil-goenka 👋 Thank you so much for updating these as well -- while we are updating these enumeration validations, could you switch these to using the newly available and automatically updating `ec2.VolumeType_Values()` so we no longer need to manually manage them? See also #14601. Cheers! e.g.
> 
> ```go
> ValidationFunc: validation.StringInSlice(ec2.VolumeType_Values(), false),
> ```

sure

**Comment by bflad** [comment]
Running `make fmt` should fix the linter errors 👍

**Comment by nikhil-goenka** [comment]
> Running `make fmt` should fix the linter errors 👍

great, that worked

**Pull request merged**
