### PR TITLE
MSK clusters

### LINKED ISSUE #6653: Feature Request: Managed Streaming for Kafka
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS now offers managed Kafka clusters

### New or Affected Resource(s)

* aws_msk_cluster

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* https://docs.aws.amazon.com/msk/index.html#lang/en_us

### PR DESCRIPTION
**Pull request by dthtvwls**
This is a continuation of #6809 addressing all the feedback received so far. I have taken over this PR since the original requester no longer has time to work on it.

The acceptance tests appear to need some work. My suspicion is that they may only need to be modified to handle the changes in code that have occurred since they were written.

However, I am hopeful that this can still receive a fresh round of feedback while I figure out how to fix the acceptance tests.

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" comments, they generate extra noise for pull request followers and do not help prioritize the request

Fixes #6653 

Changes proposed in this pull request:

* Add support for MSK

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccXXX'

(needs work still, as mentioned above)
```

### CODE REVIEW

**Comment by ewbankkit** [comment]
@dthtvwls As of [AWS SDK v1.19.14](https://github.com/aws/aws-sdk-go/releases/tag/v1.19.14), merged in https://github.com/terraform-providers/terraform-provider-aws/pull/8381, it looks like Kafka clusters now support resource tagging.
Not sure if you want to include this functionality in the initial PR or address in a subsequent one.

**Comment by dthtvwls** [comment]
@ewbankkit @bflad was kind enough to provide a thorough review of the original PR and in the interest of getting this merged expediently I am not planning to expand the scope. Still trying to find time to figure out the acceptance tests.

**Comment by ewbankkit** [comment]
@dthtvwls No worries. I'll open an issue and link to this PR.

**Comment by Richard-Mathie** [comment]
So looking forward to this being released. whats blocking it at the moment?

**Comment by hExPY** [comment]
+1

**Comment by mrf** [comment]
@Richard-Mathie acceptance tests aren't passing and it looks like a couple of small merge conflicts now need to be resolved in this branch.

**Comment by dthtvwls** [comment]
If anybody has experience with Terraform acceptance tests, would you mind taking a look? I've been having trouble making significant progress that I can tell. Some of them are failing but giving no output, so, it's been difficult.

**Comment by bflad** [comment]
Hey @dthtvwls 👋 I was planning on reviewing this tomorrow, but looks like you're stuck on the testing. Would you prefer to step through troubleshooting or just get feedback on how things were adjusted? We can work however you prefer and if you have time. We do have a hard timeline for merging MSK support approaching (for reasons I cannot say 😉) so we cannot spend too long on review cycles but we definitely want to help you on your contributing journey. Let us know!

You might find turning on a debug logging helpful, e.g. to log to `/tmp/log.txt`:

```
$ rm -f /tmp/log.txt; TF_LOG_PATH=/tmp/log.txt TF_LOG=debug TF_ACC=1 go test ./aws -v -timeout 120m -parallel 20 -run='TestAccAWSMskCluster_'
```

**Comment by dthtvwls** [comment]
@bflad That is very helpful to know actually. For what it's worth however, I think that #8635 would make a better choice for merging, for several reasons. I will probably be closing this PR in favor of that one soon, unless there is some kind of outcry.

**Comment by bflad** [comment]
Thanks for the note, @dthtvwls, and the work you had done here! We just merged in #8635 which will release with version 2.12.0 of the Terraform AWS Provider. Hopefully this was a great learning process and it will be great to see future contributions from you!

**Pull request closed without merging**
