### PR TITLE
Optionally filter server certificates by path prefix.

### PR DESCRIPTION
**Pull request by jmcarp**
Not sure how to test this, but the code is pretty straightforward.

### CODE REVIEW

**Comment by bflad** [comment]
Considering its built into the API 👍  I would just also expect a quick acceptance test as well.

**Comment by jmcarp** [comment]
Updated with a test:

```
± TF_ACC=1 go test -v github.com/terraform-providers/terraform-provider-aws/aws -run=TestAccAWSDataSourceIAMServerCertificate_
=== RUN   TestAccAWSDataSourceIAMServerCertificate_basic
--- PASS: TestAccAWSDataSourceIAMServerCertificate_basic (13.31s)
=== RUN   TestAccAWSDataSourceIAMServerCertificate_matchNamePrefix
--- PASS: TestAccAWSDataSourceIAMServerCertificate_matchNamePrefix (2.00s)
=== RUN   TestAccAWSDataSourceIAMServerCertificate_path
--- PASS: TestAccAWSDataSourceIAMServerCertificate_path (11.60s)
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws       26.967s
```

**Comment by jmcarp** [comment]
Ready for review @bflad

**Comment by jmcarp** [comment]
Bump @bflad @radeksimko 😄

**Pull request merged**
