### PR TITLE
resource/aws_dynamodb_table: Update and validate attributes

### LINKED ISSUE #1424: state does not update after running terraform apply
_This issue was originally opened by @YiyangXu as hashicorp/terraform#15807. It was migrated here as a result of the [provider split](https://www.hashicorp.com/blog/upcoming-provider-changes-in-terraform-0-10/). The original body of the issue is below._

<hr>

Hi there,
I am in a situation when terraform apply showed a correct behavior in terminal but the state does not actually update and the change did not deployed in aws. 

```sh
$ terraform apply
```
```
aws_dynamodb_table.session-table: Refreshing state... (ID: account-service-session-db)
aws_dynamodb_table.session-table: Modifying... (ID: account-service-session-db)
  attribute.#:               "2" => "4"
  attribute.1670162472.name: "" => "lastUpdateDate"
  attribute.1670162472.type: "" => "N"
  attribute.2901025699.name: "accountID" => "accountID"
  attribute.2901025699.type: "N" => "N"
  attribute.646540669.name:  "token" => "token"
  attribute.646540669.type:  "S" => "S"
  attribute.987920283.name:  "" => "createDate"
  attribute.987920283.type:  "" => "N"
aws_dynamodb_table.session-table: Modifications complete (ID: account-service-session-db)

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.
```

```sh
$ terraform show
```
```
aws_dynamodb_table.session-table:
  id = account-service-session-db
  arn = arn:aws:dynamodb:us-west-2:113514851486:table/account-service-session-db
  attribute.# = 2
  attribute.2901025699.name = accountID
  attribute.2901025699.type = N
  attribute.646540669.name = token
  attribute.646540669.type = S
  global_secondary_index.# = 0
  hash_key = token
  local_secondary_index.# = 0
  name = account-service-session-db
  range_key = accountID
  read_capacity = 5
  write_capacity = 5
```

### PR DESCRIPTION
**Pull request by radeksimko**
Fixes #1424

## Test results

```
=== RUN   TestAccAWSDynamoDbTable_attributeUpdateValidation
--- PASS: TestAccAWSDynamoDbTable_attributeUpdateValidation (2.97s)
=== RUN   TestAccAWSDynamoDbTable_tags
--- PASS: TestAccAWSDynamoDbTable_tags (53.09s)
=== RUN   TestAccAWSDynamoDbTable_importTimeToLive
--- PASS: TestAccAWSDynamoDbTable_importTimeToLive (53.51s)
=== RUN   TestAccAWSDynamoDbTable_ttl
--- PASS: TestAccAWSDynamoDbTable_ttl (113.45s)
=== RUN   TestAccAWSDynamoDbTable_importBasic
--- PASS: TestAccAWSDynamoDbTable_importBasic (127.66s)
=== RUN   TestAccAWSDynamoDbTable_importTags
--- PASS: TestAccAWSDynamoDbTable_importTags (127.85s)
=== RUN   TestAccAWSDynamoDbTable_gsiUpdateNonKeyAttributes
--- PASS: TestAccAWSDynamoDbTable_gsiUpdateNonKeyAttributes (146.59s)
=== RUN   TestAccAWSDynamoDbTable_streamSpecification
--- PASS: TestAccAWSDynamoDbTable_streamSpecification (168.25s)
=== RUN   TestAccAWSDynamoDbTable_gsiUpdateCapacity
--- PASS: TestAccAWSDynamoDbTable_gsiUpdateCapacity (312.93s)
=== RUN   TestAccAWSDynamoDbTable_gsiUpdateOtherAttributes
--- PASS: TestAccAWSDynamoDbTable_gsiUpdateOtherAttributes (452.91s)
=== RUN   TestAccAWSDynamoDbTable_attributeUpdate
--- PASS: TestAccAWSDynamoDbTable_attributeUpdate (458.46s)
=== RUN   TestAccAWSDynamoDbTable_basic
--- PASS: TestAccAWSDynamoDbTable_basic (461.79s)
```

### CODE REVIEW

**Comment by bflad** [comment]
FYI this requires a rebase for `aws/validators.go`

Can you find documentation to support this? `Indexes and attributes are tightly coupled (DynamoDB disallows unindexed attributes)` I don't remember this being a limitation of the service in the [DynamoDB documentation](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/HowItWorks.CoreComponents.html)

**Comment by radeksimko** [comment]
> Can you find documentation to support this? Indexes and attributes are tightly coupled (DynamoDB disallows unindexed attributes) I don't remember this being a limitation of the service nor does it explicitly state that in the DynamoDB documentation.

I came to that conclusion after:

a. Getting this error message:

```
ValidationException: One or more parameter values were invalid: Some AttributeDefinitions are not used. AttributeDefinitions: [TestGSIRangeKey, TestTableHashKey, TestLSIRangeKey, TestTableRangeKey], keys used: [TestTableRangeKey, TestTableHashKey, TestLSIRangeKey]
	status code: 400, request id: 9A6QGJAD38PD94IV10GJ8G2DM3VV4KQNSO5AEMVJF66Q9ASUAAJG
```

b. When DynamoDB removed an attribute during `UpdateTable` which was removing the only index that was referencing that field.

I however agree it's not very clear and we should get a confirmation from AWS support and perhaps paste it here. I'll reach out to them.

**Comment by radeksimko** [comment]
AWS support just confirmed what I wrote above:

> 00:17:12 PM **radek**: right, that's what I thought, so AttributeDefinitions in the API is basically a schema for indexes. It obviously doesn't define schema for records (as DDB is schemaless), but any attribute which is used in KeySchema and/or in GSI and/or LSI has to be in that list (AttributeDefinitions)?
> 00:18:43 PM **AWS**: yup..

Admittedly my comment may be suggesting DynamoDB requires you to define schema for all attributes, but that's partially because of how much the resource schema is drifted from API's naming convention. Maybe if `attribute` was `attribute_definition` it would be slightly more obvious? I'm open to suggestions.

**Comment by bflad** [comment]
Ah okay - this makes more sense. Thank you for clarifying here!

I just wanted to be sure this configuration is still valid (you can have attribute definitions that are not indexed):

```hcl
resource "aws_dynamodb_table" "basic-dynamodb-table" {
  name = "%s"
  read_capacity = 10
  write_capacity = 10
  hash_key = "staticHashKey"

  attribute {
    name = "staticHashKey"
    type = "S"
  }
 
  attribute {
    name = "indexed"
    type = "%s"
  }

  attribute {
    name = "notIndexed"
    type = "%s"
  }
 
   global_secondary_index {
     name = "gsiName"
     hash_key = "indexed"
     write_capacity = 10
     read_capacity = 10
     projection_type = "KEYS_ONLY"
   }
 }
```

Maybe some simple rewording of comments/variable names like this would help me personally (and potentially other future code readers) 😄 
* `s/DynamoDB disallows unindexed attributes/DynamoDB requires attribute definitions for all indexed attributes/`
* `s/Check if all attributes are indexed/Check if all indexed attributes have an attribute definition/`
* `s/unusedAttributes/missingAttributeDefintions/`

What do you think? Otherwise, I think this is good to go.

**Comment by radeksimko** [comment]
Currently blocked by https://github.com/hashicorp/terraform/pull/17261

**Comment by bflad** [comment]
Update: we're still waiting on upstream Terraform core 0.11.4 release (rather than vendoring a commit SHA)

**Comment by radeksimko** [comment]
Rebased & ran related acceptance tests - all green, so I'm going to merge this.

**Comment by bflad** [comment]
This has been released in [version 1.12.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1120-march-23-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.

**Pull request merged**
