### PR TITLE
[WIP]Transfer Server Support VPC Endpoint Type

### LINKED ISSUE #11569: aws_transfer_server: support Elastic IPs
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
AWS Transfer now supports Elastic IPs. With this, there's no more need to create a NLB to expose the server in known IP address.

Terraform provider should support these as well.

### New or Affected Resource(s)
* `aws_transfer_server`

### Potential Terraform Configuration

```hcl
resource "aws_transfer_server" "foo" {
  endpoint_details {
    address_allocation_ids = ["eipalloc-..."]
    subnet_ids = ["subnet-..."]
    vpc_id = "vpc-..."
    vpc_endpoint_id = "vpce-..."
  }
  endpoint_type = "VPC"
}
```

### References
Announcement: https://aws.amazon.com/about-aws/whats-new/2020/01/aws-transfer-for-sftp-supports-vpc-security-groups-and-elastic-ip-addresses/
Docs: https://docs.aws.amazon.com/transfer/latest/userguide/create-sftp-server-in-vpc.html
Requires [AWS SDK v1.28.0](https://github.com/aws/aws-sdk-go/releases/tag/v1.28.0):
* #11501

### LINKED ISSUE #11593: AWS Sftp now support elastic ips
_This issue was originally opened by @KVInventoR as hashicorp/terraform#23851. It was migrated here as a result of the [provider split](https://www.hashicorp.com/blog/upcoming-provider-changes-in-terraform-0-10/). The original body of the issue is below._
    
<hr>
    
Hi All

A lot of time ago, AWS announced supports security groups and elastic ip addresses for sftp server:
https://aws.amazon.com/about-aws/whats-new/2020/01/aws-transfer-for-sftp-supports-vpc-security-groups-and-elastic-ip-addresses/

do you have a plans to support it in aws module?

According to documentation: 
https://docs.aws.amazon.com/cli/latest/reference/transfer/create-server.html

it's possible to set different options:
```--endpoint-type (string)

The type of VPC endpoint that you want your SFTP server to connect to. You can choose to connect to the public internet or a virtual private cloud (VPC) endpoint. With a VPC endpoint, you can restrict access to your SFTP server and resources only within your VPC.

Possible values:

PUBLIC
VPC
VPC_ENDPOINT
```

but yours:
https://www.terraform.io/docs/providers/aws/r/transfer_server.html
supports only PUBLIC
```
endpoint_type - (Optional) The type of endpoint that you want your SFTP server connect to. If you connect to a VPC_ENDPOINT, your SFTP server isn't accessible over the public internet. If you want to connect your SFTP server via public internet, set PUBLIC. Defaults to PUBLIC.

```

any plans to update sftp server?

### LINKED ISSUE #11724: aws_transfer_server does not currently support endpoint_type: "VPC"
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
Terraform v0.12.20
+ provider.aws v2.44.0
```

### Affected Resource(s)

* aws_transfer_server

### Terraform Configuration Files

```hcl
resource "aws_transfer_server" "main" {
  identity_provider_type = "SERVICE_MANAGED"
  logging_role                 =  aws_iam_role.transfer.arn
  endpoint_type              = "VPC"

  tags = {
    NAME = "transfer-server"
  }

  endpoint_details {
    vpc_endpoint_id = aws_vpc_endpoint.transfer.id
  }
}

```

### Debug Output

```
Error: expected endpoint_type to be one of [PUBLIC VPC_ENDPOINT], got VPC
```

### Expected Behavior

Updated endpoint type to VPC.

### Actual Behavior

Produced error above: `Error: expected endpoint_type to be one of [PUBLIC VPC_ENDPOINT], got VPC`

### Steps to Reproduce

1. Create publicly-available Transfer server (& terraform apply):
```
resource "aws_iam_role" "transfer" {
  name = "transfer-server-iam-role"

  assume_role_policy = <<EOF
{
    "Version": "2012-10-17",
    "Statement": [
        {
        "Effect": "Allow",
        "Principal": {
            "Service": "transfer.amazonaws.com"
        },
        "Action": "sts:AssumeRole"
        }
    ]
}
EOF
}

resource "aws_transfer_server" "main" {
  identity_provider_type = "SERVICE_MANAGED"
  logging_role           = "${aws_iam_role.transfer.arn}"
  endpoint_type          = "PUBLIC"

  tags = {
    NAME = "transfer-server"
  }
}
```
2. Create dependencies for the changes we're about to make in the AWS console (& terraform apply):

```hcl
variable "aws_az1" {
  description = "AWS availability zone 1"
  default     = "us-east-1a"
}

variable "aws_az2" {
  description = "AWS availability zone 2"
  default     = "us-east-1b"
}

resource "aws_vpc" "main" {
  cidr_block = "10.0.0.0/16"
  enable_dns_hostnames = true
}

resource "aws_subnet" "public" {
  vpc_id = "${aws_vpc.main.id}"
  cidr_block = "10.0.0.0/16"
  availability_zone = "${var.aws_az2}"

  tags = {
    name = "cmr-datashare-public"
  }
}

resource "aws_internet_gateway" "default" {
  vpc_id = "${aws_vpc.main.id}"
}

resource "aws_route_table" "internet_access" {
  vpc_id = "${aws_vpc.main.id}"

  route {
    cidr_block = "0.0.0.0/0"
    gateway_id = "${aws_internet_gateway.default.id}"
  }
}

resource "aws_route_table_association" "subnet_route_table" {
  subnet_id = "${aws_subnet.public.id}"
  route_table_id = "${aws_route_table.internet_access.id}"
}

resource  "aws_eip" "sftp" {
  vpc = true
  depends_on = [
    "aws_internet_gateway.default"
  ]
}

# Stays the same:
resource "aws_iam_role" "transfer" {
  name = "transfer-server-iam-role"

  assume_role_policy = <<EOF
{
    "Version": "2012-10-17",
    "Statement": [
        {
        "Effect": "Allow",
        "Principal": {
            "Service": "transfer.amazonaws.com"
        },
        "Action": "sts:AssumeRole"
        }
    ]
}
EOF
}

resource "aws_transfer_server" "main" {
  identity_provider_type = "SERVICE_MANAGED"
  logging_role           = "${aws_iam_role.transfer.arn}"
  endpoint_type          = "PUBLIC"

  tags = {
    NAME = "transfer-server"
  }
}
```
3. In AWS console, visit your Transfer server. Stop instance and click "edit", change to be of type "VPC". Associate the resources you made in the previous step.

Screen Shot 2020-01-22 at 4 13 09 PM

4. Save changes to server and start again.

5. If you now `terraform apply` again, you'll see that the endpoint type for the `aws_transfer_server` wants to change as follows: `~ endpoint_type          = "VPC" -> "PUBLIC"`. If you try to change the terraform config to `endpoint_type = "VPC"` then you get the following error: `Error: expected endpoint_type to be one of [PUBLIC VPC_ENDPOINT], got VPC`.

### Important Factoids

It seems like AWS is encouraging people to use the "VPC" endpoint instead of the "VPC_ENDPOINT" endpoint type in the AWS Console and the docs (see reference below). The VPC_ENDPOINT is not available as an option if you create the Transfer server from scratch in the AWS console.

### References

* [AWS Docs: Creating an Internet-Facing Endpoint for Your SFTP Server](https://docs.aws.amazon.com/transfer/latest/userguide/create-sftp-server-in-vpc.html#create-internet-facing-endpoint)
* [AWS Docs: Moving away from VPC_ENDPOINT](https://docs.aws.amazon.com/transfer/latest/userguide/create-sftp-server-in-vpc.html#change-sftp-server-endpoint-type): "If you have an existing AWS SFTP server in a VPC displayed as VPC_ENDPOINT, we recommend that you modify it to the new VPC endpoint type. With this new endpoint type, you no longer need to use a Network Load Balancer (NLB) to associate Elastic IP addresses with your server's endpoint. Also, you can use VPC security groups to restrict access to your server's endpoint. However, you can continue to use the VPC_ENDPOINT endpoint type as needed."

### PR DESCRIPTION
**Pull request by DrFaust92**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #11724
Closes #11569
Closes #11593

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
resource_aws_transfer_server: support` VPC` endpoint type
```

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccXXX'

...
```

### CODE REVIEW

**Comment by DrFaust92** [comment]
Having issues with this as describing the transfer server returns an empty list of eip association ids.
Tried putting a sleep of a few minutes before the read, didnt help. seems like a bug on AWS side.

**Comment by bazimov** [comment]
One thing I noticed, probably you know already. I tried to launch sftp from console. With this feature AWS launched VPC endpoint automatically, I did not expect that, I had to attach security group to that vpc endpoint afterwards.

**Comment by ChristianPe** [comment]
Im stuck with the same problem as the previous poster. After creating a sftp server with endpoint style "vpc" there is no way to change/attach security groups with terraform, since one can not change the network interfaces nor get the endpoint resource to attach new security groups. Or do I get something wrong here?

**Comment by marcoreni** [comment]
@DrFaust92 according to the [doc](https://docs.aws.amazon.com/sdk-for-go/api/service/transfer/#EndpointDetails) you can use EndpointDetails/AddressAllocationIds only during UpdateServer calls. Maybe this is the reason why you're obtaining an empty list during the describe?

@bazimov @ChristianPe since a vpc endpoint is internally created by AWS when using VPC Endpoint Type, maybe we can create a vpce manually in Terraform and set that inside the SFTP Server resource during creation, so that AWS doesn't create one by himself. With this we can add SGs directly to the vpce as usual. (NOTE: I haven't tried this, I'm just making assumptions).

**Comment by DrFaust92** [comment]
@marcoreni, i think that's the reason as well, albeit its a stupid on IMO
for the second comment, that wont work as you can specify an endpoint when the type is `VPC`

**Comment by mbelang** [comment]
What is the progress on this?

**Comment by DrFaust92** [comment]
just to update all that are expecting this, the AWS API for transfer server doesn't return the IPs allocated to it and causes a perpetual diff. i dont want to mix another api all to EC2 services for this.
ill try to think of a workaround in the next couple of days for this and update again.

**Comment by sshearn** [comment]
@DrFaust92 I'm not sure what issues you're seeing exactly but I have it fully working here #12599. Including support for the VPCE SG.

**Comment by DrFaust92** [comment]
@sshearn, your PR calls 2 different service APIs. it's not a common workaround in the provider (i can't really find an an example, possibly its the same with Lambda ENIs)
i noted it's not a solution i want to work with in this PR (unless mainteners approve).

@bflad, thoughts?

**Comment by sshearn** [comment]
@DrFaust92 I was referring to specifically 

> the AWS API for transfer server doesn't return the IPs allocated to it and causes a perpetual diff.

I don't see this happening. For example:

`% aws transfer describe-server --server-id ***
{
    "Server": {
        "Arn": "***",
        "EndpointDetails": {
            "AddressAllocationIds": [
                "***",
                "***",
                "***"
            ],
            "SubnetIds": [
                "***",
                "***",
                "***"
            ],
            "VpcEndpointId": "***",
            "VpcId": "***"
        },
        "EndpointType": "VPC",
        "HostKeyFingerprint": "***",
        "IdentityProviderType": "SERVICE_MANAGED",
        "LoggingRole": "***",
        "ServerId": ***",
        "State": "ONLINE",
        "Tags": [],
        "UserCount": 2
    }
}
`

**Comment by DrFaust92** [comment]
@sshearn ill take look again

**Comment by DrFaust92** [comment]
A thought, adding an additional update call in the read func to get the IPs. I would really hate to do it but I'll give it a go

**Comment by DrFaust92** [comment]
Closing in favor of #12599

**Pull request closed without merging**
