### PR TITLE
Add Support For AWS Service Catalog

### PR DESCRIPTION
**Pull request by bw-intuit**
This is an initial PR to add support for [AWS service catalog](https://aws.amazon.com/servicecatalog/).  Provides resources to manage a portfolio, product and associate them (minimum required functionality for service catalog use).

I will be adding additional resources and capabilities over the next few weeks.  I wanted to get early feedback on the code for inclusion.

Thanks

Fixes: https://github.com/hashicorp/terraform/issues/10865

### CODE REVIEW

**Comment by Ninir** [comment]
Hi @bw-intuit 

Thanks for your work: looks amazing :)

I think we should split it in several PRs, for easier code reviews. One for vendoring, one for the main resource, one for another resource, and so on. 

What do you think?

Thanks!

**Comment by bw-intuit** [comment]
@ninir sounds good, will submit shortly

**Comment by ozbillwang** [comment]
@bw-intuit 

Thanks to add this new resource `aws_servicecatalog_portfolio`. But seems this is only for creating/manage a portfolio.

But how to manage the production, share the portfolio, and others about this service? For example:

create-constraint
create-portfolio **(created)**
create-portfolio-share
create-product
create-provisioned-product-plan
create-provisioning-artifact
create-service-action

**Comment by bw-intuit** [comment]
@ozbillwang unfortunately I was never able to get this fully merged into the mainline.

I have the following additional resources available on a fork:

https://github.com/bw-intuit/intu-terraform-provider-aws/blob/master/aws/resource_aws_servicecatalog_principal_association_portfolio.go

https://github.com/bw-intuit/intu-terraform-provider-aws/blob/master/aws/resource_aws_servicecatalog_product.go

https://github.com/bw-intuit/intu-terraform-provider-aws/blob/master/aws/resource_aws_servicecatalog_product_association.go

https://github.com/terraform-providers/terraform-provider-aws/pull/2064

Unforutnaltey I have moved to another project and won't likely have time to drive getting them merged.

**Pull request closed without merging**
