### PR TITLE
[WIP] feat(resource_vpc_flow_log): added max_aggregation_interval field

### LINKED ISSUE #11927: Amazon VPC Flow Logs now support 1-minute aggregation intervals
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

> You can now capture and aggregate your Amazon Virtual Private Cloud (Amazon VPC) flow logs at shorter intervals of up to 1 minute, giving you quicker visibility into your network traffic flows.

### New or Affected Resource(s)

* [`aws_flow_log`](https://www.terraform.io/docs/providers/aws/r/flow_log.html)

### Potential Terraform Configuration

```hcl
resource "aws_flow_log" "example" {
  max_aggregation_interval = 60
}
```

### References

[Announcement](https://aws.amazon.com/about-aws/whats-new/2020/02/amazon-vpc-flow-logs-support-1-min-aggregation-intervals/).

Requires [AWS SDK v1.28.10](https://github.com/aws/aws-sdk-go/releases/tag/v1.28.10):
* https://github.com/terraform-providers/terraform-provider-aws/pull/11893

### PR DESCRIPTION
**Pull request by ajorpheus**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #11927

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
This PR depends on aws sdk to be v1.28.10
```

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccXXX'

...
```

### CODE REVIEW

**Comment by ajorpheus** [comment]
TODO:

- [ ] Add Acceptance test(sT
- [ ] Separate out aws-sdk-go upgrade to a separate PR

**Comment by ewbankkit** [comment]
@ajorpheus Thanks for working on this.
Will you have time to address the TODOs? I have interest in using this functionality and can help out/complete.

**Comment by ewbankkit** [comment]
@ajorpheus I opened another PR including your commit to add the acceptance tests: https://github.com/terraform-providers/terraform-provider-aws/pull/12483.

**Comment by ajorpheus** [comment]
@ewbankkit : Thank you for adding the required acc. tests.

**Pull request closed without merging**
