### PR TITLE
r/vpc_peering_connection, r/vpc_peering_connection_accepter: connection options conflict with peer_region

### PR DESCRIPTION
**Pull request by kl4w**
addresses #3069

An inter-region vpc peering connection does not allow you to modify the ClassicLink nor DNS settings.

This can be easily handled in `vpc_peering_connection` by setting `ConflictsWith` attributes, but what would be the best way to handle the `vpc_peering_connection_accepter`? I personally would **prefer** to be notified on a plan rather than an apply that the conflict exists but having a check in the `Update` step would cover both resources.

### CODE REVIEW

**Comment by kl4w** [comment]
I think this should be ready for review now.

**Comment by kl4w** [comment]
```make testacc TEST=./aws TESTARGS='-run=TestAccAWSVPCPeeringConnection'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -run=TestAccAWSVPCPeeringConnection -timeout 120m
=== RUN   TestAccAWSVPCPeeringConnection_importBasic
--- PASS: TestAccAWSVPCPeeringConnection_importBasic (24.75s)
=== RUN   TestAccAWSVPCPeeringConnectionAccepter_sameRegion
--- PASS: TestAccAWSVPCPeeringConnectionAccepter_sameRegion (24.56s)
=== RUN   TestAccAWSVPCPeeringConnectionAccepter_differentRegion
--- PASS: TestAccAWSVPCPeeringConnectionAccepter_differentRegion (35.33s)
=== RUN   TestAccAWSVPCPeeringConnection_basic
--- PASS: TestAccAWSVPCPeeringConnection_basic (22.91s)
=== RUN   TestAccAWSVPCPeeringConnection_plan
--- PASS: TestAccAWSVPCPeeringConnection_plan (20.70s)
=== RUN   TestAccAWSVPCPeeringConnection_tags
--- PASS: TestAccAWSVPCPeeringConnection_tags (23.70s)
=== RUN   TestAccAWSVPCPeeringConnection_options
--- PASS: TestAccAWSVPCPeeringConnection_options (38.37s)
=== RUN   TestAccAWSVPCPeeringConnection_failedState
--- PASS: TestAccAWSVPCPeeringConnection_failedState (14.84s)
=== RUN   TestAccAWSVPCPeeringConnection_peerRegionAndAutoAccept
--- PASS: TestAccAWSVPCPeeringConnection_peerRegionAndAutoAccept (12.85s)
=== RUN   TestAccAWSVPCPeeringConnection_region
--- PASS: TestAccAWSVPCPeeringConnection_region (27.09s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	245.160s```

**Comment by cornfeedhobo** [comment]
@tombuildsstuff Hey what do you think about getting some eyes on this?

**Comment by bflad** [comment]
Hey @kl4w I think this is a decent PR however with #3909, I think we'll need to handle the schema a little differently for each resource (breaking them out to each resource, otherwise I _think_ `ConflictsWith` will complain in the new `_options` resource since `peer_region` won't exist there). Not sure if you'd like to keep this one open and fix it after #3909 is merged or simply submit something after 👍

**Comment by kl4w** [comment]
Yeah, makes sense. I'll close this out and see what happens after #3909

**Pull request closed without merging**
