### PR TITLE
#1196: added data source aws_internet_gateway

### LINKED ISSUE #1196: Implement data source for `aws_internet_gateway`
`DescribeInternetGatways` API is available, it would be very helpful if there's the corresponding data source support in TF.

### PR DESCRIPTION
**Pull request by trung**
This implements `DescribeInternetGateways` API

Fixes #1196

### CODE REVIEW

**Comment by catsby** [comment]
Hey @trung ! Thanks for the submission here. Could you please run this code change through `go fmt` first? Thanks!

Error from TravisCI: 
```
==> Checking that code complies with gofmt requirements...
gofmt needs running on the following files:
./aws/data_source_aws_internet_gateway.go
You can use the command: `make fmt` to reformat code.
make: *** [fmtcheck] Error 1
```

**Comment by trung** [comment]
@catsby thanks. I thought I ran `make test` before pushing...

**Comment by trung** [comment]
@clintoncwolfe thanks, typo in acceptance test fixed

**Comment by grubernaut** [comment]
```
$ make testacc TEST=./aws TESTARGS="-run=TestAccDataSourceAwsInternetGateway_typical" 
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -run=TestAccDataSourceAwsInternetGateway_typical -timeout 120m
=== RUN   TestAccDataSourceAwsInternetGateway_typical
--- PASS: TestAccDataSourceAwsInternetGateway_typical (60.33s)
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws       60.342s
```

**Pull request merged**
