### PR TITLE
resource/aws_route: Allow adding IPv6 routes to instances and network interfaces

### PR DESCRIPTION
**Pull request by stevenewey**
Fix for #2264 

My first PR, please be kind 😊

### CODE REVIEW

**Comment by radeksimko** [comment]
Hi @stevenewey 
thanks for the PR.

Do you mind adding an acceptance test for this bugfix? Feel free to use the config from #2264 and use "copy-paste-modify" approach. Here's an existing test you can copy:

https://github.com/terraform-providers/terraform-provider-aws/blob/b59fa964c12c294c4f83b39527c715d0c3726ec8/aws/resource_aws_route_test.go#L89-L107

The goal is to have a test which is failing prior to your patch and passing after patch. 😉 

Let me know if you need any further help.

**Comment by stevenewey** [comment]
Thanks for the pointer @radeksimko!

The tests run on master...
```
~/go/src/github.com/terraform-providers/terraform-provider-aws(master) $ TF_ACC=1 go test github.com/terraform-providers/terraform-provider-aws/aws -v -run 'TestAccAWSRoute_ipv6ToInstance'
=== RUN   TestAccAWSRoute_ipv6ToInstance
--- FAIL: TestAccAWSRoute_ipv6ToInstance (144.12s)
	testing.go:503: Step 0 error: Error applying: 1 error(s) occurred:

		* aws_route.internal-default-route-ipv6: 1 error(s) occurred:

		* aws_route.internal-default-route-ipv6: Error creating route: MissingParameter: The request must contain the parameter destinationCidrBlock or destinationIpv6CidrBlock
			status code: 400, request id: 973ea2d4-bbbb-472a-9ead-2af0ad769360
FAIL
exit status 1
FAIL	github.com/terraform-providers/terraform-provider-aws/aws	144.153s
~/go/src/github.com/terraform-providers/terraform-provider-aws(master) $ TF_ACC=1 go test github.com/terraform-providers/terraform-provider-aws/aws -v -run 'TestAccAWSRoute_ipv6ToNetworkInterface'
=== RUN   TestAccAWSRoute_ipv6ToNetworkInterface
--- FAIL: TestAccAWSRoute_ipv6ToNetworkInterface (194.86s)
	testing.go:503: Step 0 error: Error applying: 1 error(s) occurred:

		* aws_route.internal-default-route-ipv6: 1 error(s) occurred:

		* aws_route.internal-default-route-ipv6: Error creating route: MissingParameter: The request must contain the parameter destinationCidrBlock or destinationIpv6CidrBlock
			status code: 400, request id: 4f35b513-17f0-414f-9e0d-dd828e5d8634
FAIL
exit status 1
FAIL	github.com/terraform-providers/terraform-provider-aws/aws	194.893s
```

And on my branch...
```
~/go/src/github.com/terraform-providers/terraform-provider-aws(route-ipv6) $ TF_ACC=1 go test github.com/terraform-providers/terraform-provider-aws/aws -v -run 'TestAccAWSRoute_ipv6ToInstance'
=== RUN   TestAccAWSRoute_ipv6ToInstance
--- PASS: TestAccAWSRoute_ipv6ToInstance (142.91s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	142.946s
~/go/src/github.com/terraform-providers/terraform-provider-aws(route-ipv6) $ TF_ACC=1 go test github.com/terraform-providers/terraform-provider-aws/aws -v -run 'TestAccAWSRoute_ipv6ToNetworkInterface'
=== RUN   TestAccAWSRoute_ipv6ToNetworkInterface
--- PASS: TestAccAWSRoute_ipv6ToNetworkInterface (210.37s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	210.399s
```

**Comment by stevenewey** [comment]
Hi @radeksimko 
Are my acceptance tests sufficient, or do I need to do more?
Thanks.

**Comment by mindw** [comment]
Is there anything missing here?
Thanks!

**Comment by bflad** [comment]
This has been released in [terraform-provider-aws version 1.8.0](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#180-january-29-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.

**Pull request merged**
