### PR TITLE
Add aurora-postgresql as a target for DMS endpoint

### PR DESCRIPTION
**Pull request by jemmyw**

### CODE REVIEW

**Comment by bflad** [comment]
@jemmyw is this PR still work in progress?

**Comment by saiya** [comment]
I got same issue and I successfully created aws_dms_endpoint (engine=aurora-postgresql) with this patch.
I think this patch can be merged.

**Comment by jemmyw** [comment]
@bflad Taken off [wip]

**Comment by bflad** [comment]
This has been released in [version 1.11.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1110-march-09-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.

**Pull request merged**
