### PR TITLE
resource/ecs_service: fix crash when importing non-existing service

### LINKED ISSUE #3671: crash when doing terraform import
_This issue was originally opened by @rexzhen as hashicorp/terraform#17520. It was migrated here as a result of the [provider split](https://www.hashicorp.com/blog/upcoming-provider-changes-in-terraform-0-10/). The original body of the issue is below._

<hr>

### Terraform Version

```
$ terraform -v
Terraform v0.11.3
+ provider.aws v1.10.0
+ provider.template v1.0.0

Error: module.iris-service.aws_ecs_service.main (import id: lic-dev/lic-iris-dev-rw): 1 error(s) occurred:

* import module.iris-service.aws_ecs_service.main result: lic-iris-dev-rw: aws_ecs_service.main: unexpected EOF


panic: runtime error: index out of range
2018-03-07T16:58:20.993-0800 [DEBUG] plugin.terraform-provider-aws_v1.10.0_x4:
2018-03-07T16:58:20.993-0800 [DEBUG] plugin.terraform-provider-aws_v1.10.0_x4: goroutine 118 [running]:
2018-03-07T16:58:20.993-0800 [DEBUG] plugin.terraform-provider-aws_v1.10.0_x4: github.com/terraform-providers/terraform-provider-aws/aws.resourceAwsEcsServiceRead.func1(0x1039d8f)
2018-03-07T16:58:20.993-0800 [DEBUG] plugin.terraform-provider-aws_v1.10.0_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_ecs_service.go:364 +0x550
2018-03-07T16:58:20.993-0800 [DEBUG] plugin.terraform-provider-aws_v1.10.0_x4: github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/resource.Retry.func1(0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
2018-03-07T16:58:20.993-0800 [DEBUG] plugin.terraform-provider-aws_v1.10.0_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/resource/wait.go:22 +0x75
2018-03-07T16:58:20.993-0800 [DEBUG] plugin.terraform-provider-aws_v1.10.0_x4: github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/resource.(*StateChangeConf).WaitForState.func1(0xc4209ad920, 0xc420213b20, 0xc4205dd640, 0xc4207a6ba0, 0xc4205cb070, 0xc4205cb068)
2018-03-07T16:58:20.993-0800 [DEBUG] plugin.terraform-provider-aws_v1.10.0_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/resource/state.go:103 +0x4e0
2018-03-07T16:58:20.993-0800 [DEBUG] plugin.terraform-provider-aws_v1.10.0_x4: created by github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/resource.(*StateChangeConf).WaitForState
2018-03-07T16:58:20.993-0800 [DEBUG] plugin.terraform-provider-aws_v1.10.0_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/resource/state.go:80 +0x1d0
2018/03/07 16:58:20 [ERROR] root.iris-service: eval: *terraform.EvalRefresh, err: aws_ecs_service.main: unexpected EOF
2018/03/07 16:58:20 [ERROR] root.iris-service: eval: *terraform.EvalSequence, err: aws_ecs_service.main: unexpected EOF
2018/03/07 16:58:20 [TRACE] [walkImport] Exiting eval tree: import module.iris-service.aws_ecs_service.main result: lic-iris-dev-rw
2018/03/07 16:58:20 [TRACE] dag/walk: upstream errored, not walking "provider.aws (close)"
2018/03/07 16:58:20 [TRACE] dag/walk: upstream errored, not walking "root"
2018-03-07T16:58:20.996-0800 [DEBUG] plugin: plugin process exited: path=/Users/rexzhen/github/devops/terraform-licensing/Testing/.terraform/plugins/darwin_amd64/terraform-provider-aws_v1.10.0_x4
2018/03/07 16:58:20 [DEBUG] plugin: waiting for all plugin processes to complete...
2018-03-07T16:58:20.997-0800 [WARN ] plugin: error closing client during Kill: err="connection is shut down"
2018-03-07T16:58:21.000-0800 [DEBUG] plugin: plugin process exited: path=/Users/rexzhen/github/devops/terraform-licensing/Testing/.terraform/plugins/darwin_amd64/terraform-provider-template_v1.0.0_x4



!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!


```

### Terraform Configuration Files

```hcl
...
```

### PR DESCRIPTION
**Pull request by loivis**
Fix #3671 

One thing unsure though. Do we test such scenario as import error?

### CODE REVIEW

**Comment by bflad** [comment]
> Do we test such scenario as import error?

Not currently for most (any?) resources, but maybe we should given scenarios like this. 😄  I was able to generate the panic on master:

```
make testacc TEST=./aws TESTARGS='-run=TestAccAWSEcsService_basicImport'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -run=TestAccAWSEcsService_basicImport -timeout 120m
=== RUN   TestAccAWSEcsService_basicImport
panic: runtime error: index out of range

goroutine 350 [running]:
github.com/terraform-providers/terraform-provider-aws/aws.resourceAwsEcsServiceRead.func1(0xc4204c2190)
	/Users/bflad/go/src/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_ecs_service.go:364 +0x4b7
...
FAIL	github.com/terraform-providers/terraform-provider-aws/aws	11.893s
make: *** [testacc] Error 1
```

With an additional `TestStep`:
```go
			// Test non-existent resource import
			{
				ResourceName:      resourceName,
				ImportStateId:     fmt.Sprintf("%s/nonexistent", clusterName),
				ImportState:       true,
				ImportStateVerify: false,
			},
```

Assuming this works, I can add this to the PR so we can have verification, otherwise the fix looks fine. 👍

**Comment by loivis** [comment]
:+1:Please feel free to add the verification

**Comment by bflad** [comment]
Huzzah! 😂 

With naive implementation above:
```
make testacc TEST=./aws TESTARGS='-run=TestAccAWSEcsService_importBasic'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -run=TestAccAWSEcsService_importBasic -timeout 120m
=== RUN   TestAccAWSEcsService_importBasic
--- FAIL: TestAccAWSEcsService_importBasic (43.50s)
	testing.go:513: Step 2 error: 1 error(s) occurred:

		* aws_ecs_service.jenkins (import id: tf-acc-cluster-svc-0oezofzf/nonexistent): 1 error(s) occurred:

		* import aws_ecs_service.jenkins result: nonexistent: aws_ecs_service.jenkins: No ECS service found: "nonexistent"
FAIL
FAIL	github.com/terraform-providers/terraform-provider-aws/aws	43.535s
```

Modified:
```
			// Test non-existent resource import
			{
				ResourceName:      resourceName,
				ImportStateId:     fmt.Sprintf("%s/nonexistent", clusterName),
				ImportState:       true,
				ImportStateVerify: false,
				ExpectError:       regexp.MustCompile(`No ECS service found`),
			},
```

Returns:
```
make testacc TEST=./aws TESTARGS='-run=TestAccAWSEcsService_importBasic'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -run=TestAccAWSEcsService_importBasic -timeout 120m
=== RUN   TestAccAWSEcsService_importBasic
--- PASS: TestAccAWSEcsService_importBasic (33.06s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	33.115s
```

**Comment by bflad** [comment]
This has been released in [version 1.11.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1110-march-09-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.

**Pull request merged**
