### PR TITLE
added in changes for storage gateway to accept a vpc endpoint

### LINKED ISSUE #9920: Add VPC Endpoint option to storage gateway
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Looking for an option to be added to the creation of the storage gateway for a gateway created in a private subnet (using a VPC endpoint)

### New or Affected Resource(s)

* aws_storagegateway_gateway

### Potential Terraform Configuration

```hcl
resource "aws_storagegateway_gateway" "example" {
  gateway_ip_address = "192.168.0.1"
  gateway_name       = "test"
  gateway_timezone   = "GMT"
  gateway_type       = "FILE_S3"
  gateway_vpc_endpoint = "vpce-id.storagegateway.us-east-1.vpce.amazonaws.com"
}
```

### References

https://docs.aws.amazon.com/storagegateway/latest/userguide/create-gateway-file.html#GettingStarted-service-endpoint-file

Code should go before this Line
https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/resource_aws_storagegateway_gateway.go#L149

And should add `&vpcEndpoint=VPCENDPOINT_VARIABLE` to http request

example:
```http://192.168.0.1/?activationRegion=us-east-1&vpcEndpoint=vpc-id.storagegateway.us-east-1.vpce.amazonaws.com```

Also looks like you need to set it using this method:

https://github.com/aws/aws-sdk-go/blob/master/service/storagegateway/api.go#L11176

### PR DESCRIPTION
**Pull request by jecafarelli**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" comments, they generate extra noise for pull request followers and do not help prioritize the request

Closes #9920

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
resource/aws_storagegateway_gateway: Added vpc endpoint option for private storage gateway
```

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccXXX'

...
```

First run at creating a Pull request. Still reading through everything I should update. Any feedback welcome

### CODE REVIEW

**Comment by jecafarelli** [comment]
[mentioned here](https://github.com/terraform-providers/terraform-provider-aws/issues/9920#issuecomment-527595996) I am unable to run or create acceptance test for this pr, but described the approach on how to if someone could help with that part.

**Comment by tlindsay42** [comment]
Tested this PR last month for automating the provision of 160 AWS Storage Gateway VMs for scale testing a module in re:Invent workshop ENT306. The Storage Gateway VMs were deployed in a VMware Cloud on AWS software-defined datacenter (SDDC), which is the VMware virtualization stack deployed on AWS hardware in AWS datacenters. The VMware Cloud on AWS account comes with an AWS PrivateLink connection to a designated VPC in the customer's specified AWS account, and traffic traversing this is exempt from data transfer charges. The Storage Gateway VPC Endpoint was included as part of the workshop design (as well as a S3 VPC Endpoint) to demonstrate how customers could route the traffic over the PrivateLink for one way to reduce costs for scalable & resilient file & backup storage use cases.

Here's a snippet:

```hcl
# ---------------------------------------------------------------------------------------------------------------------
# CREATE A FILE GATEWAY FOR EACH LAB
# ---------------------------------------------------------------------------------------------------------------------

resource "vsphere_virtual_machine" "file_gateways" {
  count = "${var.num_labs}"

  name     = "${local.lab_prefix}${format("%03d", count.index + 1)}-file-gateway"
  guest_id = "otherGuest64"

  resource_pool_id = "${element(vsphere_resource_pool.labs.*.id, count.index)}"
  datastore_id     = "${data.vsphere_datastore.workload.id}"
  folder           = "Workloads/${local.lab_prefix}${format("%03d", count.index + 1)}"

  num_cpus = 4
  memory   = 16384

  network_interface {
    network_id = "${data.vsphere_network.student_network.id}"
  }

  disk {
    label = "disk0"
    size  = 80
  }

  disk {
    label       = "disk1"
    size        = 150
    unit_number = 1
  }

  wait_for_guest_net_timeout  = 15
  wait_for_guest_net_routable = true
  shutdown_wait_timeout       = 1

  sync_time_with_host = true

  annotation = "Lab ${count.index + 1}: AWS File Gateway"

  tags = [
    "${element(vsphere_tag.labs.*.id, count.index)}",
    "${vsphere_tag.terraform.id}",
  ]

  clone {
    template_uuid = "${data.vsphere_virtual_machine.file_gateway_template.id}"
    linked_clone  = false
  }

  depends_on = ["vsphere_folder.labs"]

  lifecycle {
    create_before_destroy = false
  }
}

# Storage Gateway VPC Endpoints are not yet supported
# https://github.com/terraform-providers/terraform-provider-aws/issues/9920
# Build from pull request
resource "aws_storagegateway_gateway" "file_gateways" {
  count = "${var.num_labs}"

  gateway_ip_address   = "${element(vsphere_virtual_machine.file_gateways.*.default_ip_address, count.index)}"
  gateway_name         = "${local.lab_prefix}${format("%03d", count.index + 1)}-file-gateway"
  gateway_timezone     = "GMT"
  gateway_type         = "FILE_S3"
  gateway_vpc_endpoint = "${element(aws_vpc_endpoint.storage_gateway.dns_entry.*.dns_name, 0)}"
}

resource "aws_storagegateway_cache" "file_gateways" {
  count = "${var.num_labs}"

  disk_id     = "${element(data.aws_storagegateway_local_disk.file_gateways.*.id, count.index)}"
  gateway_arn = "${element(aws_storagegateway_gateway.file_gateways.*.arn, count.index)}"
}

# ---------------------------------------------------------------------------------------------------------------------
# CREATE A NFS FILE SHARE FOR EACH FILE GATEWAY FOR EACH LAB
# ---------------------------------------------------------------------------------------------------------------------

resource "aws_storagegateway_nfs_file_share" "nfs_file_shares" {
  count = "${var.num_labs}"

  gateway_arn  = "${element(aws_storagegateway_gateway.file_gateways.*.arn, count.index)}"
  location_arn = "${aws_s3_bucket.vmc_lab_resiliency.arn}"
  role_arn     = "${aws_iam_role.storage_gateway_s3_bucket_access.arn}"
  client_list  = ["${element(vsphere_virtual_machine.workload_vms.*.default_ip_address, count.index)}/32"]

  default_storage_class = "S3_STANDARD"
  kms_encrypted         = false
  read_only             = false
  squash                = "RootSquash"

  nfs_file_share_defaults {
    directory_mode = "0777"
    file_mode      = "0666"
    group_id       = 65534 # nfsnobody
    owner_id       = 65534 # nfsnobody
  }

  depends_on = ["aws_storagegateway_cache.file_gateways"]
}

# ---------------------------------------------------------------------------------------------------------------------
# DATA SOURCES
# ---------------------------------------------------------------------------------------------------------------------

data "aws_storagegateway_local_disk" "file_gateways" {
  count = "${var.num_labs}"

  disk_path   = "/dev/sdb"
  gateway_arn = "${element(aws_storagegateway_gateway.file_gateways.*.arn, count.index)}"
}
```

**Comment by jecafarelli** [comment]
Removing WIP tag. Not sure what next steps would be to get this merged in.

**Comment by tlindsay42** [comment]
@bflad, acceptance test coverage is still required before merge, right? Any recommendations for seeking help for writing an acceptance test for this PR?

**Comment by Richard-Payne** [comment]
Is this likely to be released soon?  If not, is there a build I can download until it is?

**Comment by hariepuri5** [comment]
Any update on storage gateway to accept a vpc endpoint release?

**Pull request merged**
