### PR TITLE
resource/aws_api_gateway_rest_api: suppressed plan changes for policy

### LINKED ISSUE #5549: Terraform constantly updates resource policy on API Gateway
We're seeing an issue where Terraform constantly updates the resource policy of an API gateway:
```
module.apps.aws_api_gateway_rest_api.segmentation-etl-creation-api: Modifying... (ID: x023a0eez5)
  policy: "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Sid\":\"\",\"Effect\":\"Allow\",\"Principal\":\"*\",\"Action\":\"execute-api:Invoke\",\"Resource\":\"arn:aws:execute-api:us-west-1:999999999999:0123456789a/*\",\"Condition\":{\"StringEquals\":{\"aws:SourceVpc\":\"vpc-bcdef123\"}}}]}" => "{\n  \"Version\": \"2012-10-17\",\n  \"Statement\": [\n    {\n      \"Sid\": \"\",\n      \"Effect\": \"Allow\",\n      \"Action\": \"execute-api:Invoke\",\n      \"Resource\": \"execute-api:/*\",\n      \"Principal\": \"*\",\n      \"Condition\": {\n        \"StringEquals\": {\n          \"aws:SourceVpc\": \"vpc-bcdef123\"\n        }\n      }\n    }\n  ]\n}"
```

In our terraform module we want to apply a resource policy our API gateway, so we have the following:
```hcl
data "aws_iam_policy_document" "resource-policy" {
  statement {
    principals {
      type        = "*"
      identifiers = ["*"]
    }
    actions = [
      "execute-api:Invoke",
    ]
    resources = [
      "execute-api:/*",
    ]
    condition {
      test     = "StringEquals"
      variable = "aws:SourceVpc"
      values   = ["${var.vpc_id}"]
    }
  }
}
resource "aws_api_gateway_rest_api" "rest-api" {
  name        = "rest-api"
  description = "API to manage things"
  endpoint_configuration {
    types = ["PRIVATE"]
  }
  policy = "${data.aws_iam_policy_document.resource-policy.json}"
}
```

According to the [Amazon docs](https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-resource-policies-create-attach.html) we can use this `execute-api:/stage/method/part` short hand and AWS will expand this to the full ARN of the `aws_api_gateway_rest_api` instance.

Ideally we'd like to be able to change the `resources` part of the resource policy to reference the ARN of the `aws_api_gateway_rest_api` instance directly, like so:
```hcl
    resources = [
      "${aws_api_gateway_rest_api.rest-api.execution_arn}:/*",
    ]
```
except that this introduces a cycle between the resource policy and the REST API as both require each other to exist before they can be created:
```
Error: Cycle: module.apps.data.aws_iam_policy_document.resource-policy, module.apps.aws_api_gateway_rest_api.rest-api
```

This appears to be due to the unfortunate way that resource policies are stored in AWS. Reading the [docs](https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-resource-policies-create-attach.html) it looks like resource policies don't exist as entities themselves but only as things that hang off a REST API.

At the moment we're working around this by ignoring policy changes - it'd be great if there were a nicer way to do this.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

* Terraform version `0.11.7`
* AWS provider version `1.31.0`

### Affected Resource(s)

* aws_api_gateway_rest_api

### PR DESCRIPTION
**Pull request by sergei-ivanov**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" comments, they generate extra noise for pull request followers and do not help prioritize the request

Closes #5549

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
Suppress spurious plan changes for `policy` attribute of `aws_api_gateway_rest_api`
```

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccAWSAPIGatewayRestApi_*'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./... -v -count 1 -parallel 20 -run=TestAccAWSAPIGatewayRestApi_* -timeout 120m
?   	github.com/terraform-providers/terraform-provider-aws	[no test files]
=== RUN   TestAccAWSAPIGatewayRestApi_basic
=== PAUSE TestAccAWSAPIGatewayRestApi_basic
=== RUN   TestAccAWSAPIGatewayRestApi_EndpointConfiguration
=== PAUSE TestAccAWSAPIGatewayRestApi_EndpointConfiguration
=== RUN   TestAccAWSAPIGatewayRestApi_EndpointConfiguration_Private
=== PAUSE TestAccAWSAPIGatewayRestApi_EndpointConfiguration_Private
=== RUN   TestAccAWSAPIGatewayRestApi_api_key_source
=== PAUSE TestAccAWSAPIGatewayRestApi_api_key_source
=== RUN   TestAccAWSAPIGatewayRestApi_policy
=== PAUSE TestAccAWSAPIGatewayRestApi_policy
=== RUN   TestAccAWSAPIGatewayRestApi_openapi
=== PAUSE TestAccAWSAPIGatewayRestApi_openapi
=== CONT  TestAccAWSAPIGatewayRestApi_basic
=== CONT  TestAccAWSAPIGatewayRestApi_policy
=== CONT  TestAccAWSAPIGatewayRestApi_EndpointConfiguration_Private
=== CONT  TestAccAWSAPIGatewayRestApi_api_key_source
=== CONT  TestAccAWSAPIGatewayRestApi_EndpointConfiguration
=== CONT  TestAccAWSAPIGatewayRestApi_openapi
--- PASS: TestAccAWSAPIGatewayRestApi_openapi (56.80s)
--- PASS: TestAccAWSAPIGatewayRestApi_EndpointConfiguration_Private (90.50s)
--- PASS: TestAccAWSAPIGatewayRestApi_policy (141.95s)
--- PASS: TestAccAWSAPIGatewayRestApi_basic (155.77s)
--- PASS: TestAccAWSAPIGatewayRestApi_api_key_source (252.84s)
--- PASS: TestAccAWSAPIGatewayRestApi_EndpointConfiguration (472.19s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	472.219s
testing: warning: no tests to run
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws/internal/flatmap	0.003s [no tests to run]
testing: warning: no tests to run
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws/internal/keyvaluetags	0.004s [no tests to run]
```

### CODE REVIEW

**Comment by sergei-ivanov** [comment]
@bflad can you please take a look at the proposed changes? The PR triage job has died for no good reason, but the unit tests pass OK. Thanks!

**Comment by sergei-ivanov** [comment]
I have just rebased on the latest master. Can anyone from the team please review the changes?

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccAWSAPIGatewayRestApi_*'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./... -v -count 1 -parallel 20 -run=TestAccAWSAPIGatewayRestApi_* -timeout 120m
?   	github.com/terraform-providers/terraform-provider-aws	[no test files]
=== RUN   TestAccAWSAPIGatewayRestApi_basic
=== PAUSE TestAccAWSAPIGatewayRestApi_basic
=== RUN   TestAccAWSAPIGatewayRestApi_tags
=== PAUSE TestAccAWSAPIGatewayRestApi_tags
=== RUN   TestAccAWSAPIGatewayRestApi_disappears
=== PAUSE TestAccAWSAPIGatewayRestApi_disappears
=== RUN   TestAccAWSAPIGatewayRestApi_EndpointConfiguration
=== PAUSE TestAccAWSAPIGatewayRestApi_EndpointConfiguration
=== RUN   TestAccAWSAPIGatewayRestApi_EndpointConfiguration_Private
=== PAUSE TestAccAWSAPIGatewayRestApi_EndpointConfiguration_Private
=== RUN   TestAccAWSAPIGatewayRestApi_api_key_source
=== PAUSE TestAccAWSAPIGatewayRestApi_api_key_source
=== RUN   TestAccAWSAPIGatewayRestApi_policy
=== PAUSE TestAccAWSAPIGatewayRestApi_policy
=== RUN   TestAccAWSAPIGatewayRestApi_openapi
=== PAUSE TestAccAWSAPIGatewayRestApi_openapi
=== CONT  TestAccAWSAPIGatewayRestApi_basic
=== CONT  TestAccAWSAPIGatewayRestApi_api_key_source
=== CONT  TestAccAWSAPIGatewayRestApi_policy
=== CONT  TestAccAWSAPIGatewayRestApi_openapi
=== CONT  TestAccAWSAPIGatewayRestApi_EndpointConfiguration
=== CONT  TestAccAWSAPIGatewayRestApi_EndpointConfiguration_Private
=== CONT  TestAccAWSAPIGatewayRestApi_disappears
=== CONT  TestAccAWSAPIGatewayRestApi_tags
--- PASS: TestAccAWSAPIGatewayRestApi_disappears (53.21s)
--- PASS: TestAccAWSAPIGatewayRestApi_openapi (100.83s)
--- PASS: TestAccAWSAPIGatewayRestApi_api_key_source (128.06s)
--- PASS: TestAccAWSAPIGatewayRestApi_EndpointConfiguration_Private (157.38s)
--- PASS: TestAccAWSAPIGatewayRestApi_EndpointConfiguration (196.09s)
--- PASS: TestAccAWSAPIGatewayRestApi_policy (241.63s)
--- PASS: TestAccAWSAPIGatewayRestApi_tags (272.89s)
--- PASS: TestAccAWSAPIGatewayRestApi_basic (493.52s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	493.566s
testing: warning: no tests to run
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws/internal/flatmap	0.013s [no tests to run]
testing: warning: no tests to run
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws/internal/keyvaluetags	0.005s [no tests to run]
```

**Comment by bflad** [comment]
Hi @sergei-ivanov 👋 Thank you for submitting this and for the proposed implementation.

I have added the `breaking-change` label to this pull request since it changes the API return value and may cause an unexpected difference for configurations using the full ARN or change in behavior to any references pointing to this attribute's value. We may consider this type of change acceptable in a major version update, however we should try to avoid changing this attribute value if possible. As your comment alludes to in the resource code, suppressing the difference can be implemented via `DiffSuppressFunc` to allow the two values to be seen as equivalent, which is our typical approach to IAM policy differences like these.

**Comment by sergei-ivanov** [comment]
Let me bite the bullet and see if I can reimplement it using `DiffSuppressFunc`. My concern was that `DiffSuppressFunc` would need to pull the ARN out of somewhere, and I was not sure if it'd be easily available in that context.

**Comment by sergei-ivanov** [comment]
Okay, it was actually easier than I thought on the provider side (and the changes are much smaller and localised now), and a bit ugly on the acceptance test side, because I had to deal with the ever-changing execution ARNs. Please see the linked PR.

**Comment by sergei-ivanov** [comment]
Closing in favour of #10986

**Pull request closed without merging**
