### PR TITLE
deps: Migrate from github.com/hashicorp/terraform to github.com/hashicorp/terraform-plugin-sdk

### PR DESCRIPTION
**Pull request by bflad**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" comments, they generate extra noise for pull request followers and do not help prioritize the request

Reference: https://www.terraform.io/docs/extend/plugin-sdk.html

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
NOTES

* provider: The underlying Terraform codebase dependency for the provider SDK and acceptance testing framework has been migrated from `github.com/hashicorp/terraform` to `github.com/hashicorp/terraform-plugin-sdk`. They are functionality equivalent and this should only impact codebase development to switch imports. For more information see the [Terraform Plugin SDK page in the Extending Terraform documentation](https://www.terraform.io/docs/extend/plugin-sdk.html).
```

Updated via:

```console
$ tf-sdk-migrator migrate
$ go get github.com/terraform-providers/terraform-provider-tls@v2.1.1+incompatible
$ go get github.com/bflad/tfproviderlint@v0.5.0
$ go mod tidy
$ go mod vendor
```

I will also take a look at quickly switching bflad/tfproviderlint to the new dependency, which may completely remove hashicorp/terraform from the transitive dependencies as well.

Output from acceptance testing (provided as a smoke test):

```
--- PASS: TestAccAWSProvider_Region_AwsCommercial (2.85s)
--- PASS: TestAccAWSProvider_Region_AwsGovCloudUs (2.85s)
--- PASS: TestAccAWSProvider_Region_AwsChina (2.86s)
--- PASS: TestAccAWSProvider_Endpoints_Deprecated (3.06s)
--- PASS: TestAccAWSProvider_Endpoints (3.11s)
```

### CODE REVIEW

**Comment by appilon** [comment]
@bflad I'm curious why `terraform-provider-tls@v2.1.1+incompatible` ? The project has a go.mod.

**Comment by bflad** [comment]
> @bflad I'm curious why terraform-provider-tls@v2.1.1+incompatible ? The project has a go.mod.

The code within the project doesn't live under `/v2`, which is a requirement with Go modules:

```console
$ go get github.com/terraform-providers/terraform-provider-tls@v2.1.1
go: finding github.com/terraform-providers/terraform-provider-tls v2.1.1
go: finding github.com/terraform-providers/terraform-provider-tls v2.1.1
go get github.com/terraform-providers/terraform-provider-tls@v2.1.1: github.com/terraform-providers/terraform-provider-tls@v2.1.1: invalid version: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v2
```

In fact, updating via Go 1.13 doesn't work at all:

```console
$ go get github.com/terraform-providers/terraform-provider-tls@v2.1.1+incompatible
go: finding github.com/terraform-providers/terraform-provider-tls v2.1.1+incompatible
go: finding github.com/terraform-providers/terraform-provider-tls v2.1.1+incompatible
go get github.com/terraform-providers/terraform-provider-tls@v2.1.1+incompatible: github.com/terraform-providers/terraform-provider-tls@v2.1.1+incompatible: invalid version: +incompatible suffix not allowed: module contains a go.mod file, so semantic import versioning is required
```

I used Go 1.12 to workaround ☝️ -- another good reason to get off Terraform Providers as codebase dependencies.

**Comment by appilon** [comment]
Ah yes forgot about that. Well if it compiles then it LGTM

**Comment by bflad** [comment]
Rebasing due to merging #7627 then probably going to just merge this -- it will be a nightmare to keep rebasing.

**Comment by nywilken** [comment]
Looks like we have a few conflicts that need to be resolved.

**Comment by bflad** [comment]
This will be redone after tomorrow's release 👍

**Pull request closed without merging**
