### PR TITLE
[WIP] Option to track AWS ASG by Tag

### PR DESCRIPTION
**Pull request by thatrevguy**
This is an enhancement to allow tracking of ASG resource by tag for deployments that utilize CodeDeploy with COPY_AUTO_SCALING_GROUP provisioning option.

Still requires support for paging due to usage of `autoscaling.DescribeAutoScalingGroupsInput{}` option.

Example terraform manifest that would benefit from enhancement:
```
resource "aws_codedeploy_deployment_group" "app" {
  app_name               = "${aws_codedeploy_app.app.name}"
  deployment_group_name  = "${var.name}-fleet"
  service_role_arn       = "${aws_iam_role.codedeploy_role.arn}"
  deployment_config_name = "CodeDeployDefault.AllAtOnce"

  deployment_style {
    deployment_option = "WITH_TRAFFIC_CONTROL"
    deployment_type   = "BLUE_GREEN"
  }

  load_balancer_info {
    target_group_info {
      name = "${aws_lb_target_group.app.name}"
    }
  }

  blue_green_deployment_config {
    deployment_ready_option {
      action_on_timeout = "CONTINUE_DEPLOYMENT"
    }

    green_fleet_provisioning_option {
      action = "COPY_AUTO_SCALING_GROUP"
    }

    terminate_blue_instances_on_deployment_success {
      action = "TERMINATE"
      termination_wait_time_in_minutes = "0"
    }
  }

  autoscaling_groups = ["${aws_autoscaling_group.app.name}"]
}

resource "aws_autoscaling_group" "app" {
  name_prefix          = "${var.name}-ag-"
  vpc_zone_identifier  = ["${data.aws_subnet_ids.app.ids}"]
  max_size             = "2"
  min_size             = "0"
  desired_capacity     = "1"
  launch_configuration = "${aws_launch_configuration.app.name}"
  id_tag               = "special_tag_key"

  tags = [
    {
      key                 = "special_tag_key"
      value               = "special_tag_value"
      propagate_at_launch = false
    }
  ]

  lifecycle {
    create_before_destroy = true
  }
}```

### CODE REVIEW

**Comment by golimer** [comment]
when this feature will be released?

**Comment by golimer** [comment]
@bflad please take care of this

**Comment by thatrevguy** [comment]
After discussing ASG Blue/Green CodeDeploy with AWS it appears they are not interested in users using this feature and recommend performing Blue/Green deployment operations with stacks. (Evidenced by their lack of ASG Blue/Green CodeDeploy support in CloudFormation) As such I've stopped working on this feature and have moved on. If you'd like me to close this PR let me know!

**Comment by golimer** [comment]
Actually maybe i understood wrongly, but this should work, cause after codedeploy deployment  asg changing name "CodeDeploy_bla_bla" and terraform loosing this ASG  from state.. and after trying to apply again terrafrom creating new ASG.

**Comment by thatrevguy** [comment]
In its current state this does work as long as Terraform ASG resource utilizes `name_prefix` attribute or name is not specified. However, after getting CodeDeploy with Blue/Green ASG deployments working through Terraform the experience was not great. CodeDeploy still had potential to fail in creative ways that would break automation through Terraform. A much more reliable and consistent experience was achieved by dropping CodeDeploy Blue/Green all together and orchestrating Blue/Green deployments at the Stack; utilizing Route53 to route traffic as needed and destroying the "Blue" stack once tests passed on "Green" stack.

**Comment by bflad** [comment]
I think we should close this PR to not get anyone's hopes up, especially now that it has merge conflicts and the original author was willing months ago. 👍  I can say that we are unlikely to merge any resource changes that do not provide a consistent remote API object every time (e.g. the same exact ASG) as this goes against some design philosophies of Terraform. All of this is of course is open for discussion, but more appropriately in a new issue if there isn't one already covering this concept. 😄

**Pull request closed without merging**
