### PR TITLE
r/aws_route53_record: Documentation note about longer than 255 character record values

### LINKED ISSUE #2761: Unable to specify multiple TXT strings in aws_route53_record
### Terraform Version

```
[vagrant@devel dns]$ terraform -version
Terraform v0.11.1
+ provider.aws v1.6.0
```

### Affected Resource(s)

 - aws_route53_record

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
resource "aws_route53_record" "dkim" {
  # https://support.google.com/a/answer/174124
  name = "google._domainkey.naftuli.wtf."
  type = "TXT"
  ttl = "${local.default_ttl}"
  records = [
    "v=DKIM1; k=rsa; p=${substr(local.dkim_key, 0, 255-18)}",
    "${substr(local.dkim_key, 255-18, -1)}"
  ]
  zone_id = "${aws_route53_zone.public.id}"
}
```

I have a 2048bit DKIM key and it is larger than a single TXT string of 255 characters so I have to split it. What Terraform does here is split this into separate TXT records rather than TXT strings. If I manually include escaped double quotes, Terraform still shows a diff.

After fixing manually in the AWS web console, I can see the change. See before and after:

```
$ dig +short TXT google._domainkey.naftuli.wtf
"3z35k7FrNsCCsv52R+OtZoqlF/YdjI7WkI4BojINvf+7JbkZPiJoYtrpEgNWD3in1zqOi7SekPtzG52GMffQpfRyJNqbW/5khM+LQB9unJEFXxuWS0eCHNkKE060Fn3SYRkSg4HII+6Wm8JurFMQQIDAQAB"
"v=DKIM1; k=rsa; p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAlW7Ros7hdyYGF6kjoKF3EeTIT6psj+OQ5cwDhjMKBN8WZn+GzGCVmx5fPPV21Q61H6OPBmuwyUha/Hxdt0MOUTNn3+cMhEXTN4ed+MUnnssirM4dwGfY6dTr9lU0KpW5AWql1oN0SFBFdMWpQfyYWaeD6+K5rwcuRn7E5+tF97DYIGja5/cQk9kxvvUivcqRr"
naftuli@laststand:~$ dig +short TXT google._domainkey.naftuli.wtf
"v=DKIM1; k=rsa; p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAlW7Ros7hdyYGF6kjoKF3EeTIT6psj+OQ5cwDhjMKBN8WZn+GzGCVmx5fPPV21Q61H6OPBmuwyUha/Hxdt0MOUTNn3+cMhEXTN4ed+MUnnssirM4dwGfY6dTr9lU0KpW5AWql1oN0SFBFdMWpQfyYWaeD6+K5rwcuRn7E5+tF97DYIGja5/cQk9kxvvUivcqRr" "3z35k7FrNsCCsv52R+OtZoqlF/YdjI7WkI4BojINvf+7JbkZPiJoYtrpEgNWD3in1zqOi7SekPtzG52GMffQpfRyJNqbW/5khM+LQB9unJEFXxuWS0eCHNkKE060Fn3SYRkSg4HII+6Wm8JurFMQQIDAQAB"
```

### Expected Behavior

There should be a way in Terraform to express this resource.

### Actual Behavior

Terraform makes assumptions about TXT records and makes it not possible to do otherwise.

### Steps to Reproduce

Use config. 

### Important Factoids

Nope.

### References

Nope.

### PR DESCRIPTION
**Pull request by bflad**
Ran into this myself awhile ago as well with DKIM TXT records. Let's document this for future travelers!

Closes #2761

### CODE REVIEW

**Comment by jen20** [comment]
Thanks @bflad. I've not run into this personally but it seems correct based on my reading of the documentation. Perhaps we should add an interpolation function here that takes a single string and emits a list with the correct delimeters. This would be a compelling example of why providers should  be able to add their own interpolation functions, which is not currently possible.

**Comment by booi** [comment]
Sorry if I'm late to the party but can we also apply this documentation to the `google_dns_record_set` as well? Ran into this problem attempting to apply DKIM txt records against google cloud dns.

**Comment by bflad** [comment]
@booi I would suggest opening an issue in that provider's repository for triage by those maintainers: https://github.com/terraform-providers/terraform-provider-google/issues

**Comment by booi** [comment]
> @booi I would suggest opening an issue in that provider's repository for triage by those maintainers: https://github.com/terraform-providers/terraform-provider-google/issues

Yah I went ahead and opened a PR with a similar change.

**Pull request merged**
