### PR TITLE
service/appmesh: update to using typelist

### PR DESCRIPTION
**Pull request by anGie44**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates #9956 

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
service/appmesh: correct typeset usage with typelist in cases where max_items is 1
```

Output from acceptance testing:

```
--- PASS: TestAccAWSAppmesh (206.43s)
    --- PASS: TestAccAWSAppmesh/VirtualNode (206.43s)
        --- PASS: TestAccAWSAppmesh/VirtualNode/basic (16.93s)
        --- PASS: TestAccAWSAppmesh/VirtualNode/cloudMapServiceDiscovery (111.75s)
        --- PASS: TestAccAWSAppmesh/VirtualNode/listenerHealthChecks (22.79s)
        --- PASS: TestAccAWSAppmesh/VirtualNode/logging (22.79s)
        --- PASS: TestAccAWSAppmesh/VirtualNode/tags (32.17s)

--- PASS: TestAccAWSAppmesh (54.20s)
    --- PASS: TestAccAWSAppmesh/VirtualRouter (54.20s)
        --- PASS: TestAccAWSAppmesh/VirtualRouter/tags (32.77s)
        --- PASS: TestAccAWSAppmesh/VirtualRouter/basic (21.43s)
```

### CODE REVIEW

**Comment by ewbankkit** [comment]
Running acceptance tests:

```console
$ make testacc TEST=./aws/ TESTARGS='-run=TestAccAWSAppmesh/VirtualNode/'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws/ -v -count 1 -parallel 20 -run=TestAccAWSAppmesh/VirtualNode/ -timeout 120m
=== RUN   TestAccAWSAppmesh
=== RUN   TestAccAWSAppmesh/VirtualNode
=== RUN   TestAccAWSAppmesh/VirtualNode/listenerHealthChecks
=== RUN   TestAccAWSAppmesh/VirtualNode/logging
=== RUN   TestAccAWSAppmesh/VirtualNode/tags
=== RUN   TestAccAWSAppmesh/VirtualNode/basic
=== RUN   TestAccAWSAppmesh/VirtualNode/cloudMapServiceDiscovery
--- FAIL: TestAccAWSAppmesh (204.90s)
    --- FAIL: TestAccAWSAppmesh/VirtualNode (204.90s)
        --- FAIL: TestAccAWSAppmesh/VirtualNode/listenerHealthChecks (13.54s)
            testing.go:683: Step 0 error: errors during apply:
                
                Error: error creating App Mesh virtual node: BadRequestException: Service Discovery can't be set without a listener.
                
                  on /tmp/tf-test582579556/main.tf line 6:
                  (source code not available)
                
                
        --- FAIL: TestAccAWSAppmesh/VirtualNode/logging (13.73s)
            testing.go:683: Step 0 error: errors during apply:
                
                Error: error creating App Mesh virtual node: BadRequestException: Service Discovery can't be set without a listener.
                
                  on /tmp/tf-test613215798/main.tf line 6:
                  (source code not available)
                
                
        --- PASS: TestAccAWSAppmesh/VirtualNode/tags (63.88s)
        --- PASS: TestAccAWSAppmesh/VirtualNode/basic (27.90s)
        --- FAIL: TestAccAWSAppmesh/VirtualNode/cloudMapServiceDiscovery (85.85s)
            testing.go:683: Step 0 error: errors during apply:
                
                Error: error creating App Mesh virtual node: BadRequestException: Service Discovery can't be set without a listener.
                
                  on /tmp/tf-test199777152/main.tf line 10:
                  (source code not available)
                
                
FAIL
FAIL	github.com/terraform-providers/terraform-provider-aws/aws	204.956s
FAIL
GNUmakefile:26: recipe for target 'testacc' failed
make: *** [testacc] Error 1
$ make testacc TEST=./aws/ TESTARGS='-run=TestAccAWSAppmesh/VirtualRouter/'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws/ -v -count 1 -parallel 20 -run=TestAccAWSAppmesh/VirtualRouter/ -timeout 120m
=== RUN   TestAccAWSAppmesh
=== RUN   TestAccAWSAppmesh/VirtualRouter
=== RUN   TestAccAWSAppmesh/VirtualRouter/basic
=== RUN   TestAccAWSAppmesh/VirtualRouter/tags
--- FAIL: TestAccAWSAppmesh (35.23s)
    --- FAIL: TestAccAWSAppmesh/VirtualRouter (35.23s)
        --- FAIL: TestAccAWSAppmesh/VirtualRouter/basic (16.93s)
            testing.go:683: Step 0 error: Check failed: Check 5/11 error: aws_appmesh_virtual_router.test: Attribute 'spec.0.listener.#' not found
        --- FAIL: TestAccAWSAppmesh/VirtualRouter/tags (18.30s)
            testing.go:683: Step 0 error: After applying this step, the plan was not empty:
                
                DIFF:
                
                UPDATE: aws_appmesh_virtual_router.test
                  arn:                                       "arn:aws:appmesh:us-west-2:123456789012:mesh/tf-acc-test-5724134345005515619/virtualRouter/tf-acc-test-3283401432193133171" => "arn:aws:appmesh:us-west-2:123456789012:mesh/tf-acc-test-5724134345005515619/virtualRouter/tf-acc-test-3283401432193133171"
                  created_date:                              "2020-05-18T21:14:54Z" => "2020-05-18T21:14:54Z"
                  id:                                        "7016275f-4e6c-4612-8dda-7d41f2ec11bc" => "7016275f-4e6c-4612-8dda-7d41f2ec11bc"
                  last_updated_date:                         "2020-05-18T21:14:54Z" => "2020-05-18T21:14:54Z"
                  mesh_name:                                 "tf-acc-test-5724134345005515619" => "tf-acc-test-5724134345005515619"
                  name:                                      "tf-acc-test-3283401432193133171" => "tf-acc-test-3283401432193133171"
                  spec.#:                                    "1" => "1"
                  spec.0.listener.#:                         "0" => "1"
                  spec.0.listener.0.port_mapping.#:          "" => "1"
                  spec.0.listener.0.port_mapping.0.port:     "" => "8080"
                  spec.0.listener.0.port_mapping.0.protocol: "" => "http"
                  spec.0.service_names.#:                    "" => "0"
                  tags.foo:                                  "bar" => "bar"
                  tags.good:                                 "bad" => "bad"
                
                
                
                STATE:
                
                aws_appmesh_mesh.test:
                  ID = tf-acc-test-5724134345005515619
                  provider = provider.aws
                  arn = arn:aws:appmesh:us-west-2:123456789012:mesh/tf-acc-test-5724134345005515619
                  created_date = 2020-05-18T21:14:52Z
                  last_updated_date = 2020-05-18T21:14:52Z
                  name = tf-acc-test-5724134345005515619
                  spec.# = 1
                aws_appmesh_virtual_router.test:
                  ID = 7016275f-4e6c-4612-8dda-7d41f2ec11bc
                  provider = provider.aws
                  arn = arn:aws:appmesh:us-west-2:123456789012:mesh/tf-acc-test-5724134345005515619/virtualRouter/tf-acc-test-3283401432193133171
                  created_date = 2020-05-18T21:14:54Z
                  last_updated_date = 2020-05-18T21:14:54Z
                  mesh_name = tf-acc-test-5724134345005515619
                  name = tf-acc-test-3283401432193133171
                  spec.# = 1
                  tags.foo = bar
                  tags.good = bad
                
                  Dependencies:
                    aws_appmesh_mesh.test
FAIL
FAIL	github.com/terraform-providers/terraform-provider-aws/aws	35.261s
FAIL
GNUmakefile:26: recipe for target 'testacc' failed
make: *** [testacc] Error 1
```

These errors occur because the flatten/expand routines for the changed attributes (in `aws/structure.go`) will need to be modified. For example, for `aws_appmesh_virtual_router`, if I change to

```go
func expandAppmeshVirtualRouterSpec(vSpec []interface{}) *appmesh.VirtualRouterSpec {
	spec := &appmesh.VirtualRouterSpec{}

	if len(vSpec) == 0 || vSpec[0] == nil {
		// Empty Spec is allowed.
		return spec
	}
	mSpec := vSpec[0].(map[string]interface{})

	if vListener, ok := mSpec["listener"].([]interface{}); ok && len(vListener) > 0 && vListener[0] != nil {
		listener := &appmesh.VirtualRouterListener{}

		mListener := vListener[0].(map[string]interface{})

		if vPortMapping, ok := mListener["port_mapping"].([]interface{}); ok && len(vPortMapping) > 0 && vPortMapping[0] != nil {
			mPortMapping := vPortMapping[0].(map[string]interface{})

			listener.PortMapping = &appmesh.PortMapping{}

			if vPort, ok := mPortMapping["port"].(int); ok && vPort > 0 {
				listener.PortMapping.Port = aws.Int64(int64(vPort))
			}
			if vProtocol, ok := mPortMapping["protocol"].(string); ok && vProtocol != "" {
				listener.PortMapping.Protocol = aws.String(vProtocol)
			}
		}

		spec.Listeners = []*appmesh.VirtualRouterListener{listener}
	}

	return spec
}

func flattenAppmeshVirtualRouterSpec(spec *appmesh.VirtualRouterSpec) []interface{} {
	if spec == nil {
		return []interface{}{}
	}

	mSpec := map[string]interface{}{}

	if spec.Listeners != nil && len(spec.Listeners) > 0 {
		listener := spec.Listeners[0]

		mListener := map[string]interface{}{}

		if listener.PortMapping != nil {
			mPortMapping := map[string]interface{}{
				"port":     int(aws.Int64Value(listener.PortMapping.Port)),
				"protocol": aws.StringValue(listener.PortMapping.Protocol),
			}
			mListener["port_mapping"] = []interface{}{mPortMapping}
		}

		mSpec["listener"] = []interface{}{mListener}
	}

	return []interface{}{mSpec}
}
```

and re-run, I get:

```console
$ make testacc TEST=./aws/ TESTARGS='-run=TestAccAWSAppmesh/VirtualRouter/'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws/ -v -count 1 -parallel 20 -run=TestAccAWSAppmesh/VirtualRouter/ -timeout 120m
=== RUN   TestAccAWSAppmesh
=== RUN   TestAccAWSAppmesh/VirtualRouter
=== RUN   TestAccAWSAppmesh/VirtualRouter/basic
=== RUN   TestAccAWSAppmesh/VirtualRouter/tags
--- FAIL: TestAccAWSAppmesh (81.55s)
    --- FAIL: TestAccAWSAppmesh/VirtualRouter (81.55s)
        --- FAIL: TestAccAWSAppmesh/VirtualRouter/basic (17.28s)
            testing.go:683: Step 0 error: Check failed: Check 6/11 error: aws_appmesh_virtual_router.test: Attribute 'spec.0.listener.2279702354.port_mapping.#' not found
        --- PASS: TestAccAWSAppmesh/VirtualRouter/tags (64.26s)
FAIL
FAIL	github.com/terraform-providers/terraform-provider-aws/aws	81.595s
FAIL
GNUmakefile:26: recipe for target 'testacc' failed
make: *** [testacc] Error 1
```

and now the tests should pass if the attribute value is tweaked (`2279702354` to `0` in this case).

**Comment by ewbankkit** [comment]
As I remember, I had these attributes as `schema.TypeSet` in the initial implementation because the underlying AWS API types accept multiple listeners in an array, although one and only one listener is allowed.
I agree that it's best to simplify for now, and revert to `Set`s if AWS ever support multiple listeners.

**Comment by anGie44** [comment]
thanks @ewbankkit for running the tests and comments! will update as needed

**Comment by anGie44** [comment]
updated @ewbankkit, with acceptance tests passing

**Comment by ewbankkit** [comment]
Verified acceptance tests:

```console
$ make testacc TEST=./aws/ TESTARGS='-run=TestAccAWSAppmesh'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws/ -v -count 1 -parallel 20 -run=TestAccAWSAppmesh -timeout 120m
=== RUN   TestAccAWSAppmesh
=== RUN   TestAccAWSAppmesh/Mesh
=== RUN   TestAccAWSAppmesh/Mesh/egressFilter
=== RUN   TestAccAWSAppmesh/Mesh/tags
=== RUN   TestAccAWSAppmesh/Mesh/basic
=== RUN   TestAccAWSAppmesh/Route
=== RUN   TestAccAWSAppmesh/Route/tags
=== RUN   TestAccAWSAppmesh/Route/httpHeader
=== RUN   TestAccAWSAppmesh/Route/httpRoute
=== RUN   TestAccAWSAppmesh/Route/tcpRoute
=== RUN   TestAccAWSAppmesh/Route/routePriority
=== RUN   TestAccAWSAppmesh/VirtualNode
=== RUN   TestAccAWSAppmesh/VirtualNode/basic
=== RUN   TestAccAWSAppmesh/VirtualNode/cloudMapServiceDiscovery
=== RUN   TestAccAWSAppmesh/VirtualNode/listenerHealthChecks
=== RUN   TestAccAWSAppmesh/VirtualNode/logging
=== RUN   TestAccAWSAppmesh/VirtualNode/tags
=== RUN   TestAccAWSAppmesh/VirtualRouter
=== RUN   TestAccAWSAppmesh/VirtualRouter/basic
=== RUN   TestAccAWSAppmesh/VirtualRouter/tags
=== RUN   TestAccAWSAppmesh/VirtualService
=== RUN   TestAccAWSAppmesh/VirtualService/virtualNode
=== RUN   TestAccAWSAppmesh/VirtualService/virtualRouter
=== RUN   TestAccAWSAppmesh/VirtualService/tags
--- PASS: TestAccAWSAppmesh (989.12s)
    --- PASS: TestAccAWSAppmesh/Mesh (132.08s)
        --- PASS: TestAccAWSAppmesh/Mesh/egressFilter (51.55s)
        --- PASS: TestAccAWSAppmesh/Mesh/tags (56.48s)
        --- PASS: TestAccAWSAppmesh/Mesh/basic (24.06s)
    --- PASS: TestAccAWSAppmesh/Route (278.10s)
        --- PASS: TestAccAWSAppmesh/Route/tags (72.96s)
        --- PASS: TestAccAWSAppmesh/Route/httpHeader (51.70s)
        --- PASS: TestAccAWSAppmesh/Route/httpRoute (51.96s)
        --- PASS: TestAccAWSAppmesh/Route/tcpRoute (49.51s)
        --- PASS: TestAccAWSAppmesh/Route/routePriority (51.96s)
    --- PASS: TestAccAWSAppmesh/VirtualNode (303.57s)
        --- PASS: TestAccAWSAppmesh/VirtualNode/basic (28.52s)
        --- PASS: TestAccAWSAppmesh/VirtualNode/cloudMapServiceDiscovery (118.19s)
        --- PASS: TestAccAWSAppmesh/VirtualNode/listenerHealthChecks (46.55s)
        --- PASS: TestAccAWSAppmesh/VirtualNode/logging (45.45s)
        --- PASS: TestAccAWSAppmesh/VirtualNode/tags (64.85s)
    --- PASS: TestAccAWSAppmesh/VirtualRouter (108.57s)
        --- PASS: TestAccAWSAppmesh/VirtualRouter/basic (45.43s)
        --- PASS: TestAccAWSAppmesh/VirtualRouter/tags (63.14s)
    --- PASS: TestAccAWSAppmesh/VirtualService (166.80s)
        --- PASS: TestAccAWSAppmesh/VirtualService/virtualNode (50.30s)
        --- PASS: TestAccAWSAppmesh/VirtualService/virtualRouter (46.98s)
        --- PASS: TestAccAWSAppmesh/VirtualService/tags (69.50s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	989.185s
```

**Pull request merged**
