### PR TITLE
[WIP] Fix 3511 support all elbv2 attributes

### PR DESCRIPTION
**Pull request by appilon**
First PR, implement missing load balancer attributes for elbv2, small refactor to better group lbtype specific attributes.

- [ ] Acceptance coverage
- [ ] Documentation update

### CODE REVIEW

**Comment by bflad** [comment]
FYI cross-zone load balancing is being implemented in #3537

**Comment by appilon** [comment]
Dang, well it was a good exercise, I'll change it to just add support for http2 (which is on by default and I don't know that is is any advantage to turning it off.. but at least it will close off covering all the attributes).

**Comment by appilon** [comment]
I will wait for the mentioned PR to be merged and rebase from there, there is a small piece of refactoring I still think is a good idea

**Comment by mpilar** [comment]
@appilon I have a commit ready with your refactor and adding http2 with tests. Once my PR is merged I will rebase the commit.

Thinking about the refactor, it might be a good idea now but if AWS adds more LB types and rules apply to certain combinations it might get unruly, but it can just be refactored again when it gets to that.

**Comment by appilon** [comment]
@mpilar nice! yeah I agree things could get out of hand with more permutations. When your future PR gets merged I'll close this one. I was working off #3511 for reference for your next PR so you can trigger that issue being closed.

**Pull request closed without merging**
