### PR TITLE
fixes #8230

### LINKED ISSUE #8230: 2.4.0 -> 2.5.0 migration -  log_subscription_filter keeps re-planning "distribution" attribute change
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

TF: 0.11.11
AWS provider: 2.5.0 (current infrastructure was stable on version 2.4.0)

### Affected Resource(s)

*  aws_cloudwatch_log_subscription_filter

### Terraform Configuration Files

```hcl
resource "aws_cloudwatch_log_subscription_filter"
"api-svc-ec2-prd-cloudwatch-subscription"
{
  depends_on = [
    "aws_lambda_permission.api-svc-ec2-prd-sumologic-logging-allow-cloudwatch-lambda"
  ]
  name = "api-svc-ec2-prd-cloudwatch-subscription"
  filter_pattern = ""
  log_group_name =
    "${aws_cloudwatch_log_group.api-svc-ec2-prd-loggroup.name}"
  destination_arn =
    "${aws_lambda_function.cloudwatch-sumologic-logging-lambda.arn}"
}
```

### Steps to Reproduce

1. `terraform plan`

Plan output shows that TF is going to set:  `distribution: "ByLogStream" => ""`

2. ` terraform apply`

Apply output shows that TF is setting:  `distribution: "ByLogStream" => ""`

3. `terraform apply`

Plan output shows that TF is going to set:  `distribution: "ByLogStream" => ""`

### Workaround

Update the resource and add attribute `distribution = "ByLogStream"`

### PR DESCRIPTION
**Pull request by dedamico**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" comments, they generate extra noise for pull request followers and do not help prioritize the request

Fixes #8230

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
resource/aws_cloudwatch_log_subscription_filter: prevent change being reported for blank distribution attribute
```

### CODE REVIEW

**Comment by bflad** [comment]
Hi @dedamico 👋 Would you happen to have a configuration that triggers the behavior so we can add a covering acceptance test? The change to `Computed: true` is likely okay if the value has different defaults depending on other arguments, although it'd be better if we could use a `DiffSuppressFunc` based on those other triggering arguments so Terraform can continue to perform drift detection when its not configured. Thanks!

**Comment by dedamico** [comment]
Hi @bflad!  Thanks for the feedback! 

I have done the following with the latest commit to my branch:

1. Updated the code to use ``DiffSuppressFunc`` rather than ``Computed``.
2. I took a stab at updating the acceptance test to add a Test Step for the slightly different config.  The added config's only difference is that the ``distribution`` attribute is not set, which is the use case which the bug happened with (AWS API sets default distribution value to ``ByLogStream`` if it is not set).

please let me know if anything looks off/wrong and I'll fix it!

**Comment by samm-git** [comment]
@bflad hi, any chance to get this merged?

**Comment by bflad** [comment]
(This was merged in after being rebased - the commits are there despite me closing this 😄 )

**Pull request closed without merging**
