### PR TITLE
Feature/aws sagemaker instance update

### PR DESCRIPTION
**Pull request by kylebechtel77**
This is just an updated PR based on this PR by @jckuester 
     https://github.com/terraform-providers/terraform-provider-aws/pull/8011

Merge conflicts have been fixed and I will try to keep up with any feedback made on this PR. 

I'm fairly new at this so let me know if I did anything incorrectly here, thanks!

Changes proposed in this pull request:

    Adapt aws_sagemaker_instance resource to the latest API changes

### CODE REVIEW

**Comment by ltupin** [comment]
Hi there ! Is there any thing block this PR  ? We will be happy to use it :-D !

**Comment by kylebechtel77** [comment]
@ltupin Not to my knowledge, just waiting for it to be reviewed. 
I'm also excited about the ```notebookInstance.DefaultCodeRepository```!

**Comment by ltupin** [comment]
Dear @jckuester could you please check and review this PR ?

**Comment by jckuester** [comment]
@kylebechtel77 there are still a few comments and TODOs in the code that I left in my old PR. Do you want me to work on those? I think, I can find some time next week to finish them.

**Comment by kylebechtel77** [comment]
@jckuester That would be great!

**Comment by kylebechtel77** [comment]
@bflad I know you were watching @jckuester PR on this before, is there anything else we need to do to get this merged? 

I know @jckuester has some todo's he'd like to take care of, but that can be a separate PR, myself and @ltupin need the functionality thats already in here sooner rather than later.

**Comment by delwaterman** [comment]
+1 on getting this reviewed and merged

**Comment by DrFaust92** [comment]
hey @kylebechtel77 , do you mind rebasing this?

**Comment by Andeloth** [comment]
Could we get this reviewed and merged? Some of the projects I'm working on will need the extra options that are included here.

**Comment by jckuester** [comment]
Hi @bflad, I once started this PR and would like to help to finish what I started: As the scope `update resource` is probably too broad, would it help you if I split this PR up into smaller PRs for one attribute each (e.g., one for `accelerator_types`, `additional_code_repositories`, etc)?

**Comment by DrFaust92** [comment]
Hey @jckuester, I think it would be best to split the update functionally to existing arguments and open separate PRs for new argument (there are also a few existing ones for some of the ones added here)

**Comment by DrFaust92** [comment]
Closing this in favour of #15385 that been merged. thanks for all your work on this!

**Pull request closed without merging**
