### PR TITLE
adding filters for data_acm_certificate

### PR DESCRIPTION
**Pull request by Eraac**
Changes proposed in this pull request:
* adding possibilities to filters acm_certificate by tags

Output from acceptance testing:
```
AWS_PROFILE=kevin AWS_DEFAULT_REGION=eu-west-2 ACM_CERTIFICATE_SINGLE_ISSUED_DOMAIN=single.domain.tld ACM_CERTIFICATE_MULTIPLE_ISSUED_DOMAIN=multiple.domain.tld ACM_CERTIFICATE_ROOT_DOMAIN=domain.tld ACM_CERTIFICATE_NAME=my-certificate make testacc TESTARGS='-run TestAccAWSAcmCertificateDataSource'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./... -v -run TestAccAWSAcmCertificateDataSource -timeout 120m
?       github.com/terraform-providers/terraform-provider-aws   [no test files]
=== RUN   TestAccAWSAcmCertificateDataSource_singleIssued
--- PASS: TestAccAWSAcmCertificateDataSource_singleIssued (37.97s)
=== RUN   TestAccAWSAcmCertificateDataSource_multipleIssued
--- PASS: TestAccAWSAcmCertificateDataSource_multipleIssued (33.24s)
=== RUN   TestAccAWSAcmCertificateDataSource_noMatchReturnsError
--- PASS: TestAccAWSAcmCertificateDataSource_noMatchReturnsError (10.16s)
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws       81.415s

```

I am not very satisfied about the code in `tags.go`, If you have any suggestion feel free to suggest some changes

### CODE REVIEW

**Comment by Eraac** [comment]
Does something missing for be merged?

**Comment by JeremyPDC** [comment]
+1 can this be merged

**Comment by jakauppila** [comment]
Is there anything blocking this from getting merged?

**Comment by Eraac** [comment]
@bflad Any update? This PR has nearly one year and still relevant for us

**Comment by Eraac** [comment]
@ryan-Heard Can we have an update?

**Comment by DrFaust92** [comment]
i seem to have missed this and duplicated some of the logic with:
#11659

i don't mind closing it but this PR is has merge conflicts ATM because of changes to tagging, please see my PR for to address this and ill close mine.

**Comment by Eraac** [comment]
@DrFaust92 Honestly i'm tired of this PR ... waiting for a review/merge for more than one year. Furthermore yours seems to be more elegant, I hope your PR will be merge

**Pull request closed without merging**
