### PR TITLE
r/aws_elastic_beanstalk_application: Add appversion_lifecycle

### PR DESCRIPTION
**Pull request by mfenniak**
Adds `appversion_lifecycle` configuration under `aws_elastic_beanstalk_application` resource to configure automatic cleanup of application versions.

Addresses issue #537.

### CODE REVIEW

**Comment by bflad** [comment]
This has been released in [version 1.16.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1160-april-25-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.

**Comment by mfenniak** [comment]
Thanks for the review, merge, and quick release bflad!  Appreciate it.

**Comment by ozbillwang** [comment]
@mfenniak 

I recently applied the change with `appversion_lifecycle` with max-count to 50

But I found there are still more than 100 versions, I wait for one week, no versions reduced to 50 automatically?

Could you please confirm if this feature really works or not? How to confirm?

**Comment by mfenniak** [comment]
@ozbillwang Hi Bill; I can confirm that this capability actually works on AWS.  If it is appearing in the application's "Settings" page on the AWS Console, it is likely a problem with your IAM role.  Other than this, if it appears in the AWS Console, but it doesn't work, it's not a problem with the terraform side of this equation, and I'd suggest you reach out to AWS support for further help. :-)

Here's a working IAM role policy that my application uses:

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "",
            "Effect": "Allow",
            "Action": "elasticbeanstalk:DeleteApplicationVersion",
            "Resource": "arn:aws:elasticbeanstalk:*:*:applicationversion/*/*"
        },
        {
            "Sid": "",
            "Effect": "Allow",
            "Action": [
                "s3:GetObject",
                "s3:DeleteObject"
            ],
            "Resource": [
                "arn:aws:s3:::elasticbeanstalk-*/*",
                "arn:aws:s3:::elasticbeanstalk-*"
            ]
        }
    ]
}
```

**Pull request merged**
