### PR TITLE
Add glue CSV classifier

### LINKED ISSUE #9083: Add CSV classifier to the AWS Glue Classifier resource
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently the AWS Glue classifier resource supports 3/4 of the classifier types. CSV is not included for some reason (maybe it was added later?). This issue is to add the CSV classifier type to the resource 

Relevant AWS docs: https://docs.aws.amazon.com/glue/latest/dg/custom-classifier.html

### New or Affected Resource(s)

* aws_glue_classifier

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

Are there any other GitHub issues (open or closed) or pull requests that should be linked here? Vendor blog posts or documentation? For example:
Related Github Issues/PRs
* #3873 

AWS Docs:
* https://docs.aws.amazon.com/glue/latest/dg/aws-glue-api-crawler-classifiers.html
* https://docs.aws.amazon.com/sdk-for-go/api/service/glue/#Glue.CreateClassifier
*  https://docs.aws.amazon.com/glue/latest/dg/custom-classifier.html

### PR DESCRIPTION
**Pull request by ThomasWunderlich**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" comments, they generate extra noise for pull request followers and do not help prioritize the request

Relates OR Closes #9083

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```
Add glue CSV Classifier  for aws_glue_classifier

```

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccAWSGlueClassifier'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./... -v -parallel 20 -run=TestAccAWSGlueClassifier -timeout 120m
?   	github.com/terraform-providers/terraform-provider-aws	[no test files]
=== RUN   TestAccAWSGlueClassifier_CsvClassifier
=== PAUSE TestAccAWSGlueClassifier_CsvClassifier
=== RUN   TestAccAWSGlueClassifier_GrokClassifier
=== PAUSE TestAccAWSGlueClassifier_GrokClassifier
=== RUN   TestAccAWSGlueClassifier_GrokClassifier_CustomPatterns
=== PAUSE TestAccAWSGlueClassifier_GrokClassifier_CustomPatterns
=== RUN   TestAccAWSGlueClassifier_JsonClassifier
=== PAUSE TestAccAWSGlueClassifier_JsonClassifier
=== RUN   TestAccAWSGlueClassifier_TypeChange
=== PAUSE TestAccAWSGlueClassifier_TypeChange
=== RUN   TestAccAWSGlueClassifier_XmlClassifier
=== PAUSE TestAccAWSGlueClassifier_XmlClassifier
=== CONT  TestAccAWSGlueClassifier_CsvClassifier
=== CONT  TestAccAWSGlueClassifier_TypeChange
=== CONT  TestAccAWSGlueClassifier_XmlClassifier
=== CONT  TestAccAWSGlueClassifier_GrokClassifier_CustomPatterns
=== CONT  TestAccAWSGlueClassifier_GrokClassifier
=== CONT  TestAccAWSGlueClassifier_JsonClassifier
--- PASS: TestAccAWSGlueClassifier_GrokClassifier (22.67s)
--- PASS: TestAccAWSGlueClassifier_GrokClassifier_CustomPatterns (22.97s)
--- PASS: TestAccAWSGlueClassifier_CsvClassifier (22.98s)
--- PASS: TestAccAWSGlueClassifier_XmlClassifier (23.06s)
--- PASS: TestAccAWSGlueClassifier_JsonClassifier (23.13s)
--- PASS: TestAccAWSGlueClassifier_TypeChange (42.54s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	42.606s

...
```

### CODE REVIEW

**Comment by ThomasWunderlich** [comment]
So I think this should be ready to review. The one thing is that the pull request updates/pr-filter-sync keeps being cancelled, possibly because of a timeout. I'm not sure if there's something I can do to fix that or if it's something that's just failing at the moment.

**Comment by aeschright** [comment]
It's fine to ignore that pr-filter-sync check, we're using the newer GitHub actions setup on master but it doesn't matter for existing PR branches. If you rebase on master, that might fix it.

Can you add the results of your test run in the description above? We need that before we can review this.

**Comment by ThomasWunderlich** [comment]
Thanks @aeschright! This should be ready to review now.

**Comment by vertexclique** [comment]
ETA for a merge window for this one?

**Comment by banspaugh** [comment]
We really need CSV classifier support, when will this be implemented?

**Pull request merged**
