### PR TITLE
delete_on_termination on ENI has to be optional

### PR DESCRIPTION
**Pull request by savar**
There is a bug with the optional parameter `delete_on_termination` belonging to the `network_interfaces` configuration block.  

The current code treats the parameter `delete_on_termination` as type boolean (`schema.TypeBool`), the default being set to `false` in Golang when the value isn't set by the user.
If the user does not set a value, no value should be send to AWS so that the parameter is not set to any value.

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" comments, they generate extra noise for pull request followers and do not help prioritize the request

Fixes #8495 #6450 #6080 #6772 and maybe more

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
- [BREAKING BEHAVIOUR] aws_launch_template.network_interfaces if `delete_on_termination` not set, any value set in the LaunchTemplate will be removed
```

Output from acceptance testing:

before the change but with one more test change:
```diff
 func TestAccAWSLaunchTemplate_data(t *testing.T) {
        var template ec2.LaunchTemplate
        resName := "aws_launch_template.foo"
@@ -289,6 +326,7 @@ func TestAccAWSLaunchTemplate_data(t *testing.T) {
                                        resource.TestCheckResourceAttr(resName, "monitoring.#", "1"),
                                        resource.TestCheckResourceAttr(resName, "network_interfaces.#", "1"),
                                        resource.TestCheckResourceAttr(resName, "network_interfaces.0.security_groups.#", "1"),
+                                       resource.TestCheckResourceAttr(resName, "network_interfaces.0.delete_on_termination", ""),
                                        resource.TestCheckResourceAttr(resName, "placement.#", "1"),
                                        resource.TestCheckResourceAttrSet(resName, "ram_disk_id"),
                                        resource.TestCheckResourceAttr(resName, "vpc_security_group_ids.#", "1"),

```
```
$ make testacc TESTARGS='-run=TestAccAWSLaunchTemplate_data'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./... -v -parallel 20 -run=TestAccAWSLaunchTemplate_data -timeout 120m       
?       github.com/terraform-providers/terraform-provider-aws   [no test files]
=== RUN   TestAccAWSLaunchTemplate_data                                                              
=== PAUSE TestAccAWSLaunchTemplate_data                                                                      
=== CONT  TestAccAWSLaunchTemplate_data                                                                                        
--- FAIL: TestAccAWSLaunchTemplate_data (16.08s)                                                                                  
    testing.go:568: Step 0 error: Check failed: Check 16/20 error: aws_launch_template.foo: Attribute 'network_interfaces.0.delete_on_termination' expected "", got "false"
FAIL                                                                                              
FAIL    github.com/terraform-providers/terraform-provider-aws/aws       16.117s                                  
```

after the changes:
```
TF_ACC=1 go test ./... -v -parallel 20 -run=TestAccAWSLaunchTemplate_data -timeout 120m
?       github.com/terraform-providers/terraform-provider-aws   [no test files]
=== RUN   TestAccAWSLaunchTemplate_data
=== PAUSE TestAccAWSLaunchTemplate_data
=== CONT  TestAccAWSLaunchTemplate_data
--- PASS: TestAccAWSLaunchTemplate_data (23.00s)
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws       (cached)

TF_ACC=1 go test ./... -v -parallel 20 -run=TestAccAWSLaunchTemplate_NetworkInterfaces_DeleteOnTermination -timeout 120m
?       github.com/terraform-providers/terraform-provider-aws   [no test files]
=== RUN   TestAccAWSLaunchTemplate_NetworkInterfaces_DeleteOnTermination
=== PAUSE TestAccAWSLaunchTemplate_NetworkInterfaces_DeleteOnTermination
=== CONT  TestAccAWSLaunchTemplate_NetworkInterfaces_DeleteOnTermination
--- PASS: TestAccAWSLaunchTemplate_NetworkInterfaces_DeleteOnTermination (42.64s)
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws       42.673s

TF_ACC=1 go test ./... -v -parallel 20 -run=TestAccAWSLaunchTemplate_networkInterface -timeout 120m
?       github.com/terraform-providers/terraform-provider-aws   [no test files]
=== RUN   TestAccAWSLaunchTemplate_networkInterface
=== PAUSE TestAccAWSLaunchTemplate_networkInterface
=== RUN   TestAccAWSLaunchTemplate_networkInterface_ipv6Addresses
=== PAUSE TestAccAWSLaunchTemplate_networkInterface_ipv6Addresses
=== RUN   TestAccAWSLaunchTemplate_networkInterface_ipv6AddressCount
=== PAUSE TestAccAWSLaunchTemplate_networkInterface_ipv6AddressCount
=== CONT  TestAccAWSLaunchTemplate_networkInterface
=== CONT  TestAccAWSLaunchTemplate_networkInterface_ipv6AddressCount
=== CONT  TestAccAWSLaunchTemplate_networkInterface_ipv6Addresses
--- PASS: TestAccAWSLaunchTemplate_networkInterface_ipv6Addresses (27.42s)
--- PASS: TestAccAWSLaunchTemplate_networkInterface_ipv6AddressCount (27.42s)
--- PASS: TestAccAWSLaunchTemplate_networkInterface (44.52s)
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws       (cached)
```

### CODE REVIEW

**Comment by savar** [comment]
Is anyone interested in fixing this issue? It is kind of a bigger thing and it breaks in special situations the setup so that you normally run out of ENIs if you have a lot of autoscaling activities.

**Comment by savar** [comment]
@aeschright what about merging this one? I am happy to resolve the conflict but as this is hanging since almost half a year I would like to know if you are willing to fix this annoying bug?

**Comment by savar** [comment]
Thanks for the info. I rebased my pull request against master and force-pushed it. I hope that is fine?

**Comment by savar** [comment]
@aeschright 
image my merge conflict looks like someone else was doing the exact same thing as I wanted to do.. but it seems to me that this change was "fine to go into master".. can you tell me why this was the case for that change but not for mine? Again. This is a BUG which will FIX something for people.

**Comment by savar** [comment]
@aeschright ?

**Comment by bflad** [comment]
Hi @savar 👋  Thank you for submitting this -- please note that we intend on reviewing and pulling this in as part of our version 3.0.0 work beginning shortly.

**Comment by anGie44** [comment]
Looks great @savar 👍  This is just about ready to merge! just one oversight on my part to document this breaking-change in `website/docs/guides/version-3-upgrade.html.md`. if you don't mind, you'll just need  add to the list of `Upgrade topics` to add a heading for `## Resource: aws_launch_template` and add a brief description of this data type change

**Comment by savar** [comment]
> Looks great @savar +1 This is just about ready to merge! just one oversight on my part to document this breaking-change in `website/docs/guides/version-3-upgrade.html.md`. if you don't mind, you'll just need add to the list of `Upgrade topics`, add a heading for `## Resource: aws_launch_template`, and add a brief description of this data type change for the `delete_on_termination` argument

Hey, I tried my best. As I am no native English speaker, feel free to adjust the documentation as needed (maintainers can change the merge request) or tell me exactly what you would write into it.

**Pull request merged**
