### PR TITLE
Fix bug that batch_compute_environment with batch_job_queue reconstruction failed

### LINKED ISSUE #2044: `Cannot delete` error occurs when `aws_batch_compute_environment` used in `aws_batch_job_queue` is recreated
Hi there,

I found that `Cannot delete, found existing JobQueue relationship` error occurs when `aws_batch_compute_environment` used in `aws_batch_job_queue` is recreated.

Do you have any solutions in regards to this?

### Terraform Version

- Terraform v0.10.7
- Terraform-provider-aws v1.1.0

### Affected Resource(s)

- aws_batch_compute_environment
- aws_batch_job_queue

### Terraform Configuration Files
```hcl
resource "aws_batch_compute_environment" "test" {
  compute_environment_name = "test_batch"
  type                     = "MANAGED"
  service_role             = "arn:aws:iam::xxxxxxxx:role/xxxxxxxx"

  compute_resources {
    type          = "EC2"
    instance_role = "arn:aws:iam::xxxxxxxx:instance-profile/xxxxxxxx"
    instance_type = ["c4.large"]
    max_vcpus     = 8
    desired_vcpus = 0
    min_vcpus     = 0

    security_group_ids = [
      "sg-xxxxxxxx"
    ]

    subnets = [
      "subnet-xxxxxxxx", "subnet-xxxxxxxx"
    ]
  }
}

resource "aws_batch_job_queue" "test" {
  name = "test-batch-job-queue"
  state = "ENABLED"
  priority = 3
  compute_environments = ["${aws_batch_compute_environment.test.arn}"]
}
```

### Output

plan:

```
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

aws_batch_compute_environment.test: Refreshing state... (ID: test_batch)
aws_batch_job_queue.test: Refreshing state... (ID: arn:aws:batch:ap-northeast-1:xxxxxxxxxxxxx:job-queue/test-batch-job-queue)

------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place
-/+ destroy and then create replacement

Terraform will perform the following actions:

-/+ aws_batch_compute_environment.test (new resource required)
      id:                                                "test_batch" => <computed> (forces new resource)
      arn:                                               "arn:aws:batch:ap-northeast-1:xxxxxxxxxxxxx:compute-environment/test_batch" => <computed>
      compute_environment_name:                          "test_batch" => "test_batch"
      compute_resources.#:                               "1" => "1"
      compute_resources.0.desired_vcpus:                 "0" => "0"
      compute_resources.0.instance_role:                 "arn:aws:iam::xxxxxxxxxxxxx:instance-profile/xxxxxxxxxxxxx" => "arn:aws:iam::xxxxxxxxxxxxx:instance-profile/xxxxxxxxxxxxx"
      compute_resources.0.instance_type.#:               "1" => "1"
      compute_resources.0.instance_type.3819562017:      "c4.large" => "c4.large"
      compute_resources.0.max_vcpus:                     "8" => "8"
      compute_resources.0.min_vcpus:                     "0" => "0"
      compute_resources.0.security_group_ids.#:          "1" => "2" (forces new resource)
      compute_resources.0.security_group_ids.1377324769: "sg-xxxxxxxx" => "sg-xxxxxxxx"
      compute_resources.0.security_group_ids.3516056991: "" => "sg-yyyyyyyy" (forces new resource)
      compute_resources.0.subnets.#:                     "2" => "2"
      compute_resources.0.subnets.796390534:             "subnet-xxxxxxxxx" => "subnet-xxxxxxxxx"
      compute_resources.0.subnets.877356347:             "subnet-xxxxxxxxx" => "subnet-xxxxxxxxx"
      compute_resources.0.type:                          "EC2" => "EC2"
      ecc_cluster_arn:                                   "arn:aws:ecs:ap-northeast-1:xxxxxxxxxxxxx:cluster/test_batch_Batch_e2eb0db4-1f83-3935-94af-e38f529d6480" => <computed>
      ecs_cluster_arn:                                   "arn:aws:ecs:ap-northeast-1:xxxxxxxxxxxxx:cluster/test_batch_Batch_e2eb0db4-1f83-3935-94af-e38f529d6480" => <computed>
      service_role:                                      "arn:aws:iam::xxxxxxxxxxxxx:role/xxxxxxxxx" => "arn:aws:iam::xxxxxxxxxxxxx:role/xxxxxxxxx"
      state:                                             "DISABLED" => "ENABLED"
      status:                                            "VALID" => <computed>
      status_reason:                                     "ComputeEnvironment Healthy" => <computed>
      type:                                              "MANAGED" => "MANAGED"

  ~ aws_batch_job_queue.test
      compute_environments.#:                            "1" => <computed>


Plan: 1 to add, 1 to change, 1 to destroy.
```

apply:

```
aws_batch_compute_environment.test: Refreshing state... (ID: test_batch)
aws_batch_job_queue.test: Refreshing state... (ID: arn:aws:batch:ap-northeast-1:xxxx:job-queue/test-batch-job-queue)
aws_batch_compute_environment.test: Destroying... (ID: test_batch)
Error applying plan:

1 error(s) occurred:

* aws_batch_compute_environment.test (destroy): 1 error(s) occurred:

* aws_batch_compute_environment.test: : Cannot delete, found existing JobQueue relationship
        status code: 400, request id: xxx
```

### Panic Output

None

### Expected Behavior

1. delete `aws_batch_job_queue`
2. delete and create `aws_batch_compute_environment`
3. create `aws_batch_job_queue`

### Actual Behavior

1. recreate compute environment
2. update job queue

### Steps to Reproduce

1. `terraform apply`
2. Add a security group id to `aws_batch_compute_environment.test`.
3. `terraform apply`
4. The error occurs.

### Important Factoids

No

### References

I could not find any issues related this.

### PR DESCRIPTION
**Pull request by shibataka000**
## Description
Fix #2044 .

## Tests
```
$ make testacc TESTARGS='-run=TestAccAWSBatchJobQueue'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v -run=TestAccAWSBatchJobQueue -timeout 120m
?   	github.com/terraform-providers/terraform-provider-aws	[no test files]
=== RUN   TestAccAWSBatchJobQueue_basic
--- PASS: TestAccAWSBatchJobQueue_basic (151.76s)
=== RUN   TestAccAWSBatchJobQueue_update
--- PASS: TestAccAWSBatchJobQueue_update (182.52s)
=== RUN   TestAccAWSBatchJobQueue_updateComputeEnvironment
--- PASS: TestAccAWSBatchJobQueue_updateComputeEnvironment (260.25s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	594.554s
```

### CODE REVIEW

**Comment by radeksimko** [comment]
Hi @shibataka000 & @mia-0032,
I would not say this is a bug and I don't think we should be making `compute_environment` ForceNew. It is an updatable field per API: http://docs.aws.amazon.com/batch/latest/APIReference/API_UpdateJobQueue.html#Batch-UpdateJobQueue-request-computeEnvironmentOrder

Here's a way to avoid the problem:

```hcl
resource "random_string" "name" {
  length = 16
  special = false
  upper = false
}

resource "aws_batch_compute_environment" "test" {
  compute_environment_name = "sample-${random_string.name.result}"
...
  lifecycle {
    create_before_destroy = true
  }
}
```

Firstly I added the lifecycle block to reverse the ordering of operations (from `destroy env -> create env -> change references` to `create env -> change references -> destroy env`). Because we'll need two namespaces to exist at the same time, they also need to have a unique name, hence I used the `random` provider to generate one.

We can mention this example somewhere in the docs.

The other solution we can apply here is very similar, except that it doesn't involve `random` provider - see how we deal with this in [`aws_launch_configuration`](https://www.terraform.io/docs/providers/aws/r/launch_configuration.html#name_prefix) which has very similar relationship with ASG.

For the reasons above I'm inclined to close this PR - let me know what you think.

**Comment by shibataka000** [comment]
@radeksimko Thank you for your advice! I can update `compute_environment` with `job_queue` by using `random` provider and `lifecycle`.

**Comment by mia-0032** [comment]
@radeksimko Thank you for your advice. I also could re-create `aws_batch_compute_environment` using random and lifecycle.

**Comment by myco** [comment]
Waiting for merge :-)

**Comment by ploh** [comment]
@radeksimko 
> Firstly I added the lifecycle block to reverse the ordering of operations (from destroy env -> create env -> change references to create env -> change references -> destroy env).

Would the best solution not be the following order of operations:
```"nullify" references -> destroy env -> create env -> set references```

This way the `random` is not needed. Is this possible somehow?

**Comment by benderillo** [comment]
@radeksimko There is still an issue here.
I have compute environment defined following the approach you suggested (with random string as prefix for the env name).
However, whenever I make a change in configuration of the environment, my terraform apply would fail saying that the resource already exist.
It would try to create a compute environment before deleting the old one, just as it is told to do.
But the `random_string` resource is not changed, hence the new name is the same as old so the terraform bails with an error.
Suggesting to tweak the length of the `random_string` whenever we want it to pass is a hack and not a proper solution.
Another approach of using `keepers` doesn't really appeal to me either. 
There are tons of inputs to compute environment that can cause it to be `forced to be recreated` and listing them all as keepers to the random string sounds again as a hack rather than a solution.

Having `name_prefix` attribute, however that would automatically refresh once the resource is marked for re-creation would be nicer approach.

**Comment by paul-michalik** [comment]
@radeksimko 
I believe that using the random resource, setting up keepers for all immutable parameters and make the random resource ID part of the compute environment name is the cleanest way to assure that everything updates properly. I admit it feels a little hacky because you have to convert every keeper into a string - for example list of subnet ids become `join("-", local.compute_environment.compute_resources.subnets)` which is not exactly nice. Hence the proposal would be to make this nicer - allow all keepers which stringify or hash themselves internally.

Other solution I have been testing is to mark the compute environment with
```
lifecycle {
    ignore_changes = all
}
```
However this causes Terraform to announce the changes in `plan` but silently ignore the changes during `apply` instead of bailing out with an error. Unless I missed something, this behavior is hardly acceptable.

**Pull request closed without merging**
