### PR TITLE
New Resource: aws_wafregional_web_acl_association

### PR DESCRIPTION
**Pull request by DennyLoko**
This PR is a port of the originally opened by @yusukegoto at hashicorp/terraform#13712.

Depends on https://github.com/terraform-providers/terraform-provider-aws/pull/1013 and https://github.com/terraform-providers/terraform-provider-aws/pull/1014.

### CODE REVIEW

**Comment by radeksimko** [comment]
Pending https://github.com/terraform-providers/terraform-provider-aws/pull/1013 and https://github.com/terraform-providers/terraform-provider-aws/pull/1014 as both are touching the same part of codebase and are likely to result in conflicts.

**Comment by nik-shornikov** [comment]
👍 please, this functionality is getting kicked back and harder to even track..

**Comment by Ninir** [comment]
Hi @nik-shornikov 

As @radeksimko mentionned it, this is pending the other PRs to be managed & merged :/
If @DennyLoko wants, we can help him finish the other ones if time is missing! :)

Still, be sure we don't forget anything/anyone! 😄

**Comment by BSick7** [comment]
@radeksimko I am trying to finalize this PR @ https://github.com/terraform-providers/terraform-provider-aws/pull/3199

**Comment by radeksimko** [comment]
#3755 (which added this resource) was just merged. Thanks to everyone involved.

**Pull request closed without merging**
