### PR TITLE
Support for dynamic instance lists on ALB target group attachments

### PR DESCRIPTION
**Pull request by fredsted**
Currently, target group attachment instances are basically hardcoded:

```
resource "aws_alb_target_group_attachment" "attachment_backend_1" {
  target_group_arn = "${aws_alb_target_group.test.arn}"
  target_id        = "${aws_instance.backend1.id}"
}
resource "aws_alb_target_group_attachment" "attachment_backend_2" {
  target_group_arn = "${aws_alb_target_group.test.arn}"
  target_id        = "${aws_instance.backend2.id}"
}
```

Which doesn't work well when creating AWS instances using the `count` property. What if you want to scale the amount of instances?

In https://github.com/hashicorp/terraform/pull/9986 @optimisticanshul made a PR that allows you to do this — specifying multiple backends in a single target group attachment:

```
resource "aws_instance" "backend1" {
  count = 1
}

resource "aws_instance" "backend2" {
  count = 1
}

resource "aws_alb_target_group_attachment" "test" {
  target_group_arn = "${aws_alb_target_group.test.arn}"
  targets {
   target_id = "${aws_instance.backend1.id}"
  }
  targets {
   target_id = "${aws_instance.backend2.id}"
  }
}
```

Again, if you're creating a bunch of AWS instances with the `count` property, this is not ideal. I made a few small changes so instances with the `count` property can be added to an ALB attachment. I also renamed `targets` to `instances`, to keep in line with the similar `aws_elb` resource, where this is already implemented.

With this PR, you can just do this:

```
resource "aws_instance" "backend" {
  count = 2  // or how many you want
}

resource "aws_alb_target_group_attachment" "test" {
  target_group_arn = "${aws_alb_target_group.test.arn}"
  instances        = ["${aws_instance.backend.*.id}"]
}
```

---

Original PR in main repo: https://github.com/hashicorp/terraform/pull/14857

### CODE REVIEW

**Comment by grems6** [comment]
Hi,

I tested the fix but I had errors because in my infrastructure the target port is not specified in the attachement. I fixed the issue and I also added an update function. I have created a PR to fredsted with my changes.

grems6

**Comment by fredsted** [comment]
@radeksimko Thanks for labeling my PR! What would it take to get this merged?

**Comment by igordavid** [comment]
Hello,

Are there any estimates when this will be merged, which version will it be released in? 

Thanks in advance!

**Comment by jocelynthode** [comment]
@radeksimko Any ETA on this PR being merged ? This is blocking when deploying new instance to production (at the moment the change would occur some downtime)

**Comment by thatrevguy** [comment]
Would be great to get this merged! Is there anything else needed for that to happen?

**Comment by dperetti** [comment]
Can't wait !! ❤️

**Comment by fredsted** [comment]
@thatrevguy I don't know, I've tried to get feedback from Terraform team in various ways, but haven't had any luck so far. I'm also just using a local copy for now.

**Comment by seanjfellows** [comment]
We're definitely also having this issue, would like to see this merged in.

**Comment by cnoffsin** [comment]
Really need this merged.

**Comment by joshmyers** [comment]
Also need this any updates? @radeksimko

**Comment by CruzanCaramele** [comment]
hi wonderful people working on this, this is awesome. Please will this be merged in the next release?

**Comment by aries-strato** [comment]
+1, would love see this merged.

**Comment by opiumozor** [comment]
When are you guys planning on merging this?

**Comment by tomthetommy** [comment]
Can't wait for this merge. Any idea when it'll be?

**Comment by karlvlam** [comment]
When will we get this merged?

**Comment by levinse** [comment]
It's been two years since I originally reported this bug at https://github.com/hashicorp/terraform/issues/8684 and a year since the above PR was made. When is this getting fixed?

**Comment by fredsted** [comment]
I have posted a thread on the Terraform Google Group. Maybe it can help giving some attention to this. https://groups.google.com/forum/#!topic/terraform-tool/zxmQEvggmq8

**Comment by bflad** [comment]
Drive-by comment: I cannot speak for the historical context here, but its likely this was not merged because it appears this was submitted as a workaround for some limitations in the Terraform configuration language when working with `count` and removing elements of a list, e.g. removing the first element of the below list would trigger recreation with the other two elements due to their list index changing:

```hcl
var "example_list" {
  default = ["1.2.3.4", "5.6.7.8", "9.10.11.12"]
}

resource "aws_lb_target_group_attachment" "example" {
  # ... other configuration ...
  count     = "${length(var.example_list)}"
  target_id = "${var.example_list[count.index]}"
}
```

In the upcoming Terraform 0.12 release, it looks like it will be possible at a certain point to [index by using `for_each` with a map (Resource for_each section)](https://www.hashicorp.com/blog/hashicorp-terraform-0-12-preview-for-and-for-each):
> When the for_each argument value is a map, Terraform will identify each instance by the string key of the map element rather than by a numeric index, which will avoid many limitations with the current pattern of using count to iterate over a list where items may be added and removed from the middle of that list, changing the subsequent indices.

The syntax would be something like the following (where the map key doesn't matter too much in this example):

```hcl
# Example Terraform 0.12 implementation -- details may change during development
var "example_list" {
  default = ["1.2.3.4", "5.6.7.8", "9.10.11.12"]
}

resource "aws_lb_target_group_attachment" "example" {
  # ... other configuration ...
  for_each  = zipmap(var.example_list, var.example_list)
  target_id = each.value
}
```

Any item can then be removed without affecting others. This will likely remove the problem globally, rather than patching an individual resource within an individual provider.

Tracking the `for_each` support can be found in this Terraform core issue upstream: https://github.com/hashicorp/terraform/issues/17179

**Comment by fredsted** [comment]
@bflad Thanks for the response!

How is it going to work w/ aws_instance? Something like this?

```
resource "aws_instance" "backend" {
  count = 2  // or how many you want
}

resource "aws_lb_target_group_attachment" "example" {
  # ... other configuration ...
  for_each  = zipmap(aws_instance.backend.*.id, aws_instance.backend.*.id)
  target_id = each.value
}
```

**Comment by eriksw** [comment]
@bflad Given that for_each has been pushed back from the initial 0.12 release, can this PR be reconsidered for merging due to the extremely dire impact of this issue? Having live instances' attachments destroyed/re-created (thus disrupting traffic for users) when replacing a dead instance largely negates the point of having a load balancer.

**Comment by fredsted** [comment]
@bflad @radeksimko One last attempt. Do you want this or not?

**Comment by CruzanCaramele** [comment]
@fredsted I believe this is much needed please

**Comment by seanjfellows** [comment]
When I'm recommending people stay away from Terraform, this will be my go-to example.

**Comment by e-moshaya** [comment]
FYI, you can easily achieve dynamic provisioning of target group attachment with a single aws_alb_target_group_attachment resourcen.. The way I achieved this is as follows:

```
resource "aws_alb_target_group_attachment" "swarm_nodes" {
  count            = "${var.docker_swarm_node_count}"
  target_group_arn = "${module.alb.target_group_arns[0]}"
  target_id        = "${module.docker_swarm_aws_instance.id[count.index]}"
}
```

The above block creates attachments based on the number instance ids and count

**Comment by respectTheCode** [comment]
This is what I did to make it work.

```
resource "aws_lb_target_group_attachment" "elb-tg-1" {
  count            = "${var.swarm_manager_count}"
  target_group_arn = "${aws_lb_target_group.elb-tg.arn}"
  target_id        = "${element(aws_instance.swarm_manager.*.id, count.index)}"
  port             = 80
}
```

**Comment by ishworg** [comment]
> ```terraform
> # Example Terraform 0.12 implementation -- details may change during development
> var "example_list" {
>   default = ["1.2.3.4", "5.6.7.8", "9.10.11.12"]
> }
> 
> resource "aws_lb_target_group_attachment" "example" {
>   # ... other configuration ...
>   for_each  = zipmap(var.example_list, var.example_list)
>   target_id = each.value
> }
> ```

This is a good workaround.  The only very small issue is that now I need to perform targeted `apply`s instead of the usual, *plan-then-apply* workflow.

For context, I am using the https://github.com/terraform-aws-modules/terraform-aws-ec2-instance where for a single EC2 instance resource they export `module.aws_instance.*.id` only because it does not know ahead of time the number of EC2 instances to attach TG to.

E.g.,
```
$ terraform plan -target module.foo.module.foo_instance # -out
$ terrafom apply -target module.foo.module.foo_instance 
```
And then for the remaining resources
```
$ terraform plan && terraform apply
```

As such I needed to do this on `0.12.20`:
```
resource aws_lb_target_group_attachment tga {
  target_group_arn = aws_lb_target_group.tg.arn
  for_each         = zipmap(module.foo_instance.id, module.foo_instance.id)
  target_id        = each.value
  port             = 80
}
```

In closing, it'd be good to either have a better way to do this or be addressed in upcoming Terraform release.

**Pull request closed without merging**
