### PR TITLE
Remove usage of terraform.NewResourceConfig

### PR DESCRIPTION
**Pull request by appilon**
the `config` package (co-dependent of `terraform.NewResourceConfig`) is being removed. The new function `terraform.NewResourceConfigRaw` should replace both of them.

### CODE REVIEW

**Comment by aeschright** [comment]
Hold pending next week's Terraform core release.

**Comment by aeschright** [comment]
Holding till next week's tf release.

**Comment by bflad** [comment]
Terraform v0.12.7 is now merged. This is ready for rebase/resubmission. 👍

**Comment by appilon** [comment]
PR is ready for review

**Pull request merged**
