### PR TITLE
Add AWS Lake Formation service client

### PR DESCRIPTION
**Pull request by ewbankkit**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" comments, they generate extra noise for pull request followers and do not help prioritize the request

Relates https://github.com/terraform-providers/terraform-provider-aws/issues/9700.

Add service client for [AWS Lake Formation](https://aws.amazon.com/lake-formation/) following the [Contributing instructions](https://github.com/terraform-providers/terraform-provider-aws/blob/master/.github/CONTRIBUTING.md#new-service).

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note

```

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccXXX'

...
```

### CODE REVIEW

**Comment by ewbankkit** [comment]
Cannot be completed until https://github.com/terraform-providers/terraform-provider-aws/pull/9670 is merged, which requires a fix to the AWS SDK: https://github.com/aws/aws-sdk-go/issues/2741, https://github.com/aws/aws-sdk-go/pull/2742.

**Comment by aeschright** [comment]
AWS decided on a more general fix, which was just merged: https://github.com/aws/aws-sdk-go/pull/2747

**Comment by ewbankkit** [comment]
Include cb9dc0332e88648f697720459f252697c610f9f4 from https://github.com/terraform-providers/terraform-provider-aws/pull/9670.

**Comment by bflad** [comment]
Once this is rebased (just merged v1.23.0 of the AWS Go SDK), we should be able to get this in 👍

**Comment by ewbankkit** [comment]
Thanks; rebased.

**Pull request merged**
