### PR TITLE
S3 "grant" example used "permission" when key is "permissions"

### PR DESCRIPTION
**Pull request by M1ke**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
NONE
```

Tests not relevant, is change to documentation

### CODE REVIEW

**Comment by ewbankkit** [comment]
Closes https://github.com/terraform-providers/terraform-provider-aws/issues/12321.

**Comment by ewbankkit** [comment]
Thanks for this.
I think this is a duplicate of https://github.com/terraform-providers/terraform-provider-aws/pull/12426.

**Comment by M1ke** [comment]
Wow, two people with the same change within a couple hours. Guess everybody's got time to work on docs now they're in lockdown!

**Comment by M1ke** [comment]
Not to pick on #12426, but I think that adds another typo by changing to `FULL_ACONTROL` instead of `FULL_CONTROL`

**Comment by M1ke** [comment]
I missed some extra spaces which apparently the linter didn't like. Have resolved

**Comment by gdavison** [comment]
Thanks for the PR, @M1ke! I've merged #12426, but it's great that we had a couple fixes for this

**Pull request closed without merging**
