### PR TITLE
r/aws_apigatewayv2_integration: Specify required parameters on update

### PR DESCRIPTION
**Pull request by ewbankkit**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes https://github.com/terraform-providers/terraform-provider-aws/issues/15861.

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
resource/aws_apigatewayv2_integration: Correctly handle update of AWS service integrations
```

Output from acceptance testing:

```console
$ make testacc TEST=./aws/ TESTARGS='-run=TestAccAWSAPIGatewayV2Integration_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSAPIGatewayV2Integration_ -timeout 120m
=== RUN   TestAccAWSAPIGatewayV2Integration_basicWebSocket
=== PAUSE TestAccAWSAPIGatewayV2Integration_basicWebSocket
=== RUN   TestAccAWSAPIGatewayV2Integration_basicHttp
=== PAUSE TestAccAWSAPIGatewayV2Integration_basicHttp
=== RUN   TestAccAWSAPIGatewayV2Integration_disappears
=== PAUSE TestAccAWSAPIGatewayV2Integration_disappears
=== RUN   TestAccAWSAPIGatewayV2Integration_IntegrationTypeHttp
=== PAUSE TestAccAWSAPIGatewayV2Integration_IntegrationTypeHttp
=== RUN   TestAccAWSAPIGatewayV2Integration_LambdaWebSocket
=== PAUSE TestAccAWSAPIGatewayV2Integration_LambdaWebSocket
=== RUN   TestAccAWSAPIGatewayV2Integration_LambdaHttp
=== PAUSE TestAccAWSAPIGatewayV2Integration_LambdaHttp
=== RUN   TestAccAWSAPIGatewayV2Integration_VpcLinkWebSocket
=== PAUSE TestAccAWSAPIGatewayV2Integration_VpcLinkWebSocket
=== RUN   TestAccAWSAPIGatewayV2Integration_VpcLinkHttp
=== PAUSE TestAccAWSAPIGatewayV2Integration_VpcLinkHttp
=== RUN   TestAccAWSAPIGatewayV2Integration_AwsServiceIntegration
=== PAUSE TestAccAWSAPIGatewayV2Integration_AwsServiceIntegration
=== CONT  TestAccAWSAPIGatewayV2Integration_basicWebSocket
=== CONT  TestAccAWSAPIGatewayV2Integration_LambdaHttp
=== CONT  TestAccAWSAPIGatewayV2Integration_AwsServiceIntegration
=== CONT  TestAccAWSAPIGatewayV2Integration_VpcLinkHttp
=== CONT  TestAccAWSAPIGatewayV2Integration_LambdaWebSocket
=== CONT  TestAccAWSAPIGatewayV2Integration_VpcLinkWebSocket
=== CONT  TestAccAWSAPIGatewayV2Integration_IntegrationTypeHttp
=== CONT  TestAccAWSAPIGatewayV2Integration_disappears
=== CONT  TestAccAWSAPIGatewayV2Integration_basicHttp
--- PASS: TestAccAWSAPIGatewayV2Integration_disappears (34.57s)
--- PASS: TestAccAWSAPIGatewayV2Integration_basicHttp (38.92s)
--- PASS: TestAccAWSAPIGatewayV2Integration_basicWebSocket (39.36s)
--- PASS: TestAccAWSAPIGatewayV2Integration_LambdaWebSocket (56.08s)
--- PASS: TestAccAWSAPIGatewayV2Integration_IntegrationTypeHttp (58.04s)
--- PASS: TestAccAWSAPIGatewayV2Integration_AwsServiceIntegration (58.59s)
--- PASS: TestAccAWSAPIGatewayV2Integration_LambdaHttp (60.98s)
--- PASS: TestAccAWSAPIGatewayV2Integration_VpcLinkHttp (309.45s)
--- PASS: TestAccAWSAPIGatewayV2Integration_VpcLinkWebSocket (683.83s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	683.889s
```

### CODE REVIEW

**Comment by DrFaust92** [comment]
Tests are passing except for lambda tests where I get:

```
Error: error creating API Gateway v2 integration: BadRequestException: Invalid role ARN
```

* TestAccAWSAPIGatewayV2Integration_LambdaHttp
* TestAccAWSAPIGatewayV2Integration_LambdaWebSocket

**Comment by ewbankkit** [comment]
@DrFaust92 The failures are probably due to the permissions of the account you used to verify. I changed the 2 Lambda tests to use an explicit resource permission which is now configured in the test.
Please retest.

**Comment by DrFaust92** [comment]
LGTM:

```
--- PASS: TestAccAWSAPIGatewayV2Integration_disappears (37.61s)
--- PASS: TestAccAWSAPIGatewayV2Integration_basicHttp (45.59s)
--- PASS: TestAccAWSAPIGatewayV2Integration_basicWebSocket (63.01s)
--- PASS: TestAccAWSAPIGatewayV2Integration_LambdaHttp (73.07s)
--- PASS: TestAccAWSAPIGatewayV2Integration_IntegrationTypeHttp (73.38s)
--- PASS: TestAccAWSAPIGatewayV2Integration_AwsServiceIntegration (79.45s)
--- PASS: TestAccAWSAPIGatewayV2Integration_LambdaWebSocket (85.31s)
--- PASS: TestAccAWSAPIGatewayV2Integration_VpcLinkHttp (345.25s)
--- PASS: TestAccAWSAPIGatewayV2Integration_VpcLinkWebSocket (762.52s)
```

**Comment by breathingdust** [comment]
LGTM :rocket: Thanks @ewbankkit 

Verified Acceptance Tests in Commercial (us-west-2)

```console
make testacc TEST=./aws/ TESTARGS='-run=TestAccAWSAPIGatewayV2Integration_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSAPIGatewayV2Integration_ -timeout 120m
=== RUN   TestAccAWSAPIGatewayV2Integration_basicWebSocket
=== PAUSE TestAccAWSAPIGatewayV2Integration_basicWebSocket
=== RUN   TestAccAWSAPIGatewayV2Integration_basicHttp
=== PAUSE TestAccAWSAPIGatewayV2Integration_basicHttp
=== RUN   TestAccAWSAPIGatewayV2Integration_disappears
=== PAUSE TestAccAWSAPIGatewayV2Integration_disappears
=== RUN   TestAccAWSAPIGatewayV2Integration_IntegrationTypeHttp
=== PAUSE TestAccAWSAPIGatewayV2Integration_IntegrationTypeHttp
=== RUN   TestAccAWSAPIGatewayV2Integration_LambdaWebSocket
=== PAUSE TestAccAWSAPIGatewayV2Integration_LambdaWebSocket
=== RUN   TestAccAWSAPIGatewayV2Integration_LambdaHttp
=== PAUSE TestAccAWSAPIGatewayV2Integration_LambdaHttp
=== RUN   TestAccAWSAPIGatewayV2Integration_VpcLinkWebSocket
=== PAUSE TestAccAWSAPIGatewayV2Integration_VpcLinkWebSocket
=== RUN   TestAccAWSAPIGatewayV2Integration_VpcLinkHttp
=== PAUSE TestAccAWSAPIGatewayV2Integration_VpcLinkHttp
=== RUN   TestAccAWSAPIGatewayV2Integration_AwsServiceIntegration
=== PAUSE TestAccAWSAPIGatewayV2Integration_AwsServiceIntegration
=== CONT  TestAccAWSAPIGatewayV2Integration_basicWebSocket
=== CONT  TestAccAWSAPIGatewayV2Integration_LambdaHttp
=== CONT  TestAccAWSAPIGatewayV2Integration_LambdaWebSocket
=== CONT  TestAccAWSAPIGatewayV2Integration_IntegrationTypeHttp
=== CONT  TestAccAWSAPIGatewayV2Integration_AwsServiceIntegration
=== CONT  TestAccAWSAPIGatewayV2Integration_VpcLinkHttp
=== CONT  TestAccAWSAPIGatewayV2Integration_VpcLinkWebSocket
=== CONT  TestAccAWSAPIGatewayV2Integration_disappears
=== CONT  TestAccAWSAPIGatewayV2Integration_basicHttp
2020/10/29 10:56:27 [DEBUG] Trying to get account information via sts:GetCallerIdentity
--- PASS: TestAccAWSAPIGatewayV2Integration_disappears (17.27s)
--- PASS: TestAccAWSAPIGatewayV2Integration_basicHttp (19.62s)
--- PASS: TestAccAWSAPIGatewayV2Integration_basicWebSocket (19.69s)
--- PASS: TestAccAWSAPIGatewayV2Integration_AwsServiceIntegration (35.43s)
--- PASS: TestAccAWSAPIGatewayV2Integration_LambdaHttp (37.97s)
--- PASS: TestAccAWSAPIGatewayV2Integration_IntegrationTypeHttp (40.89s)
--- PASS: TestAccAWSAPIGatewayV2Integration_LambdaWebSocket (44.64s)
--- PASS: TestAccAWSAPIGatewayV2Integration_VpcLinkHttp (336.89s)
--- PASS: TestAccAWSAPIGatewayV2Integration_VpcLinkWebSocket (653.69s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	655.146s
```

Verified Acceptance Tests in GovCloud (us-gov-west-1)

```console
make testacc TEST=./aws/ TESTARGS='-run=TestAccAWSAPIGatewayV2Integration_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSAPIGatewayV2Integration_ -timeout 120m
=== RUN   TestAccAWSAPIGatewayV2Integration_basicWebSocket
=== PAUSE TestAccAWSAPIGatewayV2Integration_basicWebSocket
=== RUN   TestAccAWSAPIGatewayV2Integration_basicHttp
=== PAUSE TestAccAWSAPIGatewayV2Integration_basicHttp
=== RUN   TestAccAWSAPIGatewayV2Integration_disappears
=== PAUSE TestAccAWSAPIGatewayV2Integration_disappears
=== RUN   TestAccAWSAPIGatewayV2Integration_IntegrationTypeHttp
=== PAUSE TestAccAWSAPIGatewayV2Integration_IntegrationTypeHttp
=== RUN   TestAccAWSAPIGatewayV2Integration_LambdaWebSocket
=== PAUSE TestAccAWSAPIGatewayV2Integration_LambdaWebSocket
=== RUN   TestAccAWSAPIGatewayV2Integration_LambdaHttp
=== PAUSE TestAccAWSAPIGatewayV2Integration_LambdaHttp
=== RUN   TestAccAWSAPIGatewayV2Integration_VpcLinkWebSocket
=== PAUSE TestAccAWSAPIGatewayV2Integration_VpcLinkWebSocket
=== RUN   TestAccAWSAPIGatewayV2Integration_VpcLinkHttp
=== PAUSE TestAccAWSAPIGatewayV2Integration_VpcLinkHttp
=== RUN   TestAccAWSAPIGatewayV2Integration_AwsServiceIntegration
=== PAUSE TestAccAWSAPIGatewayV2Integration_AwsServiceIntegration
=== CONT  TestAccAWSAPIGatewayV2Integration_basicWebSocket
=== CONT  TestAccAWSAPIGatewayV2Integration_LambdaHttp
=== CONT  TestAccAWSAPIGatewayV2Integration_AwsServiceIntegration
=== CONT  TestAccAWSAPIGatewayV2Integration_VpcLinkWebSocket
=== CONT  TestAccAWSAPIGatewayV2Integration_VpcLinkHttp
=== CONT  TestAccAWSAPIGatewayV2Integration_IntegrationTypeHttp
=== CONT  TestAccAWSAPIGatewayV2Integration_LambdaWebSocket
=== CONT  TestAccAWSAPIGatewayV2Integration_disappears
=== CONT  TestAccAWSAPIGatewayV2Integration_basicHttp
--- PASS: TestAccAWSAPIGatewayV2Integration_disappears (14.29s)
--- PASS: TestAccAWSAPIGatewayV2Integration_basicWebSocket (15.68s)
--- PASS: TestAccAWSAPIGatewayV2Integration_basicHttp (16.25s)
--- PASS: TestAccAWSAPIGatewayV2Integration_IntegrationTypeHttp (25.51s)
--- PASS: TestAccAWSAPIGatewayV2Integration_LambdaHttp (30.54s)
--- PASS: TestAccAWSAPIGatewayV2Integration_LambdaWebSocket (35.90s)
--- PASS: TestAccAWSAPIGatewayV2Integration_AwsServiceIntegration (43.09s)
--- PASS: TestAccAWSAPIGatewayV2Integration_VpcLinkHttp (291.80s)
--- PASS: TestAccAWSAPIGatewayV2Integration_VpcLinkWebSocket (650.51s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	652.084s
```

**Pull request merged**
