### PR TITLE
[WIP] App Mesh preview - HTTP header based routing, route priorities, cookie based routing and retry policy

### PR DESCRIPTION
**Pull request by ewbankkit**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" comments, they generate extra noise for pull request followers and do not help prioritize the request

_WIP_ to add support for [App Mesh HTTP Header based routing](https://docs.aws.amazon.com//app-mesh/latest/userguide/route-http-headers.html): https://github.com/aws/aws-app-mesh-roadmap/issues/15.
Based on:
* https://raw.githubusercontent.com/aws/aws-app-mesh-roadmap/9d6f1b89bf7211b9239055102f40aee2ea67b412/appmesh-preview/service-model.json
* https://github.com/ewbankkit/aws-sdk-go/tree/appmesh-preview-07-2019

### CODE REVIEW

**Comment by ewbankkit** [comment]
Acceptance tests so far:

```console
$ make testacc TEST=./aws TESTARGS='-run=TestAccAWSAppmesh/Route'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -parallel 20 -run=TestAccAWSAppmesh/Route -timeout 120m
=== RUN   TestAccAWSAppmesh
=== RUN   TestAccAWSAppmesh/Route
=== RUN   TestAccAWSAppmesh/Route/httpRoute
=== RUN   TestAccAWSAppmesh/Route/tcpRoute
=== RUN   TestAccAWSAppmesh/VirtualRouter
=== RUN   TestAccAWSAppmesh/VirtualRouter/basic
=== RUN   TestAccAWSAppmesh/VirtualRouter/tags
--- FAIL: TestAccAWSAppmesh (130.92s)
    --- FAIL: TestAccAWSAppmesh/Route (30.29s)
        --- FAIL: TestAccAWSAppmesh/Route/httpRoute (15.61s)
            testing.go:568: Step 0 error: errors during apply:
                
                Error: error creating App Mesh route: NotFoundException: Mesh with name tf-test-mesh-7524312028689710824 is not found
                	status code: 404, request id: ace10de0-95b3-48c5-a572-d0ae3fc77d8a
                
                  on /var/folders/4j/lf5jdq5j4y91g80ytf6qzjwmk6drp5/T/tf-test890901864/main.tf line 35:
                  (source code not available)
                
                
        --- FAIL: TestAccAWSAppmesh/Route/tcpRoute (14.68s)
            testing.go:568: Step 0 error: errors during apply:
                
                Error: error creating App Mesh route: NotFoundException: Mesh with name tf-test-mesh-8471920719625911535 is not found
                	status code: 404, request id: d98a5862-f233-4070-ab12-ca0db326abb2
                
                  on /var/folders/4j/lf5jdq5j4y91g80ytf6qzjwmk6drp5/T/tf-test854632154/main.tf line 35:
                  (source code not available)
                
                
    --- PASS: TestAccAWSAppmesh/VirtualRouter (100.63s)
        --- PASS: TestAccAWSAppmesh/VirtualRouter/basic (41.29s)
        --- PASS: TestAccAWSAppmesh/VirtualRouter/tags (59.34s)
FAIL
FAIL	github.com/terraform-providers/terraform-provider-aws/aws	130.989s
make: *** [testacc] Error 1
```

**Comment by ewbankkit** [comment]
New acceptance test:

```console
$ make testacc TEST=./aws TESTARGS='-run=TestAccAWSAppmesh/Route/httpHeader'==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -parallel 20 -run=TestAccAWSAppmesh/Route/httpHeader -timeout 120m
=== RUN   TestAccAWSAppmesh
=== RUN   TestAccAWSAppmesh/Route
=== RUN   TestAccAWSAppmesh/Route/httpHeader
=== RUN   TestAccAWSAppmesh/VirtualRouter
--- PASS: TestAccAWSAppmesh (35.64s)
    --- PASS: TestAccAWSAppmesh/Route (35.64s)
        --- PASS: TestAccAWSAppmesh/Route/httpHeader (35.64s)
    --- PASS: TestAccAWSAppmesh/VirtualRouter (0.00s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	35.677s
```

**Comment by ewbankkit** [comment]
Once the feature is released I'll open a new PR, cherry pick the relevant commits and close this PR.

**Comment by ewbankkit** [comment]
Expanding scope to include additional preview features:
* [Route priorities](https://github.com/aws/aws-app-mesh-roadmap/issues/77)
* [Cookie based routing](https://github.com/aws/aws-app-mesh-roadmap/issues/14)
* [Retry policy](https://github.com/aws/aws-app-mesh-roadmap/issues/7) - [Documentation](https://docs.aws.amazon.com/app-mesh/latest/userguide/route-retry-policy.html)

**Comment by ewbankkit** [comment]
TODO: Support for end-to-end encryption: https://github.com/aws/aws-app-mesh-roadmap/issues/39. This looks like additions to `aws_appmesh_virtual_node.spec.listener`.

**Comment by ewbankkit** [comment]
Even though it's in the current service model, TLS is not yet supported in the preview channel:
```
ForbiddenException: TLS Certificates from ACM are not supported.
```

Current acceptance tests for virtual nodes:

```console
$ make testacc TEST=./aws TESTARGS='-run=TestAccAWSAppmesh/VirtualNode'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -parallel 20 -run=TestAccAWSAppmesh/VirtualNode -timeout 120m
=== RUN   TestAccAWSAppmesh
=== RUN   TestAccAWSAppmesh/VirtualNode
=== RUN   TestAccAWSAppmesh/VirtualNode/logging
=== RUN   TestAccAWSAppmesh/VirtualNode/basic
=== RUN   TestAccAWSAppmesh/VirtualNode/cloudMapServiceDiscovery
=== RUN   TestAccAWSAppmesh/VirtualNode/listenerHealthChecks
--- PASS: TestAccAWSAppmesh (183.95s)
    --- PASS: TestAccAWSAppmesh/VirtualNode (183.95s)
        --- PASS: TestAccAWSAppmesh/VirtualNode/logging (30.98s)
        --- PASS: TestAccAWSAppmesh/VirtualNode/basic (18.60s)
        --- PASS: TestAccAWSAppmesh/VirtualNode/cloudMapServiceDiscovery (103.84s)
        --- PASS: TestAccAWSAppmesh/VirtualNode/listenerHealthChecks (30.52s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	183.982s
```

**Comment by ewbankkit** [comment]
It looks like HTTP header and cookie based routing plus route priorities are available with [AWS SDK v1.23.2](https://github.com/aws/aws-sdk-go/releases/tag/v1.23.2).

Requires:
* https://github.com/terraform-providers/terraform-provider-aws/pull/9770

**Comment by ewbankkit** [comment]
TLS support has been re-enabled in the preview channel: https://github.com/aws/aws-app-mesh-roadmap/issues/39#issuecomment-529019693.
[Documentation](https://docs.aws.amazon.com//app-mesh/latest/userguide/virtual-node-tls.html).
[Walkthrough](https://github.com/aws/aws-app-mesh-examples/blob/master/walkthroughs/tls-with-acm/README.md).

It looks like the HTTP Retry model has also changed recently: https://github.com/aws/aws-app-mesh-roadmap/commit/ab21aee781c80df3b0a85f46c1ead45d31c39dad#diff-bed927c299bc696566dfae64bae275e2.

**Comment by ewbankkit** [comment]
Current Virtual Node acceptance tests:

```console
$ make testacc TEST=./aws TESTARGS='-run=TestAccAWSAppmesh/VirtualNode'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -parallel 20 -run=TestAccAWSAppmesh/VirtualNode -timeout 120m
=== RUN   TestAccAWSAppmesh
=== RUN   TestAccAWSAppmesh/VirtualNode
=== RUN   TestAccAWSAppmesh/VirtualNode/listenerHealthChecks
=== RUN   TestAccAWSAppmesh/VirtualNode/listenerTls
=== RUN   TestAccAWSAppmesh/VirtualNode/logging
=== RUN   TestAccAWSAppmesh/VirtualNode/basic
=== RUN   TestAccAWSAppmesh/VirtualNode/cloudMapServiceDiscovery
--- FAIL: TestAccAWSAppmesh (193.21s)
    --- FAIL: TestAccAWSAppmesh/VirtualNode (193.21s)
        --- PASS: TestAccAWSAppmesh/VirtualNode/listenerHealthChecks (30.63s)
        --- FAIL: TestAccAWSAppmesh/VirtualNode/listenerTls (11.24s)
            testing.go:568: Step 0 error: errors during apply:
                
                Error: error creating App Mesh virtual node: BadRequestException: Certificate arn:aws:acm:us-west-2:346386234494:certificate/39b1275a-1386-42fc-aceb-f551c62ea3ce is invalid. App Mesh accepts only certificates issued by AWS Certificate Manager Private Certificate Authority.
                	status code: 400, request id: 3c122985-7954-4a4b-a312-0b50558ee0e5
                
                  on /tmp/tf-test210645761/main.tf line 33:
                  (source code not available)
                
                
        --- PASS: TestAccAWSAppmesh/VirtualNode/logging (30.03s)
        --- PASS: TestAccAWSAppmesh/VirtualNode/basic (18.40s)
        --- PASS: TestAccAWSAppmesh/VirtualNode/cloudMapServiceDiscovery (102.90s)
FAIL
FAIL	github.com/terraform-providers/terraform-provider-aws/aws	193.231s
GNUmakefile:20: recipe for target 'testacc' failed
make: *** [testacc] Error 1
```

**Comment by ewbankkit** [comment]
Retry policy bug fixed: https://github.com/aws/aws-app-mesh-roadmap/issues/89.
Verify in production service: https://github.com/terraform-providers/terraform-provider-aws/issues/10075.

**Comment by ewbankkit** [comment]
### TODO

http2/gRPC support:
* https://github.com/aws/aws-app-mesh-roadmap/issues/96
* https://github.com/aws/aws-app-mesh-roadmap/pull/114

**Comment by ewbankkit** [comment]
http2/gRPC support is now available in [AWS SDK v1.25.19](https://github.com/aws/aws-sdk-go/releases/tag/v1.25.19).
Requires:
* https://github.com/terraform-providers/terraform-provider-aws/pull/10476

**Comment by bflad** [comment]
AWS Go SDK v1.25.21 has been merged if that helps

**Comment by ewbankkit** [comment]
http2/gRPC support issue: https://github.com/terraform-providers/terraform-provider-aws/issues/10803

**Comment by ewbankkit** [comment]
Closing in favour of https://github.com/terraform-providers/terraform-provider-aws/pull/11850.

**Pull request closed without merging**
