### PR TITLE
New Resource: aws_swf_domain

### PR DESCRIPTION
**Pull request by robinjoseph08**
#131 

```
TF_ACC=1 go test ./aws -v -run=TestAccAwsSwfDomain_basic -timeout 120m
=== RUN   TestAccAwsSwfDomain_basic
--- PASS: TestAccAwsSwfDomain_basic (11.93s)
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws       11.966s
```

### CODE REVIEW

**Comment by robinjoseph08** [comment]
Any chance this PR will be reviewed soon? I'd love to get this in. Thanks!

**Comment by jdpaton** [comment]
Can we get this get merged?

**Comment by robinjoseph08** [comment]
Hey @bflad, I don't think I'll be able to get to this soon unfortunately. But anyone is free to pick it up!

**Comment by bflad** [comment]
Thanks @robinjoseph08! I have addressed PR feedback in https://github.com/terraform-providers/terraform-provider-aws/commit/ec2540658fa855b1629d9642f75508ce5b136446 and it passes acceptance testing:

```
make testacc TEST=./aws TESTARGS='-run=TestAccAWSSwfDomain'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -run=TestAccAWSSwfDomain -timeout 120m
=== RUN   TestAccAWSSwfDomain_basic
--- PASS: TestAccAWSSwfDomain_basic (13.01s)
=== RUN   TestAccAWSSwfDomain_NamePrefix
--- PASS: TestAccAWSSwfDomain_NamePrefix (11.40s)
=== RUN   TestAccAWSSwfDomain_GeneratedName
--- PASS: TestAccAWSSwfDomain_GeneratedName (12.78s)
=== RUN   TestAccAWSSwfDomain_Description
--- PASS: TestAccAWSSwfDomain_Description (11.61s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	48.829s
```

**Comment by bflad** [comment]
This has been released in [version 1.27.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1270-july-11-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.

**Pull request merged**
