### PR TITLE
Adding second scenario where IPv6 is not supported

### PR DESCRIPTION
**Pull request by missingcharacter**
When trying to create a security group in AWS CN I ran into the following error:

```
* module.security_groups.aws_security_group.dev-https-in: 1 error(s) occurred:

* aws_security_group.dev-https-in: Error revoking default IPv6 egress rule for Security Group (sg-56489bc5): InvalidParameterValue: remote-ipv6-range
	status code: 400, request id: beeb90dd-7b32-4905-9b94-59e3e00f77f5
```

Added this check as another way to determine IPv6 is not supported therefore ignore the error and continue.
I already tested with the same case that gave me these errors and I no longer get them and my security groups are created.

I'm not sure the code is exactly how it should be, I'll be more than happy to modify it if needed.

### CODE REVIEW

**Comment by missingcharacter** [comment]
Looks like I didn't fix my problem, with this, I have to run terraform twice with this code change, I'll be posting an update once I'm able to make this work.

**Comment by missingcharacter** [comment]
ok, I'm now confident this works, let me know if I should change anything.

**Comment by radeksimko** [comment]
Hi @missingcharacter 
thanks for the PR.

While we do have some AWS CN specific code, it's always scoped explicitly to that region, so it's safe to assume it will only affect users of that region.

We (HashiCorp) do not have access to the Chinese AWS region, unfortunately, so we can't reliably test this - which is the main reason this is hanging here. Is this something you could potentially help us with?

An acceptable alternative is pasting full HTTP response (available from [debug log](https://www.terraform.io/docs/internals/debugging.html)) and decide how to tighten the condition to something like `isAWSErr("InvalidParameterValue", "specific IPv6 err message")`. The error code seems to be a bit too generic and there's risk of ignoring errors we don't intend to ignore.

Admittedly `InvalidPermission.NotFound` code match is already quite generic and brings some risk.

**Comment by timonwong** [comment]
FYI: The HTTP 400 bad request returned from AWS CN is:
```xml
<Response>
<Errors>
<Error><Code>InvalidParameterValue</Code><Message>remote-ipv6-range</Message></Error></Errors>
<RequestID>xxxxxxxxxxxxxxxxxxxxxxxxxxx</RequestID>
</Response>
```

**Comment by Ninir** [comment]
Hi @timonwong 

Is `remote-ipv6-range` the exact message that is returned by AWS or actually a placeholder?
If it's a placeholder, we should check that this message is actually in the form of `2620:0:2d0:200::7/32`, etc.

**Comment by timonwong** [comment]
Hi @Ninir, it's the exact message returned from AWS CN.

**Comment by Ninir** [comment]
Then as Radek exposed it, can you update this work using:

```go
isAWSErr("InvalidParameterValue", "remote-ipv6-range")
```

to handle this case?

Thanks!

**Comment by missingcharacter** [comment]
Sorry for the long delay on these changes, made the change and tested, this time I kept `TF_LOG=DEBUG` and saved the logs in case you need them.

**Comment by missingcharacter** [comment]
@Ninir yes, this fixes my issue too

**Comment by Ninir** [comment]
Thank you @missingcharacter ! :)

**Comment by hoffmannliu-ayla** [comment]
Hi,
When will new AWS provider including this PR available ? I ran into this issue too....:'(

**Pull request merged**
