### PR TITLE
d/aws_s3_bucket: get default encryption configuration

### LINKED ISSUE #2217: Feature request: New S3 encryption support
_This issue was originally opened by @wayneclancy as hashicorp/terraform#16591. It was migrated here as a result of the [provider split](https://www.hashicorp.com/blog/upcoming-provider-changes-in-terraform-0-10/). The original body of the issue is below._

<hr>

Is there any chance we can add support for the new range of AWS S3 server side encryption features? 

https://aws.amazon.com/blogs/aws/new-amazon-s3-encryption-security-features/

### PR DESCRIPTION
**Pull request by trung**
Fix #2217 and #2196 

- [x] Modify `aws_s3_bucket` data source
- [x] Add acceptance tests
- [x] Write documentation

### CODE REVIEW

**Comment by radeksimko** [comment]
Depends on #2472

**Comment by radeksimko** [comment]
(because we need a test which is actually testing S3 bucket with encryption enabled)

**Comment by trung** [comment]
as #2472 has been closed, i'll write additional test for this PR

**Comment by trung** [comment]
Done!
```
❯ make testacc TESTARGS="-run=TestAccDataSourceS3Bucket_*"
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v -run=TestAccDataSourceS3Bucket_* -timeout 120m
?   	github.com/terraform-providers/terraform-provider-aws	[no test files]
=== RUN   TestAccDataSourceS3Bucket_basic
--- PASS: TestAccDataSourceS3Bucket_basic (36.01s)
=== RUN   TestAccDataSourceS3Bucket_website
--- PASS: TestAccDataSourceS3Bucket_website (35.32s)
=== RUN   TestAccDataSourceS3Bucket_whenDefaultEncryptionNotEnabled
--- PASS: TestAccDataSourceS3Bucket_whenDefaultEncryptionNotEnabled (32.70s)
=== RUN   TestAccDataSourceS3Bucket_whenDefaultEncryptionEnabledWithAES256
--- PASS: TestAccDataSourceS3Bucket_whenDefaultEncryptionEnabledWithAES256 (34.60s)
=== RUN   TestAccDataSourceS3Bucket_whenDefaultEncryptionEnabledWithAWSKMS
--- PASS: TestAccDataSourceS3Bucket_whenDefaultEncryptionEnabledWithAWSKMS (64.13s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	202.787s
```

**Comment by radeksimko** [comment]
Hi @trung 
do you mind resolving conflicts and cleaning up the git log?

Thanks.

**Comment by trung** [comment]
sorry for the mess, i'll clean it up and submit a new PR.

**Comment by trung** [comment]
Closed this to raise another one

**Pull request closed without merging**
