### PR TITLE
Vendored AWS Organisations

### PR DESCRIPTION
**Pull request by Ninir**
Extracted the vendors from https://github.com/terraform-providers/terraform-provider-aws/pull/2530 to better review the related data source.

Ran command: `govendor fetch github.com/aws/aws-sdk-go/service/organizations@v1.12.62`

### CODE REVIEW

**Comment by bflad** [comment]
FYI I think we might be waiting until after v1.7.1 is released (ETA Friday) to bring in vendor changes. This might also need to be `v1.12.63` according to #3021 already being approved.

**Comment by radeksimko** [comment]
@Ninir https://github.com/terraform-providers/terraform-provider-aws/pull/3044 was merged, do you mind re-vendoring the right version?

Thanks!

**Comment by Ninir** [comment]
@radeksimko Sure thing, here we go :)

**Comment by radeksimko** [comment]
I'm going to merge this in now as I'd like to merge https://github.com/terraform-providers/terraform-provider-aws/pull/3084 too. 😉

**Pull request merged**
