### PR TITLE
Fixes Terraform crash for AWS Kinesis Firehose

### LINKED ISSUE #4109: Terraform plugin 1.14.0 crashing
Terraform `0.10.8`
Terraform-provider-aws: `1.14.0`

my crashlog is 54 MB so attaching gzip here
[crash.log.gz](https://github.com/terraform-providers/terraform-provider-aws/files/1885686/crash.log.gz)

### PR DESCRIPTION
**Pull request by Puneeth-n**
fixes #4109

### CODE REVIEW

**Comment by bflad** [comment]
I think this can be a one line fix:

https://github.com/terraform-providers/terraform-provider-aws/blob/20adea2e019a209563352f05f498cd265d6a2789/aws/resource_aws_kinesis_firehose_delivery_stream.go#L179

**Comment by Puneeth-n** [comment]
@bflad done. I'm running acceptance tests. will update once it is done.

**Comment by bflad** [comment]
@Puneeth-n thank you very much! Sorry I meant to look into this yesterday and submit the fix. 😅

**Comment by bflad** [comment]
I'll also kick off the tests on our side just to verify this with what testing we do have.

**Comment by Puneeth-n** [comment]
@bflad here are the tests:

```
AWS_REGION=eu-west-1 TF_ACC=1 go test ./... -v -run=TestAccAWSKinesisFirehoseDeliveryStream_ -timeout 120m -parallel=4
?   	github.com/terraform-providers/terraform-provider-aws	[no test files]
=== RUN   TestAccAWSKinesisFirehoseDeliveryStream_importBasic
--- PASS: TestAccAWSKinesisFirehoseDeliveryStream_importBasic (138.34s)
=== RUN   TestAccAWSKinesisFirehoseDeliveryStream_s3basic
--- PASS: TestAccAWSKinesisFirehoseDeliveryStream_s3basic (131.52s)
=== RUN   TestAccAWSKinesisFirehoseDeliveryStream_s3KinesisStreamSource
--- PASS: TestAccAWSKinesisFirehoseDeliveryStream_s3KinesisStreamSource (122.38s)
=== RUN   TestAccAWSKinesisFirehoseDeliveryStream_s3WithCloudwatchLogging
--- PASS: TestAccAWSKinesisFirehoseDeliveryStream_s3WithCloudwatchLogging (119.20s)
=== RUN   TestAccAWSKinesisFirehoseDeliveryStream_s3ConfigUpdates
--- PASS: TestAccAWSKinesisFirehoseDeliveryStream_s3ConfigUpdates (249.11s)
=== RUN   TestAccAWSKinesisFirehoseDeliveryStream_ExtendedS3basic
--- PASS: TestAccAWSKinesisFirehoseDeliveryStream_ExtendedS3basic (145.06s)
=== RUN   TestAccAWSKinesisFirehoseDeliveryStream_ExtendedS3KmsKeyArn
--- PASS: TestAccAWSKinesisFirehoseDeliveryStream_ExtendedS3KmsKeyArn (307.46s)
=== RUN   TestAccAWSKinesisFirehoseDeliveryStream_ExtendedS3InvalidProcessorType
--- PASS: TestAccAWSKinesisFirehoseDeliveryStream_ExtendedS3InvalidProcessorType (1.67s)
=== RUN   TestAccAWSKinesisFirehoseDeliveryStream_ExtendedS3InvalidParameterName
--- PASS: TestAccAWSKinesisFirehoseDeliveryStream_ExtendedS3InvalidParameterName (1.74s)
=== RUN   TestAccAWSKinesisFirehoseDeliveryStream_ExtendedS3Updates
--- PASS: TestAccAWSKinesisFirehoseDeliveryStream_ExtendedS3Updates (158.22s)
=== RUN   TestAccAWSKinesisFirehoseDeliveryStream_RedshiftConfigUpdates
--- PASS: TestAccAWSKinesisFirehoseDeliveryStream_RedshiftConfigUpdates (983.75s)
=== RUN   TestAccAWSKinesisFirehoseDeliveryStream_SplunkConfigUpdates
--- PASS: TestAccAWSKinesisFirehoseDeliveryStream_SplunkConfigUpdates (159.78s)
=== RUN   TestAccAWSKinesisFirehoseDeliveryStream_ElasticsearchConfigUpdates
--- PASS: TestAccAWSKinesisFirehoseDeliveryStream_ElasticsearchConfigUpdates (1133.50s)
=== RUN   TestAccAWSKinesisFirehoseDeliveryStream_missingProcessingConfiguration
--- PASS: TestAccAWSKinesisFirehoseDeliveryStream_missingProcessingConfiguration (134.28s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	3786.024s
root@5a926ca22be9:/go/src/github.com/terraform-providers/terraform-provider-aws#
```

**Comment by Puneeth-n** [comment]
@bflad No worries. :) We wanna move to `NodeJs 8.10` and this was a real blocker for us so looked into it today. Thanks for the review 🚀 Any idea when `1.14.1` will be released?

**Comment by bflad** [comment]
I'm planning on releasing v1.14.1 tomorrow 😄

**Comment by bflad** [comment]
This has been released in [version 1.14.1 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1141-april-11-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.

**Pull request merged**
