### PR TITLE
rd/launch_template -  add `partition_number` attribute + validations

### PR DESCRIPTION
**Pull request by DrFaust92**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
resource_aws_launch_template: add `partition_number` attribute
data_source_aws_launch_template: add `partition_number` attribute
aws_launch_template: add plan time validation to `volume_type`, `spot_instance_type`, `ipv6_addresses`, `ipv4_addresses`, `private_ip_address`
```

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccAWSLaunchTemplate_'
--- PASS: TestAccAWSLaunchTemplate_basic (86.50s)
--- PASS: TestAccAWSLaunchTemplate_data (44.63s)
--- PASS: TestAccAWSLaunchTemplate_description (66.45s)
--- PASS: TestAccAWSLaunchTemplate_update (129.63s)
--- PASS: TestAccAWSLaunchTemplate_tags (78.96s)
--- PASS: TestAccAWSLaunchTemplate_capacityReservation_preference (71.81s)
--- PASS: TestAccAWSLaunchTemplate_capacityReservation_target (62.00s)
--- PASS: TestAccAWSLaunchTemplate_creditSpecification_nonBurstable (112.67s)
--- PASS: TestAccAWSLaunchTemplate_creditSpecification_t2 (39.65s)
--- PASS: TestAccAWSLaunchTemplate_creditSpecification_t3 (40.29s)
--- PASS: TestAccAWSLaunchTemplate_IamInstanceProfile_EmptyConfigurationBlock (34.92s)
--- PASS: TestAccAWSLaunchTemplate_networkInterface (105.72s)
--- PASS: TestAccAWSLaunchTemplate_associatePublicIPAddress (194.07s)
--- PASS: TestAccAWSLaunchTemplate_networkInterface_ipv6Addresses (102.58s)
--- PASS: TestAccAWSLaunchTemplate_networkInterface_ipv6AddressCount (99.01s)
--- PASS: TestAccAWSLaunchTemplate_instanceMarketOptions (316.32s)
--- PASS: TestAccAWSLaunchTemplate_licenseSpecification (118.82s)
--- PASS: TestAccAWSLaunchTemplate_BlockDeviceMappings_EBS_DeleteOnTermination (117.98s)
--- PASS: TestAccAWSLaunchTemplate_ElasticInferenceAccelerator (66.85s)
--- PASS: TestAccAWSLaunchTemplate_EbsOptimized (155.83s)
--- PASS: TestAccAWSLaunchTemplate_disappears (27.77s)
--- PASS: TestAccAWSLaunchTemplate_placement_partitionNum(52.05s)



--- PASS: TestAccAWSLaunchTemplateDataSource_basic (60.08s)

...
```

### CODE REVIEW

**Comment by DrFaust92** [comment]
@gdavison , adding some tests for the partition number argument. any idea how to tackle the host_resource_group_arn argument?

**Comment by DrFaust92** [comment]
@gdavison dropped `host_resource_group_arn` from the PR as it requires a dedicated host

**Comment by Joldnine** [comment]
This change will give a default value of 0 for partition_number, causing cluster mode ASG scaling up failure.

**Comment by minggaograb** [comment]
Hi this MR will break other module like [terraform-aws-eks](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/workers_launch_template.tf#L297) which do not explicitly handle "partition_number". The "partition_number" will become "0" and create following error. 
`Launching a new EC2 instance. Status Reason: Could not launch Spot Instances. InvalidParameterValue - You cannot use PartitionNumber with a Placement Group that does not exist. Specify a valid Placement Group and try again. Launching EC2 instance failed.`

**Comment by Vlaaaaaaad** [comment]
We also make use of modules that don't handle `partition_number`. Since we did a couple applies today, and this broke all ASGs that used LTs.

Pinning the version for the provider fixes this:
```hcl
provider "aws" {
  version = "<= 2.60.0"

  region = "us-east-1
}
```

**Comment by chancez** [comment]
This seems like a regression.

**Comment by BellonXiao** [comment]
This fix brought another issue:
1 error occurred:
    * module.env_reg.module.envreg_cluster.aws_autoscaling_group.autoscaling_group: 1 error occurred:
    * aws_autoscaling_group.autoscaling_group: Error creating AutoScaling Group: ValidationError: You must use a valid fully-formed launch template. You cannot use PartitionNumber with a Placement Group that does not exist. Specify a valid Placement Group and try again.

**Pull request merged**
