### PR TITLE
provide automated authorization message decoding

### PR DESCRIPTION
**Pull request by matt-deboer**
**Changes**:
Adds a new optional boolean provider attribute `decode_authorization_messages`; when enabled, any encoded authorization messages will be automatically decoded using the `sts:DecodeAuthorizationMessage` action. Decoding requires that the effective user/role has permission to `sts:DecodeAuthorizationMessage` on resource `*`.

Example:
```
provider "aws" {
   decode_authorization_messages = true
   ...
}
```

**Before**:
```
* aws_instance.example: Error launching source instance: UnauthorizedOperation: You are not authorized to perform this operation. Encoded authorization failure message: PtmmadLNbKWVfeHgApa-62p0EM9DuD4gAtc3EhbBhVy3wIGiy2mTOcuDhCpfakJisGMB9OUTCGll2zbH-hMSguO1EOBAiswlapbXU_ovWgfAqNAawrGMs-WCo3k54Y6pzcwTkGlZYDspgh18Z98GdFOb29rLilYyHvpCW1lC9H2OGnHmpq9E2NeCZHINNE6Xzfdy468JOD_Ou3jfebEHx4oxYxShrEytBEbmhD_amiwPoIMpZ6xRWjn8KRdJM8RpAfGMoY7LIN4JQwIgiZpQOJBlzWuQq-sM7OicdDopjLRxEkApfHnh8JJIjZx6As6-42oPDd594_cdfBr6R34NA6xiDsueFL8ep8S7kprIffjt0MKqsdFe5SFat1Feo23QaU9n2f_nWcBgvUCgBpvDZk9VRe48tT72lYvHJFajutopRsvR9gjdPnrFqnbTp1HCmWZ4M2esBy7cDmZUUu02eZ_OZDEIojUAE0sfzBKIyaFvSzN07NEmd0Hi4xxGEQJcFg4RSko27b-8sI05Ot3qE_5MgZsfCPdbay4i23el4MlLSH9FS4WgUmYi-jxcAj6uVI_s19m23H4v2w_dl-9OKMEjCE6fWyoGAApT2osVirSo1t-0XhrHgzhQTNNI6WkNvNuPs95T_9ttln7u8VKBYcGQC2Rca7v5mtqzyr9NElexpLPOHND1xY4taxYyTJiC7_nv4otoXr9feW1vnH_9ewEPE2e4zVyY4ep6Cbm2xugIskrXqPElJjGjUF6rliwhKN8LjaFLEg
	status code: 403, request id: 27a76565-182c-4edd-a090-351ab9cf840c
``` 

**After**:
```
* aws_instance.example: Error launching source instance: UnauthorizedOperation: You are not authorized to perform this operation. Authorization failure message: '{"allowed":false,"explicitDeny":true,"matchedStatements":{"items":[{"statementId":"","effect":"DENY","principals":{"items":[{"value":"XXXXXXXXXXXXXXXXXX"}]},"principalGroups":{"items":[]},"actions":{"items":[{"value":"ec2:RunInstances"}]},"resources":{"items":[{"value":"arn:aws:ec2:*:*:instance/*"}]},"conditions":{"items":[{"key":"aws:RequestTag/application-group","values":{"items":[{"value":"appdev-platform"}]}}]}}]},"failures":{"items":[]},"context":{"principal":{"id":"XXXXXXXXXXXXXXXXXX:000000123456789000","arn":"arn:aws:sts::123456789012:assumed-role/appdev-platform-application-deployer-doer/000000123456789000"},"action":"ec2:RunInstances","resource":"arn:aws:ec2:us-west-2:123456789012:instance/*","conditions":{"items":[{"key":"aws:Resource","values":{"items":[{"value":"instance/*"}]}},{"key":"aws:Account","values":{"items":[{"value":"123456789012"}]}},{"key":"ec2:AvailabilityZone","values":{"items":[{"value":"us-west-2b"}]}},{"key":"ec2:ebsOptimized","values":{"items":[{"value":"false"}]}},{"key":"ec2:InstanceType","values":{"items":[{"value":"t2.nano"}]}},{"key":"ec2:RootDeviceType","values":{"items":[{"value":"ebs"}]}},{"key":"aws:Region","values":{"items":[{"value":"us-west-2"}]}},{"key":"aws:Service","values":{"items":[{"value":"ec2"}]}},{"key":"ec2:InstanceID","values":{"items":[{"value":"*"}]}},{"key":"aws:Type","values":{"items":[{"value":"instance"}]}},{"key":"ec2:Tenancy","values":{"items":[{"value":"default"}]}},{"key":"ec2:Region","values":{"items":[{"value":"us-west-2"}]}},{"key":"aws:ARN","values":{"items":[{"value":"arn:aws:ec2:us-west-2:123456789012:instance/*"}]}}]}}}'
```

**Note**: There is some discussion about adding this in the upstream, but nothing solid yet:
https://github.com/aws/aws-sdk-go/issues/1536

### CODE REVIEW

**Comment by radeksimko** [comment]
Hi @matt-deboer 
thanks for the PR.

It would be nice to add more context to the error message.
A few notes:

1. We're going to need an option for enabling this behaviour and keeping it disabled by default. There are users of Terraform which use it in very sensitive environments (in terms of both performance and security) which may not want that extra API call or potential exposure of sensitive data. This is one of the reasons why we have all the [`skip_*`](https://www.terraform.io/docs/providers/aws/index.html#skip_credentials_validation) options.
2. Wrapping CRUD of each resource seems like a heavy-hammer approach which won't cover many API calls which are inside CRUD anyway. Have you explored the option of using the SDK's handlers? https://github.com/aws/aws-sdk-go/blob/353c1631448a44b91547377df96451e3de718490/aws/request/request.go#L502-L518

**Comment by matt-deboer** [comment]
Didn't see that, but should have; thanks. Will fix.

**Comment by matt-deboer** [comment]
@radeksimko PTAL;
- made functionality optional
- leveraged request.Handlers to decode errors; I had to use `Handlers.UnmarshalError.AfterEachFn` as I need the error object to be populated before I decode it

**Comment by radeksimko** [comment]
Thanks - this looks significantly cleaner than the previous version on first sight 👍 

I'll have a play later as have a few other PR reviews in my queue...

**Comment by bflad** [comment]
Hi @matt-deboer 👋 Is this pull request still necessary/valid? The linked AWS Go SDK issue indicates that this would potentially be resolved by an EC2 API update that could've occurred. If so, we will need to clean up the merge conflicts before taking a fresh look at this. Thanks.

**Comment by bflad** [comment]
Hi again 👋 Since we haven't heard back, we are going to close this pull request for now. If anyone is still interested in this change, please submit a new pull request and we will take a fresh look. Thanks.

**Pull request closed without merging**
