### PR TITLE
Update aws_acm_certificate to add custom domain for email verification

### LINKED ISSUE #3851: add domain validation options parameter to aws_acm_certificate
### Terraform Version
Terraform v0.10.4

### Affected Resource(s)
- aws_acm_certificate

### Terraform Configuration Files
```hcl
resource "aws_acm_certificate" "cluster_internal" {
  domain_name = "www.domain.com"
  subject_alternative_names = ["app1.domain.com", "app2.domain.com", "app3.domain.com", "app4.domain.com", "app5.domain.com", "app6.domain.com", "app7.domain.com", "app8.domain.com", "app9.domain.com", "app10.domain.com", "app11.domain.com", "app12.domain.com", "app13.domain.com", "app14.domain.com", "app15.domain.com"]
  validation_method = "EMAIL"
  lifecycle {
    create_before_destroy = true
  }
}

```
### Expected Behavior
The certificate is requested and email validations are sent out to the email adresses in whois and some generic adresses.

### Actual Behavior
AWS sometimes uses the correct mail adresses from whois and derived from the second level domain, and sometimes only the mail adresses derived from the third level domain (e.g. "admin@app1.domain.com" instead of something like "hostmaster@domain.com"). This can vary between additional names for one certificate, so that some subdomains can be validated, others not.

This can be avoided by setting the ValidationDomain option for each DomainName to the second level domain. By doing this, all validation mails are sent to the domain owner configured in whois.

### Steps to Reproduce
1. request a certificate with a long list of alternative names using terraform
2. select EMAIL validation
3. check the email adresses used for validation. sometimes, the mails are not sent to the domain owner configured in whois, but only to the generic adresses derived directly from the subdomain 
4. request the same certificate via cli, e.g.:
```bash
aws acm request-certificate --domain-name www.domain.com --validation-method EMAIL --subject-alternative-names app1.domain.com app2.domain.com app3.domain.com app4.domain.com app5.domain.com app6.domain.com app7.domain.com app8.domain.com app9.domain.com app10.domain.com app11.domain.com app12.domain.com app13.domain.com app14.domain.com app15.domain.com --domain-validation-options DomainName=www.domain.com,ValidationDomain=domain.com DomainName=app1.domain.com,ValidationDomain=domain.com DomainName=app2.domain.com,ValidationDomain=domain.com DomainName=app3.domain.com,ValidationDomain=domain.com DomainName=app4.domain.com,ValidationDomain=domain.com DomainName=app5.domain.com,ValidationDomain=domain.com DomainName=app6.domain.com,ValidationDomain=domain.com DomainName=app7.domain.com,ValidationDomain=domain.com DomainName=app8.domain.com,ValidationDomain=domain.com DomainName=app9.domain.com,ValidationDomain=domain.com DomainName=app10.domain.com,ValidationDomain=domain.com DomainName=app11.domain.com,ValidationDomain=domain.com DomainName=app12.domain.com,ValidationDomain=domain.com DomainName=app13.domain.com,ValidationDomain=domain.com DomainName=app14.domain.com,ValidationDomain=domain.com DomainName=app15.domain.com,ValidationDomain=domain.com 
```
5. check the email adresses used for validation. All mails are sent to the domain owner.

### Important Factoids
I want to request a certificate for several subdomains, but I need to set the validation domain parameter.
See https://docs.aws.amazon.com/cli/latest/reference/acm/request-certificate.html and https://docs.aws.amazon.com/acm/latest/APIReference/API_DomainValidationOption.html

I have no control over the DNS for the domains, therefore I cannot use DNS validation or make whois entries.
I need to request these certificates and notify the domain owner so he can do the validations.

### PR DESCRIPTION
**Pull request by jw-maynard**
Fixes #3851 

Changes proposed in this pull request:

* Added Optional Arg email_validation_domain
* Updated creation to populate ValidationDomain with email_validation_domain arg

The code currently uses the same domain for the base domain name and all SANs on the certificate. This is probably the most common use case and avoids having to muck around in the existing domain_validation_options. I realize this breaks with the structure of the AWS API but I don't have an immediate need for the added complexity.

Output from acceptance testing:

```

make testacc TEST=./aws TESTARGS='-run=TestAccAWSAcmCertificate_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -run=TestAccAWSAcmCertificate_ -timeout 120m
=== RUN   TestAccAWSAcmCertificate_emailValidation
--- PASS: TestAccAWSAcmCertificate_emailValidation (23.89s)
=== RUN   TestAccAWSAcmCertificate_dnsValidation
--- PASS: TestAccAWSAcmCertificate_dnsValidation (21.02s)
=== RUN   TestAccAWSAcmCertificate_root
--- PASS: TestAccAWSAcmCertificate_root (23.17s)
=== RUN   TestAccAWSAcmCertificate_rootAndWildcardSan
--- PASS: TestAccAWSAcmCertificate_rootAndWildcardSan (25.57s)
=== RUN   TestAccAWSAcmCertificate_san_single
--- PASS: TestAccAWSAcmCertificate_san_single (24.77s)
=== RUN   TestAccAWSAcmCertificate_san_multiple
--- PASS: TestAccAWSAcmCertificate_san_multiple (24.98s)
=== RUN   TestAccAWSAcmCertificate_wildcard
--- PASS: TestAccAWSAcmCertificate_wildcard (23.04s)
=== RUN   TestAccAWSAcmCertificate_wildcardAndRootSan
--- PASS: TestAccAWSAcmCertificate_wildcardAndRootSan (20.47s)
=== RUN   TestAccAWSAcmCertificate_tags
--- PASS: TestAccAWSAcmCertificate_tags (73.17s)
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws       260.110s

...
```

### CODE REVIEW

**Comment by jw-maynard** [comment]
@bflad Wondering when/if this will be merged anytime soon. Just curious if there are any changes that need to be made that are preventing you guys from wanting to merge this or if you've just been too busy else where. Nice work on getting EKS out on day 0 BTW.

**Comment by bflad** [comment]
Sorry I have not personally had time to give a code review here. At quick glance it seems like we should handle this within the domain validation options so it can handle customizing it for each domain rather than introduce a singular argument which would most likely need to be deprecated in the future.

Turns out there's a previous pull request in this regard: #3853 -- I had some initial PR feedback there since it broke backwards compatibility, but maybe its worth working the original author there, providing feedback, or providing fixes on top of their commits? I'm not sure when I'll personally be able to circle back around to this topic though.

**Comment by bflad** [comment]
Hi @jw-maynard 👋 Thank you again for submitting this. Circling back, we are preferring to focus our efforts on the previous #3853 as part of our spiked effort against the `aws_acm_certificate` resource in #13053. We are hoping that by the release of version 3.0.0 of the Terraform AWS Provider, we will support this functionality in some form.

**Comment by jw-maynard** [comment]
@bflad No problem. We very quickly switched to domain validation after this PR and so I never got around to trying to fix it up. Good luck on version 3.0!

**Pull request closed without merging**
