### PR TITLE
resource/aws_storagegateway_smb_file_share: Add support for admin_user_list

### LINKED ISSUE #12255: Support AWS Storage GW SMB File Share Admin User List
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

> Storage Gateway SMB File Share adds support for specifying admin user list.

### New or Affected Resource(s)

* aws_storagegateway_smb_file_share

### Potential Terraform Configuration

```hcl
resource "aws_storagegateway_smb_file_share" "example" {
  #...
  admin_user_list = ["@smb_admins"]
}
```

### Attempted Solutions
*  #12196
    * This Pull Request implements this feature. Honestly, its my first PR here so maybe I'm missing a step in the PR process. Still, I noticed Hashibot never labeled it for `needs-triage` or anything for that matter.

### References

* [User Guide](https://docs.aws.amazon.com/storagegateway/latest/userguide/smb-acl.html)
* [Storage Gateway](https://docs.aws.amazon.com/sdk-for-go/api/service/storagegateway/)

### PR DESCRIPTION
**Pull request by Andrew-Kulpa**
This adds support for specifying a Storage Gateway SMB File Share admin user list. There was already support for invalid and valid user lists, but not an admin user list.

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #12255

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
resource/aws_storagegateway_smb_file_share: Add support for `admin_user_list` parameter
```

Output from acceptance testing:

```
$ make testacc TEST=./aws TESTARGS='-run=TestAccAWSStorageGatewaySmbFileShare_AdminUserList'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSStorageGatewaySmbFileShare_AdminUserList -timeout 120m
=== RUN   TestAccAWSStorageGatewaySmbFileShare_AdminUserList
=== PAUSE TestAccAWSStorageGatewaySmbFileShare_AdminUserList
=== CONT  TestAccAWSStorageGatewaySmbFileShare_AdminUserList
--- PASS: TestAccAWSStorageGatewaySmbFileShare_AdminUserList (841.71s)
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws       843.095s
```

### CODE REVIEW

**Comment by Andrew-Kulpa** [comment]
Why did Hashibot not look at this?

**Comment by bflad** [comment]
Hi @Andrew-Kulpa 👋  Thank you for submitting this. Please see the repository [FAQ](https://github.com/terraform-providers/terraform-provider-aws/blob/master/docs/FAQ.md#why-isnt-my-pr-merged-yet) for additional information about the review process. Overall this contribution looks to be on the right track, it just needs the merge conflicts handled then we can double check the testing and get this merged. 👍

**Review by bflad — APPROVED** [review]
Hi @Andrew-Kulpa 👋  Since we didn't hear back from you we went ahead and fixed the merge conflicts so this can be pulled in. Thank you 🚀 

Output from acceptance testing:

```
--- PASS: TestAccAWSStorageGatewaySmbFileShare_AdminUserList (905.74s)
--- PASS: TestAccAWSStorageGatewaySmbFileShare_audit (352.38s)
--- PASS: TestAccAWSStorageGatewaySmbFileShare_Authentication_ActiveDirectory (805.96s)
--- PASS: TestAccAWSStorageGatewaySmbFileShare_Authentication_GuestAccess (233.19s)
--- PASS: TestAccAWSStorageGatewaySmbFileShare_cacheAttributes (452.08s)
--- PASS: TestAccAWSStorageGatewaySmbFileShare_caseSensitivity (377.34s)
--- PASS: TestAccAWSStorageGatewaySmbFileShare_DefaultStorageClass (318.63s)
--- PASS: TestAccAWSStorageGatewaySmbFileShare_disappears (244.85s)
--- PASS: TestAccAWSStorageGatewaySmbFileShare_GuessMIMETypeEnabled (315.80s)
--- PASS: TestAccAWSStorageGatewaySmbFileShare_InvalidUserList (916.69s)
--- PASS: TestAccAWSStorageGatewaySmbFileShare_KMSEncrypted (241.10s)
--- PASS: TestAccAWSStorageGatewaySmbFileShare_KMSKeyArn (418.40s)
--- PASS: TestAccAWSStorageGatewaySmbFileShare_ObjectACL (302.70s)
--- PASS: TestAccAWSStorageGatewaySmbFileShare_ReadOnly (302.46s)
--- PASS: TestAccAWSStorageGatewaySmbFileShare_RequesterPays (293.18s)
--- PASS: TestAccAWSStorageGatewaySmbFileShare_smb_acl (959.71s)
--- PASS: TestAccAWSStorageGatewaySmbFileShare_Tags (300.74s)
--- PASS: TestAccAWSStorageGatewaySmbFileShare_ValidUserList (931.02s)
```

**Comment by Andrew-Kulpa** [comment]
Sorry, I must've missed that notification. Thanks a bunch! 😅

**Pull request merged**
