### PR TITLE
New Resource: aws_dynamodb_table_item

### PR DESCRIPTION
**Pull request by galadriel2143**
#517

### CODE REVIEW

**Comment by jniesen** [comment]
Is there any timeframe for when this might get reviewed? My team would love to use this feature.

**Comment by lorengordon** [comment]
Very interested in this feature also!

**Comment by adamdiy** [comment]
Would be useful here as well...

**Comment by joeharrison714** [comment]
This would be helpful for me

**Comment by OliverCole** [comment]
I don't know what the rules are, but I suspect Hashicorp won't want to merge this without docs. I had a go at doing it myself, but actually I don't fully understand it, or have a golang development environment.

https://github.com/terraform-providers/terraform-provider-aws/blob/master/website/docs/r/dynamodb_table.html.markdown would be a good starting point.

**Comment by radeksimko** [comment]
Hi @galadriel2143

firstly sorry for the long delay in reviewing your PR.

I took some time to think about this resource and also discuss internally
the challenges and benefits which may arise from supporting it.

I think it's :ok_hand: to support the use case of storing
some simple configuration data as we already allow folks to do via
[`aws_s3_bucket_object`](https://www.terraform.io/docs/providers/aws/r/s3_bucket_object.html)

However there are much better ways to **manage application configuration** (e.g. feature flags, connection strings etc.).
Tools like Consul, etcd, Vault, Chef/Puppet/Ansible/Salt or service like [AWS SSM](https://www.terraform.io/docs/providers/aws/r/ssm_parameter.html)
are all _designed_ to handle this problem.

I'm fine with enabling people who know the limitations, risks, trade-offs,
and reasons for using DynamoDB in this context. I also feel
the responsibility to prompt others to question the suitability though.
For that reason we should have a clear explanation of the intended
use case in the docs.

I'd also discourage people from using this resource for regular data
**backup**, basically for managing anything beyond 1-5 items, because
(again) there are much better ways to do this. e.g. scheduling
regular backups via CloudWatch Events & Lambda & [DynamoDB API](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_CreateBackup.html).

**Restoration** is something Terraform could theoretically support
in a similar way [we support restoration in RDS](https://www.terraform.io/docs/providers/aws/r/db_instance.html#snapshot_identifier). i.e. restoring
from a given backup at the time of creating `aws_dynamodb_table`.

I hope I didn't miss any valid or invalid use case here.
Do let me know if I did.

----

So I'm happy to pull this resource in, but the PR will require some significant changes.
It's been sitting here for some time and my reservations are related mostly to code
which was inspired by the existing `aws_dynamodb_table` resource
which I refactored recently in https://github.com/terraform-providers/terraform-provider-aws/pull/3136.

For that reason I will breach the etiquette a bit (usually I'd review & let you fix)
and make those changes for you and push back to your branch.

I hope it's understandable and you don't mind me making those changes.

Thanks.

**Comment by radeksimko** [comment]
@galadriel2143 I tried pushing back to your branch, but somehow ended up closing the PR. I assume it has something to do with the fact that the PR was opened from `master`. It's generally advisable to always open PRs from feature branches for the future. 😉

It not only makes it easier for reviewers, but also the author as they can keep rebasing the branch and work keep multiple PRs opened without having to force-push into `master`.

However #3238 was opened with your original commit and my changes.

**Comment by bflad** [comment]
This has been released in [terraform-provider-aws version 1.9.0](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#190-february-09-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.

**Pull request closed without merging**
