### PR TITLE
add documentation for glue default_arguments

### LINKED ISSUE #8031: Request to update aws_glue_job documentation
_This issue was originally opened by @jkhalid as hashicorp/terraform#20771. It was migrated here as a result of the [provider split](https://www.hashicorp.com/blog/upcoming-provider-changes-in-terraform-0-10/). The original body of the issue is below._

<hr>

Hi ,

Requesting you to update the documentation on 
https://www.terraform.io/docs/providers/aws/r/glue_job.html

Below is code that works 
resource "aws_glue_job" "x-feed-terraform" {
name = "x-feed"
role_arn = "${var.IAM_ROLE}"
allocated_capacity = "${var.DPU}"
max_retries = 3
timeout = 1000
command {
script_location = "s3://${var.S3_BUCKET}${var.FEED_SCRIPT}"
}
default_arguments {
"--extra-py-files" = "s3://${var.S3_BUCKET}/abcd/libs.zip"
}
}

Please update the documentation on the website based on the params provided by
https://docs.aws.amazon.com/glue/latest/dg/aws-glue-programming-etl-glue-arguments.html

### PR DESCRIPTION
**Pull request by jhole89**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #8031

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
None
```

Output from acceptance testing:

```
None - docs only
```

### CODE REVIEW

**Comment by DrFaust92** [comment]
Hey @jhole89, we should probably leave the links to the extended docs as they are (or provide some more link). playing catch with the aws docs may lead a lot of overhead. giving you some time to comment before i close this.

**Comment by jhole89** [comment]
@DrFaust92 huh? Sorry but I'm confused by the comment. The links to the extended docs are still present in the extended docs section I added.

**Comment by DrFaust92** [comment]
Hey @jhole89, what I meant was we can do without the full explanation for for the argument inline and keep just the link to AWS docs. we don't want to keep updating this for every change to the AWS docs and keep this in sync.

**Comment by jhole89** [comment]
@DrFaust92 Then why was, and still is, the issue open if you don't think anything should change? I'm fine to close this PR if you think this provides no benefit, but please triage the issue this PR addresses.

**Comment by DrFaust92** [comment]
Hey @jhole89, Thanks for working on this but as this is would make docs more verbose and a reference to the official docs is enough at this time I'm going to close this. see https://github.com/terraform-providers/terraform-provider-aws/issues/8031#issuecomment-714777306 for more details. Thanks Again for working on this!

**Pull request closed without merging**
