### PR TITLE
Data source eip filters

### LINKED ISSUE #4551: aws_eip_association data source
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently there's no way to find information about an existing EIP association. Whether these be ones created manually outside of terraform, or ones created implicitly during provisioning of other resources.

The use case I have specifically for this is to get the private IP addresses of an NLB created using subnet mappings. It is very useful to be able to find out the private IP addresses used by the load balancing nodes as these need to be whitelisted for health checking purposes. Looking up the known EIPs association would be one way to determine an NLB's private IP addresses.

### New or Affected Resource(s)

* aws_eip_association (data source)

### Potential Terraform Configuration

```hcl
resource "aws_lb" "example" {
  name               = "example-lb-tf"
  load_balancer_type = "network"

  subnet_mapping {
    subnet_id     = "${aws_subnet.example2.id}"
    allocation_id = "${aws_eip.example1.id}"
  }
  subnet_mapping {
    subnet_id     = "${aws_subnet.example2.id}"
    allocation_id = "${aws_eip.example2.id}"
  }
  subnet_mapping {
    subnet_id     = "${aws_subnet.example2.id}"
    allocation_id = "${aws_eip.example3.id}"
  }
}

data "aws_eip_association" "nlb_ip1" {
  allocation_id = "${aws_eip.example1.id}"
  depends_on    = ["aws_lb.example"]
}
data "aws_eip_association" "nlb_ip2" {
  allocation_id = "${aws_eip.example2.id}"
  depends_on    = ["aws_lb.example"]
}
data "aws_eip_association" "nlb_ip3" {
  allocation_id = "${aws_eip.example3.id}"
  depends_on    = ["aws_lb.example"]
}

resource "aws_security_group_rule" "allow_nlb_healthcheck" {
  type        = "ingress"
  from_port   = 8080
  to_port     = 8080
  protocol    = "tcp"
  cidr_blocks = [
    "${data.aws_eip_association.nlb_ip1.private_ip}"
    "${data.aws_eip_association.nlb_ip2.private_ip}"
    "${data.aws_eip_association.nlb_ip3.private_ip}"
  ]
  
  security_group_id = "sg-123456"
}
```

### PR DESCRIPTION
**Pull request by kl4w**
Fixes #4551

Changes proposed in this pull request:

* add `filter` attribute
* add `association_id` attribute
* add `private_ip` attribute

Output from acceptance testing:

```
make testacc TEST=./aws TESTARGS='-run=TestAccDataSourceAwsEip'
gofmt -w $(find . -name '*.go' |grep -v vendor)
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -run=TestAccDataSourceAwsEip -timeout 120m
=== RUN   TestAccDataSourceAwsEip_basic
--- PASS: TestAccDataSourceAwsEip_basic (14.31s)
=== RUN   TestAccDataSourceAwsEip_filter
--- PASS: TestAccDataSourceAwsEip_filter (72.64s)
=== RUN   TestAccDataSourceAwsEip_association
--- PASS: TestAccDataSourceAwsEip_association (84.53s)
=== RUN   TestAccDataSourceAwsEip_private
--- PASS: TestAccDataSourceAwsEip_private (73.64s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	245.162s
```

### CODE REVIEW

**Comment by AlexRudd** [comment]
Hey, I think this would solve my use case in #4551 

Thanks @kl4w :)

**Comment by saravanan30erd** [comment]
#3525

**Comment by kl4w** [comment]
@saravanan30erd @bflad I'm happy to close this in favor of the others. Just let me know. Cheers.

**Comment by bflad** [comment]
Hi @kl4w 👋 Sorry for the very delayed response. I spent some time merging together #3505, #3522, and #3525 for the `aws_eip` data source, which required some refactoring to get everything working together and testing correctly on master. Would you be able to rebase this PR or submit a new one? Apologies for the hassle. 😅

**Comment by kl4w** [comment]
@bflad i'm going to close this PR and submit a new one for setting some extra attributes

**Comment by kl4w** [comment]
@bflad created a new PR: #6463

**Pull request closed without merging**
