### PR TITLE
Skip ebs encryption flag for snapshots on launch template.

### LINKED ISSUE #4553: Encrypted flag cannot be specified since device /dev/sda1 has a snapshot specified
_This issue was originally opened by @jayudhandha as hashicorp/terraform#18059. It was migrated here as a result of the [provider split](https://www.hashicorp.com/blog/upcoming-provider-changes-in-terraform-0-10/). The original body of the issue is below._

<hr>

Hi,

I am migrating my **Autoscaling groups** to use **launch_template** instead of **launch_configuration**. (_To support T2 Unlimited_)

Below is my code snippet.

```
resource "aws_launch_template" "test_launch_template" {
  image_id = "ami_id"
  name_prefix     = "test-pref"
  instance_type   = "t2.small"
  key_name        = "jayesh"
  vpc_security_group_ids = ["sg-23423432","sg-23452115"]
  user_data       = "${base64encode(data.template_file.user_data.rendered)}"
  
  iam_instance_profile {
	name = "test"
  } 
  disable_api_termination = true
  instance_initiated_shutdown_behavior = "terminate"

  block_device_mappings {
	device_name = "/dev/sda1"
	ebs {
      delete_on_termination = true
      volume_size           = "${var.volume_size}"
    }
  }
    
  credit_specification {
    cpu_credits = "unlimited"
  }
  lifecycle {
    create_before_destroy = "true"
  }  
}
```
While running `terraform apply` I am getting below error.

> 1 error(s) occurred:
> 
> * aws_autoscaling_group.test_asg: 1 error(s) occurred:
> * aws_autoscaling_group.test_asg: Error creating AutoScaling Group: ValidationError: You must use a valid fully-formed launch template. the encrypted flag cannot be specified since device /dev/sda1 has a snapshot specified.
>         status code: 400, request id: 7902a390-58de-11e8-af77-87d327f8b121
> 

May be any parameter is missing but i am not sure which one.

As per error, It looks that encrypted parameter is specified. But i haven't passed that. Then why this error is coming?

Thanks in advance!

### PR DESCRIPTION
**Pull request by jmcarp**
AWS does not allow setting encryption values on ebs block devices
created from a snapshot. This patch lists block devices created from
snapshots from the image and skips the encryption flag on those devices.

[Fixes #4553]

Note: at the moment, this patch silently ignores encryption values for ebs block devices created from a snapshot. We should probably throw an error or warning if the user sets an encryption value. The only problem is that we can't disambiguate between an encryption flag set to false and an empty value with the provider as written. WDYT @bflad ?

### CODE REVIEW

**Comment by ColinHebert** [comment]
What's the status of this one? Can we merge it? @bflad

**Comment by shuqichen** [comment]
When will this change will be released? I also encountered same issue, and need use this urgent!

**Comment by rbreslow** [comment]
We encountered this, and it is now blocking some of our issues:

https://github.com/azavea/terraform-aws-ecs-cluster/pull/34

As it stands, `aws_launch_template` is broken.

**Comment by rbreslow** [comment]
@bflad?

**Comment by shuqichen** [comment]
@bflad ?

**Comment by schammah** [comment]
any plans to merge this?
unable to use `aws_launch_template` until then

**Comment by bflad** [comment]
Hi folks 👋  Sorry for the delayed response here.

The implementation in this pull request was an EC2 API lookup, which was a quite complicated workaround for the real issue of the resource schema not appropriately handling an "unspecified" value. An alternate implementation that skips the lookup has been made including the previously failing and now passing acceptance test at: #5632.

**Comment by bflad** [comment]
#5632 has been merged into master with the fix and will release with version 1.34.0 of the AWS provider, likely later today.

**Pull request closed without merging**
