### PR TITLE
remove maximum=1 for cloudwatch destination

### LINKED ISSUE #5620: aws_ses_event_destination: Multiple dimensions per CloudWatch destination
The `aws_ses_event_destination` does not appear to support multiple dimensions per CloudWatch Destination.

I am able to add multiple dimensions via the AWS console and it also appears that CloudFormation supports this as well: [AWS::SES::ConfigurationSetEventDestination](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ses-configurationseteventdestination.html)

I have tried various methods for adding additional dimensions, but keep getting the following error message (Examples 1 & 2): 
`Error: aws_ses_event_destination.cloudwatch-aw: cloudwatch_destination: attribute supports 1 item maximum, config has 2 declared`.

Other methods just try and apply 1 dimension to the CloudWatch Destination (Example 3)

Any help/suggestions welcome

### Resource Config

*Example 1*
```
resource "aws_ses_event_destination" "cloudwatch-aw" {
  name                   = "ics-aw-delivery"
  configuration_set_name = "${aws_ses_configuration_set.ics-aw-stats.name}"
  enabled                = true
  matching_types         = ["bounce", "delivery", "reject", "send"]

  cloudwatch_destination = [
    {
      default_value  = "aw-1"
      dimension_name = "ses:configuration-set"
      value_source   = "messageTag"
    },
    {
      default_value  = "aw-2"
      dimension_name = "ses:source-ip"
      value_source   = "messageTag"
    }
  ]
}
```

*Example 2*
```
resource "aws_ses_event_destination" "cloudwatch-aw" {
  name                   = "ics-aw-delivery"
  configuration_set_name = "${aws_ses_configuration_set.ics-aw-stats.name}"
  enabled                = true
  matching_types         = ["bounce", "delivery", "reject", "send"]

  cloudwatch_destination = {
    default_value  = "aw-1"
    dimension_name = "ses:configuration-set"
    value_source   = "messageTag"
  }

  cloudwatch_destination = {
    default_value  = "aw-2"
    dimension_name = "ses:source-ip"
    value_source   = "messageTag"
  }
}
```

*Example 3*
```
resource "aws_ses_event_destination" "cloudwatch-aw" {
  name                   = "ics-aw-delivery"
  configuration_set_name = "${aws_ses_configuration_set.ics-aw-stats.name}"
  enabled                = true
  matching_types         = ["bounce", "delivery", "reject", "send"]

  cloudwatch_destination = {
    default_value  = "aw-1"
    dimension_name = "ses:configuration-set"
    value_source   = "messageTag"

    default_value  = "aw-2"
    dimension_name = "ses:source-ip"
    value_source   = "messageTag"
  }
}
```

### Terraform Version

Terraform v0.11.7

### LINKED ISSUE #6689: Incorrect maximum for ses_event_destination
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.11.10

### Affected Resource(s)

* resource_aws_ses_event_destination

### Terraform Configuration Files

```hcl
resource "aws_ses_configuration_set" "dev" {
  name = "hcom"

  lifecycle {
    create_before_destroy = "true"
  }
}

resource "aws_ses_event_destination" "cloudwatch-all" {
  name                   = "dev-all"
  configuration_set_name = "${aws_ses_configuration_set.dev.name}"
  enabled                = true
  matching_types         = ["bounce", "complaint", "reject", "send", "delivery"]

  cloudwatch_destination = {
    default_value  = "${aws_ses_configuration_set.dev.name}"
    dimension_name = "ses:configuration-set"
    value_source   = "messageTag"
  }

  cloudwatch_destination = {
    default_value  = "default"
    dimension_name = "ses:caller-identity"
    value_source   = "messageTag"
  }

  cloudwatch_destination = {
    default_value  = "default"
    dimension_name = "ses:from-domain"
    value_source   = "messageTag"
  }

  cloudwatch_destination = {
    default_value  = "default"
    dimension_name = "ses:source-ip"
    value_source   = "messageTag"
  }

  cloudwatch_destination = {
    default_value  = "default"
    dimension_name = "ses:outgoing-ip"
    value_source   = "messageTag"
  }

  cloudwatch_destination = {
    default_value  = "default"
    dimension_name = "to"
    value_source   = "emailHeader"
  }
}
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

### PR DESCRIPTION
**Pull request by david-wells-1**
Fixes #6689 
Fixes #5620

Changes proposed in this pull request:

* Change 1
* Change 2

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccAWSAvailabilityZones'

...
```

### CODE REVIEW

**Comment by david-wells-1** [comment]
@bflad - can you confirm? are you requesting the removal of the default value? resource should allow for the creation of 1x ses_event_destination or multiple destinations

**Comment by david-wells-1** [comment]
@bflad - additional test added as requested for the ses_destination_event

**Comment by david-wells-1** [comment]
Thanks @bflad

**Comment by bflad** [comment]
This has been released in [version 1.51.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1510-december-05-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.

**Pull request merged**
