### PR TITLE
Removes non-existent fields from RDS cluster documentation

### LINKED ISSUE #4797: aws_rds_cluster docs claim "status" attribute exists but causes Error when used
_This issue was originally opened by @pll as hashicorp/terraform#18222. It was migrated here as a result of the [provider split](https://www.hashicorp.com/blog/upcoming-provider-changes-in-terraform-0-10/). The original body of the issue is below._

<hr>

### Terraform Version
```
$ terraform -v
Terraform v0.11.7
+ provider.aws v1.22.0
+ provider.null v1.0.0
+ provider.template v1.0.0
```

### Terraform Configuration Files

```hcl
output "rds-cluster-status" {
  value = "${aws_rds_cluster.rds.status}"
}
```

### Expected Behavior

Expected output var indicating RDS cluster status per docs:

https://www.terraform.io/docs/providers/aws/r/rds_cluster.html
```
status - The RDS instance status
```

### Actual Behavior
```
$ terraform apply
Error: Error running plan: 1 error(s) occurred:

* module.rds.output.rds-cluster-status: Resource 'aws_rds_cluster.rds' does not have attribute 'status' for variable 'aws_rds_cluster.rds.status'
```

### Steps to Reproduce
1. Create a .tf file to build an RDS cluster
2. Create an `output` variable which attempts to output the cluster status using the documented attribute
3. Run `terraform init`, then `terraform apply`
4. Get this error:
```
Error: Error running plan: 1 error(s) occurred:

* module.rds.output.rds-cluster-status: Resource 'aws_rds_cluster.rds' does not have attribute 'status' for variable 'aws_rds_cluster.rds.status'
```

### LINKED ISSUE #13594: aws_rds_cluster docs claim "status" attribute exists but causes Error when used
Re-opening/Related to: #4797 

# Original Bug Report:

Terraform Version

```
$ terraform -v
Terraform v0.11.7
+ provider.aws v1.22.0
+ provider.null v1.0.0
+ provider.template v1.0.0
```

Terraform Configuration Files

```
output "rds-cluster-status" {
  value = "${aws_rds_cluster.rds.status}"
}
```

Expected Behavior: 

Expected output var indicating RDS cluster status per docs:

https://www.terraform.io/docs/providers/aws/r/rds_cluster.html

```status - The RDS instance status```

Actual Behavior

```
$ terraform apply
Error: Error running plan: 1 error(s) occurred:

* module.rds.output.rds-cluster-status: Resource 'aws_rds_cluster.rds' does not have attribute 'status' for variable 'aws_rds_cluster.rds.status'
```

Steps to Reproduce

1. Create a .tf file to build an RDS cluster
2. Create an output variable which attempts to output the cluster status using the documented attribute
3. Run terraform init, then terraform apply

Get this error:
```
Error: Error running plan: 1 error(s) occurred:

* module.rds.output.rds-cluster-status: Resource 'aws_rds_cluster.rds' does not have attribute 'status' for variable 'aws_rds_cluster.rds.status'
```

# Latest Update:

Most recent version of Terraform continues to display the same behavior, and completely contradicts the documentation:

Terraform Version:
```
$ terraform -v
Terraform v0.12.26
+ provider.aws v2.64.0
+ provider.null v2.1.2
```

Terraform Configuration:
```
resource "aws_rds_cluster" "rds" {
  engine                  = var.rds_map["db_type"]
  cluster_identifier      = "${var.tags["system_type"]}-${var.tags["owner"]}-${var.env_name}"
  availability_zones      = slice( var.availability_zones, 0, 2)
  database_name           = var.rds_map["db_name"]
  master_username         = var.rds_map["db_user"]
  master_password         = var.rds_map["db_password"]
  vpc_security_group_ids  = split(",", var.sg_ids)
  db_subnet_group_name    = aws_db_subnet_group.rds.id
  skip_final_snapshot     = true
  final_snapshot_identifier = "${var.tags["Name"]}-snapshot"
}

output "rds-cluster-status" {
  value = aws_rds_cluster.rds.status
}
```
Error:
```
Error: Unsupported attribute

  on rds/rds_cluster.tf line 25, in output "rds-cluster-status":
  25:   value = aws_rds_cluster.rds.status

This object has no argument, nested block, or exported attribute named
"status".
```

### LINKED ISSUE #14985: aws_rds_cluster attributes do not exist/work as documented.
_This issue was originally opened by @pll as hashicorp/terraform#26103. It was migrated here as a result of the [provider split](https://www.hashicorp.com/blog/upcoming-provider-changes-in-terraform-0-10/). The original body of the issue is below._
    
<hr>
    
### Terraform Version
```
$ terraform --version
Terraform v0.12.26

Your version of Terraform is out of date! The latest version
```

### Terraform Configuration Files
```terraform

output "allocated_storage" {
  value = aws_rds_cluster.rds.allocated_storage
}

output "maintenance_window" {
  value = aws_rds_cluster.rds.maintenance_window
}

output "status" {
  value = aws_rds_cluster.rds.status
}
```

### Debug Output
```
Error: Unsupported attribute

  on aurora_rds/aurora_rds_cluster.tf line 21, in output "allocated_storage":
  21:   value = aws_rds_cluster.rds.allocated_storage

This object has no argument, nested block, or exported attribute named
"allocated_storage".


Error: Unsupported attribute

  on aurora_rds/aurora_rds_cluster.tf line 57, in output "maintenance_window":
  57:   value = aws_rds_cluster.rds.maintenance_window

This object has no argument, nested block, or exported attribute named
"maintenance_window".


Error: Unsupported attribute

  on aurora_rds/aurora_rds_cluster.tf line 78, in output "status":
  78:   value = aws_rds_cluster.rds.status
```

### Expected Behavior
According to the documentation the above mentioned attributes *should* be available. However, the Terraform documentation seems out of sync with reality according to AWS.

### Additional Context
Create an Aurora/RDS cluster in AWS with terraform, and then attempt to use the above mentioned attributes as output variables.

### References

https://github.com/terraform-providers/terraform-provider-aws/issues/4797

#18222

### PR DESCRIPTION
**Pull request by gdavison**
Removes a number of non-existent fields from `aws_rds_cluster` and `aws_rds_cluster_instance` documentation

Closes #14985
Closes #13594
Closes #4797

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
NONE
```

Output from acceptance testing:

N/A

### CODE REVIEW

**Review by pll — COMMENTED** [review]
Hey, Thanks for jumping on this. However, I'm not sure if simply removing these is the right answer.  Per the AWS documentation here: https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_DBCluster.html

- AllocatedStorage is actually a returned attribute for all DB types *except* Aurora. 
- database_name is returned if there was a database name passed into the create API
- status should is an optionally returnable attribute as well.

So, either the AWS API docs are incorrect, or, there's something inconsistent between when/how AWS expects them exist and how/when Terraform expects them to exist.

I think before simply removing the documentation, better understanding of these returned attributes is necessary, and perhaps merely updating the Terraform docs with a better indicator of how/when to expect these attributes to be set might be the better course.

**Comment by gdavison** [comment]
Hi, @pll . This PR brings the documentation in line with what the current Terraform resources implement.

`database_name` is already defined in the Arguments section, so doesn't need to be repeated as an output.

`allocated_storage` does not apply to Aurora clusters, which is what the `aws_rds_cluster` and `aws_rds_cluster_instance` create.

`status` is a run-time state, so doesn't fit with the Terraform model. The creation and update code always wait for the state `available`, any other state will return either an error or timeout.

**Comment by pll** [comment]
Hi @gdavison,

That makes sense.  Thanks for the clarification!

**Review by bflad — APPROVED** [review]
Looks good after checking the schemas for each. 🚀

**Pull request merged**
