### PR TITLE
provider: Add Macie2 service client (#13432)

### PR DESCRIPTION
**Pull request by mattburgess**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates #13432

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
NONE
```

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccXXX'

...
```

### CODE REVIEW

**Review by anGie44 — CHANGES_REQUESTED** [review]
Hi @mattburgess, thank you for this PR! One last addition and we should be set to go. In `.hashibot.hcl`, let's also add the new service to `behavior "pull_request_path_labeler" "service_labels" {` . for reference, the last bullet point in the `New Service -> Service Client` section shows an example: https://github.com/terraform-providers/terraform-provider-aws/blob/master/docs/contributing/contribution-checklists.md#new-service

**Comment by mattburgess** [comment]
Thanks for the review @anGie44! Can't believe I missed that. Fix pushed.

**Comment by anGie44** [comment]
hi @mattburgess, thank you for pushing up the additional change to `.hashibot.hcl`! apologies that there is a conflict now in this PR -- we've since removed vendoring from this project and moved to utilizing go modules. do you mind rebasing? let me know if you have any followup questions 👍

**Comment by mattburgess** [comment]
Hi @anGie44 - I *think* I've rebased this correctly! I also looked at https://github.com/terraform-providers/terraform-provider-aws/blob/master/docs/contributing/contribution-checklists.md#new-service again to make sure that there's nothing else I need to do with regard to the move away from vendoring and couldn't see anything. Let me know if I've missed anything though.

**Review by anGie44 — APPROVED** [review]
You're all set @mattburgess, thanks again! - CI checks all passing w/the rebase 👍

**Pull request merged**
