### PR TITLE
Respect lambda function qualifier on data source.

### PR DESCRIPTION
**Pull request by jmcarp**
As written, the lambda function data source always returns the most
recent version and qualified arn, even if a different qualifier is set.
This patch respects the qualifier if provided.

### CODE REVIEW

**Comment by jen20** [comment]
Hi @jmcarp! Thanks for submitting a pull request. This _does_ look like a correct change to me, however it doesn't match the pull request description, which describes the _data source_, whereas the change is to the _resource_ variant of the Lambda function. Is this a change which needs propagating across to the data source also?

**Comment by jmcarp** [comment]
@jen20: this does affect the data source, since the resource and data source share the same read function. It might make sense to refactor to two separate functions for clarity, but I figured I'd try to keep the patch simple to start with.

**Comment by jen20** [comment]
Ah yes, I see now. I'm not particularly sure I like the pattern of multiple resources sharing read functions, but this does fix the issue and that refactor can be made another time. Thanks for contributing!

**Comment by bflad** [comment]
This has been released in [version 1.21.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1210-may-31-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.

**Pull request merged**
