### PR TITLE
r/elastic_transcoder_pipeline - remove `getStringPtr` calls + refactor tests

### PR DESCRIPTION
**Pull request by DrFaust92**
refactor tests
add disappearing test case

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates #5983

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
NONE
```

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccAWSElasticTranscoderPipeline_'
--- PASS: TestAccAWSElasticTranscoderPipeline_kmsKey (110.34s)
--- PASS: TestAccAWSElasticTranscoderPipeline_notifications (134.81s)
--- PASS: TestAccAWSElasticTranscoderPipeline_withContentConfig (136.03s)
--- PASS: TestAccAWSElasticTranscoderPipeline_withPermissions (105.47s)
--- PASS: TestAccAWSElasticTranscoderPipeline_basic (84.11s)
--- PASS: TestAccAWSElasticTranscoderPipeline_disappears (77.33s)
```

### CODE REVIEW

**Comment by ewbankkit** [comment]
Verified acceptance tests:

```console
$ make testacc TEST=./aws TESTARGS='-run=TestAccAWSElasticTranscoderPipeline_' 
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSElasticTranscoderPipeline_ -timeout 120m
=== RUN   TestAccAWSElasticTranscoderPipeline_basic
=== PAUSE TestAccAWSElasticTranscoderPipeline_basic
=== RUN   TestAccAWSElasticTranscoderPipeline_kmsKey
=== PAUSE TestAccAWSElasticTranscoderPipeline_kmsKey
=== RUN   TestAccAWSElasticTranscoderPipeline_notifications
=== PAUSE TestAccAWSElasticTranscoderPipeline_notifications
=== RUN   TestAccAWSElasticTranscoderPipeline_withContentConfig
=== PAUSE TestAccAWSElasticTranscoderPipeline_withContentConfig
=== RUN   TestAccAWSElasticTranscoderPipeline_withPermissions
=== PAUSE TestAccAWSElasticTranscoderPipeline_withPermissions
=== RUN   TestAccAWSElasticTranscoderPipeline_disappears
=== PAUSE TestAccAWSElasticTranscoderPipeline_disappears
=== CONT  TestAccAWSElasticTranscoderPipeline_basic
=== CONT  TestAccAWSElasticTranscoderPipeline_withPermissions
=== CONT  TestAccAWSElasticTranscoderPipeline_disappears
=== CONT  TestAccAWSElasticTranscoderPipeline_notifications
=== CONT  TestAccAWSElasticTranscoderPipeline_withContentConfig
=== CONT  TestAccAWSElasticTranscoderPipeline_kmsKey
--- PASS: TestAccAWSElasticTranscoderPipeline_disappears (38.15s)
--- PASS: TestAccAWSElasticTranscoderPipeline_withPermissions (47.10s)
--- PASS: TestAccAWSElasticTranscoderPipeline_kmsKey (62.83s)
--- PASS: TestAccAWSElasticTranscoderPipeline_notifications (67.19s)
--- PASS: TestAccAWSElasticTranscoderPipeline_withContentConfig (67.80s)
--- PASS: TestAccAWSElasticTranscoderPipeline_basic (90.51s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	90.599s
```

**Comment by DrFaust92** [comment]
@bflad it looks like you ran the acceptance tests for my other elastic transcoder PR

**Comment by bflad** [comment]
Thanks 😓 I'll make sure this merge and the other are both fine before release.

**Comment by DrFaust92** [comment]
if it helps i rebased the other branch(+ removed the `getStringPtr` function) and it seems fine

**Pull request merged**
