### PR TITLE
provider: Change the order of authentication providers

### PR DESCRIPTION
**Pull request by atsushi-ishibashi**
#1455

### CODE REVIEW

**Comment by mrwacky42** [comment]
In my experience, most software allows environment variables to trump configuration files. If I had a vote, I would vote against this change.

**Comment by apparentlymart** [comment]
Thanks for working on this, @atsushi-ishibashi!

I agree that the current approach is inconsistent because Terraform's usual convention is that the environment variables are consulted only when there's no explicit settings in the configuration file... indeed, we don't consult the environment if `access_key` and `secret_key` are set directly here.

I'm sympathetic to @mrwacky42's concern that some other software inverts this priority. We're not currently achieving _that_ orientation either, since as mentioned above the _other_ config settings already override the environment, with `shared_credentials_file` and `profile` being the notable exception to the rule. Terraform has pretty firmly established the "configuration trumps environment" convention across all of its providers now though, so I think it's better for us to be consistent, especially since this priority is for good reason: it allows for situations where multiple instances of the provider are used, e.g. with the "default" provider using the environment while an alias provider uses an overridden configuration to access a different account or role.

So I think what's proposed here is the right behavior for consistency, but unfortunately this represents a potential breaking change for existing users, so if we change it we must do so carefully, in a major release. I've tagged this as "breaking-change" to remind us to look at it again when we're preparing for the next major release, though at this time we don't have any firm plans for when that might be.

Thanks again for working on this, and sorry we can't merge it immediately.

**Comment by atsushi-ishibashi** [comment]
@mrwacky42 Thank you for reply!
If the software follow what you are saying, is it better to change the order of `StaticProvider` and `EnvProvider`?
I was confused that `StaticProvider` config trumps environment variables but `SharedCredentialsProvider` config doesn't.

**Comment by atsushi-ishibashi** [comment]
@apparentlymart Thanks! I'm looking forward😄

**Comment by mrwacky42** [comment]
@apparentlymart - I promise not to lose sleep over this. Just offering my 2 bits.

**Comment by kbuchsicf** [comment]
I too would vote for a change here. A potential suggestion for phasing in a change with minimal breakage:

1) Immediately change the behavior upon an appropriate statement in the CLI Configuration File (.terraformrc/terraform.rc). Then the people who want this change can get immediate satisfaction. 
2) at the same time, introduce a warning message produced any time the environment variables are overriding explicit configuration file statements. Say this behavior will be changed in a future release (give rough date).
3) wait 6 months and then make the change the default, retain the CLI Config statement in a form to reverse the change (if people like the old behavior)
4) at the same time remove the prior warning and introduce a new one when environment variables are being overridden.

**Comment by bflad** [comment]
Hi folks 👋 There are currently a lot of changes already occurring in the version 2.0.0 upgrade, so the maintainers would prefer to defer this, especially since there are no upvotes on #1455 or #2020.

That said, the implementation of credential ordering has moved to its own library in https://github.com/hashicorp/aws-sdk-go-base, which is shared between the Terraform AWS Provider and the Terraform S3 Backend, so I'm going to close this pull request here now since it is invalid. If there is still interest, please submit a new pull request against the new shared library. 👍

**Pull request closed without merging**
