### PR TITLE
Add Lex bot alias data source and resoruce

### LINKED ISSUE #905: AWS Lex
Hi there,

I couldn't find any issues or code relating to AWS Lex: http://docs.aws.amazon.com/lex/latest/dg/API_Reference.html. It'd be great to be able to define entire bots as code instead of configuration through the AWS console. E.g. https://nicholasjackson.io/2017/04/25/slack-bot-aws-lambda.

More info: http://docs.aws.amazon.com/lex/latest/dg/programming-model.html#programming-model-build-time-api

Cheers!

### PR DESCRIPTION
**Pull request by jzbruno**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" comments, they generate extra noise for pull request followers and do not help prioritize the request

Relates #905 and split from PR #2616

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
FEATURES:
* **New Data Source:** `aws_lex_bot_alias`
* **New Resource:** `aws_lex_bot_alias`
```

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccDataSourceAwsLexBotAlias'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./... -v -parallel 20 -run=TestAccDataSourceAwsLexBotAlias -timeout 120m
?   	github.com/terraform-providers/terraform-provider-aws	[no test files]
=== RUN   TestAccDataSourceAwsLexBotAlias
--- SKIP: TestAccDataSourceAwsLexBotAlias (0.00s)
    data_source_aws_lex_bot_alias_test.go:12: The Lex intent PR and Lex bot PR must be merged for this test to pass. https://github.com/terraform-providers/terraform-provider-aws/pull/8917 https://github.com/terraform-providers/terraform-provider-aws/pull/8918
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	0.042s

$ make testacc TESTARGS='-run=TestAccAwsLexBotAlias'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./... -v -parallel 20 -run=TestAccAwsLexBotAlias -timeout 120m
?   	github.com/terraform-providers/terraform-provider-aws	[no test files]
=== RUN   TestAccAwsLexBotAlias
--- SKIP: TestAccAwsLexBotAlias (0.00s)
    resource_aws_lex_bot_alias_test.go:15: The Lex intent PR and Lex bot PR must be merged for this test to pass. https://github.com/terraform-providers/terraform-provider-aws/pull/8917 https://github.com/terraform-providers/terraform-provider-aws/pull/8918
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	0.040s
```

### CODE REVIEW

**Comment by nywilken** [comment]
@jzbruno, and folks following along, my apologies for the longer than normal delays on pushing forward this feature. I haven't had the chance to devote the needed time get the other pull-requests into a mergable state 😳 I appreciate your patience as we continue to work through this resource. 

While I can't say that it will get into the next upcoming release(s), I can say that the resource is still a priority for us. 

To not give false expectations around the release of this resource I am going to remove the milestone. But let's coordinate on when would be ideal to continue pushing forward. If you find that your availability has also slowed please let me know if we should consider having another community member or the maintainers take over the pull-request(s). 

Cheers

**Comment by jzbruno** [comment]
@nywilken I can continue to work on this. I believe this is ready for further review.

**Comment by jzbruno** [comment]
@gdavison Just FYI, I am updating this PR with the same review comments from the other Lex resource PRs, including adding the new fields.

**Comment by jzbruno** [comment]
@gdavison Ok. When the intent and bot PRs are merged this one is ready for review too.

```
~/src/github/terraform-providers/terraform-provider-aws $ make testacc TESTARGS='-run=TestAcc.*LexBotAlias.*'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAcc.*LexBotAlias.* -timeout 120m
=== RUN   TestAccDataSourceAwsLexBotAlias_basic
=== PAUSE TestAccDataSourceAwsLexBotAlias_basic
=== RUN   TestAccAwsLexBotAlias_basic
=== PAUSE TestAccAwsLexBotAlias_basic
=== RUN   TestAccAwsLexBotAlias_botVersion
=== PAUSE TestAccAwsLexBotAlias_botVersion
=== RUN   TestAccAwsLexBotAlias_conversationLogsText
=== PAUSE TestAccAwsLexBotAlias_conversationLogsText
=== RUN   TestAccAwsLexBotAlias_conversationLogsAudio
=== PAUSE TestAccAwsLexBotAlias_conversationLogsAudio
=== RUN   TestAccAwsLexBotAlias_description
=== PAUSE TestAccAwsLexBotAlias_description
=== RUN   TestAccAwsLexBotAlias_disappears
=== PAUSE TestAccAwsLexBotAlias_disappears
=== CONT  TestAccDataSourceAwsLexBotAlias_basic
=== CONT  TestAccAwsLexBotAlias_conversationLogsAudio
=== CONT  TestAccAwsLexBotAlias_disappears
=== CONT  TestAccAwsLexBotAlias_description
=== CONT  TestAccAwsLexBotAlias_botVersion
=== CONT  TestAccAwsLexBotAlias_conversationLogsText
=== CONT  TestAccAwsLexBotAlias_basic
=== CONT  TestAccAwsLexBotAlias_disappears
    resource_aws_lex_bot_alias_test.go:218: [INFO] Got non-empty plan, as expected
--- PASS: TestAccAwsLexBotAlias_conversationLogsAudio (76.31s)
--- PASS: TestAccAwsLexBotAlias_conversationLogsText (78.98s)
--- PASS: TestAccAwsLexBotAlias_botVersion (82.69s)
--- PASS: TestAccDataSourceAwsLexBotAlias_basic (86.27s)
--- PASS: TestAccAwsLexBotAlias_basic (91.03s)
--- PASS: TestAccAwsLexBotAlias_description (94.00s)
--- PASS: TestAccAwsLexBotAlias_disappears (98.64s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	100.184s
```

**Review by gdavison — APPROVED** [review]
LGTM 🚀 

--- PASS: TestAccDataSourceAwsLexBotAlias_basic (40.97s)
--- PASS: TestAccAwsLexBotAlias_botVersion (76.18s)
--- PASS: TestAccAwsLexBotAlias_disappears (158.05s)
--- PASS: TestAccAwsLexBotAlias_basic (194.58s)
--- PASS: TestAccAwsLexBotAlias_conversationLogsAudio (197.02s)
--- PASS: TestAccAwsLexBotAlias_conversationLogsText (198.77s)
--- PASS: TestAccAwsLexBotAlias_conversationLogsBoth (203.08s)
--- PASS: TestAccAwsLexBotAlias_description (259.16s)

**Pull request merged**
