### PR TITLE
Support bucket ACLs.

### PR DESCRIPTION
**Pull request by ameir**
I picked this up from my previous PR at https://github.com/hashicorp/terraform/pull/13448 .

It has also been requested at https://github.com/terraform-providers/terraform-provider-aws/issues/989 .

It takes a JSON-formatted ACL and applies it as a bucket policy.  Since there are many unused/optional fields, it filters nil values in the struct to avoid noop diffs.

### CODE REVIEW

**Comment by Chhed13** [comment]
Did you check it on flapping without any `acl` ? Like this:
Twice `terraform apply` this
```
resource "aws_s3_bucket" "bucket" {
	bucket = "tf-test-bucket-%d"
}
```
I faced with this in my realization #3728. That's because you can't completely delete permissions from bucket owner

**Comment by ameir** [comment]
I did notice that, but found that adding `Computed: true` fixed it.  The `acl_policy` is then added to the state file, and is not overwritten until you attempt to in the config.

**Comment by ameir** [comment]
@bflad did you have any thoughts on this or https://github.com/terraform-providers/terraform-provider-aws/pull/3728 ?

**Comment by tomelliff** [comment]
This PR is unlikely to be merged without some accompanying tests. Did you still want to finish this off? If not I can see if I can find the time to work on this as I'm also keen to enable Cloudfront access logs to an S3 bucket.

**Comment by ameir** [comment]
I'd be willing to work on this further (with tests) if I had some sort of
reassurance that it will get merged. I have very little spare time these
days, so I want to make sure the investment is fruitful.

**Comment by tomelliff** [comment]
#3728 looks to be further along but also being actively worked on so I'll wait for that instead of duplicating efforts further here.

**Comment by ewbankkit** [comment]
It looks like this has been superseded by https://github.com/terraform-providers/terraform-provider-aws/pull/3728.

**Comment by bflad** [comment]
Hi @ameir 👋 Thank you for submitting this and apologies that this went a long time without review. #3728 was recently merged and appears to provide similar functionality. If there is anything missing from that implementation, please submit a new pull request.

**Pull request closed without merging**
