### PR TITLE
Add aws_ecr_policy_statement

### PR DESCRIPTION
**Pull request by DennyLoko**
This PR was originally opened by @greenboxal at hashicorp/terraform#12078.

I'm using this and has been very useful. I believe it can be fully merged on this provider.

### CODE REVIEW

**Comment by stack72** [comment]
Hi @DennyLoko 

I am not sure how this differs from https://www.terraform.io/docs/providers/aws/r/ecr_repository_policy.html

Can you elaborate for me?

Thanks

Paul

**Comment by greenboxal** [comment]
An `ecr_repository` can have only one policy. If you need multiple components to be able to access a repository the only option you have is to add them at once.

This resource lets you manage individual statements inside a single policy, so you can have them spread in different modules.

**Comment by greenboxal** [comment]
Btw, let me open this pull request myself from my fork.

**Comment by stack72** [comment]
@greenboxal can you enhance the docs to show that you can have multiple statements? All I see is a 1-2-1 mapping :)

**Comment by greenboxal** [comment]
Sure. I'll do it and open the correct PR. Can you close this one?

**Comment by stack72** [comment]
Sure :)

**Comment by stack72** [comment]
Closing so that @greenboxal will reopen his PR

**Pull request closed without merging**
