### PR TITLE
New Resource: aws_msk_configuration

### LINKED ISSUE #8736: Support for managing MSK Configurations
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The Managed Streaming for Kafka (MSK) service just recently added support for managing Kafka configurations: https://docs.aws.amazon.com/msk/latest/developerguide/msk-configuration.html

### New Resource

* `aws_msk_configuration`

### Potential Terraform Configuration

```hcl
resource "aws_msk_configuration" "example" {
  description    = ""
  kafka_versions = [""]
  name           = ""
  server_properties = ""
}
```

### References

* https://docs.aws.amazon.com/msk/latest/developerguide/msk-configuration.html
* AWS Go SDK v1.19.34

### PR DESCRIPTION
**Pull request by bflad**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" comments, they generate extra noise for pull request followers and do not help prioritize the request

Closes #8736

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
**New Resource:** `aws_msk_configuration`
```

Output from acceptance testing:

```
--- PASS: TestAccAWSMskConfiguration_KafkaVersions (14.14s)
--- PASS: TestAccAWSMskConfiguration_Description (19.35s)
--- PASS: TestAccAWSMskConfiguration_basic (27.64s)
--- PASS: TestAccAWSMskConfiguration_ServerProperties (29.51s)
```

### CODE REVIEW

**Comment by bflad** [comment]
This has been released in [version 2.12.0 of the Terraform AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#2120-may-24-2019). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.

**Comment by paulca99** [comment]
Hi Guys,  I'm struggling here , how do I link an aws_msk_configuration to an aws_msk_cluster so that the cluster allows topics to be deleted ?

**Comment by bflad** [comment]
@paulca99 this requires the `aws_msk_cluster` updates that were just merged in as part of #8850 and will be released in version 2.14.0 of the Terraform AWS Provider likely tomorrow. e.g.

```hcl
resource "aws_msk_configuration" "example" {
  kafka_versions = ["1.1.1"]
  name           = "example"

  server_properties = <<PROPERTIES
delete.topic.enable = true
PROPERTIES
}

resource "aws_msk_cluster" "example" {
  cluster_name           = "example"
  kafka_version          = "1.1.1"
  number_of_broker_nodes = 3

  broker_node_group_info {
    client_subnets  = ["${aws_subnet.example1.id}", "${aws_subnet.example2.id}", "${aws_subnet.example3.id}"]
    ebs_volume_size = 10
    instance_type   = "kafka.m5.large"
    security_groups = ["${aws_security_group.example.id}"]
  }

  configuration_info {
    arn      = "${aws_msk_configuration.example.arn}"
    revision = "${aws_msk_configuration.example.latest_revision}"
  }
}
```

**Comment by paulca99** [comment]
Thanks @bflad

**Pull request merged**
