### PR TITLE
Move aws_kms_ciphertext to resource

### LINKED ISSUE #960: aws_kms_ciphertext 'unstable' output
### Terraform Version
Terraform v0.9.8

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_kms_ciphertext

### Terraform Configuration Files
```hcl
data "aws_caller_identity" "current" {}

provider "aws" {
    region = "eu-west-1"
}

resource "aws_iam_role" "LambdaBackend_master_lambda" {
    name               = "LambdaBackend_master_lambda"
    path               = "/"
    assume_role_policy = <<POLICY
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "Service": "lambda.amazonaws.com"
      },
      "Action": "sts:AssumeRole"
    }
  ]
}
POLICY
}

resource "aws_iam_role_policy_attachment" "LambdaBackend_master_lambda_AmazonS3ReadOnlyAccess" {
    role       = "${aws_iam_role.LambdaBackend_master_lambda.name}"
    policy_arn = "arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess"
}

resource "aws_iam_role_policy_attachment" "LambdaBackend_master_lambda_AmazonDynamoDBFullAccess" {
    role       = "${aws_iam_role.LambdaBackend_master_lambda.name}"
    policy_arn = "arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess"
}

resource "aws_iam_role_policy_attachment" "LambdaBackend_master_lambda_CloudWatchFullAccess" {
    role       = "${aws_iam_role.LambdaBackend_master_lambda.name}"
    policy_arn = "arn:aws:iam::aws:policy/CloudWatchFullAccess"
}

resource "aws_lambda_function" "LambdaBackend_lambda" {
  filename         = "email_lambda.zip"
  function_name    = "SpikeLambda"
  role             = "${aws_iam_role.LambdaBackend_master_lambda.arn}"
  handler          = "index.handler"
  source_code_hash = "${base64sha256(file("email_lambda.zip"))}"
  runtime          = "nodejs6.10"
  timeout          = 15
  publish          = true

  environment {
    variables = {
      apikey = "${data.aws_kms_ciphertext.apikey.ciphertext_blob}"
    }
  }
}

resource "aws_kms_key" "config" {
  description = "env config"
  is_enabled = true
  policy                  = <<POLICY
{
  "Version" : "2012-10-17",
  "Id" : "key-consolepolicy-3",
  "Statement" : [ {
    "Sid" : "Enable IAM User Permissions",
    "Effect" : "Allow",
    "Principal" : {
      "AWS" : "arn:aws:iam::${data.aws_caller_identity.current.account_id}:root"
    },
    "Action" : "kms:*",
    "Resource" : "*"
  }, {
    "Sid" : "Allow use of the key",
    "Effect" : "Allow",
    "Principal" : {
      "AWS" : "${aws_iam_role.LambdaBackend_master_lambda.arn}"
    },
    "Action" : [ "kms:Encrypt", "kms:Decrypt", "kms:ReEncrypt*", "kms:GenerateDataKey*", "kms:DescribeKey" ],
    "Resource" : "*"
  }, {
    "Sid" : "Allow attachment of persistent resources",
    "Effect" : "Allow",
    "Principal" : {
      "AWS" : "${aws_iam_role.LambdaBackend_master_lambda.arn}"
    },
    "Action" : [ "kms:CreateGrant", "kms:ListGrants", "kms:RevokeGrant" ],
    "Resource" : "*",
    "Condition" : {
      "Bool" : {
        "kms:GrantIsForAWSResource" : "true"
      }
    }
  } ]
}
POLICY
}

data "aws_kms_ciphertext" "apikey" {
  key_id = "${aws_kms_key.config.key_id}"
  plaintext = "hunter2"
}
```

### Debug Output
Run 1: https://gist.github.com/OliverCole/5feb1409f098a5ad5de523ed907cf93a
Run 2: https://gist.github.com/OliverCole/74ee789489a4582b6548a24cb180c07e

### Expected/Desired Behavior
Ciphertext data source should be static, resulting in no changes to downstream dependencies.

### Actual Behavior
```
λ terraform plan

...

~ aws_lambda_function.LambdaBackend_lambda
    environment.0.variables.apikey: "AQICAHhrx94Wb5zY2paCTEFBiotjAnNA5JkowPRTlnNgFDShRwEwemJy4XaanTNiJw/c4f5nAAAAazBpBgkqhkiG9w0BBwagXDBaAgEAMFUGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMNrQujwxAygW7NzoxAgEQgCjhQxFc+GZco8upPiXoqg7tBbyI+UmQvTX7Rk4Zrx+7mwGpcH0S8tlM" => "AQICAHhrx94Wb5zY2paCTEFBiotjAnNA5JkowPRTlnNgFDShRwGg+4IumuMxfn0LhPLisPCNAAAAZTBjBgkqhkiG9w0BBwagVjBUAgEAME8GCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMCWnWVlL7BZdI9/QcAgEQgCIJrOrW56mdVTpYGt6k/rhqvgF+0EMx2gwxx5JB1dzsegQ/"


Plan: 0 to add, 1 to change, 0 to destroy.

λ terraform plan

...

~ aws_lambda_function.LambdaBackend_lambda
    environment.0.variables.apikey: "AQICAHhrx94Wb5zY2paCTEFBiotjAnNA5JkowPRTlnNgFDShRwEwemJy4XaanTNiJw/c4f5nAAAAazBpBgkqhkiG9w0BBwagXDBaAgEAMFUGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMNrQujwxAygW7NzoxAgEQgCjhQxFc+GZco8upPiXoqg7tBbyI+UmQvTX7Rk4Zrx+7mwGpcH0S8tlM" => "AQICAHhrx94Wb5zY2paCTEFBiotjAnNA5JkowPRTlnNgFDShRwEsP80A7AA1DNwPeQjBwUQfAAAAZTBjBgkqhkiG9w0BBwagVjBUAgEAME8GCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM8S3Dt92qSVRXrEeAAgEQgCLiwJB1lND0Md3fKEr23kBmTj3rRkXUg/EcbXY191xLwsY5"


Plan: 0 to add, 1 to change, 0 to destroy.
```

Calls to `data.aws_kms_ciphertext.apikey.ciphertext_blob` in `terraform console` are stable and match the `...0S8tlM` value above.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan`

### References
@apparentlymart - https://groups.google.com/forum/#!topic/terraform-tool/7K4dLBmMrik

### PR DESCRIPTION
**Pull request by JoelSpeed**
Fixes #960 

As a resource, the encryption is performed on `create` only.

Changing any of the input forces a new resource.

### CODE REVIEW

**Comment by JoelSpeed** [comment]
The argument for making it into a resource was based on reading this page https://www.terraform.io/docs/configuration/data-sources.html and my general understanding of terraform idoms.

My understanding is that we are creating the ciphertext from the input. We only need to recreate this when the input changes which sounds to me, more like a resource than a datasource.

By making this a resource, we can use the `ForceNew` property on the input schema to only perform the encryption when one of the input properties changes using the `Create` function. A `Read` operation should actually not do anything to the `ciphertext_blob` as it is stored in the state and this is usually used to read remote properties.

My thoughts were that you could wrap the creation of the `ciphertext_blob` like the below within the data resource, but this seemed like a bit of an abuse of the data source type. I believe this would fix the issue but this logic shouldn't really be within a read function.
https://github.com/pusher/terraform-provider-aws/blob/df4c73b9b61962162673810d0351a8630ef9e2a5/aws/resource_aws_kms_ciphertext.go#L81-L83

**Comment by JoelSpeed** [comment]
@Ninir Assuming you won't look at this again with the `waiting-response` label, I guess I should have @'ed you in the first reply, sorry

**Comment by Ninir** [comment]
@JoelSpeed No worries 😄 

What I meant is, if we were to do such thing, we could not remove the data source for now, but first deprecate it, and in a coming future remove it. So we should instead ADD a new resource rather than moving the data source to a resource.

Having a resource might be the way to go, even though I think this is resolvable at the data source level.

**Comment by JoelSpeed** [comment]
@Ninir What would you prefer me to do then? I see two options, try and add some logic to the data type and fix it that way.

Or put the data type back into this PR and follow a deprecation path to move it to a resource?

**Comment by Ninir** [comment]
@JoelSpeed In an utopian world, I would go for your 1st suggestion, fixing it as is. Let us know If we  can help!

**Comment by JoelSpeed** [comment]
@Ninir I've had a go at this over the last few hours but have run into a few problems.

I was hoping to be able to use the `d.HasChange` method to detect the changes, but this does not work as data resources do not get passed the current state, only the new input. 

This means that you cannot check whether the input to the `Read` method has changed or not since the last run.

I then thought, maybe you could try decrypting the old ciphertext, the `Decrypt` method in the aws sdk returns the key and the plaintext if the decrypt is successful which would give you the information to compare. But this is also not possible as the old `ciphertext_blob` is not in the state passed to the `Read` method so you cannot attempt to decrypt it.

The only input the `Read` method gets are the current values of the `key_id`, `ciphertext_blob` and `context`.

Without access to the old state or the old ciphertext blob, I don't think this bug can be fixed while keeping the ciphertext as a data resource.

**Comment by johnjelinek** [comment]
It sounds like this PR is almost ready if you add it the existing behavior and add the resource.

**Comment by charles-at-geospock** [comment]
I've just encountered this problem. We would like to have idempotent deployments, and have just introduced the use of kms ciphertext into our workflow. Now, however, each execution results in a change to the ciphertext, which means that resources get updated with the new data and the deployment is no longer idempotent.

My understanding of the discussion so far is...

* Removing the data resource isn't reasonable as people will be using it. It must be deprecated first.
* Adding logic for changes in state to the data resource won't work, because the data resources don't get to know about the current state.
* The implementation to make a resource (from the existing data resource) exists in the change supplied.

So my understanding would be that if the data resource were left alone, and the new (regular) resource were created with the logic proposed here, that would allow the original data resource to continue working as it does (and nobody is any worse off who uses it), and give an easy migration path for them to move to the new resource which avoids this change in state on each invocation.

Would that be a correct understanding of the situation?

If it is, I may have a go at updating this change to implement that, if I get an opportunity in the next few weeks.

**Comment by JoelSpeed** [comment]
@charles-at-geospock If that's the case, I can just amend my commits to remove the deletion of the `data` type.

If the maintainers will accept having both a `data` and `resource` and start the migration process then I can make the PR resemble that, won't take too long

**Comment by jbergknoff** [comment]
Would it also be feasible to store a hash of the plaintext instead of the plaintext itself?

**Comment by cperilla-rival** [comment]
@Ninir I have implemented the changes you requested on this PR https://github.com/terraform-providers/terraform-provider-aws/pull/6993

**Comment by bflad** [comment]
Hi @JoelSpeed 👋 Thanks for your contribution here. As noted above, this pull request would have required creating a separate resource, which looks like was taken care of after a few months in a new pull request: #6993. Since #6993 does not introduce breaking changes and implements the functionality as expected, opting to merge that one. Thanks again for submitting this.

**Pull request closed without merging**
