### PR TITLE
tests/provider: Initial migration from hardcoded regions and shared environment variable overwrite (CUR and EC2-Classic)

### PR DESCRIPTION
**Pull request by bflad**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Reference: #8316
Reference: #15737
Reference: #15791

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
NONE
```

This includes two related commits to show migration paths for EC2-Classic handling (Redshift Security Groups) and an example service that requires special region lookup (Cost and Usage Reporting). The additional testing provider and testing region lookup pattern should only be implemented where necessary.

As noted in the new Go documentation, there is a lot of older style handling in the testing provider initialization. It is probably worth cleaning up parts of that, in particular `testAccProviderFactories` since it is problematic as-is, before applying these types of changes across other services.

Output from acceptance testing in AWS Commercial (DynamoDB to verify existing testAccProviderFactories handling):

```
--- PASS: TestAccAWSDynamoDbTable_Replica_Single (274.15s)

--- PASS: TestAccAWSRedshiftSecurityGroup_basic (10.87s)
--- PASS: TestAccAWSRedshiftSecurityGroup_ingressCidr (10.88s)
--- PASS: TestAccAWSRedshiftSecurityGroup_ingressSecurityGroup (12.45s)
--- PASS: TestAccAWSRedshiftSecurityGroup_updateIngressCidr (24.07s)
--- PASS: TestAccAWSRedshiftSecurityGroup_updateIngressSecurityGroup (27.14s)

--- PASS: TestAccAwsCurReportDefinition_refresh (13.35s)
--- PASS: TestAccAwsCurReportDefinition_overwrite (13.53s)
--- PASS: TestAccAwsCurReportDefinition_athena (13.55s)
--- PASS: TestAccAwsCurReportDefinition_basic (13.56s)
--- PASS: TestAccAwsCurReportDefinition_textOrCsv (13.77s)
--- PASS: TestAccAwsCurReportDefinition_parquet (13.83s)

--- PASS: TestAccDataSourceAwsCurReportDefinition_additional (15.71s)
--- PASS: TestAccDataSourceAwsCurReportDefinition_basic (16.05s)
```

Output from acceptance testing in AWS GovCloud (US):

```
--- SKIP: TestAccAWSRedshiftSecurityGroup_updateIngressCidr (2.50s)
--- SKIP: TestAccAWSRedshiftSecurityGroup_basic (2.50s)
--- SKIP: TestAccAWSRedshiftSecurityGroup_ingressCidr (2.50s)
--- SKIP: TestAccAWSRedshiftSecurityGroup_ingressSecurityGroup (2.50s)
--- SKIP: TestAccAWSRedshiftSecurityGroup_updateIngressSecurityGroup (2.50s)

--- SKIP: TestAccAwsCurReportDefinition_refresh (1.22s)
--- SKIP: TestAccAwsCurReportDefinition_athena (1.22s)
--- SKIP: TestAccAwsCurReportDefinition_basic (1.23s)
--- SKIP: TestAccAwsCurReportDefinition_textOrCsv (1.23s)
--- SKIP: TestAccAwsCurReportDefinition_overwrite (1.24s)
--- SKIP: TestAccAwsCurReportDefinition_parquet (1.25s)

--- SKIP: TestAccDataSourceAwsCurReportDefinition_basic (1.17s)
--- SKIP: TestAccDataSourceAwsCurReportDefinition_additional (1.19s)
```

### CODE REVIEW

**Review by YakDriver — APPROVED** [review]
So beautiful 😢 😍

**Comment by YakDriver** [comment]
Hmmm... TeamCity commercial alternate is not a fan:

Failures are for: `Error: Error creating AWS Cost And Usage Report Definition: AccessDeniedException: accountId: ******* is not authorized to callPutReportDefinition. Note: linked account is not allowed to modify report preference.`

```
--- SKIP: TestAccAWSRedshiftSecurityGroup_updateIngressSecurityGroup (0.00s)
--- SKIP: TestAccAWSRedshiftSecurityGroup_updateIngressCidr (0.00s)
--- SKIP: TestAccAWSRedshiftSecurityGroup_ingressSecurityGroup (0.00s)
--- SKIP: TestAccAWSRedshiftSecurityGroup_basic (0.00s)
--- SKIP: TestAccAWSRedshiftSecurityGroup_ingressCidr (0.00s)
--- FAIL: TestAccAwsCurReportDefinition_parquet (22.34s)
--- FAIL: TestAccAwsCurReportDefinition_basic (26.27s)
--- FAIL: TestAccAwsCurReportDefinition_overwrite (26.34s)
--- FAIL: TestAccAwsCurReportDefinition_textOrCsv (26.49s)
--- FAIL: TestAccDataSourceAwsCurReportDefinition_basic (26.56s)
--- FAIL: TestAccAwsCurReportDefinition_refresh (26.70s)
--- FAIL: TestAccAwsCurReportDefinition_athena (26.84s)
--- FAIL: TestAccDataSourceAwsCurReportDefinition_additional (26.86s)
--- PASS: TestAccAWSDynamoDbTable_Replica_Single (654.70s)
```

**Comment by bflad** [comment]
@YakDriver the "main" and "alternate" testing accounts are member accounts of an Organization and do not have permissions to modify CUR. Any standalone account, e.g. our "organizations" account, has permissions since its the administrative account of the Organization after its created.

**Comment by bflad** [comment]
@YakDriver Ah, it was previously guarded by the `DescribeReportDefinitions` in the `PreCheck` -- I'll move that into the new function.

**Comment by YakDriver** [comment]
The GovCloud account likes it more, Shirley, for the reasons you mentioned: 

```
--- SKIP: TestAccDataSourceAwsCurReportDefinition_basic (0.00s)
--- SKIP: TestAccDataSourceAwsCurReportDefinition_additional (0.00s)
--- SKIP: TestAccAwsCurReportDefinition_overwrite (0.00s)
--- SKIP: TestAccAwsCurReportDefinition_basic (0.00s)
--- SKIP: TestAccAwsCurReportDefinition_textOrCsv (0.00s)
--- SKIP: TestAccAWSRedshiftSecurityGroup_ingressCidr (0.00s)
--- SKIP: TestAccAwsCurReportDefinition_parquet (0.00s)
--- SKIP: TestAccAwsCurReportDefinition_athena (0.00s)
--- SKIP: TestAccAwsCurReportDefinition_refresh (0.00s)
--- SKIP: TestAccAWSRedshiftSecurityGroup_ingressSecurityGroup (0.00s)
--- SKIP: TestAccAWSRedshiftSecurityGroup_updateIngressSecurityGroup (0.00s)
--- SKIP: TestAccAWSRedshiftSecurityGroup_updateIngressCidr (0.00s)
--- SKIP: TestAccAWSRedshiftSecurityGroup_basic (0.00s)
--- PASS: TestAccAWSDynamoDbTable_Replica_Single (450.99s)
```

**Comment by bflad** [comment]
https://github.com/terraform-providers/terraform-provider-aws/pull/15803/commits/d1cde12b8ba38cbefcc722e411c913dc8c32f230 should be much happier. Thanks for catching that!

Output from acceptance testing in AWS Commercial ("main" testing account -- Organizations member account):

```
=== CONT  TestAccAwsCurReportDefinition_basic
    cur_test.go:66: skipping acceptance testing: AccessDeniedException: accountId: --OMITTED-- is not authorized to callDescribeReportDefinitions. Note: linked account is not allowed to modify report preference.
        	status code: 400, request id: 6e513d8a-4ff8-4af2-a4d3-7523dacb2dbb
--- SKIP: TestAccAwsCurReportDefinition_basic (2.42s)
```

Output from acceptance testing in AWS Commercial (standalone account):

```
--- PASS: TestAccAwsCurReportDefinition_basic (13.76s)
```

Output from acceptance testing in AWS GovCloud (US):

```
=== CONT  TestAccAwsCurReportDefinition_basic
    provider_test.go:602: skipping tests; partition aws-us-gov does not support cur service
--- SKIP: TestAccAwsCurReportDefinition_basic (1.37s)
```

**Pull request merged**
