### PR TITLE
New Resource: aws_wafregional_rule

### PR DESCRIPTION
**Pull request by knehring**
This PR is a port of the originally opened by @yusukegoto at hashicorp/terraform#13710, with some minor tweaks based off of conversations in other PRs for wafregional

### CODE REVIEW

**Comment by radeksimko** [comment]
Hi @knehring 
this PR was already re-raised in https://github.com/terraform-providers/terraform-provider-aws/pull/1045 and there are other WAF regional PRs pending some work based on feedback I provided in https://github.com/terraform-providers/terraform-provider-aws/pull/1013 or https://github.com/terraform-providers/terraform-provider-aws/pull/1014

Do you have any plans to implement the feedback?

If not, that's 👌  - just FYI given that this PR was re-opened couple of times and always went stale I will go ahead and implement the changes on top of @yusukegoto's PRs (because he we the first one raising PRs for this).

**Comment by giuliocalzolari** [comment]
Hi do you plan to merge it?

**Comment by knehring** [comment]
All of the changes that you linked in the above PR's have been implemented in this PR, its been awhile since I looked at this, but from looking at the feedback on those PR some of them do not apply in this case.

1. No plural tuple/tuples (not used in this)
2. This is not missing any fields afaik
3. The Update code uses existing code in the global waf rule for diffing the updates and should be good here
4. the tests reflect what is currently there for the global WAF Rule, if I am missing any tests here please let me know

I don't think there need to be any more changes to this bit of code. The only other thing I think would be beneficial is to have the other resources implemented as well. That shouldn't stop this PR from being implemented because this would allow the use of the byte match set and ipsets that are already implemented. @radeksimko

**Comment by radeksimko** [comment]
https://github.com/terraform-providers/terraform-provider-aws/pull/3756 which added this resource was just merged. Thanks to everyone involved 🎉

**Pull request closed without merging**
