### PR TITLE
s3_bucket_object: Fix ETAG changes not forcing new

### LINKED ISSUE #2411: aws_s3_bucket_object etag doesn't trigger new resource
Hi there,

aws_s3_bucket_object etag doesn't trigger new resource

### Terraform Version
```
Terraform v0.11.0
+ provider.archive v1.0.0
+ provider.aws v1.2.0
+ provider.null v1.0.0
+ provider.template v1.0.0
```

### Affected Resource(s)
- aws_s3_bucket_object

### Terraform Configuration Files
```hcl
resource "aws_s3_bucket_object" "ansible-roles" {
  bucket = "${aws_s3_bucket.config.id}"
  key    = "config/ansible/roles.zip"
  source = "config/ansible/roles.zip"
  etag   = "${data.archive_file.zip.output_md5}"
}
```

### Expected Behavior
etag should force new resource so updated source file is uploaded to s3

### Actual Behavior
just changes the value of the etag and doesn't update the s3 object
```
aws_s3_bucket_object.ansible-groups: Refreshing state... (ID: config/ansible/groups.yaml)

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  ~ aws_s3_bucket_object.ansible-roles
      etag: "adc8d9a264cb5105cf63e611b9c79f9c" => "5bc7c6f6d565dcb0a785cf998fe2b15d"


Plan: 0 to add, 1 to change, 0 to destroy.
```

### Steps to Reproduce
1. `terraform apply`
2. make changes to file
3. `terraform apply`

### PR DESCRIPTION
**Pull request by YakDriver**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" comments, they generate extra noise for pull request followers and do not help prioritize the request

Closes #2411

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
resource/aws_s3_bucket_object: Update object contents when the source is the same but the contents/ETAG are not [GH-2411]
```

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccAWSS3BucketObject_updateSameFile'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./... -v -parallel 20 -run=TestAccAWSS3BucketObject_updateSameFile -timeout 120m
?   	github.com/terraform-providers/terraform-provider-aws	[no test files]
=== RUN   TestAccAWSS3BucketObject_updateSameFile
=== PAUSE TestAccAWSS3BucketObject_updateSameFile
=== CONT  TestAccAWSS3BucketObject_updateSameFile
--- PASS: TestAccAWSS3BucketObject_updateSameFile (55.93s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	55.986s
```

### CODE REVIEW

**Comment by YakDriver** [comment]
@bflad This is rebased. Any adjust you'd like on this? This fix will make several of our processes much cleaner.

**Comment by bflad** [comment]
Hey @YakDriver, all 👋 

The new acceptance test is currently passing on `master` for me:

```
--- PASS: TestAccAWSS3BucketObject_updateSameFile (49.72s)
```

What is the incorrect behavior that is supposed to be fixed by forced recreation of the object? The debug logging, as part of the testing passing, is showing the expected non-empty plan after rewriting the file and the `PutObject` call to update it.

**Comment by lorengordon** [comment]
@bflad, it's described in https://github.com/terraform-providers/terraform-provider-aws/issues/2411... when the source _contents_ change but the source value does not, `etag` presumably can be used to force the provider to upload the new contents to S3. That hadn't been working for a while now.

The plan I've seen wants to update just the `etag` value (exactly as depicted in the linked issue), which S3 does not support (makes sense). The apply was still failing in whatever the latest release was just a couple weeks ago, but maybe it's somehow now magically working?

**Comment by YakDriver** [comment]
>  but maybe it's somehow now magically working?

Exactly.

@bflad Although now I believe this was always an AWS bug, see my explanation https://github.com/terraform-providers/terraform-provider-aws/issues/2411#issuecomment-523719225, I would feel better if we added the acceptance test anyway. Then if the s3 service API breaks again, we'd know about it. I updated this PR to leave just the acceptance test.

**Comment by bostrowski13** [comment]
As FYI, this issue is not noted in the changelog.

**Comment by bflad** [comment]
@bostrowski13 thanks for the notice. The fix occurred in the API itself, not Terraform. Because of that, this pull request became only adding an acceptance test so we can potentially detect any API regression that might occur. We typically do not CHANGELOG testing-only changes as they are not operator facing. 👍

**Pull request merged**
