### PR TITLE
Update validateArn to use arn.Parse for validation

### LINKED ISSUE #8307: validateArn incorrectly rejects ARNs in isolated AWS regions
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.11.13
+ provider.aws v2.6.0

### Affected Resource(s)

* All resources that have a field that uses `validateArn` for validation

### Terraform Configuration Files

```hcl
resource "aws_ebs_volume" "test" {
  // Some configuration...

  encrypted = true
  kms_key_id = "arn:aws-iso:kms:us-iso-east-1:012345678901:key/some-uuid-abc123"
}
```

### Expected Behavior

The ARN should validate.

### Actual Behavior

The ARN does not validate:
```
aws_ebs_volume.test: "kms_key_id" doesn't look like a valid ARN ("^arn:[\\w-]+:([a-zA-Z0-9\\-])+:([a-z]{2}-(gov-)?[a-z]+-\\d{1})?:(\\d{12})?:(.*)$"): <arn here>
```

Suggested fix is to update the regex in the `validateArn` function of `aws/validators.go` to match on ARNs from the iso and isob partitions:

```go
pattern := `^arn:[\w-]+:([a-zA-Z0-9\-])+:([a-z]{2}-((?:gov|iso|isob)-)?[a-z]+-\d{1})?:(\d{12})?:(.*)$`
```

### Steps to Reproduce

1. Create a configuration that uses an ARN from an isolated AWS region.
2. `terraform validate`

### Important Factoids

This account is located in an isolated AWS region.

### PR DESCRIPTION
**Pull request by ccday**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" comments, they generate extra noise for pull request followers and do not help prioritize the request

Closes #8307

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
NONE
```

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccXXX'

...
```

### CODE REVIEW

**Comment by ccday** [comment]
@ewbankkit Here's the implementation using `arn.Parse` as suggested. It causes invalid ARN `arn:aws:logs:region:*:*` to pass validation. I'm not sure if this test case can be safely removed or if it represents something that needs to be validated using a different method than `arn.Parse`.

**Comment by ewbankkit** [comment]
@ccday Yes, I think that failing test case can be removed.
`arn:aws:logs:region:*:*` is a structurally sound ARN, it was failing because of our assumption on what an AWS region name should look like.
The [AWS docs](https://docs.aws.amazon.com/general/latest/gr/aws-arns-and-namespaces.html) don't strictly define what a region name should look like.

**Comment by ewbankkit** [comment]
Can use new `IsARN` https://github.com/terraform-providers/terraform-provider-aws/blob/03a2526a98061f27046eb3d7465958492b69cd21/vendor/github.com/aws/aws-sdk-go/aws/arn/arn.go#L78-L82 function.

**Comment by ewbankkit** [comment]
@ccday I think this PR has been superseded by https://github.com/terraform-providers/terraform-provider-aws/pull/11471.
Could you please verify and close this one if appropriate.
Thanks.

**Pull request closed without merging**
