### PR TITLE
API Gateway deployment resource, field stage_name not required #2918

### LINKED ISSUE #2918: Error creating API Gateway Stage: ConflictException: Stage already exists
(See #1153. Since this issue was closed by the submitter and I can't re-open it, I'm duplicating it.)

Using `resource "aws_api_gateway_deployment"` together with a `resource "aws_api_gateway_stage"` of the same name results in a `Error creating API Gateway Stage: ConflictException: Stage already exists`.

Apart from the obvious issues with the documentation (as discussed in #1153), this seems to be caused by AWS *creating a new stage* for each `create-deployment`, rather than referencing it. I take this from [the documentation](https://docs.aws.amazon.com/cli/latest/reference/apigateway/create-deployment.html):
> `--stage-name (string)`
>
> The name of the Stage resource for the Deployment resource to create.
>
> `--stage-description (string)`
>
> The description of the Stage resource for the Deployment resource to create.

Together with a stage of the same name (which may be required e.g. to assign a certificate to the stage), this leads to a conflict.

According to the documentation, the `--stage-name` and `--stage-description` parameters are optional. Terraform, however, treats them as required parameters. The `stage_name` parameter of the `aws_api_gateway_deployment` resource should be optional.

Minimal example to reproduce the problem:

```tf
resource "aws_api_gateway_rest_api" "my_api" {
  name = "My API"
}

resource "aws_api_gateway_stage" "prod" {
  stage_name            = "prod"
  rest_api_id           = "${aws_api_gateway_rest_api.my_api.id}"
  deployment_id         = "${aws_api_gateway_deployment.my_deployment.id}"
  client_certificate_id = "${var.client_cert_id}" // This is why I need the explicit resource and cannot rely on the one implicitly created by `aws_api_gateway_deployment.my_deployment`.
  description           = "foo"
}

resource "aws_api_gateway_deployment" "my_deployment" {
  rest_api_id = "${aws_api_gateway_rest_api.my_api.id}"
  stage_name  = "prod" // This tries to *create* a stage, which then conflicts with `aws_api_gateway_stage.prod`. This parameter should be optional!
}
```

### PR DESCRIPTION
**Pull request by sousmangoosta**
Fixes #2918

Changes proposed in this pull request:

* Field stage_name changed from required to optional

### CODE REVIEW

**Comment by bflad** [comment]
Hi @sousmangoosta 👋 Thanks for submitting this! Would you be able to include a new acceptance test and test configuration that covers not setting this argument?

**Comment by sousmangoosta** [comment]
Hi @bflad , I'll try doing that, I found a bug for this change.
When I change from stage for example "default" to no one, the plan create a map like that : 
`"stage_name":*terraform.ResourceAttrDiff{Old:"default", New:"", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Sensitive:false, Type:0x0}`

But on apply, the map does not contain stage_name, so terraform complaints with `Mismatch reason: attribute mismatch: stage_name`

**Comment by sousmangoosta** [comment]
Hey @bflad, I don't have this bug anymore, so I will add new acceptance test, and push when ready.

**Comment by sousmangoosta** [comment]
@bflad acceptance tests has been added.

`make testacc TESTARGS='-run=TestAccAWSAPIGatewayDeployment'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./... -v -parallel 20 -run=TestAccAWSAPIGatewayDeployment -timeout 120m
?       github.com/terraform-providers/terraform-provider-aws   [no test files]
=== RUN   TestAccAWSAPIGatewayDeployment_basic
=== PAUSE TestAccAWSAPIGatewayDeployment_basic
=== RUN   TestAccAWSAPIGatewayDeployment_basicEmptyStage
=== PAUSE TestAccAWSAPIGatewayDeployment_basicEmptyStage
=== RUN   TestAccAWSAPIGatewayDeployment_namedToEmptyStage
=== PAUSE TestAccAWSAPIGatewayDeployment_namedToEmptyStage
=== RUN   TestAccAWSAPIGatewayDeployment_createBeforeDestoryUpdate
=== PAUSE TestAccAWSAPIGatewayDeployment_createBeforeDestoryUpdate
=== CONT  TestAccAWSAPIGatewayDeployment_basic
=== CONT  TestAccAWSAPIGatewayDeployment_createBeforeDestoryUpdate
=== CONT  TestAccAWSAPIGatewayDeployment_namedToEmptyStage
=== CONT  TestAccAWSAPIGatewayDeployment_basicEmptyStage
--- PASS: TestAccAWSAPIGatewayDeployment_basic (33.58s)
--- PASS: TestAccAWSAPIGatewayDeployment_namedToEmptyStage (66.86s)
--- PASS: TestAccAWSAPIGatewayDeployment_basicEmptyStage (102.53s)
--- PASS: TestAccAWSAPIGatewayDeployment_createBeforeDestoryUpdate (159.43s)
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws       159.467s`

**Comment by sousmangoosta** [comment]
@bflad : Is there someone to review this one ?

**Comment by anthonyagresta** [comment]
Commenting to bump this PR, ran into this issue today.

**Comment by mkirlin** [comment]
Just wanted to put another bump in here. I'm working around this with an apply-import-apply chain of commands, but it would be nice to have this actually optional as displayed in the docs.

**Comment by jpadhye** [comment]
Hit this issue at work. Giving a bump

**Comment by simsinght** [comment]
also running into this issue. bump.

**Comment by jvanwagner** [comment]
@bflad @nywilken @mikecook any progress on possibly reviewing/approving this? We just hit this issue at our company and seems like a lot of others ran across it as well.

**Comment by bflad** [comment]
This has been released in [version 2.3.0 of the Terraform AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#230-march-21-2019). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.

**Pull request merged**
