### PR TITLE
Add codebuild environment variables

### PR DESCRIPTION
**Pull request by fnaoto**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates OR Closes #0000

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
- Add SECRETS_MANAGER to codebuild environment variables.
  - go doc: https://godoc.org/github.com/aws/aws-sdk-go/service/codebuild#EnvironmentVariable
```

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccXXX'

...
```

### CODE REVIEW

**Comment by dylantack** [comment]
resolves #11331

**Comment by dylantack** [comment]
@fnaoto I needed to add one more line to make work: https://github.com/fnaoto/terraform-provider-aws/pull/1

**Comment by arvinep** [comment]
Do we have any update on this?

**Comment by kingsquirrel152** [comment]
Any chances this is going to get merged? Looks promising. As an aside, workaround is available in the form of adding the env vars to codebuild build spec directly.

**Comment by bflad** [comment]
Hi folks 👋  Sorry for any confusion on this and thank you to @fnaoto for contributing this. It appears this functionality was covered by https://github.com/terraform-providers/terraform-provider-aws/pull/12572, which was released in version 2.62.0 of the Terraform AWS Provider two months ago. Apologies that this one should have been reviewed/merged first. We are hoping that we can get some automated CI tooling in place to catch duplicate pull requests and prevent this type of contribution issue going forward. Thanks again, @fnaoto.

**Comment by fnaoto** [comment]
Thank you to cover this functionality !
This is what I've been waiting for.
I really appreciate what you've done.
thank you 👏

**Pull request closed without merging**
