### PR TITLE
WIP!: r/aws-athena-workgroup added

### LINKED ISSUE #7650: New Resource: aws_athena_workgroup
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS released Athena Workgroups earlier this week. It would be very useful to have the ability to create these from Terraform.

"You can now use Amazon Athena Workgroups - A new resource type that can be used to separate query execution and query history between Users, Teams, or Applications running under the same AWS account. Because Workgroups act as resources, you can use resource-based policies to control access to a Workgroup. For example, if you have two teams or different applications using Athena, you can limit access by assigning them to different Workgroups. You can also separate ad hoc usage from scheduled reports by assigning them to different Workgroups. Queries running in one Workgroup are not visible to users or applications running in a different Workgroup."

### New or Affected Resource(s)

* aws_athena_workgroup

### Potential Terraform Configuration

```hcl
resource "aws_athena_workgroup" "hr_workgroup" {
    name                                = "HR Workgroup"
    description                         = "Athena Workgroup for HR"
    bytes_scanned_cutoff_per_query      = "${var.cut_off_bytes}"
    enforce_work_group_configuration    = "true"
    publish_cloudwatch_metrics_enabled  = "true"
    output_location                     = "${aws_s3_bucket.hr_bucket.arn}"
    encryption_option                   = "SSE_KMS"
    kms_key                             = "${aws_kms_key.hr_kms_key.arn}"    
}
```

### References

* https://aws.amazon.com/about-aws/whats-new/2019/02/athena_workgroups/

### PR DESCRIPTION
**Pull request by marcotesch**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" comments, they generate extra noise for pull request followers and do not help prioritize the request

Fixes #7650, #7667 

Changes proposed in this pull request:

* Add new resource aws_athena_workgroup

This is now WIP, Test Output will be added when available

```terraform
resource "aws_athena_workgroup" "hr_workgroup" {
    name                                  = "HR Workgroup"
    description                           = "Athena Workgroup for HR"
    bytes_scanned_cutoff_per_query        = "${var.cut_off_bytes}"
    enforce_workgroup_configuration       = true
    publish_cloudwatch_metrics_enabled    = true
    output_location                       = "s3://path/to/output"
    encryption_option                     = "SSE_KMS"
    kms_key                               = "${aws_kms_key.hr_kms_key.arn}"   
} 
```

First test(s) are written and running: 

```sh
make testacc TEST=./aws TESTARGS='-run=TestAccAWSAthenaWorkGroup_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -parallel 20 -run=TestAccAWSAthenaWorkGroup_ -timeout 120m
=== RUN   TestAccAWSAthenaWorkGroup_basic
=== PAUSE TestAccAWSAthenaWorkGroup_basic
=== RUN   TestAccAWSAthenaWorkGroup_withDescription
=== PAUSE TestAccAWSAthenaWorkGroup_withDescription
=== RUN   TestAccAWSAthenaWorkGroup_withDescriptionUpdate
=== PAUSE TestAccAWSAthenaWorkGroup_withDescriptionUpdate
=== RUN   TestAccAWSAthenaWorkGroup_withBytesScannedCutoffPerQuery
=== PAUSE TestAccAWSAthenaWorkGroup_withBytesScannedCutoffPerQuery
=== RUN   TestAccAWSAthenaWorkGroup_withBytesScannedCutoffPerQueryUpdate
=== PAUSE TestAccAWSAthenaWorkGroup_withBytesScannedCutoffPerQueryUpdate
=== RUN   TestAccAWSAthenaWorkGroup_withEnforceWorkgroupConfiguration
=== PAUSE TestAccAWSAthenaWorkGroup_withEnforceWorkgroupConfiguration
=== RUN   TestAccAWSAthenaWorkGroup_withEnforceWorkgroupConfigurationUpdate
=== PAUSE TestAccAWSAthenaWorkGroup_withEnforceWorkgroupConfigurationUpdate
=== RUN   TestAccAWSAthenaWorkGroup_withPublishCloudWatchMetricsEnabled
=== PAUSE TestAccAWSAthenaWorkGroup_withPublishCloudWatchMetricsEnabled
=== RUN   TestAccAWSAthenaWorkGroup_withPublishCloudWatchMetricsEnabledUpdate
=== PAUSE TestAccAWSAthenaWorkGroup_withPublishCloudWatchMetricsEnabledUpdate
=== RUN   TestAccAWSAthenaWorkGroup_withOutputLocation
=== PAUSE TestAccAWSAthenaWorkGroup_withOutputLocation
=== RUN   TestAccAWSAthenaWorkGroup_withOutputLocationUpdate
=== PAUSE TestAccAWSAthenaWorkGroup_withOutputLocationUpdate
=== RUN   TestAccAWSAthenaWorkGroup_withSseS3Encryption
=== PAUSE TestAccAWSAthenaWorkGroup_withSseS3Encryption
=== RUN   TestAccAWSAthenaWorkGroup_withKmsEncryption
=== PAUSE TestAccAWSAthenaWorkGroup_withKmsEncryption
=== RUN   TestAccAWSAthenaWorkGroup_withKmsEncryptionUpdate
=== PAUSE TestAccAWSAthenaWorkGroup_withKmsEncryptionUpdate
=== CONT  TestAccAWSAthenaWorkGroup_basic
=== CONT  TestAccAWSAthenaWorkGroup_withPublishCloudWatchMetricsEnabled
=== CONT  TestAccAWSAthenaWorkGroup_withPublishCloudWatchMetricsEnabledUpdate
=== CONT  TestAccAWSAthenaWorkGroup_withKmsEncryptionUpdate
=== CONT  TestAccAWSAthenaWorkGroup_withKmsEncryption
=== CONT  TestAccAWSAthenaWorkGroup_withSseS3Encryption
=== CONT  TestAccAWSAthenaWorkGroup_withOutputLocationUpdate
=== CONT  TestAccAWSAthenaWorkGroup_withOutputLocation
=== CONT  TestAccAWSAthenaWorkGroup_withBytesScannedCutoffPerQueryUpdate
=== CONT  TestAccAWSAthenaWorkGroup_withEnforceWorkgroupConfigurationUpdate
=== CONT  TestAccAWSAthenaWorkGroup_withEnforceWorkgroupConfiguration
=== CONT  TestAccAWSAthenaWorkGroup_withDescriptionUpdate
=== CONT  TestAccAWSAthenaWorkGroup_withBytesScannedCutoffPerQuery
=== CONT  TestAccAWSAthenaWorkGroup_withDescription
--- PASS: TestAccAWSAthenaWorkGroup_basic (9.95s)
--- PASS: TestAccAWSAthenaWorkGroup_withSseS3Encryption (10.62s)
--- PASS: TestAccAWSAthenaWorkGroup_withPublishCloudWatchMetricsEnabled (11.73s)
--- PASS: TestAccAWSAthenaWorkGroup_withEnforceWorkgroupConfiguration (12.21s)
--- PASS: TestAccAWSAthenaWorkGroup_withBytesScannedCutoffPerQuery (12.51s)
--- PASS: TestAccAWSAthenaWorkGroup_withDescriptionUpdate (16.72s)
--- PASS: TestAccAWSAthenaWorkGroup_withBytesScannedCutoffPerQueryUpdate (16.98s)
--- PASS: TestAccAWSAthenaWorkGroup_withPublishCloudWatchMetricsEnabledUpdate (18.38s)
--- PASS: TestAccAWSAthenaWorkGroup_withEnforceWorkgroupConfigurationUpdate (25.56s)
--- PASS: TestAccAWSAthenaWorkGroup_withDescription (25.80s)
--- PASS: TestAccAWSAthenaWorkGroup_withOutputLocationUpdate (28.07s)
--- PASS: TestAccAWSAthenaWorkGroup_withOutputLocation (30.88s)
--- PASS: TestAccAWSAthenaWorkGroup_withKmsEncryption (32.30s)
--- PASS: TestAccAWSAthenaWorkGroup_withKmsEncryptionUpdate (48.41s)
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws       48.450s
```

### CODE REVIEW

**Comment by marcotesch** [comment]
Added first TestCase, still working on create/update/read functionality.

#7667 might become an issue as the SDK does not allow to have an ARN for the WorkGroup, which is needed to list-tags. But still working on it.

**Comment by marcotesch** [comment]
@bflad : Got some Travis CI Problems with the govet/nillness checks you have fixed here how I might recover my branch from that?

**Comment by bflad** [comment]
@marcotesch the fixes need to be reviewed and merged into master first then we can restart the TravisCI build. You could also pull in my commits, but that could be troublesome if we change the implementation during review.

**Comment by marcotesch** [comment]
> @marcotesch the fixes need to be reviewed and merged into master first then we can restart the TravisCI build. You could also pull in my commits, but that could be troublesome if we change the implementation during review.

Looks good now @bflad. I will keep working on this, probably tags will not be ready for the first release version and get added later on, if thats fine with you?

**Comment by florianlocqueneux** [comment]
Athena workgroups provide the ability to follow costs using tag allocation for specific processing, without the tags, workgroups are useless

**Comment by marcotesch** [comment]
> Athena workgroups provide the ability to follow costs using tag allocation for specific processing, without the tags, workgroups are useless ( for my usage )

@florianlocqueneux: For sure there are UseCases where Tags are needed. But lets look at the plain resource functionality, for that tags are not needed at all. So imho a working resource might be the first merge and the tag support for said resource might be a second seperate merge. 

This does not imply that I'm not trying to squeeze tag-support in the resource right from the get go but there might be some problems wich are not that easy to overcome.

**Comment by marcotesch** [comment]
This is now the first functioning version without Tags, so far.

I will now add some documentation, but the main code is ready for an official review at this point.

**Comment by xmj** [comment]
@marcotesch wondering if you could fix the merge conflicts

thanks!

**Comment by zerfahp** [comment]
Would it be possible to get this one going? Sorry, I can't tell if this is difficult or not. It would be extremely useful to have this capability. Thanks.

**Comment by DominicBreuker** [comment]
would also love to see it merged :)

**Comment by marcotesch** [comment]
At the moment, I unfortunately don't have the time to write the needed documentation, which leads to the problem that this might not be merged any time soon. But for now I resolved the existing merge conflict.

**Comment by bflad** [comment]
Hi @marcotesch 👋 Would it be okay if the maintainers or another community member finished up this functionality in followup commits?

**Comment by marcotesch** [comment]
Hi,

Yes it would be absolutely fine and appreciated, I’m sorry that I can’t finish it up on my own at the moment.

Am 09.07.2019 um 05:17 schrieb Brian Flad <notifications@github.com<mailto:notifications@github.com>>:


Hi @marcotesch<https://github.com/marcotesch> 👋 Would it be okay if the maintainers or another community member finished up this functionality in followup commits?

**Comment by bflad** [comment]
@marcotesch no worries, you did great work and many people will be happy when the functionality is made available! We hope that you can continue contributing in the future. 😄 

I will post a followup PR either later today or tomorrow that combines this with #8136

**Comment by bflad** [comment]
Followup PR which includes all the commits here is available at: #9290

Please follow that pull request for further updates and thank you again for all the hard work, @marcotesch!

**Comment by zerfahp** [comment]
Thanks for pushing on with this. Much appreciated. Looking forward to putting it to use soon.

**Comment by DominicBreuker** [comment]
thx a lot!

**Comment by bflad** [comment]
#9290 has been merged and will release with version 2.19.0 of the Terraform AWS Provider, likely later today. 👍

**Pull request closed without merging**
