### PR TITLE
Added data source to retrieve a list of all of the accounts in an organization

### PR DESCRIPTION
**Pull request by alucillo**
This data source will return a list of all of the accounts in an organization.  This operation can be called only from the organization's master account.

### CODE REVIEW

**Comment by bflad** [comment]
@alucillo could you please take a look at #2530 and see if you can provide assistance/feedback on that original PR or base your commits off that work?

**Comment by alucillo** [comment]
@bflad I have reviewed the PR you referenced and made adjustments to mine based off of it.

**Comment by alucillo** [comment]
@Ninir I noticed that you commented on PR #2530.  My PR is very similar, I was wondering if you had any comments.

**Comment by alucillo** [comment]
@bflad @loivis @radeksimko 
I know everyone is super busy, but can I get some love on my PR? :)

**Comment by bflad** [comment]
Hi @alucillo 👋 Thank you very much for your time and contribution here. My apologies for the long silence on this pull request. The support for AWS Organizations has been quite the long process and there were differing implementations offered by various members of the community. In the future, we am hoping that we can host these type of implementation discussions in design issues where the implementation choice is agreed on before we wind up in the same situation of conflicting contributions.

After evaluating all the contributions, we decided to opt for a single `aws_organization_organization` data source that was able to represent the same functionality as the `aws_organization_organization` resource. This will allow operators to have a similar experience between these two options and will have the following modes of operation:

* If used in an account that is not part of an Organization, it will return an error
* If used within an Organization but outside the master account, it will return the Organization ID, ARN, and master account ID information
* If used within the Organization master account, it will return all the arguments and attributes available in the `aws_organizations_organization` resource including all member account information such as account ARNs and account IDs

This new `aws_organizations_organization` data source has been merged and will release with version 2.21.0 of the Terraform AWS Provider, in about a week. Since the functionality available in this new data source supersedes the need to an additional data source, I'm going to close out this pull request.

We really appreciate the time and effort that went into this contribution and we hope to be able to work with you again in the future.

**Pull request closed without merging**
