### PR TITLE
resource/aws_kinesis_firehose: add splunk configuration

### PR DESCRIPTION
**Pull request by WhileLoop**
```$ make testacc TEST=./aws TESTARGS='-run=TestAccAWSKinesisFirehoseDeliveryStream_SplunkConfigUpdates'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -run=TestAccAWSKinesisFirehoseDeliveryStream_SplunkConfigUpdates -timeout 120m
=== RUN   TestAccAWSKinesisFirehoseDeliveryStream_SplunkConfigUpdates
--- PASS: TestAccAWSKinesisFirehoseDeliveryStream_SplunkConfigUpdates (131.81s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	132.360s

### CODE REVIEW

**Comment by WhileLoop** [comment]
closes #2897

**Comment by scottpazelt** [comment]
Is there any ETA on the splunk destination for Firehose? Thanks.

**Comment by WhileLoop** [comment]
@bflad ship it! :)

**Comment by bflad** [comment]
This has been released in [terraform-provider-aws version 1.9.0](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#190-february-09-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.

**Comment by connor-tyndall** [comment]
Unable to use 'extended_s3_configuration' argument with Splunk as a destination. Getting the following error: `aws_kinesis_firehose_delivery_stream.delivery_stream: When destination is splunk, s3_configuration is required`. Unable to add the data transformation Lambda function ARN unless 'extented_s3_configuration' is supported. https://www.terraform.io/docs/providers/aws/r/kinesis_firehose_delivery_stream.html#extended_s3_configuration

**Comment by connor-tyndall** [comment]
Data transformation via Lambda is still not available for the Firehose resource. Can this be added ASAP with Splunk as a destination? #513

**Pull request merged**
