### PR TITLE
Support AWS cn-northwest-1 Ningxia (fixes #3053)

### LINKED ISSUE #3053: Terraform v0.11.2 with provider.aws v1.7.0 doesn't support region cn-northwest-1
_This issue was originally opened by @yydoow as hashicorp/terraform#17136. It was migrated here as a result of the [provider split](https://www.hashicorp.com/blog/upcoming-provider-changes-in-terraform-0-10/). The original body of the issue is below._

<hr>

Hello,

I am trying to ran terraform upon the new launched China region cn-northwest-1 with following version
### Terraform Version

```
$ terraform -v
Terraform v0.11.2
+ provider.aws v1.7.0
+ provider.null v1.0.0

```
I also checked the github code, it seems with version I am running has the region supported 
https://github.com/terraform-providers/terraform-provider-aws/commit/8499d2e3651bfc8c7019175bf2f94ee6ee7a276c#diff-59e28844253678de7bce92be14f06597

I have no idea the issue here, could you please help me !

Thanks

### Crash Output

```
$ terraform plan
var.environment
  The environment of the resource

  Enter a value: dev

Acquiring state lock. This may take a few moments...
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

data.null_data_source.configuration: Refreshing state...

Error: Error refreshing state: 1 error(s) occurred:

* provider.aws: Not a valid region: cn-northwest-1
```

### PR DESCRIPTION
**Pull request by kwerey**
Hi Terraform team - this adds the new Ningxia region to the list of valid options for the AWS provider, fixing https://github.com/terraform-providers/terraform-provider-aws/issues/3053

A lot of the acceptance tests will fail run in Nginxia, since the region doesn't support a very large number of AWS services, but these changes let the provider can successfully make client connections to the region:

```
$ export AWS_DEFAULT_REGION=cn-northwest-1
$ make testacc TEST=.//aws TESTARGS='-run=TestAccAWSCloudWatchMetricAlarm_basic'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test .//aws -v -run=TestAccAWSCloudWatchMetricAlarm_basic -timeout 120m
=== RUN   TestAccAWSCloudWatchMetricAlarm_basic
--- PASS: TestAccAWSCloudWatchMetricAlarm_basic (55.58s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	56.088s
```

I've not read a single line of go source code before today, so please let me know if there's a neater way to add the region. Is there an "is in [list of regions]" comparison operator for strings? I didn't see one with a cursory google!

Thanks for making a cool project, I've spent a few days prototyping stuff in TF and I like it lot 👍

### CODE REVIEW

**Comment by kwerey** [comment]
No problem Brian, I've added those IDs.

**Comment by bflad** [comment]
Sorry I realized I didn't specifically answer your question here:
> Is there an "is in [list of regions]" comparison operator for strings? I didn't see one with a cursory google!

The [endpoints package in the AWS Go SDK](https://docs.aws.amazon.com/sdk-for-go/api/aws/endpoints/) does have constants and some helper functions which we could utilize to automate this region/partition handling/validation for us. We would greatly appreciate any pull requests that utilized either the region constants across the codebase or the helper functions. 😄

**Comment by bflad** [comment]
Thanks for removing those empty mappings (that was a bad recommendation on my part). I'm going to merge this in so this new region can potentially be used starting with the v1.8.0 release.

**Comment by kwerey** [comment]
No problem, I read the thread on that docs PR and went "yup, that's legit".

I'd love to see cloud integration tools move away from having to keep all these lists in their own codebases - if we end up committing to TF at my shop I'll try to get some work in on it.

**Comment by kwerey** [comment]
Sweet, I get 'contributor' by my name! \o/ Thanks for getting feedback in on this PR so quick, it's really neat to be able to just jump in and get something useful sorted out in a project in a matter of hours.

**Comment by bflad** [comment]
This has been released in [terraform-provider-aws version 1.8.0](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#180-january-29-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.

Important note: if you're planning on using `cn-northwest-1` S3 for backend state, this PR (or newer version of it) needs to be merged and released in Terraform core (which will be 0.11.3+): https://github.com/hashicorp/terraform/pull/17216

**Pull request merged**
