### PR TITLE
New resource: aws_apigatewayv2_stage

### PR DESCRIPTION
**Pull request by ewbankkit**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" comments, they generate extra noise for pull request followers and do not help prioritize the request

Another resource for #7004.

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
FEATURES:

* New Resource: aws_api_gateway_v2_stage (#7004)
```

Output from acceptance testing:

```console
$ make testacc TEST=./aws/ TESTARGS='-run=TestAccAWSAPIGateway2Stage_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws/ -v -parallel 20 -run=TestAccAWSAPIGateway2Stage_ -timeout 120m
=== RUN   TestAccAWSAPIGateway2Stage_basic
=== PAUSE TestAccAWSAPIGateway2Stage_basic
=== RUN   TestAccAWSAPIGateway2Stage_AccessLogSettings
=== PAUSE TestAccAWSAPIGateway2Stage_AccessLogSettings
=== RUN   TestAccAWSAPIGateway2Stage_ClientCertificateIdAndDescription
=== PAUSE TestAccAWSAPIGateway2Stage_ClientCertificateIdAndDescription
=== RUN   TestAccAWSAPIGateway2Stage_DefaultRouteSettings
=== PAUSE TestAccAWSAPIGateway2Stage_DefaultRouteSettings
=== RUN   TestAccAWSAPIGateway2Stage_Deployment
=== PAUSE TestAccAWSAPIGateway2Stage_Deployment
=== RUN   TestAccAWSAPIGateway2Stage_RouteSettings
=== PAUSE TestAccAWSAPIGateway2Stage_RouteSettings
=== RUN   TestAccAWSAPIGateway2Stage_StageVariables
=== PAUSE TestAccAWSAPIGateway2Stage_StageVariables
=== RUN   TestAccAWSAPIGateway2Stage_Tags
=== PAUSE TestAccAWSAPIGateway2Stage_Tags
=== CONT  TestAccAWSAPIGateway2Stage_basic
=== CONT  TestAccAWSAPIGateway2Stage_Tags
=== CONT  TestAccAWSAPIGateway2Stage_StageVariables
=== CONT  TestAccAWSAPIGateway2Stage_RouteSettings
=== CONT  TestAccAWSAPIGateway2Stage_Deployment
=== CONT  TestAccAWSAPIGateway2Stage_DefaultRouteSettings
=== CONT  TestAccAWSAPIGateway2Stage_ClientCertificateIdAndDescription
=== CONT  TestAccAWSAPIGateway2Stage_AccessLogSettings
--- PASS: TestAccAWSAPIGateway2Stage_basic (31.82s)
--- PASS: TestAccAWSAPIGateway2Stage_RouteSettings (32.55s)
--- PASS: TestAccAWSAPIGateway2Stage_DefaultRouteSettings (37.20s)
--- PASS: TestAccAWSAPIGateway2Stage_Deployment (38.77s)
--- PASS: TestAccAWSAPIGateway2Stage_StageVariables (41.24s)
--- PASS: TestAccAWSAPIGateway2Stage_ClientCertificateIdAndDescription (44.85s)
--- PASS: TestAccAWSAPIGateway2Stage_Tags (46.23s)
--- PASS: TestAccAWSAPIGateway2Stage_AccessLogSettings (84.62s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	84.660s
```

Currently based on https://github.com/terraform-providers/terraform-provider-aws/pull/8842, will need to rebase once that PR is merged.

### CODE REVIEW

**Comment by ewbankkit** [comment]
TODO
* Include https://github.com/terraform-providers/terraform-provider-aws/pull/9245 to test `deployment_id`

**Comment by ewbankkit** [comment]
Includes
* https://github.com/terraform-providers/terraform-provider-aws/pull/9245 for `aws_api_gateway_v2_deployment` tests

**Comment by ewbankkit** [comment]
Rebased to fix merge conflict.
Acceptance tests:

```console
$ make testacc TEST=./aws/ TESTARGS='-run=TestAccAWSAPIGateway2Stage_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws/ -v -parallel 20 -run=TestAccAWSAPIGateway2Stage_ -timeout 120m
=== RUN   TestAccAWSAPIGateway2Stage_basic
=== PAUSE TestAccAWSAPIGateway2Stage_basic
=== RUN   TestAccAWSAPIGateway2Stage_AccessLogSettings
=== PAUSE TestAccAWSAPIGateway2Stage_AccessLogSettings
=== RUN   TestAccAWSAPIGateway2Stage_ClientCertificateIdAndDescription
=== PAUSE TestAccAWSAPIGateway2Stage_ClientCertificateIdAndDescription
=== RUN   TestAccAWSAPIGateway2Stage_DefaultRouteSettings
=== PAUSE TestAccAWSAPIGateway2Stage_DefaultRouteSettings
=== RUN   TestAccAWSAPIGateway2Stage_Deployment
=== PAUSE TestAccAWSAPIGateway2Stage_Deployment
=== RUN   TestAccAWSAPIGateway2Stage_RouteSettings
=== PAUSE TestAccAWSAPIGateway2Stage_RouteSettings
=== RUN   TestAccAWSAPIGateway2Stage_StageVariables
=== PAUSE TestAccAWSAPIGateway2Stage_StageVariables
=== RUN   TestAccAWSAPIGateway2Stage_Tags
=== PAUSE TestAccAWSAPIGateway2Stage_Tags
=== CONT  TestAccAWSAPIGateway2Stage_basic
=== CONT  TestAccAWSAPIGateway2Stage_Tags
=== CONT  TestAccAWSAPIGateway2Stage_StageVariables
=== CONT  TestAccAWSAPIGateway2Stage_RouteSettings
=== CONT  TestAccAWSAPIGateway2Stage_Deployment
=== CONT  TestAccAWSAPIGateway2Stage_DefaultRouteSettings
=== CONT  TestAccAWSAPIGateway2Stage_ClientCertificateIdAndDescription
=== CONT  TestAccAWSAPIGateway2Stage_AccessLogSettings
--- PASS: TestAccAWSAPIGateway2Stage_RouteSettings (32.88s)
--- PASS: TestAccAWSAPIGateway2Stage_DefaultRouteSettings (38.23s)
--- PASS: TestAccAWSAPIGateway2Stage_Deployment (38.57s)
--- PASS: TestAccAWSAPIGateway2Stage_basic (41.96s)
--- PASS: TestAccAWSAPIGateway2Stage_StageVariables (42.46s)
--- PASS: TestAccAWSAPIGateway2Stage_Tags (45.56s)
--- PASS: TestAccAWSAPIGateway2Stage_ClientCertificateIdAndDescription (46.07s)
--- PASS: TestAccAWSAPIGateway2Stage_AccessLogSettings (64.36s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	64.402s
```

**Comment by ewbankkit** [comment]
Re-ran acceptance tests:

```console
$ make testacc TEST=./aws/ TESTARGS='-run=TestAccAWSAPIGateway2Stage_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws/ -v -parallel 20 -run=TestAccAWSAPIGateway2Stage_ -timeout 120m
=== RUN   TestAccAWSAPIGateway2Stage_basic
=== PAUSE TestAccAWSAPIGateway2Stage_basic
=== RUN   TestAccAWSAPIGateway2Stage_AccessLogSettings
=== PAUSE TestAccAWSAPIGateway2Stage_AccessLogSettings
=== RUN   TestAccAWSAPIGateway2Stage_ClientCertificateIdAndDescription
=== PAUSE TestAccAWSAPIGateway2Stage_ClientCertificateIdAndDescription
=== RUN   TestAccAWSAPIGateway2Stage_DefaultRouteSettings
=== PAUSE TestAccAWSAPIGateway2Stage_DefaultRouteSettings
=== RUN   TestAccAWSAPIGateway2Stage_Deployment
=== PAUSE TestAccAWSAPIGateway2Stage_Deployment
=== RUN   TestAccAWSAPIGateway2Stage_RouteSettings
=== PAUSE TestAccAWSAPIGateway2Stage_RouteSettings
=== RUN   TestAccAWSAPIGateway2Stage_StageVariables
=== PAUSE TestAccAWSAPIGateway2Stage_StageVariables
=== RUN   TestAccAWSAPIGateway2Stage_Tags
=== PAUSE TestAccAWSAPIGateway2Stage_Tags
=== CONT  TestAccAWSAPIGateway2Stage_basic
=== CONT  TestAccAWSAPIGateway2Stage_Tags
=== CONT  TestAccAWSAPIGateway2Stage_StageVariables
=== CONT  TestAccAWSAPIGateway2Stage_RouteSettings
=== CONT  TestAccAWSAPIGateway2Stage_Deployment
=== CONT  TestAccAWSAPIGateway2Stage_DefaultRouteSettings
=== CONT  TestAccAWSAPIGateway2Stage_ClientCertificateIdAndDescription
=== CONT  TestAccAWSAPIGateway2Stage_AccessLogSettings
--- PASS: TestAccAWSAPIGateway2Stage_RouteSettings (27.10s)
--- PASS: TestAccAWSAPIGateway2Stage_Deployment (30.78s)
--- PASS: TestAccAWSAPIGateway2Stage_basic (35.01s)
--- PASS: TestAccAWSAPIGateway2Stage_ClientCertificateIdAndDescription (36.80s)
--- PASS: TestAccAWSAPIGateway2Stage_Tags (43.35s)
--- PASS: TestAccAWSAPIGateway2Stage_StageVariables (43.38s)
--- PASS: TestAccAWSAPIGateway2Stage_DefaultRouteSettings (45.93s)
--- PASS: TestAccAWSAPIGateway2Stage_AccessLogSettings (96.57s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	96.596s
```

**Comment by mvisonneau** [comment]
@ewbankkit, would you mind rebasing your branch please? 🙏

**Comment by ewbankkit** [comment]
After merge of https://github.com/terraform-providers/terraform-provider-aws/pull/9245, incorporate all the feedback:
* Migrate to Terraform provider SDK
* Change resource name to `aws_apigatewayv2_blah`; Rename source files
* Remove `sidebar_current` from documentation
* Add `subcategory: "API Gateway v2 (WebSocket and HTTP APIs)"` to documentation
* Change function names to `ApiGatewayV2`
* Add `_disappears` acceptance test
* Use `multierror` in any test sweeper

**Comment by ewbankkit** [comment]
Renamed resource to `aws_apigatewayv2_stage`.
Re-ran acceptance tests:

```console
$ make testacc TEST=./aws/ TESTARGS='-run=TestAccAWSAPIGatewayV2Stage_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws/ -v -count 1 -parallel 20 -run=TestAccAWSAPIGatewayV2Stage_ -timeout 120m
=== RUN   TestAccAWSAPIGatewayV2Stage_basic
=== PAUSE TestAccAWSAPIGatewayV2Stage_basic
=== RUN   TestAccAWSAPIGatewayV2Stage_disappears
=== PAUSE TestAccAWSAPIGatewayV2Stage_disappears
=== RUN   TestAccAWSAPIGatewayV2Stage_AccessLogSettings
=== PAUSE TestAccAWSAPIGatewayV2Stage_AccessLogSettings
=== RUN   TestAccAWSAPIGatewayV2Stage_ClientCertificateIdAndDescription
=== PAUSE TestAccAWSAPIGatewayV2Stage_ClientCertificateIdAndDescription
=== RUN   TestAccAWSAPIGatewayV2Stage_DefaultRouteSettings
=== PAUSE TestAccAWSAPIGatewayV2Stage_DefaultRouteSettings
=== RUN   TestAccAWSAPIGatewayV2Stage_Deployment
=== PAUSE TestAccAWSAPIGatewayV2Stage_Deployment
=== RUN   TestAccAWSAPIGatewayV2Stage_RouteSettings
=== PAUSE TestAccAWSAPIGatewayV2Stage_RouteSettings
=== RUN   TestAccAWSAPIGatewayV2Stage_StageVariables
=== PAUSE TestAccAWSAPIGatewayV2Stage_StageVariables
=== RUN   TestAccAWSAPIGatewayV2Stage_Tags
=== PAUSE TestAccAWSAPIGatewayV2Stage_Tags
=== CONT  TestAccAWSAPIGatewayV2Stage_basic
=== CONT  TestAccAWSAPIGatewayV2Stage_Deployment
=== CONT  TestAccAWSAPIGatewayV2Stage_Tags
=== CONT  TestAccAWSAPIGatewayV2Stage_StageVariables
=== CONT  TestAccAWSAPIGatewayV2Stage_RouteSettings
=== CONT  TestAccAWSAPIGatewayV2Stage_ClientCertificateIdAndDescription
=== CONT  TestAccAWSAPIGatewayV2Stage_DefaultRouteSettings
=== CONT  TestAccAWSAPIGatewayV2Stage_AccessLogSettings
=== CONT  TestAccAWSAPIGatewayV2Stage_disappears
--- PASS: TestAccAWSAPIGatewayV2Stage_disappears (25.02s)
--- PASS: TestAccAWSAPIGatewayV2Stage_basic (29.68s)
--- PASS: TestAccAWSAPIGatewayV2Stage_Deployment (37.20s)
--- PASS: TestAccAWSAPIGatewayV2Stage_RouteSettings (46.32s)
--- PASS: TestAccAWSAPIGatewayV2Stage_DefaultRouteSettings (47.29s)
--- PASS: TestAccAWSAPIGatewayV2Stage_Tags (47.70s)
--- PASS: TestAccAWSAPIGatewayV2Stage_ClientCertificateIdAndDescription (55.28s)
--- PASS: TestAccAWSAPIGatewayV2Stage_StageVariables (60.01s)
--- PASS: TestAccAWSAPIGatewayV2Stage_AccessLogSettings (73.02s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	73.068s
```

**Comment by ewbankkit** [comment]
Ready for review.

**Pull request merged**
