### PR TITLE
ses_identity_notification_topic: add support for include_original_headers

### LINKED ISSUE #4376: Include ability to request headers with ses_identity_notification_topic
[ses_identity_notification_topic](https://www.terraform.io/docs/providers/aws/r/ses_identity_notification_topic.html) does not appear to offer the ability to request headers with notifications.

This functionality is presented in the web console as:

image

And is available via the AWS cli command [`aws ses set-identity-headers-in-notifications-enabled`](https://docs.aws.amazon.com/cli/latest/reference/ses/set-identity-headers-in-notifications-enabled.html) (unfortunately it's not part of [`set-identity-notification-topic`](https://docs.aws.amazon.com/cli/latest/reference/ses/set-identity-notification-topic.html) which might be why it didn't make it into Terraform!)

Is this possible?

### PR DESCRIPTION
**Pull request by vaskevich**
Fixes #4376

Changes proposed in this pull request:

* Support setting whether SES includes original email headers in SNS notifications of the specified type ([reference](https://docs.aws.amazon.com/cli/latest/reference/ses/set-identity-headers-in-notifications-enabled.html))

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccAwsSESIdentityNotificationTopic'

==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./... -v -parallel 20 -run=TestAccAwsSESIdentityNotificationTopic -timeout 120m
?       github.com/terraform-providers/terraform-provider-aws   [no test files]
=== RUN   TestAccAwsSESIdentityNotificationTopic_basic
=== PAUSE TestAccAwsSESIdentityNotificationTopic_basic
=== CONT  TestAccAwsSESIdentityNotificationTopic_basic
--- PASS: TestAccAwsSESIdentityNotificationTopic_basic (25.00s)
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws       25.046s
```

### CODE REVIEW

**Comment by neilbartley** [comment]
@vaskevich would you have the time to update this? If not please yell and I'll get my merge boots on :)

**Comment by vaskevich** [comment]
Sure, updated.

**Comment by neilbartley** [comment]
Thanks @vaskevich.

Hopefully, this will get merged soon and cut out the only manual step in my proccess ⛏

**Comment by papluh** [comment]
Any updates on this?

**Comment by vaskevich** [comment]
It's ready to go on my end. Just need a maintainer to review and merge.

**Pull request merged**
