### PR TITLE
Adds Kinesis Stream Consumer resource and data source

### PR DESCRIPTION
**Pull request by robertstettner**
This adds the new feature of AWS Kinesis Stream Consumers, that allow for a dedicated consumer using enhanced fan-out.
https://docs.aws.amazon.com/streams/latest/dev/building-consumers.html

And: https://aws.amazon.com/about-aws/whats-new/2018/11/aws-lambda-supports-kinesis-data-streams-enhanced-fan-out-and-http2/

Changes proposed in this pull request:

* Adds `aws_kinesis_stream_consumer` as new resource
* Adds `aws_kinesis_stream_consumer` as new data source

Output from acceptance testing (still WIP):

```
$ make testacc TESTARGS='-run=TestAccKinesisStreamConsumer'

...
```

### CODE REVIEW

**Comment by coen-hyde** [comment]
@robertstettner is this still in development?

**Comment by cludden** [comment]
@robertstettner Any update on this?

**Comment by muthu-vgh** [comment]
just wondering if there is any movements on this ?

**Comment by robertstettner** [comment]
Sorry, I don't think I can continue with this feature. If anyone wants to take over, please do so. I'm closing this one.

**Comment by muthu-vgh** [comment]
@chris-whittick sad times, lol

**Comment by pgilad** [comment]
@robertstettner Can you please specify what is missing if someone would want to pick this up?

**Comment by rockycore** [comment]
I made a new PR for this [#10487](https://github.com/terraform-providers/terraform-provider-aws/pull/10487)

**Pull request closed without merging**
