### PR TITLE
Allow CAA record type

### PR DESCRIPTION
**Pull request by gazoakley**
Addresses https://github.com/terraform-providers/terraform-provider-aws/issues/1465

### CODE REVIEW

**Comment by Ninir** [comment]
Hey @gazoakley 

Thanks for the work. Could you update the version we use for AWS servies to 1.10.29, so that we are in sync with changes in the SDK?

Latest version added information, constant for CAA, etc. (https://github.com/aws/aws-sdk-go/releases)

Thanks!

**Comment by Ninir** [comment]
Hey @gazoakley 

I saw that you pushed the vendoring. Is it all ok for you? (looking at the WIP)

Thanks.

**Comment by gazoakley** [comment]
Hi @Ninir - I'm adding an acceptance test as well. Will remove WIP tag shortly

**Comment by gazoakley** [comment]
Acceptance tests run:

```
make testacc TEST=./aws TESTARGS='-run=TestAccAWSRoute53Record_caaSupport'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -run=TestAccAWSRoute53Record_caaSupport -timeout 120m
=== RUN   TestAccAWSRoute53Record_caaSupport
--- PASS: TestAccAWSRoute53Record_caaSupport (164.24s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	164.268s
```

**Comment by gazoakley** [comment]
Hi @Ninir - hopefully looking better now. I've also added a list of valid record types to the documentation

**Pull request merged**
