### PR TITLE
Sagemaker example of "deploy your own model"

### PR DESCRIPTION
**Pull request by jckuester**
***Please review only the [last commit](https://github.com/terraform-providers/terraform-provider-aws/pull/2585/commits/8b76f4941c06954d05451b8f34ba4a908aca48b9) of this PR, which contains the example itself (the other commits are from rebasing the referenced PRs below, which contain the new SageMaker resources).***

This example shows how to use the three new SageMaker resources 

* `resource_aws_sagemaker_model` (https://github.com/terraform-providers/terraform-provider-aws/pull/2478),
* `resource_aws_sagemaker_endpoint_configuration` (https://github.com/terraform-providers/terraform-provider-aws/pull/2477), and
* `resource_aws_sagemaker_endpoint` (https://github.com/terraform-providers/terraform-provider-aws/pull/2479)

to deploy your own model algorithm container.

This PR can only be merged once the referenced PRs above are merged, as this example depends on the three new resources.

### CODE REVIEW

**Comment by radeksimko** [comment]
Hi @jckuester 
I appreciate this is still WIP - just so you know we always prefer 1 resource per PR to keep diff small and easier to review. 😉 

Just let us know when it's ready for review and we can take a look.

**Comment by jckuester** [comment]
Hi @radeksimko 
Thanks. I know - I hope I read all of the developer guidelines :) This PR is the last 4 PRs that all depend on each other. The first three contain the new sagemaker resources and this last one the example (I rebased the branch of the PR on the other ones, so can the example working).

Actually, the first PR of the series is now ready to review (https://github.com/terraform-providers/terraform-provider-aws/pull/2478). I am looking fwd to your feedback :)

**Comment by bflad** [comment]
Hey @jckuester 👋 Thanks for submitting this -- since we merged a bunch of the required resources here with changes, this PR is showing conflicts with pretty much every previous file and requires a rebase. If you are interested in submitting this, please re-submit it with only the last commit against master so it can get reviewed. Thanks again.

**Comment by jckuester** [comment]
Ok, @bflad. Resubmitted and tested that the example is still working: https://github.com/terraform-providers/terraform-provider-aws/pull/9948

**Pull request closed without merging**
