### PR TITLE
autoscaling: set conflict between availability_zones and vpc_zone_identifier

### PR DESCRIPTION
**Pull request by bendrucker**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

This PR adds `ConflictsWith` to `vpc_zone_identifier`, ensuring that a user that has passed VPC subnet IDs does not also pass a set of AZ names. This configuration would have previously resulted in an error on apply and now will trigger and error during validation.

Relates to https://github.com/terraform-providers/terraform-provider-aws/issues/9622

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
Prevent `availability_zones` and `vpc_zone_identifier` from being specified together
```

### CODE REVIEW

**Comment by bflad** [comment]
Hi @bendrucker 👋 Thank you for submitting this change. Please note I've marked this as a breaking change, since it currently causes some existing acceptance testing to fail that previously succeeded:

```
--- FAIL: TestAccAWSAutoScalingGroup_classicVpcZoneIdentifier (4.08s)
    testing.go:669: Step 0 error: config is invalid: "vpc_zone_identifier": conflicts with availability_zones

--- FAIL: TestAccAWSAutoScalingGroup_emptyAvailabilityZones (23.59s)
    testing.go:669: Step 0 error: errors during apply:
        
        Error: "vpc_zone_identifier": conflicts with availability_zones
```

The test configurations with these are using empty lists with the arguments, e.g.

```hcl
resource "aws_autoscaling_group" "test" {
  min_size = 0
  max_size = 0

  availability_zones   = []
  launch_configuration = "${aws_launch_configuration.test.name}"
  vpc_zone_identifier  = ["${aws_subnet.test.id}"]
}
```

Which the resource code is designed to only pass elements when there is more than 0, e.g.

https://github.com/terraform-providers/terraform-provider-aws/blob/8a8845ed183d2f084f356cb8631d09870d05d340/aws/resource_aws_autoscaling_group.go#L533

The Terraform Plugin SDK `ConflictsWith` behavior strictly checks argument existence; not the final semantics of the given configuration values. Given that we probably should implement this at the schema level so it does return a plan-time validation error, at the cost of forcing operators to specify `null` for missing lists instead `[]`, I will put this our next major release milestone for future consideration.

**Comment by bendrucker** [comment]
Thank you! Rushed through this a bit and didn't have a chance to run the acceptance tests. Totally understand that this is breaking, I have a similar change or two (adding `ConflictsWith`) similarly queued up for the Google provider.

* Updated `TestAccAWSAutoScalingGroup_classicVpcZoneIdentifier` to not use an empty list for `vpc_zone_identifiers`
* Removed `TestAccAWSAutoScalingGroup_emptyAvailabilityZones`, which is now appears irrelevant

I can set up and actually run the tests later today.

It also seemed like `DiffSuppressFunc` wasn't necessary anymore but then started to doubt myself.

**Comment by bendrucker** [comment]
Verified that the remaining acceptance test passes:

```sh
make testacc TESTARGS='-run=TestAccAWSAutoScalingGroup_classicVpcZoneIdentifier'
```

**Comment by bendrucker** [comment]
Thank you!

**Pull request merged**
