### PR TITLE
Support EXTERNAL deployment controller for ECS

### LINKED ISSUE #8133: Add EXTERNAL to deployment_controller of ECS Service
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s)

* aws_ecs_service

### References

https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_DeploymentController.html

### PR DESCRIPTION
**Pull request by kumarappan-arumugam**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" comments, they generate extra noise for pull request followers and do not help prioritize the request

Fixes #8133

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
resource/aws_ecs_service: Add support for `EXTERNAL` deployment_controller
```

Changes:
- resource/aws_ecs_service: Add support for `EXTERNAL` deployment_controller

Output from acceptance testing:

```
$ AWS_PROFILE=terraform-dev-test make testacc TEST=./aws TESTARGS='-run=TestAccAWSEcsService_withDeploymentController_Type_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -parallel 20 -run=TestAccAWSEcsService_withDeploymentController_Type_ -timeout 120m
=== RUN   TestAccAWSEcsService_withDeploymentController_Type_CodeDeploy
=== PAUSE TestAccAWSEcsService_withDeploymentController_Type_CodeDeploy
=== RUN   TestAccAWSEcsService_withDeploymentController_Type_External
=== PAUSE TestAccAWSEcsService_withDeploymentController_Type_External
=== CONT  TestAccAWSEcsService_withDeploymentController_Type_CodeDeploy
=== CONT  TestAccAWSEcsService_withDeploymentController_Type_External
--- PASS: TestAccAWSEcsService_withDeploymentController_Type_External (191.92s)
--- PASS: TestAccAWSEcsService_withDeploymentController_Type_CodeDeploy (268.54s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	269.551s
```

### CODE REVIEW

**Comment by ludov04** [comment]
Any update on this PR??

**Comment by ewbankkit** [comment]
It looks like this is a duplicate of https://github.com/terraform-providers/terraform-provider-aws/pull/8134.

**Comment by ludov04** [comment]
Right, would be nice if one of them gets merged tho

**Comment by komlow** [comment]
Anyone can merge this PR or https://github.com/terraform-providers/terraform-provider-aws/pull/8134 ?
This feature was implemented on AWS about 10 month ago but we cannot use it yet with terraform.

**Comment by ludov04** [comment]
@bflad Looks like this PR is got burried, and forgotten
Lots of people are waiting for this feature

**Comment by aoskotsky-amplify** [comment]
Could this PR be revived?

**Comment by kumarappan-arumugam** [comment]
Fixed merge conflict, can someone please merge this? PR is a year old.

**Pull request merged**
