### PR TITLE
Resource aws athena workgroup

### PR DESCRIPTION
**Pull request by leppikallio**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates to #10085

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
Adding recursive_delete_option for aws_athena_workgroup resource
```

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccAWSAthenaWorkGroup'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./... -v -count 1 -parallel 20 -run=TestAccAWSAthenaWorkGroup -timeout 120m
?   	github.com/terraform-providers/terraform-provider-aws	[no test files]
=== RUN   TestAccAWSAthenaWorkGroup_basic
=== PAUSE TestAccAWSAthenaWorkGroup_basic
=== RUN   TestAccAWSAthenaWorkGroup_disappears
=== PAUSE TestAccAWSAthenaWorkGroup_disappears
=== RUN   TestAccAWSAthenaWorkGroup_Configuration_BytesScannedCutoffPerQuery
=== PAUSE TestAccAWSAthenaWorkGroup_Configuration_BytesScannedCutoffPerQuery
=== RUN   TestAccAWSAthenaWorkGroup_Configuration_EnforceWorkgroupConfiguration
=== PAUSE TestAccAWSAthenaWorkGroup_Configuration_EnforceWorkgroupConfiguration
=== RUN   TestAccAWSAthenaWorkGroup_Configuration_PublishCloudWatchMetricsEnabled
=== PAUSE TestAccAWSAthenaWorkGroup_Configuration_PublishCloudWatchMetricsEnabled
=== RUN   TestAccAWSAthenaWorkGroup_Configuration_ResultConfiguration_EncryptionConfiguration_SseS3
=== PAUSE TestAccAWSAthenaWorkGroup_Configuration_ResultConfiguration_EncryptionConfiguration_SseS3
=== RUN   TestAccAWSAthenaWorkGroup_Configuration_ResultConfiguration_EncryptionConfiguration_Kms
=== PAUSE TestAccAWSAthenaWorkGroup_Configuration_ResultConfiguration_EncryptionConfiguration_Kms
=== RUN   TestAccAWSAthenaWorkGroup_Configuration_ResultConfiguration_OutputLocation
=== PAUSE TestAccAWSAthenaWorkGroup_Configuration_ResultConfiguration_OutputLocation
=== RUN   TestAccAWSAthenaWorkGroup_Configuration_ResultConfiguration_OutputLocation_ForceDestroy
=== PAUSE TestAccAWSAthenaWorkGroup_Configuration_ResultConfiguration_OutputLocation_ForceDestroy
=== RUN   TestAccAWSAthenaWorkGroup_Description
=== PAUSE TestAccAWSAthenaWorkGroup_Description
=== RUN   TestAccAWSAthenaWorkGroup_State
=== PAUSE TestAccAWSAthenaWorkGroup_State
=== RUN   TestAccAWSAthenaWorkGroup_ForceDestroy
=== PAUSE TestAccAWSAthenaWorkGroup_ForceDestroy
=== RUN   TestAccAWSAthenaWorkGroup_Tags
=== PAUSE TestAccAWSAthenaWorkGroup_Tags
=== CONT  TestAccAWSAthenaWorkGroup_basic
=== CONT  TestAccAWSAthenaWorkGroup_Configuration_ResultConfiguration_OutputLocation
=== CONT  TestAccAWSAthenaWorkGroup_Tags
=== CONT  TestAccAWSAthenaWorkGroup_Configuration_ResultConfiguration_EncryptionConfiguration_SseS3
=== CONT  TestAccAWSAthenaWorkGroup_ForceDestroy
=== CONT  TestAccAWSAthenaWorkGroup_State
=== CONT  TestAccAWSAthenaWorkGroup_Description
=== CONT  TestAccAWSAthenaWorkGroup_Configuration_ResultConfiguration_OutputLocation_ForceDestroy
=== CONT  TestAccAWSAthenaWorkGroup_Configuration_PublishCloudWatchMetricsEnabled
=== CONT  TestAccAWSAthenaWorkGroup_Configuration_BytesScannedCutoffPerQuery
=== CONT  TestAccAWSAthenaWorkGroup_disappears
=== CONT  TestAccAWSAthenaWorkGroup_Configuration_EnforceWorkgroupConfiguration
=== CONT  TestAccAWSAthenaWorkGroup_Configuration_ResultConfiguration_EncryptionConfiguration_Kms
--- PASS: TestAccAWSAthenaWorkGroup_disappears (25.30s)
--- PASS: TestAccAWSAthenaWorkGroup_Configuration_ResultConfiguration_EncryptionConfiguration_SseS3 (29.73s)
--- PASS: TestAccAWSAthenaWorkGroup_basic (32.79s)
--- PASS: TestAccAWSAthenaWorkGroup_Description (45.51s)
--- PASS: TestAccAWSAthenaWorkGroup_Configuration_PublishCloudWatchMetricsEnabled (47.53s)
--- PASS: TestAccAWSAthenaWorkGroup_Configuration_EnforceWorkgroupConfiguration (47.57s)
--- PASS: TestAccAWSAthenaWorkGroup_Configuration_BytesScannedCutoffPerQuery (50.91s)
--- PASS: TestAccAWSAthenaWorkGroup_ForceDestroy (57.47s)
--- PASS: TestAccAWSAthenaWorkGroup_Tags (59.53s)
--- PASS: TestAccAWSAthenaWorkGroup_State (61.78s)
--- PASS: TestAccAWSAthenaWorkGroup_Configuration_ResultConfiguration_OutputLocation (63.52s)
--- PASS: TestAccAWSAthenaWorkGroup_Configuration_ResultConfiguration_OutputLocation_ForceDestroy (64.33s)
--- PASS: TestAccAWSAthenaWorkGroup_Configuration_ResultConfiguration_EncryptionConfiguration_Kms (71.83s)
PASS
```

### CODE REVIEW

**Comment by ewbankkit** [comment]
@leppikallio @teraken0509 This looks like the same functionality as https://github.com/terraform-providers/terraform-provider-aws/pull/10111 but implemented via the API `RecursiveDeleteOption` field.

**Comment by leppikallio** [comment]
> @leppikallio @teraken0509 This looks like the same functionality as #10111 but implemented via the API `RecursiveDeleteOption` field.

Oh, how embarrassing to even admit but I didn't notice the one and original from @teraken0509 which is obviously quite a bit more elegant way to achieve the goal.

Thank you @ewbankkit for pointing this out.

**Comment by ewbankkit** [comment]
@leppikallio Using the API-provided mechanism is simpler and means less code to maintain over the long term. Maybe use some of the ideas from #10111 (e.g. name the attribute `force_destroy` as that seems to be a convention in other resources and reusesome of the acceptance test cases)?

**Comment by leppikallio** [comment]
Based on comments from @ewbankkit I changed the optional feature to `force_destroy` instead of `recursive_delete_option`. 

Added test case inspired by @teraken0509 , [resource_aws_athena_workgroup_test.go](https://github.com/teraken0509/terraform-provider-aws/blob/feature/add-force_destroy-attribute-for-aws_athena_workgroup-resource/aws/resource_aws_athena_workgroup_test.go)

Updated the documentation / help page to reflect the change.

**Pull request merged**
