### PR TITLE
r/workspaces_directory - add attributes + fix tags

### LINKED ISSUE #13070: resource aws_workspaces_directory should return IDs of security groups created
_This issue was originally opened by @akozichev as hashicorp/terraform#24791. It was migrated here as a result of the [provider split](https://www.hashicorp.com/blog/upcoming-provider-changes-in-terraform-0-10/). The original body of the issue is below._
    
<hr>
    
When AD is associated with Workspaces by creating resource "aws_workspaces_directory" AWS will create 2 Security groups:
<controller_id>_workspacesMembers
<controller_id>_controllers
Would be helpful if we could get IDs of both groups when resource aws_workspaces_directory created.

### PR DESCRIPTION
**Pull request by DrFaust92**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #13070

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
resource_aws_workspaces_directory: add attributes for `workspace_security_group_id`, `iam_role_id`, `registration_code`, `directory_name`, `directory_type`, `customer_user_name`, `alias`, `ip_group_ids` and `dns_ip_addresses`
resource_aws_workspaces_directory: fix tagging
```

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccAwsWorkspacesDirectory'
    --- PASS: TestAccAwsWorkspacesDirectory/basic (837.91s)
    --- PASS: TestAccAwsWorkspacesDirectory/disappears (673.38s)
    --- PASS: TestAccAwsWorkspacesDirectory/subnetIds (682.54s)
    --- PASS: TestAccAwsWorkspacesDirectory/tags (837.28s)
```

### CODE REVIEW

**Comment by DrFaust92** [comment]
@ewbankkit , i've created a separate tags test case and noticed that tags aren't removed properly only added.
i think it has got to do with the code here: https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/internal/keyvaluetags/workspaces_tags.go#L35

i think its missing some diff logic and actually remove those tags.

thoughts?

**Comment by ewbankkit** [comment]
@DrFaust92 I think you're correct, if my comment

> // https://docs.aws.amazon.com/workspaces/latest/api/API_CreateTags.html
> // "If you want to add new tags to a set of existing tags, you must submit all of the existing tags along with the new ones."
> // This doesn't in fact seem to be correct..

is right.
There is discussion in https://github.com/terraform-providers/terraform-provider-aws/pull/11645 that may be relevant, and maybe do some testing with https://github.com/terraform-providers/terraform-provider-aws/pull/13039?

**Comment by DrFaust92** [comment]
generating the workspaces tagging func with the internal keyvalues package seems to have fixed it.

i'll open a follow up to amend tests for other workspaces resources (spoiler, I tested it for the other ones first because it took less time to run an validate)

**Comment by ewbankkit** [comment]
Verified acceptance tests:

```console
$ make testacc TEST=./aws/ TESTARGS='-run=TestAccAwsWorkspacesDirectory'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws/ -v -count 1 -parallel 20 -run=TestAccAwsWorkspacesDirectory -timeout 120m
=== RUN   TestAccAwsWorkspacesDirectory
=== RUN   TestAccAwsWorkspacesDirectory/subnetIds
=== RUN   TestAccAwsWorkspacesDirectory/tags
=== RUN   TestAccAwsWorkspacesDirectory/basic
=== RUN   TestAccAwsWorkspacesDirectory/disappears
--- PASS: TestAccAwsWorkspacesDirectory (2571.63s)
    --- PASS: TestAccAwsWorkspacesDirectory/subnetIds (630.31s)
    --- PASS: TestAccAwsWorkspacesDirectory/tags (663.52s)
    --- PASS: TestAccAwsWorkspacesDirectory/basic (670.33s)
    --- PASS: TestAccAwsWorkspacesDirectory/disappears (607.46s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	2571.667s
```

**Pull request merged**
