### PR TITLE
r/ecs_service: Add EXTERNAL to deployment_controller

### LINKED ISSUE #8133: Add EXTERNAL to deployment_controller of ECS Service
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s)

* aws_ecs_service

### References

https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_DeploymentController.html

### PR DESCRIPTION
**Pull request by atsushi-ishibashi**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" comments, they generate extra noise for pull request followers and do not help prioritize the request

Fixes #8133

Changes proposed in this pull request:

* aws_ecs_service

### CODE REVIEW

**Comment by ewbankkit** [comment]
It looks like this is a duplicate of https://github.com/terraform-providers/terraform-provider-aws/pull/8652.

**Comment by adenot** [comment]
Can we get this merged? It seems like a very small change but huge impact on those trying to use TaskSet for deployments on a "real" blue-green fashion

**Comment by aoskotsky-amplify** [comment]
Can somebody merge this?

**Comment by aoskotsky-amplify** [comment]
@bflad Could somebody look into this PR?

**Comment by aoskotsky-amplify** [comment]
@bflad Could somebody take a look at this PR? It's a very tiny change but it has been over a year now. It would help us out a lot. Thanks

**Comment by tehmaspc** [comment]
If anyone can share how they plan on using this feature in an automated - i.e. CI/CD - mechanism - I'd love to hear it! Cheers!

**Pull request merged**
