### PR TITLE
 r/aws_ec2_client_vpn_endpoint: Reworked endpoint resource to include network associations and authorization rules as parameters

### LINKED ISSUE #7494: Client VPN Endpoint - Add Ingress Authorisation
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

This request asks for the ability to automate the set up of ingress authorisation for a Client VPN endpoint.

The recently added Client VPN support creates the endpoint but does not go so far as to allow automation of the authorisation rules to grant the client access to areas of the network. Authorisation for Client VPN is described in the AWS [Client VPN Authorisation Rules documentation](https://docs.aws.amazon.com/vpn/latest/clientvpn-admin/cvpn-working-rules.html).

> Authorization rules act as ﬁrewall rules that grant access to networks. You should have an authorization rule for each network for which you want to grant access. 

### New or Affected Resource(s)

This relates to the aws_ec2_client_vpn_endpoint resource, recently added to 1.58.0 by @slapula under #7009.

### References
* https://docs.aws.amazon.com/vpn/latest/clientvpn-admin/cvpn-working-rules.html
* #7009

### LINKED ISSUE #7495: Client VPN Endpoint - Allow Custom Security Groups
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

This request asks for custom (non-VPC default) security groups to be associated with the Client VPN endpoint.

The Target Network configuration of the recently added Client VPN support allows the configuration of the 'landing subnets' for connected clients but does not allow custom security groups to be specified and retains the default settings for a Client VPN endpoint:

> The VPC's default security group is automatically applied for the subnet association. You can modify the security group after associating the subnet.

See the [Client VPN Target Network documentation](https://docs.aws.amazon.com/vpn/latest/clientvpn-admin/cvpn-working-target.html#cvpn-working-target-apply) for more information.

### New or Affected Resource(s)

This relates to the aws_ec2_client_vpn_endpoint and aws_ec2_client_vpn_network_association resources, recently added to 1.58.0 by @slapula under #7009.

### References
* https://docs.aws.amazon.com/vpn/latest/clientvpn-admin/cvpn-working-target.html
* #7009

### PR DESCRIPTION
**Pull request by slapula**
Fixes #7494

Changes proposed in this pull request:

* Removed `aws_ec2_client_vpn_network_association` resource and worked it into the `aws_ec2_client_vpn_endpoint` resource
* Added `security_groups` sub-parameter to `network_association` parameter
* Added `authorization_rule` parameter

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccAwsEc2ClientVpnEndpoint_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./... -v -parallel 20 -run=TestAccAwsEc2ClientVpnEndpoint_ -timeout 120m
?   	github.com/terraform-providers/terraform-provider-aws	[no test files]
=== RUN   TestAccAwsEc2ClientVpnEndpoint_basic
--- PASS: TestAccAwsEc2ClientVpnEndpoint_basic (19.03s)
=== RUN   TestAccAwsEc2ClientVpnEndpoint_msAD
--- PASS: TestAccAwsEc2ClientVpnEndpoint_msAD (1752.23s)
=== RUN   TestAccAwsEc2ClientVpnEndpoint_withLogGroup
--- PASS: TestAccAwsEc2ClientVpnEndpoint_withLogGroup (30.81s)
=== RUN   TestAccAwsEc2ClientVpnEndpoint_withDNSServers
--- PASS: TestAccAwsEc2ClientVpnEndpoint_withDNSServers (27.35s)
=== RUN   TestAccAwsEc2ClientVpnEndpoint_withNetworkAssociation
--- PASS: TestAccAwsEc2ClientVpnEndpoint_withNetworkAssociation (513.87s)
=== RUN   TestAccAwsEc2ClientVpnEndpoint_withAuthorizationRules
--- PASS: TestAccAwsEc2ClientVpnEndpoint_withAuthorizationRules (496.18s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	2839.502s
```

### CODE REVIEW

**Comment by slapula** [comment]
Reviews are appreciated but, at the moment, this is a WIP.  @bflad @Bwanabanana

After thinking about it and reviewing outstanding issues around the Client VPN resources,  I've decided to make authorization rules and network associations as parameters to `aws_ec2_client_vpn_endpoint`.  This makes more sense now that I've dug a little deeper.  Authorization rules are tied to the endpoint's associated networks and it didn't make sense to manage network associations outside of the endpoint resource when the authorization rule depend on them.  The authorization rules themselves are tied specifically to endpoints meaning that they are not tracked at all by a separate ID just the endpoint ID (that makes them a bad candidate for stand-alone resource imo).  All of that led me to this PR.

**Comment by Bwanabanana** [comment]
Can't comment on the code as I don't have an understanding of the terraform internals but, reading the documentation changes, the approach looks sensible to me. Thanks!

**Comment by slapula** [comment]
@dimisjim Yeah, I actually had a separate resource written for that when I realized these features should be consolidated into the endpoint resource.  I'm tied up on other projects at the moment but when I have some free time I'll definitely look into it.

**Comment by slapula** [comment]
@dimisjim @bflad Added the ability to manage routes within the VPN Endpoint resource: 
```
$ make testacc TESTARGS='-run=TestAccAwsEc2ClientVpnEndpoint_withRoutes'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./... -v -parallel 20 -run=TestAccAwsEc2ClientVpnEndpoint_withRoutes -timeout 120m
?   	github.com/terraform-providers/terraform-provider-aws	[no test files]
=== RUN   TestAccAwsEc2ClientVpnEndpoint_withRoutes
--- PASS: TestAccAwsEc2ClientVpnEndpoint_withRoutes (642.04s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	642.061s
```

**Comment by dimisjim** [comment]
> @dimisjim @bflad Added the ability to manage routes within the VPN Endpoint resource:
> 
> ```
> $ make testacc TESTARGS='-run=TestAccAwsEc2ClientVpnEndpoint_withRoutes'
> ==> Checking that code complies with gofmt requirements...
> TF_ACC=1 go test ./... -v -parallel 20 -run=TestAccAwsEc2ClientVpnEndpoint_withRoutes -timeout 120m
> ?   	github.com/terraform-providers/terraform-provider-aws	[no test files]
> === RUN   TestAccAwsEc2ClientVpnEndpoint_withRoutes
> --- PASS: TestAccAwsEc2ClientVpnEndpoint_withRoutes (642.04s)
> PASS
> ok  	github.com/terraform-providers/terraform-provider-aws/aws	642.061s
> ```

@slapula That's awesome! Let's merge!

**Comment by bflad** [comment]
_If_ a Terraform resource is to be removed, it should follow these steps so it can properly be deprecated so operators are aware of the breaking change and later removed in a major version update: https://www.terraform.io/docs/extend/best-practices/deprecations.html#provider-data-source-or-resource-removal

Decisions like these should be performed in a proposal issue so the community can understand why a breaking change is necessary, have the opportunity to potentially weigh in between various options, and see design sketches of configuration and workflow changes that may eventually wind up documented in an upgrade guide.

**Comment by dimisjim** [comment]
@bflad Are we able to merge now for the 2.6.0 release?

**Comment by giuliocalzolari** [comment]
@bflad Are we able to merge now for the 2.10.0 release?
the original `aws_ec2_client_vpn_endpoint` without `authorization_rule` and `route` required to do some manual configuration! could be awesome to have a complete toolset to configure the client vpn

**Comment by bryanlikes** [comment]
What else do we need to make progress on this?

**Comment by giuliocalzolari** [comment]
AWS recently released the full support of Client VPN with CloudFormation
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-clientvpnroute.html

@bflad  can we merge this PR in order to have feature parity with CloudFormation?
Cheers

**Comment by giuliocalzolari** [comment]
@aeschright  any luck?

**Comment by drankard** [comment]
Any progress here ?

**Comment by TommyM** [comment]
Any update on when this will be merged?

**Comment by slapula** [comment]
@bflad @aeschright I removed the parts that delete the network_authorization resource. This should just be considered a feature addition now. Is there anything else I can do to help move this along?

**Comment by borisroman** [comment]
Hi @aeschright 

Thanks for your comment. How's the internal discussion going? As @slapula mentioned here (https://github.com/terraform-providers/terraform-provider-aws/pull/7564#issuecomment-524637114) it is not a breaking change anymore as the deletion of the network_authorization resource has been excluded from this PR, the PR only contains additions now.

Would you be so kind to reconsider merging this?

Thanks in advance,
Boris

**Comment by dcw77** [comment]
Also missing from the functionality in aws_ec2_client_vpn_endpoint is the ability to select multiple authentication options to make use of MFA.

Also the route table cannot be updated along with the issue tracked here

**Comment by rabidscorpio** [comment]
@slapula Any way you can fix the failing tests and the conflicting files so we can get the terraform team to merge this?  Cheers!

**Comment by Rakhmanov** [comment]
Please remove breaking-change label. This has been reworked by author to not have any.

**Comment by trebidav** [comment]
I would like to see this one merged too! Please!

**Comment by jaredtkatz** [comment]
Ugh, let's get this PR merged. Are there any alternative methods of authorizing ingresses to Client VPN Endpoints without the proposed approach of parameterizing `aws_ec2_client_vpn_endpoint`? Do I really have to manually create the ingress authorizations from the AWS console, CLI, etc.?

**Comment by connor-tyndall** [comment]
+1

**Comment by AdamiHamza** [comment]
+1

**Comment by gdavison** [comment]
Hi @slapula. Thanks for the PR and our apologies for the delay on addressing this.

This functionality would be better implemented with separate resources instead of inline in `aws_ec2_client_vpn_endpoint`. This would allow for greater flexibility for some use cases.

Networking especially can sometimes have different stakeholders managing different parts of the infrastructure, with perhaps a core network team managing the VPN itself, and other teams managing the connections into their infrastructure. These teams could have separate Terraform states, which would require separate resources.

Defining them inline could also limit flexibility in cases where, for example, the number of subnets is not known beforehand.

A case could be made for allowing a simple case where these are defined inline, but also creating the standalone resource for more complex cases. However, this multiples the efforts for maintenance. It can also cause confusion for practitioners, especially if they try to combine the two methods and get unexpected results.

**Comment by gdavison** [comment]
Hi @slapula. I will finish up this PR. If you'd like to continue, please let me know by Monday, 22 June

**Pull request merged**
