### PR TITLE
resource/aws_elasticsearch_domain: Future proof new log type values in order to support the new `AUDIT_LOGS` log type

### LINKED ISSUE #15217: resource/aws_elasticsearch_domain: Support audit logging
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

> Amazon Elasticsearch Service now offers a detailed audit log of all Elasticsearch requests. Audit Logs allows customers to record a trail of all user actions, helping meet compliance regulations, improving the overall security posture and providing evidence for security investigations. 
>
> Amazon Elasticsearch Service Audit Logs allows customers to log all of their user activity on their Elasticsearch clusters, including keeping a history of user authentication success and failures, logging all requests to Elasticsearch, modifications to indices, recording incoming search queries and much more. Audit Logs provides a default configuration that covers a popular set of user actions to be tracked. Administrators can further configure and fine tune the settings to meet their needs. Audit Logs is integrated with Fine Grained Access Control, allowing you the ability to log access or modification requests to sensitive documents or fields, to meet any compliance requirements. Once configured, Audit Logs will be continuously streamed to CloudWatch Logs and can be further analyzed there. Audit Logs settings can be changed at any time and are automatically updated.

Requires aws/aws-sdk-go v1.34.26

### New or Affected Resource(s)

* aws_elasticsearch_domain

### Potential Terraform Configuration

```hcl
resource "aws_elasticsearch_domain" "example" {
  # .. other configuration ...

  log_publishing_options {
    cloudwatch_log_group_arn = aws_cloudwatch_log_group.example.arn
    log_type                 = "AUDIT_LOGS"
  }
}
```

### References

* https://aws.amazon.com/about-aws/whats-new/2020/09/audit-logs-launch/
* https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/audit-logs.htm

### PR DESCRIPTION
**Pull request by reedloden**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #15217

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
ENHANCEMENTS

* resource/aws_elasticsearch_domain: Add `AUDIT_LOGS` as a possible log type [GH-15218]
```

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccAWSElasticSearchDomain_LogPublishingOptions'

... [unfortunately, don't have a set up testing environment for this]
```

### CODE REVIEW

**Comment by reedloden** [comment]
Note this requires aws/aws-sdk-go v1.34.26 to actually work. https://github.com/terraform-providers/terraform-provider-aws/pull/15123

**Comment by anGie44** [comment]
Hi @reedloden, thank you for creating this PR! With the SDK update we'll have to add one additional update in the "log_type" definition w/in the resource's schema as this field has a validation function in place which checks that the provided input value matches an item in the list of possible log types - currently the list of valid types includes the SDK enums:
```
elasticsearch.LogTypeIndexSlowLogs,
elasticsearch.LogTypeSearchSlowLogs,
elasticsearch.LogTypeEsApplicationLogs,
```
we could add the new "AuditLogs" enum available in the SDK update or better yet replace the explicit string array seen [here](https://github.com/terraform-providers/terraform-provider-aws/blob/27308a5bc7c9a13b042f891dcf856bc820e6d9b6/aws/resource_aws_elasticsearch_domain.go#L369) with `elasticsearchdomain.LogType_Values()` provided by the SDK so that all possible values are included, making long-term maintenance a bit easier.

**Comment by bflad** [comment]
Just merged in the AWS Go SDK update so updating the validation to `elasticsearchdomain.LogType_Values()` will enable this now. 👍

**Comment by reedloden** [comment]
@anGie44 My late night grep mad skillz missed that somehow. My apologies! Good call on just changing this to use the `LogType_Values()` function (and thanks for the SDK update, @bflad). I have updated my commit. However, I don't have a good working AWS test environment to test this change, unfortunately.

**Comment by anGie44** [comment]
No worries @reedloden, changes look great! If you don't mind, I can follow-up with a commit to this PR to add acceptance testing around validating the changes to `log_type` 👍

**Comment by reedloden** [comment]
@anGie44 Sounds good, and many thanks!

**Comment by reedloden** [comment]
`TestAccAWSElasticSearchDomain_LogPublishingOptions` already tests the `INDEX_SLOW_LOGS` log type. Would it make sense to just convert that to a variable and loop through all four possible options to ensure they work?

**Comment by anGie44** [comment]
@reedloden, for this attribute it would be best to create a separate test as different configurations are required for the different logging types. in my initial testing, I found that `AUDIT_LOGS` type required `AdvancedSecurityOptions` configured while `INDEX_SLOW_LOGS`, for example, do not.

**Review by anGie44 — APPROVED** [review]
Thanks again @reedloden  🚀 
Output of acceptance tests:
```
--- PASS: TestAccAWSElasticSearchDomain_CognitoOptionsCreateAndRemove (1692.96s)
--- PASS: TestAccAWSElasticSearchDomain_duplicate (800.39s)
--- PASS: TestAccAWSElasticSearchDomainPolicy_basic (874.70s)
--- PASS: TestAccAWSElasticSearchDomain_basic (1016.79s)
--- PASS: TestAccAWSElasticSearchDomain_LogPublishingOptions_EsApplicationLogs (1051.29s)
--- PASS: TestAccAWSElasticSearchDomain_vpc (1067.70s)
--- PASS: TestAccAWSElasticSearchDomain_v23 (1157.55s)
--- PASS: TestAccAWSElasticSearchDomain_AdvancedSecurityOptions_UserDB (1286.58s)
--- PASS: TestAccAWSElasticSearchDomain_policy (647.51s)
--- PASS: TestAccAWSElasticSearchDomain_AdvancedSecurityOptions_IAM (1552.30s)
--- PASS: TestAccAWSElasticSearchDomain_AdvancedSecurityOptions_Disabled (1652.79s)
--- PASS: TestAccAWSElasticSearchDomain_LogPublishingOptions_AuditLogs (1860.44s)
--- PASS: TestAccAWSElasticSearchDomain_LogPublishingOptions_SearchSlowLogs (1880.79s)
--- PASS: TestAccAWSElasticSearchDomain_LogPublishingOptions_IndexSlowLogs (1930.89s)
--- PASS: TestAccAWSElasticSearchDomain_encrypt_at_rest_specify_key (947.75s)
--- PASS: TestAccAWSElasticSearchDomain_encrypt_at_rest_default_key (1096.99s)
--- PASS: TestAccAWSElasticSearchDomain_tags (931.47s)
--- PASS: TestAccAWSElasticSearchDomain_NodeToNodeEncryption (961.64s)
--- PASS: TestAccAWSElasticSearchDomain_RequireHTTPS (2016.41s)
--- PASS: TestAccAWSElasticSearchDomain_complex (2074.74s)
--- PASS: TestAccAWSElasticSearchDomain_WithVolumeType_Missing (1032.62s)
--- PASS: TestAccAWSElasticSearchDomain_CognitoOptionsUpdate (2528.93s)
--- PASS: TestAccAWSElasticSearchDomain_vpc_update (2616.26s)
--- PASS: TestAccAWSElasticSearchDomain_withDedicatedMaster (3121.48s)
--- PASS: TestAccAWSElasticSearchDomain_update (2003.60s)
--- PASS: TestAccAWSElasticSearchDomain_internetToVpcEndpoint (3686.54s)
--- PASS: TestAccAWSElasticSearchDomain_update_version (3329.99s)
--- PASS: TestAccAWSElasticSearchDomain_update_volume_type (3383.02s)
--- PASS: TestAccAWSElasticSearchDomain_ClusterConfig_ZoneAwarenessConfig (5046.46s)
--- PASS: TestAccAWSElasticSearchDomain_warm (5737.54s)
```

**Pull request merged**
