### PR TITLE
Sagemaker example of "deploy your own model"

### PR DESCRIPTION
**Pull request by jckuester**
This example shows how to use the three new SageMaker resources 

* `resource_aws_sagemaker_model` (https://github.com/terraform-providers/terraform-provider-aws/pull/2478),
* `resource_aws_sagemaker_endpoint_configuration` (https://github.com/terraform-providers/terraform-provider-aws/pull/2477), and
* `resource_aws_sagemaker_endpoint` (https://github.com/terraform-providers/terraform-provider-aws/pull/2479)

to deploy your own model algorithm container.

### CODE REVIEW

**Comment by bflad** [comment]
Hi @jckuester 👋  Apologies for the minor hassle, could you rebase this pull request against master and push to this pull request branch? This should trigger our automatic `examples/` testing and we can get it in when that's passing. Thanks for writing this up!

**Comment by jckuester** [comment]
Hi @bflad, rebase is done. Tests for Terraform 12 seem to fail, do you want me to change the example code to Terraform 12 conform?

**Comment by bflad** [comment]
@jckuester let's go ahead and get it 0.12 compliant and feel free to exclude it in the GitHub Action workflow file (https://github.com/terraform-providers/terraform-provider-aws/blob/a1a03e9da9136eca583c5e97abf27ec9ba9335ff/.github/workflows/examples.yml#L47-L49) for 0.11 if necessary since we'll be converting these in the next week or so anyways. Thanks!

**Comment by jckuester** [comment]
@bflad done.

**Pull request merged**
