### PR TITLE
Add support for 'redirect' and 'fixed-response' into lb_listener and lb_listener_rule

### LINKED ISSUE #5344: Add support for 'redirect' and 'fixed-response' into lb_listener_rule action type
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS added support for ELB Redirects, which is very useful to do an out-of-the-box experience for HTTP to HTTPS redirects without using an EC2 instance with an HTTP server listening in there.

It would be cool if you could add the support for this feature.

### New or Affected Resource(s)

* aws_lb_listener_rule

### Potential Terraform Configuration

```hcl
resource "aws_lb_listener_rule" "static" {
  listener_arn = "${aws_lb_listener.front_end.arn}"
  priority     = 100

  action {
    type = "redirect" # "fixed-response"
    # the rest has to be concepted
  }
}
```

### References

Official announcement: https://aws.amazon.com/about-aws/whats-new/2018/07/elastic-load-balancing-announces-support-for-redirects-and-fixed-responses-for-application-load-balancer/

Documentation:
* https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-listeners.html#redirect-actions
* https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-listeners.html#fixed-response-actions

### PR DESCRIPTION
**Pull request by jianyuan**
Fixes #5344.

Changes proposed in this pull request:

* Add support for `redirect` and `fixed-response` into `lb_listener`.
* Add support for `redirect` and `fixed-response` into `lb_listener_rule`.
* Updated docs.

Output from acceptance testing:

```
$ make testacc TEST=./aws TESTARGS='-run=TestAccAWSLBListener\(Rule\)?'

==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -run=TestAccAWSLBListener\(Rule\)? -timeout 120m
=== RUN   TestAccAWSLBListenerRule_basic
--- PASS: TestAccAWSLBListenerRule_basic (223.11s)
=== RUN   TestAccAWSLBListenerRuleBackwardsCompatibility
--- PASS: TestAccAWSLBListenerRuleBackwardsCompatibility (250.42s)
=== RUN   TestAccAWSLBListenerRule_redirect
--- PASS: TestAccAWSLBListenerRule_redirect (234.50s)
=== RUN   TestAccAWSLBListenerRule_fixedResponse
--- PASS: TestAccAWSLBListenerRule_fixedResponse (221.45s)
=== RUN   TestAccAWSLBListenerRule_updateRulePriority
--- PASS: TestAccAWSLBListenerRule_updateRulePriority (338.63s)
=== RUN   TestAccAWSLBListenerRule_changeListenerRuleArnForcesNew
--- PASS: TestAccAWSLBListenerRule_changeListenerRuleArnForcesNew (265.98s)
=== RUN   TestAccAWSLBListenerRule_multipleConditionThrowsError
--- PASS: TestAccAWSLBListenerRule_multipleConditionThrowsError (1.53s)
=== RUN   TestAccAWSLBListenerRule_priority
--- PASS: TestAccAWSLBListenerRule_priority (429.05s)
=== RUN   TestAccAWSLBListener_basic
--- PASS: TestAccAWSLBListener_basic (233.51s)
=== RUN   TestAccAWSLBListenerBackwardsCompatibility
--- PASS: TestAccAWSLBListenerBackwardsCompatibility (230.56s)
=== RUN   TestAccAWSLBListener_https
--- PASS: TestAccAWSLBListener_https (243.43s)
=== RUN   TestAccAWSLBListener_redirect
--- PASS: TestAccAWSLBListener_redirect (232.45s)
=== RUN   TestAccAWSLBListener_fixedResponse
--- PASS: TestAccAWSLBListener_fixedResponse (236.17s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	3140.836s

```

### CODE REVIEW

**Comment by melo** [comment]
Any idea when this PR will have a milestone associated?

Thank you

**Comment by bflad** [comment]
@melo it will generally receive a milestone right before merge unless its an important bug/crash fix

**Comment by bacoboy** [comment]
Unfortunately AWS doesn't support custom headers in the `fixed-response` (for like an HSTS header), but AWS support said they'd take it under advisement.  Just an FYI for the group...

**Comment by tdmalone** [comment]
Thanks so much @jianyuan!

**Comment by bflad** [comment]
This has been released in [version 1.33.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1330-august-22-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.

**Comment by stszap** [comment]
Thanks to all who contributed to add this feature, it is awesome! I can specify path = "#{path}" and terrafrom tries to create a listener but gets an error from aws:

* aws_lb_listener.external_http: Error creating LB Listener: InvalidLoadBalancerAction: The Path parameter must be a valid path, should start with a '/', and may contain up to one of each of these placeholders: '#{path}', '#{host}', '#{port}'.
	status code: 400, request id: febe9779-a6a8-11e8-9d4a-818ad1227d6

It works with path = "/#{path}" but maybe there should be an additional check for leading "/" just to fail faster?

**Pull request merged**
