### PR TITLE
Added appstream stack and fleet resources

### PR DESCRIPTION
**Pull request by wrschneider**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates #6508 

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
Adds minimal-viable product support for Appstream stack and fleet.
```

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccXXX'

...
```

### CODE REVIEW

**Comment by wrschneider** [comment]
How do I add the "help wanted" label?

**Comment by wrschneider** [comment]
Has anyone looked at this?

**Comment by DrFaust92** [comment]
Hey @wrschneider, first of all thank you for your contribution. 
To make reviewing for maintainers easier let's split this to PR per resource.

**Comment by wrschneider** [comment]
Closing this and replacing with two new PRs for each individual resource: stack and fleet go in different PRs

**Pull request closed without merging**
