### PR TITLE
tests/provider: Enable AWSAT004 check for CI

### PR DESCRIPTION
**Pull request by bflad**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Reference: https://github.com/terraform-providers/terraform-provider-aws/pull/14097

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
NONE
```

Output from acceptance testing: N/A (CI testing)

### CODE REVIEW

**Comment by bflad** [comment]
@YakDriver CI is passing for this. `All checks have passed` Are you sure you're looking at AWSAT004 and not AT004?

**Comment by YakDriver** [comment]
Fixes #8983

**Comment by bflad** [comment]
Just ran this again on master and its passing fine for me:

```
$ go install ./awsproviderlint
$ awsproviderlint -AWSAT004 ./aws
$ echo $?
0
```

**Comment by YakDriver** [comment]
Very sneaky of you to change the title from AT004 to AWSAT004 without GitHub even noticing!

**Pull request merged**
