### PR TITLE
New Resource: aws_lb_listener_certificate

### PR DESCRIPTION
**Pull request by Puneeth-n**
Fixes the acceptance tests in #2649 and closes #2649 and #1853. as requested in this comment [here](https://github.com/terraform-providers/terraform-provider-aws/issues/1853#issuecomment-351545878)

@oarmstrong  

1. Removed the `TLS` resource in tests because sometimes the tests were failing because of "malformed certificate". 
1. Fixed the segmentation fault
1. Add debug statements
1. Fixed the Destroy function to handle LB deletions in acceptance tests
1. Added a full cycle test

For some reason, I couldn't create a PR on the original branch hence creating the PR against master.

```
make testacc TESTARGS='-run=TestAccAwsLbListenerCertificate_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v -run=TestAccAwsLbListenerCertificate_ -timeout 120m
?   	github.com/terraform-providers/terraform-provider-aws	[no test files]
=== RUN   TestAccAwsLbListenerCertificate_basic
--- PASS: TestAccAwsLbListenerCertificate_basic (227.65s)
=== RUN   TestAccAwsLbListenerCertificate_cycle
--- PASS: TestAccAwsLbListenerCertificate_cycle (288.34s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	516.021s
```

### CODE REVIEW

**Comment by Puneeth-n** [comment]
@Ninir @radeksimko Can you please review it so that I and @oarmstrong see it to completion :)

**Comment by oarmstrong** [comment]
Should my PR #2649 be closed in favour of this one now then?

**Comment by Puneeth-n** [comment]
@oarmstrong feel free to to either close and work on this one or merge this to your branch and I close this one.

**Comment by ArmandSag** [comment]
Hello guys,

Great feature here ! Do you have any idea when this will be released ?

**Comment by Puneeth-n** [comment]
@radeksimko @Ninir Can you please review it?

**Comment by ArmandSag** [comment]
Does anyone plan to review this ? This is so important to have only one application load balancer with all the certificates. Tx !!

**Comment by egorchabala** [comment]
Pls, review, since this functionality can be very useful for many cases

**Comment by naveenacharya** [comment]
Is there anyway to get this feature up asap? We have been waiting for this since a long time.

**Comment by derBroBro** [comment]
We have also a issue which would be solved by this. Maybe someone else like @bflad can support?

**Comment by Puneeth-n** [comment]
@paddycarver  Sure. Will give it a spin and get back to you.

**Comment by Puneeth-n** [comment]
@paddycarver done!

```
TF_ACC=1 go test ./... -v -run=TestAccAwsLbListenerCertificate_ -timeout 120m -parallel=5
?   	github.com/terraform-providers/terraform-provider-aws	[no test files]
=== RUN   TestAccAwsLbListenerCertificate_basic
--- PASS: TestAccAwsLbListenerCertificate_basic (205.78s)
=== RUN   TestAccAwsLbListenerCertificate_cycle
--- PASS: TestAccAwsLbListenerCertificate_cycle (280.92s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	486.728s
```

**Comment by paddycarver** [comment]
Tests pass for me! Thanks!

**Comment by Puneeth-n** [comment]
@oarmstrong @paddycarver Thanks!

**Comment by oarmstrong** [comment]
Thanks for all your help @Puneeth-n on my original PR and for all the maintainers involved in getting this merged! Great work everyone!

**Comment by bflad** [comment]
This has been released in [version 1.10.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1100-february-24-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.

**Pull request merged**
