### PR TITLE
r/aws_appmesh_route: Add support for HTTP-header-based routing and route priorities

### LINKED ISSUE #9802: AWS App Mesh HTTP-header-based routing and route priorities
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS App Mesh HTTP-header-based routing and route priorities are now available.

### New or Affected Resource(s)

* [`aws_appmesh_route`](https://www.terraform.io/docs/providers/aws/r/appmesh_route.html)

### Potential Terraform Configuration

```hcl
resource "aws_appmesh_route" "serviceb" {
  name                = "serviceB-route"
  mesh_name           = "${aws_appmesh_mesh.simple.id}"
  virtual_router_name = "${aws_appmesh_virtual_router.serviceb.name}"

  spec {
    http_route {
      match {
        prefix = "/"
      }

      header {
        name = "clientRequestId"

        match {
          prefix = "123"
        }
      }

      action {
        weighted_target {
          virtual_node = "${aws_appmesh_virtual_node.serviceb1.name}"
          weight       = 90
        }

        weighted_target {
          virtual_node = "${aws_appmesh_virtual_node.serviceb2.name}"
          weight       = 10
        }
      }
    }
  }
}
```

### References

[Announcement](https://aws.amazon.com/about-aws/whats-new/2019/08/aws-app-mesh-supports-routing-based-on-http-headers-and-specifying-route-priorities/).
[User Guide](https://docs.aws.amazon.com//app-mesh/latest/userguide/route-http-headers.html).
[API Reference](https://docs.aws.amazon.com/app-mesh/latest/APIReference/API_HttpRouteHeader.html).

Available in [AWS SDK v1.23.2](https://github.com/aws/aws-sdk-go/releases/tag/v1.23.2).

AWS App Mesh roadmap:
* https://github.com/aws/aws-app-mesh-roadmap/issues/15
* https://github.com/aws/aws-app-mesh-roadmap/issues/77

Requires:
* https://github.com/terraform-providers/terraform-provider-aws/pull/9770

### PR DESCRIPTION
**Pull request by ewbankkit**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" comments, they generate extra noise for pull request followers and do not help prioritize the request

Closes #9802.
Replaces #9803.

Relevant commits have been cherry picked from #9468.

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
resource/aws_appmesh_route: Add `priority` and `header` attributes to support route priorities and HTTP-header-based routing
```

Output from acceptance testing:

```console
$ make testacc TEST=./aws TESTARGS='-run=TestAccAWSAppmesh'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -parallel 20 -run=TestAccAWSAppmesh -timeout 120m
=== RUN   TestAccAWSAppmesh
=== RUN   TestAccAWSAppmesh/Mesh
=== RUN   TestAccAWSAppmesh/Mesh/basic
=== RUN   TestAccAWSAppmesh/Mesh/egressFilter
=== RUN   TestAccAWSAppmesh/Mesh/tags
=== RUN   TestAccAWSAppmesh/Route
=== RUN   TestAccAWSAppmesh/Route/httpHeader
=== RUN   TestAccAWSAppmesh/Route/httpRoute
=== RUN   TestAccAWSAppmesh/Route/tcpRoute
=== RUN   TestAccAWSAppmesh/Route/routePriority
=== RUN   TestAccAWSAppmesh/Route/tags
=== RUN   TestAccAWSAppmesh/VirtualNode
=== RUN   TestAccAWSAppmesh/VirtualNode/basic
=== RUN   TestAccAWSAppmesh/VirtualNode/cloudMapServiceDiscovery
=== RUN   TestAccAWSAppmesh/VirtualNode/listenerHealthChecks
=== RUN   TestAccAWSAppmesh/VirtualNode/logging
=== RUN   TestAccAWSAppmesh/VirtualNode/tags
=== RUN   TestAccAWSAppmesh/VirtualRouter
=== RUN   TestAccAWSAppmesh/VirtualRouter/basic
=== RUN   TestAccAWSAppmesh/VirtualRouter/tags
=== RUN   TestAccAWSAppmesh/VirtualService
=== RUN   TestAccAWSAppmesh/VirtualService/tags
=== RUN   TestAccAWSAppmesh/VirtualService/virtualNode
=== RUN   TestAccAWSAppmesh/VirtualService/virtualRouter
--- PASS: TestAccAWSAppmesh (811.85s)
    --- PASS: TestAccAWSAppmesh/Mesh (101.56s)
        --- PASS: TestAccAWSAppmesh/Mesh/basic (19.32s)
        --- PASS: TestAccAWSAppmesh/Mesh/egressFilter (38.74s)
        --- PASS: TestAccAWSAppmesh/Mesh/tags (43.51s)
    --- PASS: TestAccAWSAppmesh/Route (206.73s)
        --- PASS: TestAccAWSAppmesh/Route/httpHeader (41.00s)
        --- PASS: TestAccAWSAppmesh/Route/httpRoute (41.44s)
        --- PASS: TestAccAWSAppmesh/Route/tcpRoute (40.93s)
        --- PASS: TestAccAWSAppmesh/Route/routePriority (41.19s)
        --- PASS: TestAccAWSAppmesh/Route/tags (42.16s)
    --- PASS: TestAccAWSAppmesh/VirtualNode (280.35s)
        --- PASS: TestAccAWSAppmesh/VirtualNode/basic (22.52s)
        --- PASS: TestAccAWSAppmesh/VirtualNode/cloudMapServiceDiscovery (122.72s)
        --- PASS: TestAccAWSAppmesh/VirtualNode/listenerHealthChecks (49.25s)
        --- PASS: TestAccAWSAppmesh/VirtualNode/logging (35.40s)
        --- PASS: TestAccAWSAppmesh/VirtualNode/tags (50.45s)
    --- PASS: TestAccAWSAppmesh/VirtualRouter (86.63s)
        --- PASS: TestAccAWSAppmesh/VirtualRouter/basic (35.42s)
        --- PASS: TestAccAWSAppmesh/VirtualRouter/tags (51.21s)
    --- PASS: TestAccAWSAppmesh/VirtualService (136.58s)
        --- PASS: TestAccAWSAppmesh/VirtualService/tags (57.21s)
        --- PASS: TestAccAWSAppmesh/VirtualService/virtualNode (40.82s)
        --- PASS: TestAccAWSAppmesh/VirtualService/virtualRouter (38.54s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	811.930s
```

### CODE REVIEW

**Comment by ewbankkit** [comment]
The errors when running the labeler action
```
##[error]HttpError: Resource not accessible by integration
##[error]Resource not accessible by integration
##[error]Node run failed with exit code 1
```
are the same as seen in other PRs, e.g. https://github.com/terraform-providers/terraform-provider-aws/pull/8259#issuecomment-521402785.

**Comment by aeschright** [comment]
@ewbankkit I think we can remove the GitHub action from our own repo as soon as someone copies the remaining items from https://github.com/terraform-providers/terraform-provider-aws/blob/master/.github/PULL_REQUEST_LABELS.yml to https://github.com/terraform-providers/terraform-provider-aws/blob/master/.hashibot.hcl#L431

**Comment by ewbankkit** [comment]
It seems that there is a known issue with the current GitHub _labeler_ action and PRs on forks: https://github.com/actions/labeler/issues/12.

**Comment by ewbankkit** [comment]
Closing in favor of #10075.

**Pull request closed without merging**
