### PR TITLE
[WIP] Update aws_sagemaker_instance resource

### PR DESCRIPTION
**Pull request by jckuester**
Changes proposed in this pull request:

* Adapt `aws_sagemaker_instance` resource to the latest API changes

### CODE REVIEW

**Comment by bflad** [comment]
Once #7585 and #7586 are merged we can take a look at this here. 👍

**Comment by bflad** [comment]
Hi @jckuester 👋 Are you planning on continuing work on this pull request? No worries if not, just trying to access when we should look at it again. Thanks.

**Comment by jckuester** [comment]
Yes, I will finish it. Just need a week or so to find some time.

**Comment by bflad** [comment]
This pull request has been superseded by #8880

**Pull request closed without merging**
