### PR TITLE
Add DataPipeline Resource Support

### LINKED ISSUE #1538: Support AWS Data Pipeline
It would be nice to be able to use AWS Data Pipeline with Terraform.
We are using it for dumping data from RDS to S3 every night.

http://docs.aws.amazon.com/datapipeline/latest/APIReference/Welcome.html

I need ability to create: 
 - S3DataNode
    - CSVDataFormat
    - TSVDataFormat
 - SqlDataNode
    - RdsDatabase
 - CopyActivity
    - Ec2Resource

Similar issue in core before split: hashicorp/terraform#4077

### PR DESCRIPTION
**Pull request by kterada0509**
Fixes #1538 

Changes proposed in this pull request:

* Add DataPipeline Resource
  * Support Pipeline Objects
    * default
    * [copy activity](https://docs.aws.amazon.com/datapipeline/latest/DeveloperGuide/dp-object-copyactivity.html)
    * Resources
      * [ec2 resource](https://docs.aws.amazon.com/datapipeline/latest/DeveloperGuide/dp-object-ec2resource.html)
    * Databases
      - [x] [Rds Database](https://docs.aws.amazon.com/datapipeline/latest/DeveloperGuide/dp-object-rdsdatabase.html)
    * Data nodes
      * [s3 data node](https://docs.aws.amazon.com/datapipeline/latest/DeveloperGuide/dp-object-s3datanode.html)
      * [sql data node](https://docs.aws.amazon.com/datapipeline/latest/DeveloperGuide/dp-object-sqldatanode.html)
    * [schedule](https://docs.aws.amazon.com/datapipeline/latest/DeveloperGuide/dp-object-schedule.html)

Output from acceptance testing:

```
$ make testacc TEST=./aws TESTARGS='-run=TestAccAWSDataPipeline_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -parallel 20 -run=TestAccAWSDataPipeline_ -timeout 120m
=== RUN   TestAccAWSDataPipeline_basic
=== PAUSE TestAccAWSDataPipeline_basic
=== RUN   TestAccAWSDataPipeline_copyActivity
=== PAUSE TestAccAWSDataPipeline_copyActivity
=== RUN   TestAccAWSDataPipeline_disappears
=== PAUSE TestAccAWSDataPipeline_disappears
=== CONT  TestAccAWSDataPipeline_basic
=== CONT  TestAccAWSDataPipeline_disappears
=== CONT  TestAccAWSDataPipeline_copyActivity
--- PASS: TestAccAWSDataPipeline_disappears (31.63s)
--- PASS: TestAccAWSDataPipeline_basic (36.01s)
--- PASS: TestAccAWSDataPipeline_copyActivity (37.50s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	37.557s
```

TODO
- [x] Add support serveral resources
- [x] Add documentation

### CODE REVIEW

**Comment by scraly** [comment]
Do you know when this feature will be released?
Thanks! :-)

**Comment by kterada0509** [comment]
Rerun test after `rebase master`
```
$ make testacc TEST=./aws TESTARGS='-run=TestAccAWSDataPipeline_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -parallel 20 -run=TestAccAWSDataPipeline_ -timeout 120m
=== RUN   TestAccAWSDataPipeline_basic
=== PAUSE TestAccAWSDataPipeline_basic
=== RUN   TestAccAWSDataPipeline_copyActivity
=== PAUSE TestAccAWSDataPipeline_copyActivity
=== RUN   TestAccAWSDataPipeline_disappears
=== PAUSE TestAccAWSDataPipeline_disappears
=== CONT  TestAccAWSDataPipeline_basic
=== CONT  TestAccAWSDataPipeline_disappears
=== CONT  TestAccAWSDataPipeline_copyActivity
--- PASS: TestAccAWSDataPipeline_disappears (35.32s)
--- PASS: TestAccAWSDataPipeline_copyActivity (41.50s)
--- PASS: TestAccAWSDataPipeline_basic (41.64s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	41.694s
```

**Comment by dave2535** [comment]
following

**Comment by noldar** [comment]
Nice work! Hope it will be merged soon!

**Comment by Szasza** [comment]
Thank you for the implementation, it is much appreciated.

@bflad do you happen to know when this will be merged?

Thank you in advance for the response.

**Comment by Szasza** [comment]
@kterada0509 apparently this now has a merge conflict.

**Comment by kterada0509** [comment]
> @kterada0509 apparently this now has a merge conflict.

@Szasza Thanks. I rebased master.

**Comment by vauchok** [comment]
Thanks, @kterada0509 
hope, it'll be included in the next terraform-aws-provider release. @bflad

**Comment by kterada0509** [comment]
Rebase master & fix to corresponding to sdk update.

```
$ make testacc TEST=./aws TESTARGS='-run=TestAccAWSDataPipeline_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -parallel 20 -run=TestAccAWSDataPipeline_ -timeout 120m
=== RUN   TestAccAWSDataPipeline_basic
=== PAUSE TestAccAWSDataPipeline_basic
=== RUN   TestAccAWSDataPipeline_copyActivity
=== PAUSE TestAccAWSDataPipeline_copyActivity
=== RUN   TestAccAWSDataPipeline_disappears
=== PAUSE TestAccAWSDataPipeline_disappears
=== CONT  TestAccAWSDataPipeline_basic
=== CONT  TestAccAWSDataPipeline_disappears
=== CONT  TestAccAWSDataPipeline_copyActivity
--- PASS: TestAccAWSDataPipeline_disappears (44.21s)
--- PASS: TestAccAWSDataPipeline_basic (50.54s)
--- PASS: TestAccAWSDataPipeline_copyActivity (74.77s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	74.838s
```

**Comment by Szasza** [comment]
@bflad do you happen to have any information on when will this get merged?

Thank you in advance for your insight, it is much appreciated.

**Comment by kyprifog** [comment]
Ditto, when will this be released?  Lack of Terraform support for Data pipelines derailed an initiative I tried to push recently.

**Comment by scraly** [comment]
Any news about the release date? :-) 
Thx

**Comment by Szasza** [comment]
@bflad now that TF 0.12 is released, could this PR get some attention please?

Thank you in advance for your time.

**Comment by kterada0509** [comment]
This pull request seems to be difficult to merge.
I split pr to #9267 .

**Pull request closed without merging**
