### PR TITLE
[WIP] DynamoDB: autoscaling policy

### PR DESCRIPTION
**Pull request by stephencoe**
### Reasoning for this change
Adding autoscaling support for DynamoDB

[Related issue](https://github.com/terraform-providers/terraform-provider-aws/issues/888)

API Reference: http://docs.aws.amazon.com/ApplicationAutoScaling/latest/APIReference/API_PutScalingPolicy.html

### Example configuration
```js
resource "aws_appautoscaling_target" "dynamo_test" {
  service_namespace = "dynamodb"
  resource_id = "${aws_dynamodb_table.dynamodb_table_test.name}"
  scalable_dimension = "dynamodb:table:WriteCapacityUnits"
  role_arn = "${aws_iam_role.autoscale_role.arn}"
  min_capacity = 1
  max_capacity = 10
}

resource "aws_appautoscaling_policy" "dynamo_test" {
  name = "%s"
  service_namespace = "dynamodb"
  resource_id = "${aws_dynamodb_table.dynamodb_table_test.name}"
  scalable_dimension = "dynamodb:table:WriteCapacityUnits"
  adjustment_type = "ChangeInCapacity"
  cooldown = 60
  metric_aggregation_type = "Maximum"

  step_adjustment {
    metric_interval_lower_bound = 0
    scaling_adjustment = 1
  }
  
  customized_metric_specification = {
    metric_name = "foo"
    namespace = "dynamodb"
    statistic = "Sum"
  }

  predefined_metric_specification = {
    predefined_metric_type = "DynamoDBWriteCapacityUtilization"
  }
  
  scale_in_cooldown = 10
  scale_out_cooldown = 10
  target_value = 70

  depends_on = ["aws_appautoscaling_target.dynamo_test"]
}
```

### CODE REVIEW

**Comment by bflad** [comment]
aws-sdk-go was updated to 1.8.44 on master already: #900

**Comment by johnthedev97** [comment]
I am interested in this feature. I don't see any recent activity on this thread. Is this still being worked? If not I can give it a shot

**Comment by stephencoe** [comment]
I have pushed where I am with it, not had a lot of time but will try finish it up this week

**Comment by mcwqy9** [comment]
It would be nice if this patch also supported autoscaling on GSIs. You may run into a blocker in https://github.com/terraform-providers/terraform-provider-aws/issues/671, the lack of any way to have terraform ignore changes to a GSI's capacity. 

That brings up another point, the docs for aws_appautoscaling_policy should probably indicate [how](https://www.terraform.io/docs/configuration/resources.html#ignore_changes) to have terraform ignore changes on the table capacity. Otherwise, assuming the table itself is captured in Terraform, every time you run an `apply` the capacity on the table will be reset to whatever you hardcoded in the config for the table itself.

**Comment by johnthedev97** [comment]
I don't think additional code changes are required to support autoscaling on GSI - just keep the scalabledimension as dynamodb:index:ReadCapacityUnits

**Comment by bflad** [comment]
Any update on this PR? We're excited to implement. 😄

**Comment by stephencoe** [comment]
Hi @radeksimko, 

Thanks for the feedback.  Its unlikely that I am going to have a chance to pick this up again in the short term and I am aware there are a lot of people waiting for this to be implemented. Feel free to make the changes you have suggested if it helps to progress this towards being complete

**Comment by radeksimko** [comment]
@stephencoe Thanks for the quick response and honesty, I'll pick it up in upcoming days. 😉

**Pull request closed without merging**
