### PR TITLE
[WIP] r/aws_route53_resolver_rule: Add resource

### LINKED ISSUE #6550: Feature Request: Route53 Resolver Rule
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s)

* `aws_route53_resolver_rule`

### Potential Terraform Configuration

```hcl
resource "aws_route53_resolver_rule" "example" {
  name                 = "example"
  domain_name          = "example.com"
  resolver_endpoint_id = "..."
  rule_type            = "FORWARD"

  target_ip {
    ip   = "123.45.67.89"
    port = 1234
  }

  tags {
    Foo = "Barr"
  }
}
```

### References

* https://docs.aws.amazon.com/Route53/latest/APIReference/API_route53resolver_CreateResolverRule.html
* https://docs.aws.amazon.com/Route53/latest/APIReference/API_route53resolver_GetResolverRule.html
* https://docs.aws.amazon.com/Route53/latest/APIReference/API_route53resolver_UpdateResolverRule.html
* https://docs.aws.amazon.com/Route53/latest/APIReference/API_route53resolver_DeleteResolverRule.html

### PR DESCRIPTION
**Pull request by gazoakley**
Closes #6550

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccAWSAvailabilityZones'

...
```

### CODE REVIEW

**Comment by jantman** [comment]
It looks like this PR has been open for a month and a half... we're really, really anxious to have this working. Any update?

**Comment by gazoakley** [comment]
Hi @jantman - @ewbankkit is trying to figure out how best to tackle the Route53 Resolver Endpoint resource in https://github.com/terraform-providers/terraform-provider-aws/pull/6574. Unfortunately that's a prerequisite to writing acceptance tests and being able to get this merged. I'm keeping an eye on progress 👍

**Comment by jantman** [comment]
Ok, thanks so much for the update!!!

**Comment by ewbankkit** [comment]
@gazoakley https://github.com/terraform-providers/terraform-provider-aws/issues/6563 has (finally) been merged. Are you able to complete this one?

**Comment by ewbankkit** [comment]
@gazoakley I took the liberty of cherry picking your commit and completing the `aws_route53_resolver_rule` and `aws_route53_resolver_rule_association` resources in https://github.com/terraform-providers/terraform-provider-aws/pull/7799 as we have an urgent need for these resources.
The only attribute changes I made were to add `owner_id` and `share_status` as computed attributes to `aws_route53_resolver_rule`.

**Comment by nywilken** [comment]
@gazoakley  thanks for the work on getting this started. I'm going to close this PR and help push forward #7799. Please feel free to add any comments or feedback to the new PR.

**Pull request closed without merging**
