### PR TITLE
feature(sagemaker notebook): Add DirectInternetAccess support 

### PR DESCRIPTION
**Pull request by bcatubig**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" comments, they generate extra noise for pull request followers and do not help prioritize the request

Fixes #0000

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
* Add direct_internet_access option to Sagemaker Notebook Resource
```

Output from acceptance testing:

~I'm not able to run tests locally, would need some help with my local go setup~

I'm not able to run tests. I will need these to be run by another maintainer.

```
⌂681% [brandon:~/go … terraform-provider-aws] feature/sagemaker-private-internet-access 1m7s ± make testacc TESTARGS='-run=TestAccAWSSagemakerNotebookInstance_directInternetAccess'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./... -v -parallel 20 -run=TestAccAWSSagemakerNotebookInstance_directInternetAccess -timeout 120m
main.go:5:2: cannot find package "github.com/terraform-providers/terraform-provider-aws/aws" in any of:
	/Users/brandon/go/src/github.com/bcatubig/terraform-provider-aws/vendor/github.com/terraform-providers/terraform-provider-aws/aws (vendor tree)
	/usr/local/Cellar/go/1.12.1/libexec/src/github.com/terraform-providers/terraform-provider-aws/aws (from $GOROOT)
	/Users/brandon/go/src/github.com/terraform-providers/terraform-provider-aws/aws (from $GOPATH)
make: *** [testacc] Error 1
```

### CODE REVIEW

**Comment by bflad** [comment]
Hi @bcatubig 👋 Is this pull request still work in progress as noted by the title?

**Comment by bcatubig** [comment]
Hey @bflad -- this is ready for review/feedback. I borked my last PR for this feature by mistake.

I'll try moving the folder

**Comment by rainmanh** [comment]
@bcatubig @bflad, any estimate when this will be released please?

**Comment by seoane** [comment]
@bflad Greetings, do we have any eta for when this will be released?.
Thank you for everything!

**Comment by pserrano** [comment]
Hi,
when this feature will be released? It's very useful because if you need to disable the DirectInternetAccess you can't use terraform to handle this Notebook confit and you should do manually. Any ETA? @ryndaniels @bcatubig

**Comment by bcatubig** [comment]
I'll update this branch with upstream this weekend

**Comment by bcatubig** [comment]
PR has been re-synced with upstream. Commits have also been squashed to a single commit.

**Comment by jacoor** [comment]
Any update on state of this PR? Would be very usefull.

**Pull request merged**
