### PR TITLE
[WIP] New Resources: aws_dx_private_vif,  aws_dx_private_vif_allocation and aws_dx_private_vif_confirmation

### PR DESCRIPTION
**Pull request by spirius**
Implemented direct connect private virtual interface and confirmation resources. Supports private VIFs for own and foreign AWS accounts. Only virtual private gateway is supported atm. Confirmation resource can be used to attach VIF to foreign account's virtual gateway.

### CODE REVIEW

**Comment by spirius** [comment]
Any suggestions regarding how to write acceptance tests for this? In order to create virtual interfaces aws requires dx connection to be in "available" state and that might take up to 72 hours after creation.

**Comment by ewbankkit** [comment]
See also:
* https://github.com/terraform-providers/terraform-provider-aws/pull/3253
* https://github.com/terraform-providers/terraform-provider-aws/pull/3255

**Comment by spirius** [comment]
@ewbankkit thanks. Closing this, since it's already covered by your PRs.

**Comment by ewbankkit** [comment]
@spirius If there's any functionality that I missed, please let me know. AFAIK the issue with acceptance is the fact that you need an active Direct Connect connection available for creating the virtual interfaces and the creation of the connection is not 100% programmatic.

**Pull request closed without merging**
