### PR TITLE
New resource: aws_cognito_user_pool_app_client

### PR DESCRIPTION
**Pull request by tomelliff**
Minimal Cognito User Pool App/Client resource.
Only implements generate_secret, refresh_token_validity and read/write_attributes so far.
All the Oauth stuff has been left for work at a later date.

### CODE REVIEW

**Comment by tomelliff** [comment]
```
$ make testacc TEST=./aws TESTARGS="-run=TestAccAWSCognitoUserPoolAppClient"
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -run=TestAccAWSCognitoUserPoolAppClient -timeout 120m
=== RUN   TestAccAWSCognitoUserPoolAppClient_basic
--- PASS: TestAccAWSCognitoUserPoolAppClient_basic (28.67s)
=== RUN   TestAccAWSCognitoUserPoolAppClient_generate_secret
--- PASS: TestAccAWSCognitoUserPoolAppClient_generate_secret (28.65s)
=== RUN   TestAccAWSCognitoUserPoolAppClient_complex
--- PASS: TestAccAWSCognitoUserPoolAppClient_complex (52.34s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	109.667s
```

**Comment by tomelliff** [comment]
Interestingly I managed to accidentally return `resourceAwsCognitoUserPoolRead` from the update instead of `resourceAwsCognitoUserPoolAppClientRead` but all my tests still passed. When I checked, I had a Cognito user pool still left in us-west-2 from the test that hadn't been destroyed despite all the tests having a `CheckDestroy` that _looks_ like it should be fine.

I've since fixed the mistake and squashed the fix but have I done something wrong there?

**Comment by tomelliff** [comment]
Moving this back to WIP because after a little bit of testing it looks like updating either read or write attributes but not both then wipes the other one. I'll try and debug what's going on there but it's not good to be merged until then.

**Comment by tomelliff** [comment]
https://github.com/terraform-providers/terraform-provider-aws/pull/2874/commits/6ced0dc5dc82d8b4d6ea65a63844bbfc3e1e7072 fixes the issue with read/write attributes being removed on an update where they weren't being updated (such as to the other attribute type or to refresh_validation) but I wasn't able to get a test go red before fixing it.

If anyone can point me in the right direction or add it so that https://github.com/terraform-providers/terraform-provider-aws/pull/2874/commits/9b9c56a2a626b44f48d437110968923d02d97784 fails but https://github.com/terraform-providers/terraform-provider-aws/pull/2874/commits/6ced0dc5dc82d8b4d6ea65a63844bbfc3e1e7072 passes then that would be great.

I originally had a test that looked like:
```
func TestAccAWSCognitoUserPoolAppClient_update_just_read_attribute(t *testing.T) {
	name := acctest.RandString(5)

	resource.Test(t, resource.TestCase{
		PreCheck:     func() { testAccPreCheck(t) },
		Providers:    testAccProviders,
		CheckDestroy: testAccCheckAWSCognitoUserPoolAppClientDestroy,
		Steps: []resource.TestStep{
			{
				Config: testAccAWSCognitoUserPoolAppClientConfig_update_just_read_attribute(name),
				Check: resource.ComposeAggregateTestCheckFunc(
					testAccCheckAWSCognitoUserPoolAppClientExists("aws_cognito_user_pool_app_client.update_read"),
					resource.TestCheckResourceAttr("aws_cognito_user_pool_app_client.update_read", "name", "terraform-test-pool-app-client-"+name),
					resource.TestCheckResourceAttr("aws_cognito_user_pool_app_client.update_read", "read_attributes.881205744", "email"),
					resource.TestCheckResourceAttr("aws_cognito_user_pool_app_client.update_read", "write_attributes.881205744", "email"),
					resource.TestCheckNoResourceAttr("aws_cognito_user_pool_app_client.update_read", "read_attributes.140932285"),
					resource.TestCheckNoResourceAttr("aws_cognito_user_pool_app_client.update_read", "client_secret"),
				),
			},
			{
				Config: testAccAWSCognitoUserPoolAppClientConfig_update_just_read_attribute_updated(name),
				Check: resource.ComposeAggregateTestCheckFunc(
					testAccCheckAWSCognitoUserPoolAppClientExists("aws_cognito_user_pool_app_client.update_read"),
					resource.TestCheckResourceAttr("aws_cognito_user_pool_app_client.update_read", "name", "terraform-test-pool-app-client-"+name),
					resource.TestCheckResourceAttr("aws_cognito_user_pool_app_client.update_read", "read_attributes.881205744", "email"),
					resource.TestCheckResourceAttr("aws_cognito_user_pool_app_client.update_read", "read_attributes.140932285", "email_verified"),
					resource.TestCheckResourceAttr("aws_cognito_user_pool_app_client.update_read", "write_attributes.881205744", "email"),
					resource.TestCheckNoResourceAttr("aws_cognito_user_pool_app_client.update_read", "client_secret"),
				),
			},
		},
	})
}
```
with config:
```
func testAccAWSCognitoUserPoolAppClientConfig_update_just_read_attribute(name string) string {
	return fmt.Sprintf(`
resource "aws_cognito_user_pool" "pool" {
  name = "terraform-test-pool-%s"
}

resource "aws_cognito_user_pool_app_client" "update_read" {
  name         = "terraform-test-pool-app-client-%s"
  user_pool_id = "${aws_cognito_user_pool.pool.id}"

  read_attributes = [
    "email",
  ]

  write_attributes = [
    "email",
  ]
}`, name, name)
}

func testAccAWSCognitoUserPoolAppClientConfig_update_just_read_attribute_updated(name string) string {
	return fmt.Sprintf(`
resource "aws_cognito_user_pool" "pool" {
  name = "terraform-test-pool-%s"
}

resource "aws_cognito_user_pool_app_client" "update_read" {
  name         = "terraform-test-pool-app-client-%s"
  user_pool_id = "${aws_cognito_user_pool.pool.id}"

  read_attributes = [
    "email",
    "email_verified",
  ]

  write_attributes = [
    "email",
  ]
}`, name, name)
}
````

but this doesn't go red because the API response doesn't include the `write_attributes` element at all and so this isn't written to the state (see https://github.com/terraform-providers/terraform-provider-aws/pull/2874/files#diff-5c8f78e03a5cbaffd203afb21271c6d4R118) and the state thinks the user pool app still has the missing attributes.

Is there a safe way I'm missing that I can get it to update those read/write attribute parameters without erroring when they're not present?

**Comment by tomelliff** [comment]
Think that's fixed everything and have tests to cover that last issue too:
```
$ make testacc TEST=./aws TESTARGS="-run=TestAccAWSCognitoUserPoolAppClient"
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -run=TestAccAWSCognitoUserPoolAppClient -timeout 120m
=== RUN   TestAccAWSCognitoUserPoolAppClient_basic
--- PASS: TestAccAWSCognitoUserPoolAppClient_basic (28.99s)
=== RUN   TestAccAWSCognitoUserPoolAppClient_update_basic
--- PASS: TestAccAWSCognitoUserPoolAppClient_update_basic (28.35s)
=== RUN   TestAccAWSCognitoUserPoolAppClient_generate_secret
--- PASS: TestAccAWSCognitoUserPoolAppClient_generate_secret (28.47s)
=== RUN   TestAccAWSCognitoUserPoolAppClient_complex
--- PASS: TestAccAWSCognitoUserPoolAppClient_complex (53.17s)
=== RUN   TestAccAWSCognitoUserPoolAppClient_update_non_attributes
--- PASS: TestAccAWSCognitoUserPoolAppClient_update_non_attributes (48.38s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	187.378s
```

**Comment by jen20** [comment]
Hi @tomelliff! Thanks for the comprehensive pull request. I have another couple to review ahead of this one but if no-one else picks this up first I will do so shortly.

**Comment by tomelliff** [comment]
Cool, thanks. The only time I get to write any Go is when I contribute to Terraform so let me know if there's anything I've done wrong or could do better.

**Comment by radeksimko** [comment]
Hi @tomelliff 
this looks like a duplicate of a resource which I just merged: https://github.com/terraform-providers/terraform-provider-aws/pull/1803 (admittedly raised earlier) https://github.com/terraform-providers/terraform-provider-aws/commit/c583147b8c8b872c6c06dddee62ceb0a7b410646

Can you please take a look and confirm that we can close this PR?

Thanks.

**Comment by tomelliff** [comment]
Ack, I'm not doing too well with Github search apparently and keep missing things that other people have done before starting.

Looking at the discussion in the PR I can see [this comment](https://github.com/terraform-providers/terraform-provider-aws/pull/1803#pullrequestreview-80903918) that seems to suggest that there's no support for custom attributes but I can't see why not because it was straightforward for me to add them (and I have tests for them too).

I also noticed that the read_attributes and write_attributes are only set on an update when they are changed (https://github.com/terraform-providers/terraform-provider-aws/commit/c583147b8c8b872c6c06dddee62ceb0a7b410646#diff-691a9416b6661d1ee9e2ed38b6dce6fdR269) but this won't actually work because if you set just the read attributes and not the write attributes the API annoyingly blanks the write attributes and vice versa. This has the awful fallback of making everything readable/writable as well :( I added a test in my PR to cover that use case but I could probably rework fixes on top of that work and close that PR if you want? I'd probably want to test the update a bit more heavily with a test case that loops through a lot of changes just from the weirdness going on with the attributes.

**Comment by radeksimko** [comment]
> I could probably rework fixes on top of that work and close that PR if you want?

That sounds like a good plan 👍  Thanks.

**Comment by radeksimko** [comment]
I'm going to close this PR then and let you pick any changes & PR them separately.

Thanks for all the efforts!

**Pull request closed without merging**
