### PR TITLE
Add load_balancers and target_group_arns options to Spot fleets

### LINKED ISSUE #2320: Feature request: Add ELB configuration to spot fleet request
_This issue was originally opened by @gotoadmin as hashicorp/terraform#16670. It was migrated here as a result of the [provider split](https://www.hashicorp.com/blog/upcoming-provider-changes-in-terraform-0-10/). The original body of the issue is below._

<hr>

I checked the terraform documentation several times but I was unable to find such functionality. It is available in AWS CLI but could not be performed via Terraform

### LINKED ISSUE #3633: LoadBalancersConfig is missing from spot_fleet_request resource
### Terraform Version
Terraform v0.11.3
AWS Provider v1.9.0

### Affected Resource(s)
Please list the resources as a list, for example:
- spot_fleet_request

### Expected Behavior
"LoadBalancersConfig" is missing from the spot_fleet_request resource.

### Important Factoids
AWS API includes LoadBalancersConfig in `--spot-fleet-request-config` JSON
https://docs.aws.amazon.com/cli/latest/reference/ec2/request-spot-fleet.html

```
  "LoadBalancersConfig": {
    "ClassicLoadBalancersConfig": {
      "ClassicLoadBalancers": [
        {
          "Name": "string"
        }
        ...
      ]
    },
```

But its missing from the terraform [module](https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/resource_aws_spot_fleet_request.go) and [documentation](https://www.terraform.io/docs/providers/aws/r/spot_fleet_request.html).

### PR DESCRIPTION
**Pull request by coop182**
A few changes to allow Spot fleets to be created with a load balancer defined. Tried to keep things the same as the naming used on ASG's.

Fixes #2320 
Closes #3633

### CODE REVIEW

**Comment by henrydobson** [comment]
👍  Any idea which release this will be in or how far away this is from release?

**Comment by eoly** [comment]
Please release this soon. Thanks!

**Comment by bflad** [comment]
Hi everyone! 👋  Sorry this PR got lost in the shuffle. It looks like its in pretty good shape at first glance so hopefully we can get this in real quick.

**Comment by bflad** [comment]
This has been released in [version 1.11.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1110-march-09-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.

**Pull request merged**
