### PR TITLE
Support AWS PrivateLink

### PR DESCRIPTION
**Pull request by ewbankkit**
Fixes https://github.com/terraform-providers/terraform-provider-aws/issues/2222 and https://github.com/terraform-providers/terraform-provider-aws/issues/2460.
Incorporates https://github.com/terraform-providers/terraform-provider-aws/pull/2253.

* [x] `aws_vpc_endpoint_service` data source - Update
* [x] `aws_vpc_endpoint` data source - Update
* [x] `aws_vpc_endpoint` resource - Update
* [x] `aws_vpc_endpoint_subnet_association` resource - New
* [x] `aws_vpc_endpoint_service` resource - New
* [x] `aws_vpc_endpoint_service_allowed_principal` resource - New
* [x] `aws_vpc_endpoint_connection_notification` resource - New
* [x] `aws_vpc_endpoint_service` data source - Update
* [x] Documentation
* [x] Acceptance tests

### CODE REVIEW

**Comment by ewbankkit** [comment]
Initial commits are just an excuse to write down a task list 😄.

**Comment by ewbankkit** [comment]
There will be no `aws_vpc_endpoint_connection_accepter` resource as my initial understanding of VPC endpoint connection acceptance was wrong. I think we can add an `auto_accept` attribute to the `aws_vpc_endpoint` resource to accept the endpoint connection if the endpoint service is in the same account.

**Comment by darrenhaken** [comment]
Any idea when this might be complete?

**Comment by ewbankkit** [comment]
Need to complete the `aws_vpc_endpoint_connection_notification` and then make some updates to the `aws_vpc_endpoint` resource and `aws_vpc_endpoint`/`aws_vpc_endpoint_service` data sources.
May well need to merge #2253 in and submit the combined PR for completeness.
Don't want to make promises, but shouldn't be too long.

**Comment by darrenhaken** [comment]
Sure thanks. If you need any help ping me, happy to try and contribute. I haven’t done much Go before but certainly always prepared to roll up my sleeves 😁

________________________________

**Comment by ewbankkit** [comment]
The PR now incorporates the work done in https://github.com/terraform-providers/terraform-provider-aws/pull/2253 and support AWS Private Link for both AWS and non-AWS (user defined) services.
I made the decision to combine as completing the non-AWS service work completely built on the work in https://github.com/terraform-providers/terraform-provider-aws/pull/2253.

The `aws_vpc_endpoint_service` has been added as the resource through which non-AWS VPC Endpoint Services are managed.
The associated `aws_vpc_endpoint_service_allowed_principal` allows whitelisted resources to be added or removed independent of the main resource (e.g. in a separate Terraform state).

In addition to the changes in https://github.com/terraform-providers/terraform-provider-aws/pull/2253, the `aws_vpc_endpoint` resource has been enhanced with the `auto_accept` attribute which allows a same-account non-AWS VPC Endpoint to be accepted.

**Comment by ewbankkit** [comment]
Acceptance tests:
`aws_vpc_endpoint_service` data source:
```
make testacc TEST=./aws/ TESTARGS='-run=TestAccDataSourceAwsVpcEndpointService_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws/ -v -run=TestAccDataSourceAwsVpcEndpointService_ -timeout 120m
=== RUN   TestAccDataSourceAwsVpcEndpointService_gateway
--- PASS: TestAccDataSourceAwsVpcEndpointService_gateway (14.77s)
=== RUN   TestAccDataSourceAwsVpcEndpointService_interface
--- PASS: TestAccDataSourceAwsVpcEndpointService_interface (13.73s)
=== RUN   TestAccDataSourceAwsVpcEndpointService_custom
--- PASS: TestAccDataSourceAwsVpcEndpointService_custom (240.52s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	269.032s
```
`aws_vpc_endpoint` data source:
```
make testacc TEST=./aws/ TESTARGS='-run=TestAccDataSourceAwsVpcEndpoint_'
make testacc TEST=./aws/ TESTARGS='-run=TestAccDataSourceAwsVpcEndpoint_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws/ -v -run=TestAccDataSourceAwsVpcEndpoint_ -timeout 120m
=== RUN   TestAccDataSourceAwsVpcEndpoint_gatewayBasic
--- PASS: TestAccDataSourceAwsVpcEndpoint_gatewayBasic (44.07s)
=== RUN   TestAccDataSourceAwsVpcEndpoint_byId
--- PASS: TestAccDataSourceAwsVpcEndpoint_byId (43.84s)
=== RUN   TestAccDataSourceAwsVpcEndpoint_gatewayWithRouteTable
--- PASS: TestAccDataSourceAwsVpcEndpoint_gatewayWithRouteTable (47.68s)
=== RUN   TestAccDataSourceAwsVpcEndpoint_interface
--- PASS: TestAccDataSourceAwsVpcEndpoint_interface (282.24s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	417.844s
```
`aws_vpc_endpoint_service` resource:
```
make testacc TEST=./aws/ TESTARGS='-run=TestAccAwsVpcEndpointService_'
```
`aws_vpc_endpoint_service_allowed_principal` resource:
```
make testacc TEST=./aws/ TESTARGS='-run=TestAccAwsVpcEndpointServiceAllowedPrincipal_'
```
`aws_vpc_endpoint` resource:
```
make testacc TEST=./aws/ TESTARGS='-run=TestAccAwsVpcEndpoint_'
```
`aws_vpc_endpoint_route_table_association` resource:
```
make testacc TEST=./aws/ TESTARGS='-run=TestAccAwsVpcEndpointRouteTableAssociation_'
```
`aws_vpc_endpoint_subnet_association` resource:
```
make testacc TEST=./aws/ TESTARGS='-run=TestAccAwsVpcEndpointSubnetAssociation_'
```
`aws_vpc_endpoint_connection_notification` resource:
```
make testacc TEST=./aws/ TESTARGS='-run=TestAccAwsVpcEndpointConnectionNotification_'
```

**Comment by ewbankkit** [comment]
Removed _WIP_.

**Comment by RyanJarv** [comment]
Hey awesome work! Quick observation here, allowed_principals on aws_vpc_endpoint_service doesn't seem to be updated if it is removed in terraform (whitelisted principals stay whitelisted on the endpoint service.

**Comment by skeller88** [comment]
Any update on when this might be merged? I'm also eagerly awaiting a fix.

**Comment by ewbankkit** [comment]
@RyanJarv By "removed in terraform" do you mean that you removed the `allowed_principals` attribute (in which case Terraform will no longer manage that value as it's marked as Computed) or set it to the empty list: `allowed_principals = []`?

**Comment by RyanJarv** [comment]
@ewbankkit looks like I was removing allowed_principals. Setting it to an empty array behaves as expected.

**Comment by ewbankkit** [comment]
Rebased to fix conflicts.

**Comment by tombooth** [comment]
@jen20 @radeksimko what's holding this up? having to run a forked version of this provider for the moment

**Comment by jen20** [comment]
My mistake, I've been busy with other things. I'll try to pick this up today unless another maintainer does before me.

**Comment by sverze** [comment]
Any ETA on when this will be merged?

**Comment by stevenayers** [comment]
@jen20 @radeksimko Any ETA on when this'll be merged? Thanks.

**Comment by jen20** [comment]
I've rebased and merged this locallly, and it looks good to go - it landed in 35b273ec. Thanks for a great PR @ewbankkit.

Sorry for the delay on merging this, but I have limited time to work on outside projects such as Terraform these days.

**Comment by bflad** [comment]
This has been released in [terraform-provider-aws version 1.9.0](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#190-february-09-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.

**Pull request closed without merging**
