### PR TITLE
bump aws-sdk-go to v1.12.30

### PR DESCRIPTION
**Pull request by Puneeth-n**
commands used: `govendor fetch github.com/aws/aws-sdk-go/...@v1.12.30 `

### CODE REVIEW

**Comment by Ninir** [comment]
Hi @Puneeth-n 

Thanks for the work here!

I'm pretty annoyed by a small edge-case i'm encountering...

Using your branch and running the command again, I have 2 modified files:
```
	deleted:    vendor/github.com/aws/aws-sdk-go/aws/request/connection_reset_error_other.go
	modified:   vendor/vendor.json
```

In vendor.json, here is the change (checksum of the release changing):

```
-                       "checksumSHA1": "9GvAyILJ7g+VUg8Ef5DsT5GuYsg=",
+                       "checksumSHA1": "86TEBLzyjsUoovbC0M1YwsKB7zo=",
```

However, briefly looking, the file `vendor/github.com/aws/aws-sdk-go/aws/request/connection_reset_error_other.go` do is present in the repository so can't really tell what is happening right now. Could you re-run the update command and tell me what happens?

Thanks!

**Comment by Puneeth-n** [comment]
@Ninir Sure. I will do it right away.

**Comment by Puneeth-n** [comment]
@Ninir, I am not sure why you are getting this.

I cloned the repo fresh again, 
1. `git clean -fdx`

1. `docker run --rm -it -v $(pwd):/go/src/github.com/terraform-providers/terraform-provider-aws -w /go/src/github.com/terraform-providers/terraform-provider-aws golang:latest bash`

1. `go get -u github.com/kardianos/govendor`

1. `govendor fetch github.com/aws/aws-sdk-go/...@v1.12.30` from the `root` of the project

1. 

```
git status

On branch master
Your branch is up-to-date with 'upstream/master'.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   vendor/github.com/aws/aws-sdk-go/aws/endpoints/defaults.go
	modified:   vendor/github.com/aws/aws-sdk-go/aws/version.go
	modified:   vendor/github.com/aws/aws-sdk-go/private/protocol/json/jsonutil/build.go
	modified:   vendor/github.com/aws/aws-sdk-go/private/protocol/json/jsonutil/unmarshal.go
	modified:   vendor/github.com/aws/aws-sdk-go/private/protocol/rest/build.go
	modified:   vendor/github.com/aws/aws-sdk-go/private/protocol/rest/unmarshal.go
	modified:   vendor/github.com/aws/aws-sdk-go/service/apigateway/api.go
	modified:   vendor/github.com/aws/aws-sdk-go/service/applicationautoscaling/api.go
	modified:   vendor/github.com/aws/aws-sdk-go/service/applicationautoscaling/doc.go
	modified:   vendor/github.com/aws/aws-sdk-go/service/databasemigrationservice/api.go
	modified:   vendor/github.com/aws/aws-sdk-go/service/ec2/api.go
	modified:   vendor/github.com/aws/aws-sdk-go/service/elbv2/api.go
	modified:   vendor/github.com/aws/aws-sdk-go/service/glue/api.go
	modified:   vendor/github.com/aws/aws-sdk-go/service/rds/api.go
	modified:   vendor/github.com/aws/aws-sdk-go/service/rds/doc.go
	modified:   vendor/github.com/aws/aws-sdk-go/service/route53/api.go
	modified:   vendor/github.com/aws/aws-sdk-go/service/route53/errors.go
	modified:   vendor/github.com/aws/aws-sdk-go/service/s3/api.go
	modified:   vendor/github.com/aws/aws-sdk-go/service/ses/api.go
	modified:   vendor/github.com/aws/aws-sdk-go/service/ses/errors.go
	modified:   vendor/github.com/aws/aws-sdk-go/service/sfn/api.go
	modified:   vendor/github.com/aws/aws-sdk-go/service/sfn/doc.go
	modified:   vendor/github.com/aws/aws-sdk-go/service/sfn/errors.go
	modified:   vendor/vendor.json

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	vendor/github.com/aws/aws-sdk-go/private/protocol/jsonvalue.go

```
1. `git add vendor/github.com/aws/aws-sdk-go/private/protocol/jsonvalue.go`
1. `git commit -am "blah blah blah"`


I did the same steps on my existing PR branch too. Nothing was deleted nor modified.

```
HEAD detached at origin/chore/aws-sdk-go-1.12.30
nothing to commit, working tree clean
```

**Comment by Ninir** [comment]
That's really weird... doing it on the master branch results in the same behaviour as yours.
However on your branch it brings what I exposed earlier.

Could you run `govendor -version` so that we try to understand what is happening here? mine is v1.0.8.

Thanks!

**Comment by Puneeth-n** [comment]
```
root@642ea7df57c7:/go/src/github.com/terraform-providers/terraform-provider-aws# govendor --version
v1.0.9
```

**Comment by Puneeth-n** [comment]
@Ninir Are you running it on my old PR or this PR?

**Comment by Puneeth-n** [comment]
@Ninir I found the issue. It has to do with `govendor` version `v1.0.8` for some reason.

I manually installed govendor v1.0.8 and could reproduce your issue. However, I am not sure why it is happening.

```
root@642ea7df57c7:/go/src/github.com/terraform-providers/terraform-provider-aws# govendor --version
v1.0.8
```

`govendor fetch github.com/aws/aws-sdk-go/...@v1.12.30`

```
➜  terraform-provider-aws git:(chore/aws-sdk-go-1.12.30) ✗ git status
On branch chore/aws-sdk-go-1.12.30
Your branch is ahead of 'upstream/master' by 1 commit.
  (use "git push" to publish your local commits)
Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	deleted:    vendor/github.com/aws/aws-sdk-go/aws/request/connection_reset_error_other.go
	modified:   vendor/vendor.json
```

```
diff --git a/vendor/github.com/aws/aws-sdk-go/aws/request/connection_reset_error_other.go b/vendor/github.com/aws/aws-sdk-go/aws/request/connection_reset_error_other.go
deleted file mode 100644
index daf9eca..0000000
--- a/vendor/github.com/aws/aws-sdk-go/aws/request/connection_reset_error_other.go
+++ /dev/null
@@ -1,11 +0,0 @@
-// +build appengine plan9
-
-package request
-
-import (
-       "strings"
-)
-
-func isErrConnectionReset(err error) bool {
-       return strings.Contains(err.Error(), "connection reset")
-}
diff --git a/vendor/vendor.json b/vendor/vendor.json
index f5d38eb..e1bb5b2 100644
--- a/vendor/vendor.json
+++ b/vendor/vendor.json
@@ -253,7 +253,7 @@
                        "versionExact": "v1.12.30"
                },
                {
-                       "checksumSHA1": "9GvAyILJ7g+VUg8Ef5DsT5GuYsg=",
+                       "checksumSHA1": "86TEBLzyjsUoovbC0M1YwsKB7zo=",
                        "path": "github.com/aws/aws-sdk-go/aws/request",
                        "revision": "e4f7e38b704e3ed0acc4a7f8196b777696f6f1f3",
                        "revisionTime": "2017-11-17T22:19:00Z",
(END)
```

**Comment by Ninir** [comment]
@Puneeth-n Thanks for the investigation ;)

Was able to check it also on my side with govendor 1.0.9. Will merge once the AWS provider 1.3.1 is released.

Thanks! :)

**Comment by Puneeth-n** [comment]
@Ninir Thanks :) BTW Can you please let me know if the `SFN`#2349 is ok and when it will be merged?

**Pull request merged**
