### PR TITLE
resource/launch_configuration: introduce user_data_base64

### LINKED ISSUE #4197: AWS Launch Configuration wants to update user_data despite lack of changes
### Terraform Version

```
Terraform v0.11.7
+ provider.aws v1.14.1
+ provider.dnsimple v0.1.0
+ provider.template v1.0.0
```

### Affected Resource(s)
- aws_launch_configuration
- template_cloudinit_config

### Terraform Configuration Files

(relevant parts only)

```hcl
data "template_cloudinit_config" "userdata_config" {
  gzip          = true
  base64_encode = true

  # Regular userdata script
  part {
    content_type = "text/x-shellscript"
    content      = "${data.template_file.setup_script.rendered}"
  }

  # cloud-boothook
  part {
    content_type = "text/cloud-boothook"
    content      = "${data.template_file.cloud_boothook.rendered}"
  }
}

resource "aws_launch_configuration" "ecs" {
  name_prefix                 = "${title(var.environment)} ECS-"
  image_id                    = "${var.image_id}"
  instance_type               = "${var.instance_type}"
  security_groups             = ["${aws_security_group.ecs.id}"]
  iam_instance_profile        = "${aws_iam_instance_profile.ecs.name}"
  key_name                    = "${var.environment}"
  associate_public_ip_address = true
  user_data                   = "${data.template_cloudinit_config.userdata_config.rendered}"
}

```

### Debug Output

(need to figure out if this contains sensitive info)

### Expected Behavior

The contents of the user_data scripts hasn't changed, so Terraform should not plan to do anything.

### Actual Behavior

Terraform wants to change the user_data field for the AWS launch configuration, forcing a new resource. In `terraform plan`, I'd see something like

`      user_data: "fedbca..." => "abcdef..." (forces new resource)`

Actually, right now it's wanting to create a new launch configuration, even though it already exists (rather than destroying and creating the existing one, which is what it normally tries to do).

Even if I apply the changes, the next time I run plan it will keep thinking that it needs to change the "user_data" field, and the old and new hash will still be the same as before.

### Steps to Reproduce

1. `terraform plan`

### Important Factoids

I had no issue on earlier versions of the AWS provider (v1.6), but this started happening when I upgraded to v1.14.1.

UPDATE: I went back and downloaded a bunch of versions of the AWS provider, and this issue did not exist in v1.10, v1.11, and v1.14, so this is due to something that changed in the latest version of the provider.

### References

Not sure if it's related to https://github.com/terraform-providers/terraform-provider-aws/issues/4056 because I'm not actually getting any errors, it's just doing the wrong thing.

### PR DESCRIPTION
**Pull request by loivis**
fix #4197, an issue caused by #2800 

As spotted with https://github.com/terraform-providers/terraform-provider-aws/issues/4197#issuecomment-382026874, try to borrow logic from `aws_instance` and introduce `user_data_base64` as fix.

### CODE REVIEW

**Comment by loivis** [comment]
```
⎇  make fmt; and echo > aws/debug.log ; and make testacc TEST=./aws TESTARGS='-run=TestAccAWSLaunchConfiguration_'
gofmt -w $(find . -name '*.go' |grep -v vendor)
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -run=TestAccAWSLaunchConfiguration_ -timeout 120m
=== RUN   TestAccAWSLaunchConfiguration_importBasic
--- PASS: TestAccAWSLaunchConfiguration_importBasic (44.71s)
=== RUN   TestAccAWSLaunchConfiguration_basic
--- PASS: TestAccAWSLaunchConfiguration_basic (105.32s)
=== RUN   TestAccAWSLaunchConfiguration_withBlockDevices
--- PASS: TestAccAWSLaunchConfiguration_withBlockDevices (75.61s)
=== RUN   TestAccAWSLaunchConfiguration_updateRootBlockDevice
--- PASS: TestAccAWSLaunchConfiguration_updateRootBlockDevice (120.58s)
=== RUN   TestAccAWSLaunchConfiguration_withSpotPrice
--- PASS: TestAccAWSLaunchConfiguration_withSpotPrice (75.36s)
=== RUN   TestAccAWSLaunchConfiguration_withVpcClassicLink
--- PASS: TestAccAWSLaunchConfiguration_withVpcClassicLink (63.80s)
=== RUN   TestAccAWSLaunchConfiguration_withIAMProfile
--- PASS: TestAccAWSLaunchConfiguration_withIAMProfile (110.68s)
=== RUN   TestAccAWSLaunchConfiguration_withEncryption
--- PASS: TestAccAWSLaunchConfiguration_withEncryption (74.11s)
=== RUN   TestAccAWSLaunchConfiguration_updateEbsBlockDevices
--- PASS: TestAccAWSLaunchConfiguration_updateEbsBlockDevices (122.56s)
=== RUN   TestAccAWSLaunchConfiguration_ebs_noDevice
--- PASS: TestAccAWSLaunchConfiguration_ebs_noDevice (36.32s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	829.154s
⎇  make fmt; and echo > aws/debug.log ; and make testacc TEST=./aws TESTARGS='-run=TestAccAWSLaunchConfiguration_userData'
gofmt -w $(find . -name '*.go' |grep -v vendor)
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -run=TestAccAWSLaunchConfiguration_userData -timeout 120m
=== RUN   TestAccAWSLaunchConfiguration_userData
--- PASS: TestAccAWSLaunchConfiguration_userData (108.36s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	108.439s
```

**Comment by bflad** [comment]
Hmm. I'm consistently getting testing failures in us-west-2:
```
=== RUN   TestAccAWSLaunchConfiguration_updateEbsBlockDevices
--- FAIL: TestAccAWSLaunchConfiguration_updateEbsBlockDevices (80.75s)
    testing.go:518: Step 1 error: After applying this step and refreshing, the plan was not empty:
        
        DIFF:
        
        DESTROY/CREATE: aws_launch_configuration.baz
          associate_public_ip_address:                       "false" => "false"
          ebs_block_device.#:                                "2" => "1"
          ebs_block_device.4131155854.delete_on_termination: "true" => "true"
          ebs_block_device.4131155854.device_name:           "/dev/sdb" => "/dev/sdb"
          ebs_block_device.4131155854.encrypted:             "true" => "true"
          ebs_block_device.4131155854.iops:                  "0" => "<computed>"
          ebs_block_device.4131155854.no_device:             "false" => ""
          ebs_block_device.4131155854.snapshot_id:           "" => "<computed>"
          ebs_block_device.4131155854.volume_size:           "10" => "10"
          ebs_block_device.4131155854.volume_type:           "" => "<computed>"
          ebs_block_device.486837074.delete_on_termination:  "true" => "false" (forces new resource)
          ebs_block_device.486837074.device_name:            "xvdco" => "" (forces new resource)
          ebs_block_device.486837074.no_device:              "false" => "false"
          ebs_optimized:                                     "false" => "<computed>"
          enable_monitoring:                                 "true" => "true"
          image_id:                                          "ami-f83e5180" => "ami-f83e5180"
          instance_type:                                     "t2.micro" => "t2.micro"
          key_name:                                          "" => "<computed>"
          name:                                              "terraform-20180420142505971700000002" => "<computed>"
          root_block_device.#:                               "0" => "1"
          root_block_device.0.delete_on_termination:         "" => "true" (forces new resource)
          root_block_device.0.iops:                          "" => "<computed>"
          root_block_device.0.volume_size:                   "" => "11" (forces new resource)
          root_block_device.0.volume_type:                   "" => "gp2" (forces new resource)

=== RUN   TestAccAWSLaunchConfiguration_updateRootBlockDevice
--- FAIL: TestAccAWSLaunchConfiguration_updateRootBlockDevice (89.24s)
    testing.go:518: Step 1 error: After applying this step and refreshing, the plan was not empty:
        
        DIFF:
        
        DESTROY/CREATE: aws_launch_configuration.bar
          associate_public_ip_address:               "true" => "true"
          ebs_block_device.#:                        "1" => "<computed>"
          ebs_optimized:                             "false" => "<computed>"
          enable_monitoring:                         "true" => "true"
          image_id:                                  "ami-f83e5180" => "ami-f83e5180"
          instance_type:                             "m1.small" => "m1.small"
          key_name:                                  "" => "<computed>"
          name:                                      "tf-acc-test-718685494963449961120180420142512221900000002" => "<computed>"
          name_prefix:                               "tf-acc-test-7186854949634499611" => "tf-acc-test-7186854949634499611"
          root_block_device.#:                       "0" => "1"
          root_block_device.0.delete_on_termination: "" => "true" (forces new resource)
          root_block_device.0.iops:                  "" => "<computed>"
          root_block_device.0.volume_size:           "" => "20" (forces new resource)
          root_block_device.0.volume_type:           "" => "gp2" (forces new resource)
          user_data:                                 "f9b375662f3ccb320a2d59fefdfa0f79ee9be21c" => "f9b375662f3ccb320a2d59fefdfa0f79ee9be21c"

=== RUN   TestAccAWSLaunchConfiguration_withBlockDevices
--- FAIL: TestAccAWSLaunchConfiguration_withBlockDevices (65.95s)
    testing.go:518: Step 0 error: After applying this step and refreshing, the plan was not empty:
        
        DIFF:
        
        DESTROY/CREATE: aws_launch_configuration.bar
          associate_public_ip_address:                      "true" => "true"
          ebs_block_device.#:                               "3" => "2"
          ebs_block_device.415261930.delete_on_termination: "true" => "true"
          ebs_block_device.415261930.device_name:           "/dev/sdc" => "/dev/sdc"
          ebs_block_device.415261930.encrypted:             "false" => "<computed>"
          ebs_block_device.415261930.iops:                  "100" => "100"
          ebs_block_device.415261930.no_device:             "false" => ""
          ebs_block_device.415261930.snapshot_id:           "" => "<computed>"
          ebs_block_device.415261930.volume_size:           "10" => "10"
          ebs_block_device.415261930.volume_type:           "io1" => "io1"
          ebs_block_device.766970953.delete_on_termination: "true" => "false" (forces new resource)
          ebs_block_device.766970953.device_name:           "/dev/sda1" => "" (forces new resource)
          ebs_block_device.766970953.no_device:             "false" => "false"
          ebs_block_device.784505502.delete_on_termination: "true" => "true"
          ebs_block_device.784505502.device_name:           "/dev/sdb" => "/dev/sdb"
          ebs_block_device.784505502.encrypted:             "false" => "<computed>"
          ebs_block_device.784505502.iops:                  "0" => "<computed>"
          ebs_block_device.784505502.no_device:             "false" => ""
          ebs_block_device.784505502.snapshot_id:           "" => "<computed>"
          ebs_block_device.784505502.volume_size:           "9" => "9"
          ebs_block_device.784505502.volume_type:           "" => "<computed>"
          ebs_optimized:                                    "false" => "<computed>"
          enable_monitoring:                                "true" => "true"
          ephemeral_block_device.#:                         "1" => "1"
          ephemeral_block_device.1692014856.device_name:    "/dev/sde" => "/dev/sde"
          ephemeral_block_device.1692014856.virtual_name:   "ephemeral0" => "ephemeral0"
          image_id:                                         "ami-f83e5180" => "ami-f83e5180"
          instance_type:                                    "m1.small" => "m1.small"
          key_name:                                         "" => "<computed>"
          name:                                             "tf-acc-test-3907438456770510797" => "tf-acc-test-3907438456770510797"
          root_block_device.#:                              "0" => "1"
          root_block_device.0.delete_on_termination:        "" => "true" (forces new resource)
          root_block_device.0.iops:                         "" => "<computed>"
          root_block_device.0.volume_size:                  "" => "11" (forces new resource)
          root_block_device.0.volume_type:                  "" => "gp2" (forces new resource)
          user_data:                                        "f9b375662f3ccb320a2d59fefdfa0f79ee9be21c" => "f9b375662f3ccb320a2d59fefdfa0f79ee9be21c"

=== RUN   TestAccAWSLaunchConfiguration_withEncryption
--- FAIL: TestAccAWSLaunchConfiguration_withEncryption (52.16s)
    testing.go:518: Step 0 error: Check failed: Check 2/2 error: block device doesn't exist: /dev/sda1
```

**Comment by loivis** [comment]
That's weird. I just tried with `us-west-2` without error. I also checked the image from debug log, which shows `image_id = ami-f83e5180`. It is an image from that region.

```
⎇  set -x AWS_REGION us-west-2
⎇  make fmt; and echo > aws/debug.log ; and make testacc TEST=./aws TESTARGS='-run=TestAccAWSLaunchConfiguration_withBlockDevices'
gofmt -w $(find . -name '*.go' |grep -v vendor)
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -run=TestAccAWSLaunchConfiguration_withBlockDevices -timeout 120m
=== RUN   TestAccAWSLaunchConfiguration_withBlockDevices
--- PASS: TestAccAWSLaunchConfiguration_withBlockDevices (101.16s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	101.283s
```

**Comment by loivis** [comment]
Now I get the same error, checking....

**Comment by loivis** [comment]
```
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -run=TestAccAWSLaunchConfiguration_ -timeout 120m
=== RUN   TestAccAWSLaunchConfiguration_importBasic
--- PASS: TestAccAWSLaunchConfiguration_importBasic (40.01s)
=== RUN   TestAccAWSLaunchConfiguration_basic
--- PASS: TestAccAWSLaunchConfiguration_basic (78.54s)
=== RUN   TestAccAWSLaunchConfiguration_withBlockDevices
--- PASS: TestAccAWSLaunchConfiguration_withBlockDevices (48.68s)
=== RUN   TestAccAWSLaunchConfiguration_updateRootBlockDevice
--- PASS: TestAccAWSLaunchConfiguration_updateRootBlockDevice (87.64s)
=== RUN   TestAccAWSLaunchConfiguration_withSpotPrice
--- PASS: TestAccAWSLaunchConfiguration_withSpotPrice (50.50s)
=== RUN   TestAccAWSLaunchConfiguration_withVpcClassicLink
--- PASS: TestAccAWSLaunchConfiguration_withVpcClassicLink (80.84s)
=== RUN   TestAccAWSLaunchConfiguration_withIAMProfile
--- PASS: TestAccAWSLaunchConfiguration_withIAMProfile (64.21s)
=== RUN   TestAccAWSLaunchConfiguration_withEncryption
--- PASS: TestAccAWSLaunchConfiguration_withEncryption (48.94s)
=== RUN   TestAccAWSLaunchConfiguration_updateEbsBlockDevices
--- PASS: TestAccAWSLaunchConfiguration_updateEbsBlockDevices (83.35s)
=== RUN   TestAccAWSLaunchConfiguration_ebs_noDevice
--- PASS: TestAccAWSLaunchConfiguration_ebs_noDevice (45.43s)
=== RUN   TestAccAWSLaunchConfiguration_userData
--- PASS: TestAccAWSLaunchConfiguration_userData (76.23s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	704.454s
```

**Comment by gseyetik** [comment]
It is not clear to me why the introduction of a new attribute was needed here. The only issue with #2800 was that the "StateFunc" for "user_data" did double encoding of already Base64 encoded data. 

To address this issue we could have updated use "StateFunc" for "user_data" to utilize the "userDataHashSum" function.

@bflad

**Comment by bflad** [comment]
This has been released in [version 1.16.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1160-april-25-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.

**Comment by ibrahima** [comment]
Agree with @gseyetik , the issue I reported is now fixed in v1.16.0 without actually using the new attribute.

**Pull request merged**
