### PR TITLE
Handle nil value for AutoVerifiedAttributes in CognitoUserPool

### LINKED ISSUE #3009: AutoVerifiedAttributes for CognitoUserPool being removed by terraform
Hi,

I'm having a strange behaviour with `aws_cognito_user_pool`. Sorry if this doesn't contain enough information. I can provide a bit more if needed.

### Terraform Version
```
Terraform v0.11.1
+ provider.archive v1.0.0
+ provider.aws v1.7.0
+ provider.external v1.0.0
+ provider.null v1.0.0
+ provider.template v1.0.0
```

### Affected Resource
- `aws_cognito_user_pool`

### Terraform Configuration Files
```hcl
# I've masked the domain name
resource "aws_cognito_user_pool" "main" {
  name = "Main"

  username_attributes      = ["email"]
  auto_verified_attributes = ["email"]

  device_configuration {
    device_only_remembered_on_user_prompt = "true"
  }

  email_configuration {
    source_arn = "arn:aws:ses:eu-west-1:${var.production_account_id}:identity/comms@XXXXXX"
  }

  email_verification_subject = "Confirm your email"
  email_verification_message = "<a href=\"https://XXXXXX/confirm?username={username}&amp;code={####}\">Click here to verify your email address.</a>"
  sms_authentication_message = "Your authentication code is {####}. "
  sms_verification_message   = "Your verification code is {####}. "

  mfa_configuration = "OFF"

  password_policy {
    minimum_length    = 8
    require_lowercase = false
    require_uppercase = false
    require_numbers   = false
    require_symbols   = false
  }

  admin_create_user_config {
    allow_admin_create_user_only = false
    unused_account_validity_days = 7

    invite_message_template {
      email_message = "Your username is {username} and temporary password is {####}. "
      email_subject = "Your temporary password"
      sms_message   = "Your username is {username} and temporary password is {####}. "
    }
  }

  schema {
    name                = "email"
    attribute_data_type = "String"
    required            = true
    mutable             = true
  }
}
```

### Expected Behavior
`AutoVerifiedAttributes` should contain `email`

### Actual Behavior
`AutoVerifiedAttributes` doesn't contain `email`

### Steps to Reproduce
1. Turn email verification on from the aws console
2. `aws cognito-idp describe-user-pool --user-pool-id eu-west-2_XXXXXX > output1.txt`
3. `terraform apply`
4. `aws cognito-idp describe-user-pool --user-pool-id eu-west-2_XXXXXX > output2.txt`
5. `diff output1.txt output2.txt`

```
11c11
< ||  LastModifiedDate                                              |  1516123461.045                                         ||
---
> ||  LastModifiedDate                                              |  1516124308.176                                         ||
20,28c20,25
< |||                                                 AutoVerifiedAttributes                                                 |||
< ||+------------------------------------------------------------------------------------------------------------------------+||
< |||  email                                                                                                                 |||
< ||+------------------------------------------------------------------------------------------------------------------------+||
< |||                                                   DeviceConfiguration                                                  |||
< ||+------------------------------------------------------------------------------------------------+-----------------------+||
< |||  ChallengeRequiredOnNewDevice                                                                  |  False                |||
< |||  DeviceOnlyRememberedOnUserPrompt                                                              |  True                 |||
< ||+------------------------------------------------------------------------------------------------+-----------------------+||
---
> ||||                                                 InviteMessageTemplate                                                ||||
> |||+---------------------+------------------------------------------------------------------------------------------------+|||
> ||||  EmailMessage       |  Your username is {username} and temporary password is {####}.                                 ||||
> ||||  EmailSubject       |  Your temporary password                                                                       ||||
> ||||  SMSMessage         |  Your username is {username} and temporary password is {####}.                                 ||||
> |||+---------------------+------------------------------------------------------------------------------------------------+|||
```

You can see that for some reason `AutoVerifiedAttributes` is gone from `output2.txt`

### PR DESCRIPTION
**Pull request by louy**
Fixes #3009

### CODE REVIEW

**Comment by Puneeth-n** [comment]
@bflad This PR seems to be orphaned. Would you mind if I hijacked it and took it till the end?

**Comment by louy** [comment]
@Puneeth-n I've yet not managed to find time to finish it so please do!

**Comment by Puneeth-n** [comment]
Will give it a spin later and create a separate PR. Thanks :)

**Comment by bflad** [comment]
The updated PR has been merged into master and will release with v1.12.0 of the AWS provider, likely in about a week. 😄

**Comment by bflad** [comment]
The updated PR has been released in [version 1.12.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1120-march-23-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.

**Pull request closed without merging**
