### PR TITLE
Allow keeping the old task definition revisions when updating

### LINKED ISSUE #258: aws_ecs_task_definition overwrites previous revision
_This issue was originally opened by @dimahavrylevych as hashicorp/terraform#8740. It was migrated here as part of the [provider split](https://www.hashicorp.com/blog/upcoming-provider-changes-in-terraform-0-10/). The original body of the issue is below._

<hr>

Hello community, 

I faced an issue while working with `aws_ecs_task_definition`. 
I have a script:

```
data "template_file" "task_definition" {
  template = "${file("task-definitions/service.json")}"
  vars {
    SERVICE_NAME = "test"
    IMAGE_URL = "test:latest"
  }
}

resource "aws_ecs_task_definition" "test" {
    family = "test"
    network_mode = "bridge"
    container_definitions = "${data.template_file.task_definition.rendered}"
}

resource "aws_ecs_service" "test" {
  name = "test"
  cluster = "test"
  task_definition = "${aws_ecs_task_definition.test.arn}"
  desired_count = 2
  deployment_minimum_healthy_percent = 100
}
```

Im trying to running: `terraform plan` so the part of output looks like:

```
-/+ ...
...
 revision:              "24" => "<computed>"
...
```

While running `terraform apply` and loging to AWS I see that the new revision has created but the previous one dissapeared. 
### Question:

Is is possible to implement a flag that will allow me to save previous revisions?

### PR DESCRIPTION
**Pull request by tomelliff**
Task definition revisions are immutable so Terraform is unable to just update this resource and instead needs to delete the old revision and create a new one.
This isn't helpful if you still want access to the old task definition such as if you are using another system to manage rollbacks etc as you are unable to roll a service back to an inactive task definition.

Personally I was happy with the current state of affairs for a while because I had Gitlab CI run deploys with Terraform and a roll back was to run a deployment with the previous commit SHA tagged Docker image which created a further task revision but largely worked fine.
Unfortunately I now have a new requirement where we need to create our own ECS orchestrator for a specific workload and that will need to be able to schedule tasks from previous versions.
Without this change (or an equivalent) we will be forced to ditch Terraform for the task definition creation for this workload which makes it harder to more centrally manage shared, abstracted stuff (such as logging config etc) which is currently handled in a Terraform module and shared across all of our services.

A similar, although incomplete and not working, PR (#4198) was raised by @binarydud a while back but @bflad was hoping that https://github.com/hashicorp/terraform/issues/3874 would solve this in a wider way. Unfortunately that's yet to have any development started on it yet.
If it's still deemed to be the better approach and this is wanted to be the way we go then I could take a stab at the core lifecycle change instead but I suspect the timescales on that are going to be a lot longer than works for the timeframe I would like to land this in.
As a hedge, if we could ship this change for now this would help a few other users as well as myself and I can take a better look at the core changes required for a different lifecycle flag.

Closes https://github.com/terraform-providers/terraform-provider-aws/issues/258

Fixes #258

Changes proposed in this pull request:

* Adds a `keep_old_task_definitions` flag that skips the deletion (setting `INACTIVE`) of the old task definition.

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccAWSEcsTaskDefinition_'==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./... -v -parallel 20 -run=TestAccAWSEcsTaskDefinition_ -timeout 120m
?   	github.com/terraform-providers/terraform-provider-aws	[no test files]
=== RUN   TestAccAWSEcsTaskDefinition_basic
=== PAUSE TestAccAWSEcsTaskDefinition_basic
=== RUN   TestAccAWSEcsTaskDefinition_withScratchVolume
=== PAUSE TestAccAWSEcsTaskDefinition_withScratchVolume
=== RUN   TestAccAWSEcsTaskDefinition_withDockerVolume
=== PAUSE TestAccAWSEcsTaskDefinition_withDockerVolume
=== RUN   TestAccAWSEcsTaskDefinition_withDockerVolumeMinimalConfig
=== PAUSE TestAccAWSEcsTaskDefinition_withDockerVolumeMinimalConfig
=== RUN   TestAccAWSEcsTaskDefinition_withTaskScopedDockerVolume
=== PAUSE TestAccAWSEcsTaskDefinition_withTaskScopedDockerVolume
=== RUN   TestAccAWSEcsTaskDefinition_withEcsService
=== PAUSE TestAccAWSEcsTaskDefinition_withEcsService
=== RUN   TestAccAWSEcsTaskDefinition_withTaskRoleArn
=== PAUSE TestAccAWSEcsTaskDefinition_withTaskRoleArn
=== RUN   TestAccAWSEcsTaskDefinition_withNetworkMode
=== PAUSE TestAccAWSEcsTaskDefinition_withNetworkMode
=== RUN   TestAccAWSEcsTaskDefinition_constraint
=== PAUSE TestAccAWSEcsTaskDefinition_constraint
=== RUN   TestAccAWSEcsTaskDefinition_changeForcesNewResource
=== PAUSE TestAccAWSEcsTaskDefinition_changeForcesNewResource
=== RUN   TestAccAWSEcsTaskDefinition_arrays
=== PAUSE TestAccAWSEcsTaskDefinition_arrays
=== RUN   TestAccAWSEcsTaskDefinition_Fargate
=== PAUSE TestAccAWSEcsTaskDefinition_Fargate
=== RUN   TestAccAWSEcsTaskDefinition_ExecutionRole
=== PAUSE TestAccAWSEcsTaskDefinition_ExecutionRole
=== RUN   TestAccAWSEcsTaskDefinition_Inactive
=== PAUSE TestAccAWSEcsTaskDefinition_Inactive
=== CONT  TestAccAWSEcsTaskDefinition_basic
=== CONT  TestAccAWSEcsTaskDefinition_constraint
=== CONT  TestAccAWSEcsTaskDefinition_withScratchVolume
=== CONT  TestAccAWSEcsTaskDefinition_ExecutionRole
=== CONT  TestAccAWSEcsTaskDefinition_arrays
=== CONT  TestAccAWSEcsTaskDefinition_withTaskScopedDockerVolume
=== CONT  TestAccAWSEcsTaskDefinition_withNetworkMode
=== CONT  TestAccAWSEcsTaskDefinition_withTaskRoleArn
=== CONT  TestAccAWSEcsTaskDefinition_Inactive
=== CONT  TestAccAWSEcsTaskDefinition_Fargate
=== CONT  TestAccAWSEcsTaskDefinition_withEcsService
=== CONT  TestAccAWSEcsTaskDefinition_withDockerVolume
=== CONT  TestAccAWSEcsTaskDefinition_withDockerVolumeMinimalConfig
=== CONT  TestAccAWSEcsTaskDefinition_changeForcesNewResource
--- PASS: TestAccAWSEcsTaskDefinition_withTaskScopedDockerVolume (21.38s)
--- PASS: TestAccAWSEcsTaskDefinition_withDockerVolumeMinimalConfig (21.52s)
--- PASS: TestAccAWSEcsTaskDefinition_arrays (21.73s)
--- PASS: TestAccAWSEcsTaskDefinition_withDockerVolume (21.89s)
--- PASS: TestAccAWSEcsTaskDefinition_constraint (22.74s)
--- PASS: TestAccAWSEcsTaskDefinition_withScratchVolume (22.92s)
--- PASS: TestAccAWSEcsTaskDefinition_withNetworkMode (24.42s)
--- PASS: TestAccAWSEcsTaskDefinition_withTaskRoleArn (25.20s)
--- PASS: TestAccAWSEcsTaskDefinition_ExecutionRole (26.20s)
--- PASS: TestAccAWSEcsTaskDefinition_Fargate (30.88s)
--- PASS: TestAccAWSEcsTaskDefinition_Inactive (36.76s)
--- PASS: TestAccAWSEcsTaskDefinition_basic (37.94s)
--- PASS: TestAccAWSEcsTaskDefinition_withEcsService (51.92s)
--- PASS: TestAccAWSEcsTaskDefinition_changeForcesNewResource (110.09s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	110.109s
...
```

### CODE REVIEW

**Comment by tomelliff** [comment]
Note that `TestAccAWSEcsTaskDefinition_changeForcesNewResource` currently leaves a dangling active task definition revision (the second one of the four created).

I'm not sure if that's an issue because there's no charge for active task definitions and having all inactive task definition revisions for a family doesn't clean up the resource and they're always left in the AWS account.

I can write a sweeper to remove dangling active task definitions when left behind by this test if it's needed though.

**Comment by tomelliff** [comment]
Now that I think about it I don't think this functionality would fit with the proposals in the linked core issue (https://github.com/hashicorp/terraform/issues/3874) as this is about a replacement of an immutable resource.

The lifecycle issue over at core would need to skip the deletion of the resource but also maintain state for the resource otherwise an apply after the skipped deletion would create a duplicate resource (or error on a duplicate clash).

If we used that same lifecycle proposal with ECS task definitions then we'd have a problem as we have another resource's state to track instead.

This PR does away with that by removing the resource state but leaving the resource in AWS alone, simplifying things.

**Comment by bjweaver** [comment]
Any update with this PR?  We have been looking for this functionality so have better rollback of the taskdef when a healthcheck fails.

**Comment by binarydud** [comment]
would love to see this land in the provider

**Comment by tomelliff** [comment]
Rebased on master after the tag changes caused merge conflicts. I want to rerun the acceptance tests on this once I get off the train and to somewhere with a stable internet connection just to be safe.

**Comment by tomelliff** [comment]
Still interested in landing this at some point if anyone wouldn't mind reviewing it? We're going to need this functionality for the forseeable future and I'm not sure if it really works as a feature in core either.

[This comment](https://github.com/hashicorp/terraform/issues/15485#issuecomment-401969070) from @apparentlymart also suggests moving this functionality out to providers and specific resources right now.

**Comment by FernandoMiguel** [comment]
Wouldn't having a new state file just for a new task definition solve most of the issues?

**Comment by tomelliff** [comment]
We create more than the task definition with Terraform so that's not really applicable to us. We also don't want new task definitions being created if nothing has changed so I don't want to just rm it out of the state out of band each time.

**Comment by tomelliff** [comment]
Rebased on v2.4.0

**Comment by tomelliff** [comment]
Rebased on top of v2.11.0 (after mucking it up first :/)

**Comment by bbeesley** [comment]
Any news on when this might be merged? I'm going to need to put together a dirty hack otherwise...

**Comment by tomelliff** [comment]
We build off my fork but I'm force pushing changes when we need a newer AWS provider version so unless you're happy to take my new versions as well then I'd recommend forking from my branch.

I suspect this won't get merged but the design around a new lifecycle to support this ability in core more broadly is still uncertain so it's equally difficult to do this in core instead which would arguably be the better place for it.

If I get some free time at some point I might draft up a PR for the new lifecycle action in core but it's hard to justify the time for something without obvious scope and design right now.

**Comment by tomelliff** [comment]
As mentioned above I don't think it will be merged at this point because, as pointed out elsewhere, there are workarounds for this such as removing the task definition from state before hand.

As it turns out I've decided to go in that direction rather than maintain this fork which slows down our team from keeping up to date with AWS provider versions.

Instead we make sure that CI removes the relevant task definitions from state before applying changes. This is fine as long as you can assume that only CI would apply out changes anyway because humans are fallible and could forget this step. Alternatively you could write something to automatically remove any task definitions from state before applying if you are wrapping Terraform in a shell script or something else like a lot of people do (myself included).

Although our custom scheduler for one of our workloads still needs this it's also not really all that disastrous because even if a task definition is accidentally deleted somehow we can redeploy an older version of our application and it will create a forward release of that older version.

I'm going to close this pull request to clean things up for the maintainers. If a maintainer thinks this is worth merging at some point then I am happy to rebase it at that point but otherwise I'm going to assume that the workaround should be removing state instead.

**Pull request closed without merging**
