### PR TITLE
support for importing aws_default_route_table resource

### LINKED ISSUE #12912: Support aws_default_route_table Resource Import
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The `aws_default_route_table` resource does not currently support import. It would be great if it did!

Implementation should include:
- [x] Resource `Importer` `State` implementation
- [x] Acceptance testing with `ImportState` and `ImportStateVerify`
- [x] Documentation

### Affected Resource(s)

* aws_default_route_table

### References

* [Contributing Guide section on Adding Resource Import Support](https://github.com/terraform-providers/terraform-provider-aws/blob/master/.github/CONTRIBUTING.md#adding-resource-import-support)

### PR DESCRIPTION
**Pull request by anGie44**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #12912

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
add support for importing aws_default_route_table resource and set tags on creation
```

Output from acceptance testing:

```
--- PASS: TestAccAWSDefaultRouteTable_disappears_Vpc (20.22s)
--- PASS: TestAccAWSDefaultRouteTable_basic (40.65s)
--- PASS: TestAccAWSDefaultRouteTable_vpc_endpoint (50.58s)
--- PASS: TestAccAWSDefaultRouteTable_swap (70.84s)
--- PASS: TestAccAWSDefaultRouteTable_Route (86.11s)
--- PASS: TestAccAWSDefaultRouteTable_Route_TransitGatewayID (296.34s)
```

### CODE REVIEW

**Comment by DrFaust92** [comment]
i think this is partially similar to https://github.com/terraform-providers/terraform-provider-aws/pull/12858 (from tags perspective)

**Comment by ewbankkit** [comment]
Verified acceptance tests:

```console
$ make testacc TEST=./aws/ TESTARGS='-run=TestAccAWSDefaultRouteTable_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws/ -v -count 1 -parallel 20 -run=TestAccAWSDefaultRouteTable_ -timeout 120m
=== RUN   TestAccAWSDefaultRouteTable_basic
=== PAUSE TestAccAWSDefaultRouteTable_basic
=== RUN   TestAccAWSDefaultRouteTable_disappears_Vpc
=== PAUSE TestAccAWSDefaultRouteTable_disappears_Vpc
=== RUN   TestAccAWSDefaultRouteTable_Route
=== PAUSE TestAccAWSDefaultRouteTable_Route
=== RUN   TestAccAWSDefaultRouteTable_swap
=== PAUSE TestAccAWSDefaultRouteTable_swap
=== RUN   TestAccAWSDefaultRouteTable_Route_TransitGatewayID
=== PAUSE TestAccAWSDefaultRouteTable_Route_TransitGatewayID
=== RUN   TestAccAWSDefaultRouteTable_vpc_endpoint
=== PAUSE TestAccAWSDefaultRouteTable_vpc_endpoint
=== CONT  TestAccAWSDefaultRouteTable_disappears_Vpc
=== CONT  TestAccAWSDefaultRouteTable_vpc_endpoint
=== CONT  TestAccAWSDefaultRouteTable_Route_TransitGatewayID
=== CONT  TestAccAWSDefaultRouteTable_swap
=== CONT  TestAccAWSDefaultRouteTable_Route
=== CONT  TestAccAWSDefaultRouteTable_basic
--- PASS: TestAccAWSDefaultRouteTable_disappears_Vpc (25.15s)
--- PASS: TestAccAWSDefaultRouteTable_basic (52.36s)
--- PASS: TestAccAWSDefaultRouteTable_vpc_endpoint (56.68s)
--- PASS: TestAccAWSDefaultRouteTable_swap (80.88s)
--- PASS: TestAccAWSDefaultRouteTable_Route (99.38s)
--- PASS: TestAccAWSDefaultRouteTable_Route_TransitGatewayID (315.23s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	315.272s
```

**Comment by anGie44** [comment]
@DrFaust92 thanks for catching that! I'll remove the change from here then

**Comment by anGie44** [comment]
Updated acceptance test output: 
```
--- FAIL: TestAccAWSDefaultRouteTable_Route (41.33s)
--- FAIL: TestAccAWSDefaultRouteTable_vpc_endpoint (41.80s)
--- FAIL: TestAccAWSDefaultRouteTable_swap (43.09s)
--- PASS: TestAccAWSDefaultRouteTable_disappears_Vpc (20.78s)
--- PASS: TestAccAWSDefaultRouteTable_basic (44.67s)
--- PASS: TestAccAWSDefaultRouteTable_Route_TransitGatewayID (336.92s)
```

Note: failures to be fixed with #12858

**Comment by anGie44** [comment]
After merging with master, acceptanct test output:
```
PASS:  TestAccAWSDefaultRouteTable_disappears_Vpc
PASS:  TestAccAWSDefaultRouteTable_basic
PASS:  TestAccAWSDefaultRouteTable_tags
PASS:  TestAccAWSDefaultRouteTable_vpc_endpoint
PASS:  TestAccAWSDefaultRouteTable_swap
PASS:  TestAccAWSDefaultRouteTable_Route
PASS:  TestAccAWSDefaultRouteTable_Route_TransitGatewayID
```

**Pull request merged**
