### PR TITLE
Adding processing_configuration to elasticsearch section

### PR DESCRIPTION
**Pull request by jamesrenfro**
This is a partial fix for the issue listed below. The problem currently is
that you can add an extended_s3_configuration to the
aws_kinesis_firehose_delivery_stream and set the destination to 'extended_s3'
if you want data transformation to be enabled for S3, but you can't do the
same if your destination is 'elastisearch' - this commit fixes that.

Support Kinesis Firehose Data Transformation #513
https://github.com/terraform-providers/terraform-provider-aws/issues/513

### CODE REVIEW

**Comment by bflad** [comment]
Can you please add an acceptance test that exercises this new code? You can take a look at #3944 for inspiration

**Comment by bflad** [comment]
Actually do not worry about the acceptance testing, I will add it before I merge, as I would like to submit a followup PR to prevent some crashes that will interfere with the implementation of this PR as-is.

**Comment by jamesrenfro** [comment]
Ok - thanks very much!

**Comment by bflad** [comment]
This has been released in [version 1.14.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1140-april-06-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.

**Pull request merged**
