### PR TITLE
Update provider's S3 bucket lookup to use GetBucketRegion utility

### LINKED ISSUE #14217: Amazon S3 buckets region lookup with FIPS endpoints will fail with dial tcp errors.
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The Terraform's AWS Provider uses the aws-sdk-go's Amazon S3 client's [GetBucketLocation](https://docs.aws.amazon.com/AmazonS3/latest/API/API_GetBucketLocation.html) to discover the AWS region of the user's Amazon S3 Bucket. This works fine for Buckets that are owned by the user, and when the user is using Terraform with a non-FIPS endpoint, (e.g. `s3.us-west-2.amazonaws.com`). But, if the user uses Terraform configured for a FIPS region like `s3-fips.us-east-1.amazonaws.com` attmpts to get the bucket's region will fail with an error, like:

```
Get https://s3-fips.us-east-1.amazonaws.com/testbucket?location=: dial tcp: lookup s3-fips.us-east-1.amazonaws.com: no such host
```
This error is caused by the `aws-sdk-go` Amazon S3 client's GetBucketLocation implementation. The SDK uses `path style` endpoint building pattern. This pattern puts the `BucketName` into the URI path. This is in conflict with S3 behavior for FIPS regions, which require the BucketName to be in the endpoint host prefix. This pattern is called `virtual host style`.

* Virtual host style: `bucketname.s3.us-west-2.amazonaws.com`
* Path style: `s3.us-west-2.amazonaws.com/bucketname`

Most of the SDKs customize the GetBucketLocation operation to use path style only, to address under documented error behavior. This makes the operation awkward to use when discovering the region of a bucket due to how virtual host style requests will return AWS signature errors when the request is made to the wrong region.

To address this issue the aws-sdk-go library created a [s3manager.GetBucketRegion](https://docs.aws.amazon.com/sdk-for-go/api/service/s3/s3manager/#GetBucketRegion) utility. This utility allows discovery of a Bucket's region regardless of ownership, and is compatible with FIPS endpoints.

```go
	region, err := s3manager.GetBucketRegionWithClient(context.Background(), s3Client, "mybucket",
		func(r *request.Request) {
			r.Config.S3ForcePathStyle = aws.Bool(false)
		})
```

The extra functional option disabling path style is done to ensure that the call is compatible with FIPS endpoints.

### New or Affected Resource(s)

Looks like Terraform uses GetBucketLocation in 3 locations:
* [resource_aws_s3_bucket.go](https://github.com/terraform-providers/terraform-provider-aws/blob/96b93a820be442bc157fab0bd5b6a6b412b282e8/aws/resource_aws_s3_bucket.go)
* [resource_aws_s3_bucket_test.go](https://github.com/terraform-providers/terraform-provider-aws/blob/844f6b9bf03c505e272ed1e0d6db221d826216b7/aws/resource_aws_s3_bucket_test.go)
* [data_source_aws_s3_bucket.go](https://github.com/terraform-providers/terraform-provider-aws/blob/e3e065deda322c0e29bc071d2ba85fef801a4e04/aws/data_source_aws_s3_bucket.go)

If these were updated to use the `s3manager.GetBucketRegion` or `s3manager.GetBucketRegionWithClient` utility instead of `GetBucketLocation` operation users would be able to use Amazon S3 FIPS endpoints with Terraform's bucket region discovery.

### References

This is related to https://github.com/aws/aws-sdk-go/issues/3115 for AWS SDK for Go.

### PR DESCRIPTION
**Pull request by jasdel**
This change updates the AWS Provider to use GetBucketRegion utility instead of the GetBucketLocation S3 API operation. This utility can discover the bucket's region without authentication, buckets not owned by the user, and to be compatible with FIPS endpoints.

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #14217
Relates https://github.com/aws/aws-sdk-go/issues/3115

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
Replaces the usage of S3's GetBucketLocation with the aws-sdk-go's GetBucketRegion utility. This utility can discover the bucket's region without authentication, buckets not owned by the user, and to be compatible with FIPS endpoints.
```

Output from acceptance testing:

```
make testacc TESTARGS='-run=TestAccDataSourceAWSS3'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccDataSourceAWSS3 -timeout 120m
=== RUN   TestAccDataSourceAWSS3BucketObject_basic
=== PAUSE TestAccDataSourceAWSS3BucketObject_basic
=== RUN   TestAccDataSourceAWSS3BucketObject_basicViaAccessPoint
=== PAUSE TestAccDataSourceAWSS3BucketObject_basicViaAccessPoint
=== RUN   TestAccDataSourceAWSS3BucketObject_readableBody
=== PAUSE TestAccDataSourceAWSS3BucketObject_readableBody
=== RUN   TestAccDataSourceAWSS3BucketObject_kmsEncrypted
=== PAUSE TestAccDataSourceAWSS3BucketObject_kmsEncrypted
=== RUN   TestAccDataSourceAWSS3BucketObject_allParams
=== PAUSE TestAccDataSourceAWSS3BucketObject_allParams
=== RUN   TestAccDataSourceAWSS3BucketObject_ObjectLockLegalHoldOff
=== PAUSE TestAccDataSourceAWSS3BucketObject_ObjectLockLegalHoldOff
=== RUN   TestAccDataSourceAWSS3BucketObject_ObjectLockLegalHoldOn
=== PAUSE TestAccDataSourceAWSS3BucketObject_ObjectLockLegalHoldOn
=== RUN   TestAccDataSourceAWSS3BucketObject_LeadingSlash
=== PAUSE TestAccDataSourceAWSS3BucketObject_LeadingSlash
=== RUN   TestAccDataSourceAWSS3BucketObject_MultipleSlashes
=== PAUSE TestAccDataSourceAWSS3BucketObject_MultipleSlashes
=== RUN   TestAccDataSourceAWSS3BucketObjects_basic
=== PAUSE TestAccDataSourceAWSS3BucketObjects_basic
=== RUN   TestAccDataSourceAWSS3BucketObjects_basicViaAccessPoint
=== PAUSE TestAccDataSourceAWSS3BucketObjects_basicViaAccessPoint
=== RUN   TestAccDataSourceAWSS3BucketObjects_all
=== PAUSE TestAccDataSourceAWSS3BucketObjects_all
=== RUN   TestAccDataSourceAWSS3BucketObjects_prefixes
=== PAUSE TestAccDataSourceAWSS3BucketObjects_prefixes
=== RUN   TestAccDataSourceAWSS3BucketObjects_encoded
=== PAUSE TestAccDataSourceAWSS3BucketObjects_encoded
=== RUN   TestAccDataSourceAWSS3BucketObjects_maxKeys
=== PAUSE TestAccDataSourceAWSS3BucketObjects_maxKeys
=== RUN   TestAccDataSourceAWSS3BucketObjects_startAfter
=== PAUSE TestAccDataSourceAWSS3BucketObjects_startAfter
=== RUN   TestAccDataSourceAWSS3BucketObjects_fetchOwner
=== PAUSE TestAccDataSourceAWSS3BucketObjects_fetchOwner
=== CONT  TestAccDataSourceAWSS3BucketObject_basic
=== CONT  TestAccDataSourceAWSS3BucketObjects_basicViaAccessPoint
=== CONT  TestAccDataSourceAWSS3BucketObjects_encoded
=== CONT  TestAccDataSourceAWSS3BucketObjects_maxKeys
=== CONT  TestAccDataSourceAWSS3BucketObject_ObjectLockLegalHoldOff
=== CONT  TestAccDataSourceAWSS3BucketObjects_fetchOwner
=== CONT  TestAccDataSourceAWSS3BucketObject_ObjectLockLegalHoldOn
=== CONT  TestAccDataSourceAWSS3BucketObjects_startAfter
=== CONT  TestAccDataSourceAWSS3BucketObjects_prefixes
=== CONT  TestAccDataSourceAWSS3BucketObject_kmsEncrypted
=== CONT  TestAccDataSourceAWSS3BucketObject_allParams
=== CONT  TestAccDataSourceAWSS3BucketObjects_all
=== CONT  TestAccDataSourceAWSS3BucketObject_basicViaAccessPoint
=== CONT  TestAccDataSourceAWSS3BucketObjects_basic
=== CONT  TestAccDataSourceAWSS3BucketObject_MultipleSlashes
=== CONT  TestAccDataSourceAWSS3BucketObject_LeadingSlash
=== CONT  TestAccDataSourceAWSS3BucketObject_readableBody
--- PASS: TestAccDataSourceAWSS3BucketObject_basic (24.31s)
--- PASS: TestAccDataSourceAWSS3BucketObject_readableBody (26.84s)
--- PASS: TestAccDataSourceAWSS3BucketObject_ObjectLockLegalHoldOff (28.26s)
--- PASS: TestAccDataSourceAWSS3BucketObject_kmsEncrypted (28.62s)
--- PASS: TestAccDataSourceAWSS3BucketObject_basicViaAccessPoint (29.24s)
--- PASS: TestAccDataSourceAWSS3BucketObject_ObjectLockLegalHoldOn (30.11s)
--- PASS: TestAccDataSourceAWSS3BucketObject_allParams (30.11s)
--- PASS: TestAccDataSourceAWSS3BucketObjects_basic (33.90s)
--- PASS: TestAccDataSourceAWSS3BucketObjects_prefixes (34.24s)
--- PASS: TestAccDataSourceAWSS3BucketObjects_maxKeys (34.35s)
--- PASS: TestAccDataSourceAWSS3BucketObject_MultipleSlashes (34.58s)
--- PASS: TestAccDataSourceAWSS3BucketObjects_fetchOwner (34.92s)
--- PASS: TestAccDataSourceAWSS3BucketObjects_basicViaAccessPoint (35.48s)
--- PASS: TestAccDataSourceAWSS3BucketObjects_startAfter (35.51s)
--- PASS: TestAccDataSourceAWSS3BucketObjects_encoded (36.23s)
--- PASS: TestAccDataSourceAWSS3BucketObjects_all (36.96s)
--- PASS: TestAccDataSourceAWSS3BucketObject_LeadingSlash (37.30s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	38.541s

make testacc TESTARGS='-run=TestAccDataSourceS3'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccDataSourceS3 -timeout 120m
=== RUN   TestAccDataSourceS3Bucket_basic
=== PAUSE TestAccDataSourceS3Bucket_basic
=== RUN   TestAccDataSourceS3Bucket_website
=== PAUSE TestAccDataSourceS3Bucket_website
=== CONT  TestAccDataSourceS3Bucket_basic
=== CONT  TestAccDataSourceS3Bucket_website
--- PASS: TestAccDataSourceS3Bucket_website (16.89s)
--- PASS: TestAccDataSourceS3Bucket_basic (17.51s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	18.713s
```

### CODE REVIEW

**Comment by jasdel** [comment]
Not quite sure why the `golangci-lint` litter is failing. `make build` `test` built locally.

**Comment by ewbankkit** [comment]
@jasdel Thanks for the contirbution.
The problem with `golangci-lint` will be because of the use of the new (to the provider) package `github.com/aws/aws-sdk-go/service/s3/s3manager`. Please run

```console
go mod tidy
go mod vendor
```

and commit the resulting changes.
That should clean up the CI build.

**Comment by jasdel** [comment]
Thanks! I didn't think of that, makes sense. Updated dependencies using that command.

**Comment by jasdel** [comment]
Ah looks like per the failing check:

> Ensure the new AWS service changes are following the [Contributing Guide section on new services](https://github.com/terraform-providers/terraform-provider-aws/blob/master/docs/contributing/contribution-checklists.md#new-service), in particular that the dependency addition and initial provider support are in a separate pull request from other changes (e.g. new resources). Contributions not following this item will not be reviewed until the changes are split.

I should split the vendor changes out into their own pull request, and rebase this one off that?

**Comment by ewbankkit** [comment]
@jasdel That's fine, leave the PR as-is. This isn't exactly adding a new service, more like adding a subset of an existing service.

**Comment by bflad** [comment]
Hey @jasdel 👋  Great to hear from you and thank you for submitting this. I replied to you out-of-band to hopefully discuss some things before we go this direction and pull this in.

This passes all existing S3 Bucket testing in Commercial (us-west-2) and GovCloud (us-gov-west-1), running a little wider swath of tests just to be sure. We'll need to backfill FIPS endpoint testing, which is not well supported by our provider configuration and testing framework at the moment, but I don't want to hold up this on account of that shortcoming.

Output from acceptance testing in AWS Commercial:

```
--- PASS: TestAccAWSS3Bucket_acceleration (33.77s)
--- PASS: TestAccAWSS3Bucket_AclToGrant (31.06s)
--- PASS: TestAccAWSS3Bucket_basic (19.08s)
--- PASS: TestAccAWSS3Bucket_Bucket_EmptyString (19.83s)
--- PASS: TestAccAWSS3Bucket_Cors_Delete (18.82s)
--- PASS: TestAccAWSS3Bucket_Cors_EmptyOrigin (23.59s)
--- PASS: TestAccAWSS3Bucket_Cors_Update (34.66s)
--- PASS: TestAccAWSS3Bucket_disableDefaultEncryption_whenDefaultEncryptionIsEnabled (34.38s)
--- PASS: TestAccAWSS3Bucket_enableDefaultEncryption_whenAES256IsUsed (21.20s)
--- PASS: TestAccAWSS3Bucket_enableDefaultEncryption_whenTypical (22.64s)
--- PASS: TestAccAWSS3Bucket_forceDestroy (14.50s)
--- PASS: TestAccAWSS3Bucket_forceDestroyWithEmptyPrefixes (14.84s)
--- PASS: TestAccAWSS3Bucket_forceDestroyWithObjectLockEnabled (15.16s)
--- PASS: TestAccAWSS3Bucket_generatedName (20.12s)
--- PASS: TestAccAWSS3Bucket_GrantToAcl (33.22s)
--- PASS: TestAccAWSS3Bucket_LifecycleExpireMarkerOnly (31.64s)
--- PASS: TestAccAWSS3Bucket_LifecycleRule_Expiration_EmptyConfigurationBlock (19.75s)
--- PASS: TestAccAWSS3Bucket_Logging (25.99s)
--- PASS: TestAccAWSS3Bucket_namePrefix (20.86s)
--- PASS: TestAccAWSS3Bucket_objectLock (23.75s)
--- PASS: TestAccAWSS3Bucket_Policy (47.38s)
--- PASS: TestAccAWSS3Bucket_Replication (113.25s)
--- PASS: TestAccAWSS3Bucket_ReplicationConfiguration_Rule_Destination_AccessControlTranslation (68.94s)
--- PASS: TestAccAWSS3Bucket_ReplicationConfiguration_Rule_Destination_AddAccessControlTranslation (68.35s)
--- PASS: TestAccAWSS3Bucket_ReplicationExpectVersioningValidationError (30.44s)
--- PASS: TestAccAWSS3Bucket_ReplicationSchemaV2 (111.32s)
--- PASS: TestAccAWSS3Bucket_ReplicationWithoutPrefix (55.07s)
--- PASS: TestAccAWSS3Bucket_ReplicationWithoutStorageClass (55.17s)
--- PASS: TestAccAWSS3Bucket_RequestPayer (34.34s)
--- PASS: TestAccAWSS3Bucket_shouldFailNotFound (14.96s)
--- PASS: TestAccAWSS3Bucket_tagsWithNoSystemTags (69.74s)
--- PASS: TestAccAWSS3Bucket_tagsWithSystemTags (95.66s)
--- PASS: TestAccAWSS3Bucket_UpdateAcl (31.57s)
--- PASS: TestAccAWSS3Bucket_UpdateGrant (47.95s)
--- PASS: TestAccAWSS3Bucket_Versioning (43.70s)
--- PASS: TestAccAWSS3Bucket_Website_Simple (46.58s)
--- PASS: TestAccAWSS3Bucket_WebsiteRedirect (45.72s)
--- PASS: TestAccAWSS3Bucket_WebsiteRoutingRules (35.48s)

--- PASS: TestAccAWSS3BucketAnalyticsConfiguration_basic (22.26s)
--- PASS: TestAccAWSS3BucketAnalyticsConfiguration_removed (39.13s)
--- PASS: TestAccAWSS3BucketAnalyticsConfiguration_updateBasic (63.51s)
--- PASS: TestAccAWSS3BucketAnalyticsConfiguration_WithFilter_Empty (3.90s)
--- PASS: TestAccAWSS3BucketAnalyticsConfiguration_WithFilter_MultipleTags (28.01s)
--- PASS: TestAccAWSS3BucketAnalyticsConfiguration_WithFilter_Prefix (30.50s)
--- PASS: TestAccAWSS3BucketAnalyticsConfiguration_WithFilter_PrefixAndTags (29.86s)
--- PASS: TestAccAWSS3BucketAnalyticsConfiguration_WithFilter_Remove (38.04s)
--- PASS: TestAccAWSS3BucketAnalyticsConfiguration_WithFilter_SingleTag (53.61s)
--- PASS: TestAccAWSS3BucketAnalyticsConfiguration_WithStorageClassAnalysis_Default (37.43s)
--- PASS: TestAccAWSS3BucketAnalyticsConfiguration_WithStorageClassAnalysis_Empty (4.60s)
--- PASS: TestAccAWSS3BucketAnalyticsConfiguration_WithStorageClassAnalysis_Full (18.09s)

--- PASS: TestAccAWSS3BucketInventory_basic (39.01s)
--- PASS: TestAccAWSS3BucketInventory_encryptWithSSEKMS (30.52s)
--- PASS: TestAccAWSS3BucketInventory_encryptWithSSES3 (17.98s)

--- PASS: TestAccAWSS3BucketMetric_basic (25.82s)
--- PASS: TestAccAWSS3BucketMetric_WithEmptyFilter (14.47s)
--- PASS: TestAccAWSS3BucketMetric_WithFilterMultipleTags (34.95s)
--- PASS: TestAccAWSS3BucketMetric_WithFilterPrefix (28.33s)
--- PASS: TestAccAWSS3BucketMetric_WithFilterPrefixAndMultipleTags (26.00s)
--- PASS: TestAccAWSS3BucketMetric_WithFilterPrefixAndSingleTag (46.80s)
--- PASS: TestAccAWSS3BucketMetric_WithFilterSingleTag (26.21s)

--- PASS: TestAccAWSS3BucketNotification_LambdaFunction (50.35s)
--- PASS: TestAccAWSS3BucketNotification_LambdaFunction_LambdaFunctionArn_Alias (40.21s)
--- PASS: TestAccAWSS3BucketNotification_Queue (18.67s)
--- PASS: TestAccAWSS3BucketNotification_Topic (17.62s)
--- PASS: TestAccAWSS3BucketNotification_Topic_Multiple (17.91s)
--- PASS: TestAccAWSS3BucketNotification_update (62.44s)

--- PASS: TestAccAWSS3BucketObject_acl (40.07s)
--- PASS: TestAccAWSS3BucketObject_content (14.33s)
--- PASS: TestAccAWSS3BucketObject_contentBase64 (26.66s)
--- PASS: TestAccAWSS3BucketObject_empty (15.48s)
--- PASS: TestAccAWSS3BucketObject_etagEncryption (14.80s)
--- PASS: TestAccAWSS3BucketObject_kms (17.00s)
--- PASS: TestAccAWSS3BucketObject_metadata (40.01s)
--- PASS: TestAccAWSS3BucketObject_noNameNoKey (4.20s)
--- PASS: TestAccAWSS3BucketObject_NonVersioned (15.47s)
--- PASS: TestAccAWSS3BucketObject_ObjectLockLegalHoldStartWithNone (39.89s)
--- PASS: TestAccAWSS3BucketObject_ObjectLockLegalHoldStartWithOn (28.94s)
--- PASS: TestAccAWSS3BucketObject_ObjectLockRetentionStartWithNone (62.16s)
--- PASS: TestAccAWSS3BucketObject_ObjectLockRetentionStartWithSet (54.08s)
--- PASS: TestAccAWSS3BucketObject_source (15.94s)
--- PASS: TestAccAWSS3BucketObject_sse (16.16s)
--- PASS: TestAccAWSS3BucketObject_storageClass (63.28s)
--- PASS: TestAccAWSS3BucketObject_tags (53.00s)
--- PASS: TestAccAWSS3BucketObject_tagsLeadingSlash (61.10s)
--- PASS: TestAccAWSS3BucketObject_updates (49.69s)
--- PASS: TestAccAWSS3BucketObject_updateSameFile (26.25s)
--- PASS: TestAccAWSS3BucketObject_updatesWithVersioning (25.03s)
--- PASS: TestAccAWSS3BucketObject_updatesWithVersioningViaAccessPoint (37.04s)
--- PASS: TestAccAWSS3BucketObject_withContentCharacteristics (15.92s)

--- PASS: TestAccAWSS3BucketPolicy_basic (32.47s)
--- PASS: TestAccAWSS3BucketPolicy_policyUpdate (33.81s)

--- PASS: TestAccAWSS3BucketPublicAccessBlock_basic (21.06s)
--- PASS: TestAccAWSS3BucketPublicAccessBlock_BlockPublicAcls (53.08s)
--- PASS: TestAccAWSS3BucketPublicAccessBlock_BlockPublicPolicy (45.34s)
--- PASS: TestAccAWSS3BucketPublicAccessBlock_bucketDisappears (14.32s)
--- PASS: TestAccAWSS3BucketPublicAccessBlock_disappears (18.48s)
--- PASS: TestAccAWSS3BucketPublicAccessBlock_IgnorePublicAcls (45.05s)
--- PASS: TestAccAWSS3BucketPublicAccessBlock_RestrictPublicBuckets (44.33s)

--- PASS: TestAccAWSS3MultiBucket_withTags (22.91s)

--- PASS: TestAccDataSourceS3Bucket_basic (31.94s)
--- PASS: TestAccDataSourceS3Bucket_website (18.12s)
```

Output from acceptance testing in AWS GovCloud (US):

```
--- PASS: TestAccAWSS3Bucket_AclToGrant (22.38s)
--- PASS: TestAccAWSS3Bucket_basic (16.86s)
--- PASS: TestAccAWSS3Bucket_Bucket_EmptyString (15.63s)
--- PASS: TestAccAWSS3Bucket_Cors_Delete (13.31s)
--- PASS: TestAccAWSS3Bucket_Cors_EmptyOrigin (15.49s)
--- PASS: TestAccAWSS3Bucket_Cors_Update (23.09s)
--- PASS: TestAccAWSS3Bucket_disableDefaultEncryption_whenDefaultEncryptionIsEnabled (25.25s)
--- PASS: TestAccAWSS3Bucket_enableDefaultEncryption_whenAES256IsUsed (14.12s)
--- PASS: TestAccAWSS3Bucket_enableDefaultEncryption_whenTypical (17.04s)
--- PASS: TestAccAWSS3Bucket_forceDestroy (8.64s)
--- PASS: TestAccAWSS3Bucket_forceDestroyWithEmptyPrefixes (8.65s)
--- PASS: TestAccAWSS3Bucket_forceDestroyWithObjectLockEnabled (9.56s)
--- PASS: TestAccAWSS3Bucket_generatedName (17.05s)
--- PASS: TestAccAWSS3Bucket_GrantToAcl (24.26s)
--- PASS: TestAccAWSS3Bucket_LifecycleExpireMarkerOnly (22.31s)
--- PASS: TestAccAWSS3Bucket_LifecycleRule_Expiration_EmptyConfigurationBlock (13.52s)
--- PASS: TestAccAWSS3Bucket_Logging (16.54s)
--- PASS: TestAccAWSS3Bucket_namePrefix (16.74s)
--- PASS: TestAccAWSS3Bucket_objectLock (12.02s)
--- PASS: TestAccAWSS3Bucket_Policy (32.85s)
--- PASS: TestAccAWSS3Bucket_ReplicationConfiguration_Rule_Destination_AccessControlTranslation (64.90s)
--- PASS: TestAccAWSS3Bucket_ReplicationConfiguration_Rule_Destination_AddAccessControlTranslation (63.30s)
--- PASS: TestAccAWSS3Bucket_ReplicationExpectVersioningValidationError (25.63s)
--- PASS: TestAccAWSS3Bucket_ReplicationSchemaV2 (135.34s)
--- PASS: TestAccAWSS3Bucket_ReplicationWithoutPrefix (40.12s)
--- PASS: TestAccAWSS3Bucket_ReplicationWithoutStorageClass (42.72s)
--- PASS: TestAccAWSS3Bucket_RequestPayer (27.72s)
--- PASS: TestAccAWSS3Bucket_shouldFailNotFound (10.49s)
--- PASS: TestAccAWSS3Bucket_tagsWithNoSystemTags (40.92s)
--- PASS: TestAccAWSS3Bucket_UpdateAcl (25.50s)
--- PASS: TestAccAWSS3Bucket_UpdateGrant (34.61s)
--- PASS: TestAccAWSS3Bucket_Versioning (29.35s)
--- PASS: TestAccAWSS3Bucket_Website_Simple (32.52s)
--- PASS: TestAccAWSS3Bucket_WebsiteRedirect (34.55s)
--- PASS: TestAccAWSS3Bucket_WebsiteRoutingRules (23.33s)

--- PASS: TestAccAWSS3BucketAnalyticsConfiguration_basic (16.65s)
--- PASS: TestAccAWSS3BucketAnalyticsConfiguration_removed (21.47s)
--- PASS: TestAccAWSS3BucketAnalyticsConfiguration_updateBasic (34.48s)
--- PASS: TestAccAWSS3BucketAnalyticsConfiguration_WithFilter_Empty (3.27s)
--- PASS: TestAccAWSS3BucketAnalyticsConfiguration_WithFilter_MultipleTags (27.08s)
--- PASS: TestAccAWSS3BucketAnalyticsConfiguration_WithFilter_Prefix (25.46s)
--- PASS: TestAccAWSS3BucketAnalyticsConfiguration_WithFilter_PrefixAndTags (27.57s)
--- PASS: TestAccAWSS3BucketAnalyticsConfiguration_WithFilter_Remove (27.48s)
--- PASS: TestAccAWSS3BucketAnalyticsConfiguration_WithFilter_SingleTag (25.57s)
--- PASS: TestAccAWSS3BucketAnalyticsConfiguration_WithStorageClassAnalysis_Default (16.61s)
--- PASS: TestAccAWSS3BucketAnalyticsConfiguration_WithStorageClassAnalysis_Empty (3.62s)
--- PASS: TestAccAWSS3BucketAnalyticsConfiguration_WithStorageClassAnalysis_Full (15.74s)

--- PASS: TestAccAWSS3BucketInventory_basic (18.59s)
--- PASS: TestAccAWSS3BucketInventory_encryptWithSSES3 (16.63s)

--- PASS: TestAccAWSS3BucketMetric_basic (14.92s)
--- PASS: TestAccAWSS3BucketMetric_WithEmptyFilter (14.14s)
--- PASS: TestAccAWSS3BucketMetric_WithFilterMultipleTags (23.18s)
--- PASS: TestAccAWSS3BucketMetric_WithFilterPrefix (23.12s)
--- PASS: TestAccAWSS3BucketMetric_WithFilterPrefixAndMultipleTags (21.95s)
--- PASS: TestAccAWSS3BucketMetric_WithFilterPrefixAndSingleTag (21.76s)
--- PASS: TestAccAWSS3BucketMetric_WithFilterSingleTag (22.42s)

--- PASS: TestAccAWSS3BucketNotification_LambdaFunction (28.47s)
--- PASS: TestAccAWSS3BucketNotification_LambdaFunction_LambdaFunctionArn_Alias (28.23s)
--- PASS: TestAccAWSS3BucketNotification_Queue (16.45s)
--- PASS: TestAccAWSS3BucketNotification_Topic (16.35s)
--- PASS: TestAccAWSS3BucketNotification_Topic_Multiple (17.12s)
--- PASS: TestAccAWSS3BucketNotification_update (23.63s)

--- PASS: TestAccAWSS3BucketObject_acl (32.97s)
--- PASS: TestAccAWSS3BucketObject_content (14.39s)
--- PASS: TestAccAWSS3BucketObject_contentBase64 (15.34s)
--- PASS: TestAccAWSS3BucketObject_empty (13.87s)
--- PASS: TestAccAWSS3BucketObject_etagEncryption (13.26s)
--- PASS: TestAccAWSS3BucketObject_kms (14.32s)
--- PASS: TestAccAWSS3BucketObject_metadata (33.67s)
--- PASS: TestAccAWSS3BucketObject_noNameNoKey (4.27s)
--- PASS: TestAccAWSS3BucketObject_NonVersioned (14.88s)
--- PASS: TestAccAWSS3BucketObject_ObjectLockLegalHoldStartWithNone (34.36s)
--- PASS: TestAccAWSS3BucketObject_ObjectLockLegalHoldStartWithOn (24.58s)
--- PASS: TestAccAWSS3BucketObject_ObjectLockRetentionStartWithNone (32.66s)
--- PASS: TestAccAWSS3BucketObject_ObjectLockRetentionStartWithSet (41.13s)
--- PASS: TestAccAWSS3BucketObject_source (13.71s)
--- PASS: TestAccAWSS3BucketObject_sse (14.78s)
--- PASS: TestAccAWSS3BucketObject_storageClass (51.42s)
--- PASS: TestAccAWSS3BucketObject_tags (39.52s)
--- PASS: TestAccAWSS3BucketObject_tagsLeadingSlash (43.24s)
--- PASS: TestAccAWSS3BucketObject_updates (23.83s)
--- PASS: TestAccAWSS3BucketObject_updateSameFile (23.63s)
--- PASS: TestAccAWSS3BucketObject_updatesWithVersioning (24.56s)
--- PASS: TestAccAWSS3BucketObject_updatesWithVersioningViaAccessPoint (25.14s)
--- PASS: TestAccAWSS3BucketObject_withContentCharacteristics (14.84s)

--- PASS: TestAccAWSS3BucketPolicy_basic (17.08s)
--- PASS: TestAccAWSS3BucketPolicy_policyUpdate (26.70s)

--- PASS: TestAccAWSS3BucketPublicAccessBlock_basic (17.67s)
--- PASS: TestAccAWSS3BucketPublicAccessBlock_BlockPublicAcls (34.47s)
--- PASS: TestAccAWSS3BucketPublicAccessBlock_BlockPublicPolicy (32.93s)
--- PASS: TestAccAWSS3BucketPublicAccessBlock_bucketDisappears (11.73s)
--- PASS: TestAccAWSS3BucketPublicAccessBlock_disappears (15.05s)
--- PASS: TestAccAWSS3BucketPublicAccessBlock_IgnorePublicAcls (33.38s)
--- PASS: TestAccAWSS3BucketPublicAccessBlock_RestrictPublicBuckets (32.44s)

--- PASS: TestAccAWSS3MultiBucket_withTags (18.23s)

--- PASS: TestAccDataSourceS3Bucket_basic (17.50s)
--- PASS: TestAccDataSourceS3Bucket_website (16.49s)
```

**Pull request merged**
