### PR TITLE
service/iam: replace custom SchemaValidateFunc with provided ones

### PR DESCRIPTION
**Pull request by megubyte**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates: #11872

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
NONE
```

Output from acceptance testing:

```
--- PASS: TestAccAWSIAMGroup_nameChange (37.66s)
--- PASS: TestAccAWSIAMGroup_basic (41.33s)

--- PASS: TestAccAWSIAMInstanceProfile_withoutRole (22.81s)
--- PASS: TestAccAWSIAMInstanceProfile_basic (26.42s)
--- PASS: TestAccAWSIAMInstanceProfile_withRoleNotRoles (26.49s)
--- PASS: TestAccAWSIAMInstanceProfile_namePrefix (26.62s)

--- PASS: TestAccAWSIAMPolicy_disappears (18.30s)
--- PASS: TestAccAWSIAMPolicy_basic (25.80s)
--- PASS: TestAccAWSIAMPolicy_description (25.93s)
--- PASS: TestAccAWSIAMPolicy_namePrefix (26.13s)
--- PASS: TestAccAWSIAMPolicy_path (26.13s)
--- PASS: TestAccAWSIAMPolicy_policy (43.53s)

--- PASS: TestAccAWSIAMRole_badJSON (2.65s)
--- PASS: TestAccAWSIAMRole_disappears (18.17s)
--- PASS: TestAccAWSIAMRole_basic (24.06s)
--- PASS: TestAccAWSIAMRole_namePrefix (24.35s)
--- PASS: TestAccAWSIAMRole_force_detach_policies (29.42s)
--- PASS: TestAccAWSIAMRole_tags (39.39s)
--- PASS: TestAccAWSIAMRole_MaxSessionDuration (41.98s)
--- PASS: TestAccAWSIAMRole_testNameChange (50.72s)
--- PASS: TestAccAWSIAMRole_basicWithDescription (54.37s)
--- PASS: TestAccAWSIAMRole_PermissionsBoundary (85.03s)

--- PASS: TestAccAWSUser_disappears (18.00s)
--- PASS: TestAccAWSUser_ForceDestroy_LoginProfile (26.15s)
--- PASS: TestAccAWSUser_ForceDestroy_SSHKey (26.69s)
--- PASS: TestAccAWSUser_ForceDestroy_AccessKey (26.97s)
--- PASS: TestAccAWSUser_ForceDestroy_MFADevice (27.28s)
--- PASS: TestAccAWSUser_pathChange (38.76s)
--- PASS: TestAccAWSUser_nameChange (38.98s)
--- PASS: TestAccAWSUser_basic (39.10s)
--- PASS: TestAccAWSUser_tags (41.03s)
--- PASS: TestAccAWSUser_permissionsBoundary (87.66s)
```

### CODE REVIEW

**Comment by megubyte** [comment]
Hi @bflad! 👋 Thanks for your feedback on my PR - I've gone ahead and inlined the calls to the validation methods and am currently running the acceptance tests again to ensure that I've not done anything silly. 😄

If this is approved, I see no real reason why I can't attempt to round off the entire tech debt issue that is linked to this, submitting one PR per service in cases like IAM where there are multiple resources affected, I took the opportunity of making a change to my commit message and PR title to the same spec which it seems everyone else uses - hope you don't mind!

**Comment by megubyte** [comment]
**Updated Acceptance Testing:**
```
--- PASS: TestAccAWSIAMGroup_nameChange (43.81s)
--- PASS: TestAccAWSIAMGroup_basic (44.87s)

--- PASS: TestAccAWSIAMInstanceProfile_withoutRole (27.07s)
--- PASS: TestAccAWSIAMInstanceProfile_basic (30.53s)
--- PASS: TestAccAWSIAMInstanceProfile_withRoleNotRoles (31.05s)
--- PASS: TestAccAWSIAMInstanceProfile_namePrefix (31.07s)

--- PASS: TestAccAWSIAMPolicy_disappears (21.33s)
--- PASS: TestAccAWSIAMPolicy_description (29.71s)
--- PASS: TestAccAWSIAMPolicy_path (30.59s)
--- PASS: TestAccAWSIAMPolicy_namePrefix (30.65s)
--- PASS: TestAccAWSIAMPolicy_basic (31.89s)
--- PASS: TestAccAWSIAMPolicy_policy (50.61s)

--- PASS: TestAccAWSIAMRole_badJSON (3.33s)
--- PASS: TestAccAWSIAMRole_disappears (22.63s)
--- PASS: TestAccAWSIAMRole_namePrefix (30.06s)
--- PASS: TestAccAWSIAMRole_basic (30.74s)
--- PASS: TestAccAWSIAMRole_force_detach_policies (36.42s)
--- PASS: TestAccAWSIAMRole_tags (46.93s)
--- PASS: TestAccAWSIAMRole_MaxSessionDuration (51.21s)
--- PASS: TestAccAWSIAMRole_testNameChange (61.86s)
--- PASS: TestAccAWSIAMRole_basicWithDescription (66.90s)
--- PASS: TestAccAWSIAMRole_PermissionsBoundary (132.94s)

--- PASS: TestAccAWSUser_disappears (23.31s)
--- PASS: TestAccAWSUser_ForceDestroy_AccessKey (34.52s)
--- PASS: TestAccAWSUser_ForceDestroy_LoginProfile (34.52s)
--- PASS: TestAccAWSUser_ForceDestroy_SSHKey (34.65s)
--- PASS: TestAccAWSUser_ForceDestroy_MFADevice (34.97s)
--- PASS: TestAccAWSUser_nameChange (62.57s)
--- PASS: TestAccAWSUser_basic (62.83s)
--- PASS: TestAccAWSUser_pathChange (64.76s)
--- PASS: TestAccAWSUser_tags (64.98s)
--- PASS: TestAccAWSUser_permissionsBoundary (124.60s)
```

**Comment by bflad** [comment]
For the CI failures, looks like it just needs `make fmt` run on the branch and committed. 👍

**Comment by megubyte** [comment]
Thanks for letting me know about that - I hadn't caught that when I committed the last time. I've checked the status of Travis and it looks like all is good this time. :+1: My apologies!

**Comment by anGie44** [comment]
Confirmed output of acceptance tests:
```
--- PASS: TestAccAWSIAMPolicy_*
--- PASS: TestAccAWSIAMGroupPolicy_*
--- PASS: TestAccAWSIAMInstanceProfile_*
--- PASS: TestAccAWSIAMRolePolicy_*
--- PASS: TestAccAWSIAMGroup_*
--- PASS: TestAccAWSIAMRole_*
--- PASS: TestAccAWSIAMPolicyAttachment_*
--- PASS: TestAccAWSUserSSHKey_*
--- PASS: TestAccAWSIAMRolePolicy_*
--- PASS: TestAccAWSUserLoginProfile_*
--- PASS: TestAccAWSUser_*
--- PASS: TestAccAWSUserGroupMembership_*
```

**Pull request merged**
