### PR TITLE
r/aws_appmesh_route: Add support for retry policies

### PR DESCRIPTION
**Pull request by ewbankkit**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes: https://github.com/terraform-providers/terraform-provider-aws/issues/10075.
Relates: https://github.com/terraform-providers/terraform-provider-aws/issues/14601.

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
resource/aws_appmesh_route: Add `retry_policy` attribute to support App Mesh retry policies
```

Output from acceptance testing:

```console
$ make testacc TEST=./aws TESTARGS='-run=TestAccAWSAppmesh/Route'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSAppmesh/Route -timeout 120m
=== RUN   TestAccAWSAppmesh
=== RUN   TestAccAWSAppmesh/VirtualRouter
=== RUN   TestAccAWSAppmesh/VirtualRouter/basic
=== RUN   TestAccAWSAppmesh/VirtualRouter/tags
=== RUN   TestAccAWSAppmesh/Route
=== RUN   TestAccAWSAppmesh/Route/httpHeader
=== RUN   TestAccAWSAppmesh/Route/httpRetryPolicy
=== RUN   TestAccAWSAppmesh/Route/httpRoute
=== RUN   TestAccAWSAppmesh/Route/tcpRoute
=== RUN   TestAccAWSAppmesh/Route/routePriority
=== RUN   TestAccAWSAppmesh/Route/tags
--- PASS: TestAccAWSAppmesh (434.45s)
    --- PASS: TestAccAWSAppmesh/VirtualRouter (109.11s)
        --- PASS: TestAccAWSAppmesh/VirtualRouter/basic (45.09s)
        --- PASS: TestAccAWSAppmesh/VirtualRouter/tags (64.02s)
    --- PASS: TestAccAWSAppmesh/Route (325.34s)
        --- PASS: TestAccAWSAppmesh/Route/httpHeader (49.89s)
        --- PASS: TestAccAWSAppmesh/Route/httpRetryPolicy (50.95s)
        --- PASS: TestAccAWSAppmesh/Route/httpRoute (50.59s)
        --- PASS: TestAccAWSAppmesh/Route/tcpRoute (51.15s)
        --- PASS: TestAccAWSAppmesh/Route/routePriority (51.17s)
        --- PASS: TestAccAWSAppmesh/Route/tags (71.60s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	434.502s
```

~Includes changes from https://github.com/terraform-providers/terraform-provider-aws/pull/10402.~

### CODE REVIEW

**Comment by ewbankkit** [comment]
Rebased to remove merge conflicts.
Re-ran acceptance tests:

```console
% make testacc TEST=./aws TESTARGS='-run=TestAccAWSAppmesh/Route'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSAppmesh/Route -timeout 120m
=== RUN   TestAccAWSAppmesh
=== RUN   TestAccAWSAppmesh/Route
=== RUN   TestAccAWSAppmesh/Route/tags
=== RUN   TestAccAWSAppmesh/Route/httpHeader
=== RUN   TestAccAWSAppmesh/Route/httpRetryPolicy
=== RUN   TestAccAWSAppmesh/Route/httpRoute
=== RUN   TestAccAWSAppmesh/Route/tcpRoute
=== RUN   TestAccAWSAppmesh/Route/routePriority
=== RUN   TestAccAWSAppmesh/VirtualRouter
=== RUN   TestAccAWSAppmesh/VirtualRouter/basic
=== RUN   TestAccAWSAppmesh/VirtualRouter/tags
--- PASS: TestAccAWSAppmesh (445.43s)
    --- PASS: TestAccAWSAppmesh/Route (333.66s)
        --- PASS: TestAccAWSAppmesh/Route/tags (73.39s)
        --- PASS: TestAccAWSAppmesh/Route/httpHeader (51.38s)
        --- PASS: TestAccAWSAppmesh/Route/httpRetryPolicy (52.67s)
        --- PASS: TestAccAWSAppmesh/Route/httpRoute (52.26s)
        --- PASS: TestAccAWSAppmesh/Route/tcpRoute (52.30s)
        --- PASS: TestAccAWSAppmesh/Route/routePriority (51.66s)
    --- PASS: TestAccAWSAppmesh/VirtualRouter (111.77s)
        --- PASS: TestAccAWSAppmesh/VirtualRouter/basic (46.41s)
        --- PASS: TestAccAWSAppmesh/VirtualRouter/tags (65.36s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	446.634s
```

**Comment by ewbankkit** [comment]
Rebased.
Re-ran acceptance tests:

```console
$ make testacc TEST=./aws TESTARGS='-run=TestAccAWSAppmesh/Route'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSAppmesh/Route -timeout 120m
=== RUN   TestAccAWSAppmesh
=== RUN   TestAccAWSAppmesh/Route
=== RUN   TestAccAWSAppmesh/Route/httpHeader
=== RUN   TestAccAWSAppmesh/Route/httpRetryPolicy
=== RUN   TestAccAWSAppmesh/Route/httpRoute
=== RUN   TestAccAWSAppmesh/Route/tcpRoute
=== RUN   TestAccAWSAppmesh/Route/routePriority
=== RUN   TestAccAWSAppmesh/Route/tags
=== RUN   TestAccAWSAppmesh/VirtualRouter
=== RUN   TestAccAWSAppmesh/VirtualRouter/basic
=== RUN   TestAccAWSAppmesh/VirtualRouter/tags
--- PASS: TestAccAWSAppmesh (430.75s)
    --- PASS: TestAccAWSAppmesh/Route (322.16s)
        --- PASS: TestAccAWSAppmesh/Route/httpHeader (50.67s)
        --- PASS: TestAccAWSAppmesh/Route/httpRetryPolicy (50.74s)
        --- PASS: TestAccAWSAppmesh/Route/httpRoute (49.51s)
        --- PASS: TestAccAWSAppmesh/Route/tcpRoute (49.95s)
        --- PASS: TestAccAWSAppmesh/Route/routePriority (50.31s)
        --- PASS: TestAccAWSAppmesh/Route/tags (70.99s)
    --- PASS: TestAccAWSAppmesh/VirtualRouter (108.59s)
        --- PASS: TestAccAWSAppmesh/VirtualRouter/basic (45.22s)
        --- PASS: TestAccAWSAppmesh/VirtualRouter/tags (63.37s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	430.797s
```

**Comment by ewbankkit** [comment]
Revisit, considering #13194.

**Comment by ewbankkit** [comment]
Rebased and removed unnecessary custom hash functions.
Re-ran acceptance tests:

```console
$ make testacc TEST=./aws/ TESTARGS='-run=TestAccAWSAppmesh/Route/'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws/ -v -count 1 -parallel 20 -run=TestAccAWSAppmesh/Route/ -timeout 120m
=== RUN   TestAccAWSAppmesh
=== RUN   TestAccAWSAppmesh/Route
=== RUN   TestAccAWSAppmesh/Route/httpRoute
=== RUN   TestAccAWSAppmesh/Route/tcpRoute
=== RUN   TestAccAWSAppmesh/Route/routePriority
=== RUN   TestAccAWSAppmesh/Route/tags
=== RUN   TestAccAWSAppmesh/Route/httpHeader
=== RUN   TestAccAWSAppmesh/Route/httpRetryPolicy
=== RUN   TestAccAWSAppmesh/VirtualRouter
=== RUN   TestAccAWSAppmesh/VirtualRouter/basic
=== RUN   TestAccAWSAppmesh/VirtualRouter/tags
--- PASS: TestAccAWSAppmesh (440.07s)
    --- PASS: TestAccAWSAppmesh/Route (329.37s)
        --- PASS: TestAccAWSAppmesh/Route/httpRoute (50.93s)
        --- PASS: TestAccAWSAppmesh/Route/tcpRoute (52.49s)
        --- PASS: TestAccAWSAppmesh/Route/routePriority (52.43s)
        --- PASS: TestAccAWSAppmesh/Route/tags (71.69s)
        --- PASS: TestAccAWSAppmesh/Route/httpHeader (51.15s)
        --- PASS: TestAccAWSAppmesh/Route/httpRetryPolicy (50.66s)
    --- PASS: TestAccAWSAppmesh/VirtualRouter (110.70s)
        --- PASS: TestAccAWSAppmesh/VirtualRouter/basic (45.90s)
        --- PASS: TestAccAWSAppmesh/VirtualRouter/tags (64.81s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	440.128s
```

**Comment by ewbankkit** [comment]
Rebased.
Re-ran acceptance tests:

```console
$ make testacc TEST=./aws/ TESTARGS='-run=TestAccAWSAppmesh/Route/'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws/ -v -count 1 -parallel 20 -run=TestAccAWSAppmesh/Route/ -timeout 120m
=== RUN   TestAccAWSAppmesh
=== RUN   TestAccAWSAppmesh/Route
=== RUN   TestAccAWSAppmesh/Route/httpHeader
=== RUN   TestAccAWSAppmesh/Route/httpRetryPolicy
=== RUN   TestAccAWSAppmesh/Route/httpRoute
=== RUN   TestAccAWSAppmesh/Route/tcpRoute
=== RUN   TestAccAWSAppmesh/Route/routePriority
=== RUN   TestAccAWSAppmesh/Route/tags
=== RUN   TestAccAWSAppmesh/VirtualRouter
=== RUN   TestAccAWSAppmesh/VirtualRouter/basic
=== RUN   TestAccAWSAppmesh/VirtualRouter/tags
--- PASS: TestAccAWSAppmesh (475.74s)
    --- PASS: TestAccAWSAppmesh/Route (365.43s)
        --- PASS: TestAccAWSAppmesh/Route/httpHeader (50.77s)
        --- PASS: TestAccAWSAppmesh/Route/httpRetryPolicy (50.27s)
        --- PASS: TestAccAWSAppmesh/Route/httpRoute (70.72s)
        --- PASS: TestAccAWSAppmesh/Route/tcpRoute (70.46s)
        --- PASS: TestAccAWSAppmesh/Route/routePriority (50.92s)
        --- PASS: TestAccAWSAppmesh/Route/tags (72.28s)
    --- PASS: TestAccAWSAppmesh/VirtualRouter (110.31s)
        --- PASS: TestAccAWSAppmesh/VirtualRouter/basic (45.97s)
        --- PASS: TestAccAWSAppmesh/VirtualRouter/tags (64.34s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	475.789s
```

**Comment by ewbankkit** [comment]
Rebased to remove merge conflict.
Re-ran acceptance tests:

```console
$ make testacc TEST=./aws/ TESTARGS='-run=TestAccAWSAppmesh/Route/'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws/ -v -count 1 -parallel 20 -run=TestAccAWSAppmesh/Route/ -timeout 120m
=== RUN   TestAccAWSAppmesh
=== RUN   TestAccAWSAppmesh/Route
=== RUN   TestAccAWSAppmesh/Route/httpHeader
=== RUN   TestAccAWSAppmesh/Route/httpRetryPolicy
=== RUN   TestAccAWSAppmesh/Route/httpRoute
=== RUN   TestAccAWSAppmesh/Route/tcpRoute
=== RUN   TestAccAWSAppmesh/Route/routePriority
=== RUN   TestAccAWSAppmesh/Route/tags
=== RUN   TestAccAWSAppmesh/VirtualRouter
=== RUN   TestAccAWSAppmesh/VirtualRouter/basic
=== RUN   TestAccAWSAppmesh/VirtualRouter/tags
--- PASS: TestAccAWSAppmesh (477.10s)
    --- PASS: TestAccAWSAppmesh/Route (365.74s)
        --- PASS: TestAccAWSAppmesh/Route/httpHeader (51.37s)
        --- PASS: TestAccAWSAppmesh/Route/httpRetryPolicy (51.20s)
        --- PASS: TestAccAWSAppmesh/Route/httpRoute (69.49s)
        --- PASS: TestAccAWSAppmesh/Route/tcpRoute (70.81s)
        --- PASS: TestAccAWSAppmesh/Route/routePriority (51.94s)
        --- PASS: TestAccAWSAppmesh/Route/tags (70.92s)
    --- PASS: TestAccAWSAppmesh/VirtualRouter (111.36s)
        --- PASS: TestAccAWSAppmesh/VirtualRouter/basic (46.08s)
        --- PASS: TestAccAWSAppmesh/VirtualRouter/tags (65.27s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	477.164s
```

**Comment by ewbankkit** [comment]
Rebased and migrated acceptance test and documentation syntax to TF 0.12.
Re-ran acceptance tests:

```console
$ make testacc TEST=./aws/ TESTARGS='-run=TestAccAWSAppmesh/Route/'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSAppmesh/Route/ -timeout 120m
=== RUN   TestAccAWSAppmesh_serial
=== RUN   TestAccAWSAppmesh_serial/Route
=== RUN   TestAccAWSAppmesh_serial/Route/httpHeader
=== RUN   TestAccAWSAppmesh_serial/Route/httpRetryPolicy
=== RUN   TestAccAWSAppmesh_serial/Route/httpRoute
=== RUN   TestAccAWSAppmesh_serial/Route/tcpRoute
=== RUN   TestAccAWSAppmesh_serial/Route/routePriority
=== RUN   TestAccAWSAppmesh_serial/Route/tags
=== RUN   TestAccAWSAppmesh_serial/VirtualRouter
=== RUN   TestAccAWSAppmesh_serial/VirtualRouter/tags
=== RUN   TestAccAWSAppmesh_serial/VirtualRouter/basic
--- PASS: TestAccAWSAppmesh_serial (352.76s)
    --- PASS: TestAccAWSAppmesh_serial/Route (271.85s)
        --- PASS: TestAccAWSAppmesh_serial/Route/httpHeader (37.80s)
        --- PASS: TestAccAWSAppmesh_serial/Route/httpRetryPolicy (37.55s)
        --- PASS: TestAccAWSAppmesh_serial/Route/httpRoute (52.51s)
        --- PASS: TestAccAWSAppmesh_serial/Route/tcpRoute (52.73s)
        --- PASS: TestAccAWSAppmesh_serial/Route/routePriority (37.16s)
        --- PASS: TestAccAWSAppmesh_serial/Route/tags (54.10s)
    --- PASS: TestAccAWSAppmesh_serial/VirtualRouter (80.91s)
        --- PASS: TestAccAWSAppmesh_serial/VirtualRouter/tags (47.36s)
        --- PASS: TestAccAWSAppmesh_serial/VirtualRouter/basic (33.55s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	352.802s
```

**Review by DrFaust92 — COMMENTED** [review]
LGTM

```
    --- PASS: TestAccAWSAppmesh_serial/VirtualRouter (199.63s)
        --- PASS: TestAccAWSAppmesh_serial/VirtualRouter/basic (81.46s)
        --- PASS: TestAccAWSAppmesh_serial/VirtualRouter/tags (118.17s)

```

wasnt able to run Route tests, getting 
```
Error: error creating App Mesh virtual node: ConflictException: VirtualNode with name tf-acc-test-7197939696529239263 already exists with different clientRequestToken 4B53144C-2F10-4403-8D7B-9B37E8B9D657
```

but its probably an issue running tests from windows, i get these edge cases sometime..

**Comment by ewbankkit** [comment]
@DrFaust92 Interesting. Does that error occur every time you run the tests? Are there any additional errors reported?

**Comment by DrFaust92** [comment]
Yes, my suspicious it that it doesn't randomize the name in windows when using acctest.randomwithprefix when they are in the same test (or calls are too close)

**Comment by ewbankkit** [comment]
Yes, it seems that on Windows that the underlying golang `time.Now().UnixNano()` can have relatively low precision: https://stackoverflow.com/questions/57285292/why-does-time-now-unixnano-returns-the-same-result-after-an-io-operation.

**Review by DrFaust92 — APPROVED** [review]
LGTM

**Comment by breathingdust** [comment]
LGTM! 🚀  Thanks @ewbankkit 

Verified Acceptance Tests in Commercial (us-west-2)

```console
make testacc TEST=./aws TESTARGS='-run=TestAccAWSAppmesh/Route'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSAppmesh/Route -timeout 120m
=== RUN   TestAccAWSAppmesh_serial
=== RUN   TestAccAWSAppmesh_serial/Route
=== RUN   TestAccAWSAppmesh_serial/Route/tcpRoute
=== RUN   TestAccAWSAppmesh_serial/Route/routePriority
=== RUN   TestAccAWSAppmesh_serial/Route/tags
=== RUN   TestAccAWSAppmesh_serial/Route/httpHeader
=== RUN   TestAccAWSAppmesh_serial/Route/httpRetryPolicy
=== RUN   TestAccAWSAppmesh_serial/Route/httpRoute
=== RUN   TestAccAWSAppmesh_serial/VirtualRouter
=== RUN   TestAccAWSAppmesh_serial/VirtualRouter/basic
=== RUN   TestAccAWSAppmesh_serial/VirtualRouter/tags
--- PASS: TestAccAWSAppmesh_serial (275.96s)
    --- PASS: TestAccAWSAppmesh_serial/Route (211.99s)
        --- PASS: TestAccAWSAppmesh_serial/Route/tcpRoute (43.30s)
        --- PASS: TestAccAWSAppmesh_serial/Route/routePriority (27.73s)
        --- PASS: TestAccAWSAppmesh_serial/Route/tags (43.05s)
        --- PASS: TestAccAWSAppmesh_serial/Route/httpHeader (27.46s)
        --- PASS: TestAccAWSAppmesh_serial/Route/httpRetryPolicy (28.65s)
        --- PASS: TestAccAWSAppmesh_serial/Route/httpRoute (41.80s)
    --- PASS: TestAccAWSAppmesh_serial/VirtualRouter (63.97s)
        --- PASS: TestAccAWSAppmesh_serial/VirtualRouter/basic (26.40s)
        --- PASS: TestAccAWSAppmesh_serial/VirtualRouter/tags (37.58s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	277.397s


```

**Pull request merged**
